---
- name: Add pg_hba entry for host computer
  lineinfile: dest="/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf" line="host all all 192.168.111.0/24 trust"
  notify: 
    - postgresql restart

- name: Listen on all interfaces in postgresql.conf
  lineinfile: dest="/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf" line="listen_addresses='*'"
  notify: 
    - postgresql restart
