# Generated by Django 4.2.25 on 2025-12-15 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0400_add_status_optymalizacji_bulk"),
        ("rozbieznosci_if", "0003_auto_20210323_0109"),
    ]

    operations = [
        migrations.CreateModel(
            name="RozbieznosciIfLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "if_before",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="IF przed zmianą",
                    ),
                ),
                (
                    "if_after",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="IF po zmianie",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiedy"),
                ),
                (
                    "rekord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.wydawnictwo_ciagle",
                        verbose_name="Rekord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.zrodlo",
                        verbose_name="Źródło",
                    ),
                ),
            ],
            options={
                "verbose_name": "log zmiany IF",
                "verbose_name_plural": "logi zmian IF",
                "ordering": ["-created_on"],
            },
        ),
    ]
