# Generated by Django 3.2.14 on 2022-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_if", "0003_auto_20210323_0109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ignorujrozbieznoscif",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
