# Generated by Django 4.2.25 on 2025-10-17 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pbn_api", "0062_sent_data_success_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0392_alter_autor_dyscyplina_rodzaj_autora"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrzeMapowanieZrodla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liczba_rekordow",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Liczba przemapowanych rekordów"
                    ),
                ),
                (
                    "utworzono",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "rekordy_historia",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista przemapowanych rekordów z podstawowymi informacjami",
                        verbose_name="Historia przemapowanych rekordów",
                    ),
                ),
                (
                    "utworzono_przez",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzono przez",
                    ),
                ),
                (
                    "zrodlo_nowe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_jako_nowe",
                        to="bpp.zrodlo",
                        verbose_name="Źródło nowe (BPP)",
                    ),
                ),
                (
                    "zrodlo_skasowane_pbn_uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_jako_stare",
                        to="pbn_api.journal",
                        verbose_name="Źródło skasowane (Journal PBN)",
                    ),
                ),
                (
                    "zrodlo_stare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_jako_stare",
                        to="bpp.zrodlo",
                        verbose_name="Źródło stare (BPP)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przemapowanie źródła",
                "verbose_name_plural": "Przemapowania źródeł",
                "ordering": ["-utworzono"],
            },
        ),
    ]
