# Generated by Django 4.2.25 on 2025-10-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0392_alter_autor_dyscyplina_rodzaj_autora"),
        ("przemapuj_zrodla_pbn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="przemapowaniezrodla",
            name="typ_operacji",
            field=models.CharField(
                choices=[
                    ("przemapowanie", "Przemapowanie"),
                    ("usuniecie", "Usunięcie"),
                ],
                default="przemapowanie",
                max_length=20,
                verbose_name="Typ operacji",
            ),
        ),
        migrations.AlterField(
            model_name="przemapowaniezrodla",
            name="zrodlo_nowe",
            field=models.ForeignKey(
                blank=True,
                help_text="Wypełnione tylko dla operacji typu 'przemapowanie'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="przemapowania_jako_nowe",
                to="bpp.zrodlo",
                verbose_name="Źródło nowe (BPP)",
            ),
        ),
    ]
