# Generated by Django 4.2.25 on 2025-10-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0392_alter_autor_dyscyplina_rodzaj_autora"),
        ("przemapuj_zrodla_pbn", "0002_przemapowaniezrodla_typ_operacji_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="przemapowaniezrodla",
            name="zrodlo_nowe",
            field=models.ForeignKey(
                blank=True,
                help_text="Wypełnione tylko dla operacji typu 'przemapowanie'",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="przemapowania_jako_nowe",
                to="bpp.zrodlo",
                verbose_name="Źródło nowe (BPP)",
            ),
        ),
        migrations.AlterField(
            model_name="przemapowaniezrodla",
            name="zrodlo_stare",
            field=models.ForeignKey(
                blank=True,
                help_text="Może być NULL jeśli źródło zostało usunięte",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="przemapowania_jako_stare",
                to="bpp.zrodlo",
                verbose_name="Źródło stare (BPP)",
            ),
        ),
    ]
