---
- name: Install postgresql optimized settings
  lineinfile: line="{{item}}" dest="/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
  with_items:
    - max_connections = 100
    - shared_buffers = 256MB
    - effective_cache_size = 768MB
    - work_mem = 2621kB
    - maintenance_work_mem = 64MB
    - min_wal_size = 1GB
    - max_wal_size = 2GB
    - checkpoint_completion_target = 0.7
    - wal_buffers = 7864kB
    - default_statistics_target = 100
    - fsync = off
    - synchronous_commit = off
    - wal_writer_delay = 10000ms
    - commit_delay = 100000
    - full_page_writes = off
    - random_page_cost = 1.1
  notify: 
    - postgresql restart
