# Generated by Django 3.0.14 on 2021-10-11 08:26

import django.db.models.deletion
from django.db import migrations, models

import ewaluacja2021.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bpp", "0306_delete_ewaluacja2021liczbandlauczelni"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiczbaNDlaUczelni",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liczba_n",
                    ewaluacja2021.fields.LiczbaNField(decimal_places=4, max_digits=9),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.Dyscyplina_Naukowa",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.Uczelnia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Liczba N dla uczelni",
                "verbose_name_plural": "Liczby N dla uczelni",
                "unique_together": {("uczelnia", "dyscyplina_naukowa")},
            },
        ),
        migrations.CreateModel(
            name="LiczbaNDlaAutora",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liczba_n",
                    ewaluacja2021.fields.LiczbaNField(decimal_places=4, max_digits=9),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.Autor"
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.Dyscyplina_Naukowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "liczba N dla autora",
                "verbose_name_plural": "liczby N dla autora",
                "unique_together": {("autor", "dyscyplina_naukowa")},
            },
        ),
    ]
