# Generated by Django 3.2.14 on 2022-07-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja2021", "0009_zamowienienaraport_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wierszimportumaksymalnychslotow",
            name="orig_data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="wierszimportumaksymalnychslotow",
            name="poprawny",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="wierszimportumaksymalnychslotow",
            name="wymagana_integracja",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
