# Generated by Django 3.2.14 on 2022-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja2021", "0010_django32"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wierszimportumaksymalnychslotow",
            name="poprawny",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="wierszimportumaksymalnychslotow",
            name="wymagana_integracja",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
