# Generated by Django 4.2.19 on 2025-05-11 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import ewaluacja2021.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0380_rekord_wydawca"),
        ("ewaluacja2021", "0013_alter_iloscudzialowdlaautora_ilosc_udzialow_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IloscUdzialowDlaAutoraZaRok",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilosc_udzialow",
                    ewaluacja2021.fields.LiczbaNField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[django.core.validators.MaxValueValidator(4)],
                    ),
                ),
                (
                    "ilosc_udzialow_monografie",
                    ewaluacja2021.fields.LiczbaNField(decimal_places=2, max_digits=9),
                ),
                ("rok", models.IntegerField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "ilość udziałów dla autora za rok",
                "verbose_name_plural": "ilości udziałów dla autorów za lata",
                "unique_together": {("autor", "dyscyplina_naukowa", "rok")},
            },
        ),
    ]
