# Generated by Django 4.2.19 on 2025-05-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0382_alter_uczelnia_przydzielaj_1_slot_gdy_udzial_mniejszy"),
        ("ewaluacja2021", "0014_iloscudzialowzarok"),
    ]

    operations = [
        migrations.CreateModel(
            name="DyscyplinaNieRaportowana_2022_2025",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.uczelnia"
                    ),
                ),
            ],
            options={
                "unique_together": {("uczelnia", "dyscyplina_naukowa")},
            },
        ),
    ]
