# Generated by Django 4.2.19 on 2025-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja2021", "0015_dyscyplina_nie_raportowana"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="iloscudzialowdlaautora_2022_2025",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="iloscudzialowdlaautora_2022_2025",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="iloscudzialowdlaautora_2022_2025",
            name="dyscyplina_naukowa",
        ),
        migrations.AlterUniqueTogether(
            name="iloscudzialowdlaautorazarok",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="iloscudzialowdlaautorazarok",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="iloscudzialowdlaautorazarok",
            name="dyscyplina_naukowa",
        ),
        migrations.AlterUniqueTogether(
            name="liczbandlauczelni_2022_2025",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="liczbandlauczelni_2022_2025",
            name="dyscyplina_naukowa",
        ),
        migrations.RemoveField(
            model_name="liczbandlauczelni_2022_2025",
            name="uczelnia",
        ),
        migrations.AlterField(
            model_name="zamowienienaraport",
            name="rodzaj",
            field=models.CharField(
                choices=[
                    (
                        "plecakowy",
                        "plecakowy - szybki wynik, dokładne wyliczenia dla autora, niezbyt dokładne dla uczelni",
                    ),
                    (
                        "plecakowy_bez_limitu",
                        "plecakowy bez limitu na uczelnię - szybki wynik, dokładne wyliczenia dla autora, ale bez warunku limitu na uczelnię",
                    ),
                    (
                        "genetyczny",
                        "genetyczny - dokładne wyliczenia dla autora i uczelni, dłuższy czas oczekiwania; uwzględnia przypięcia/odpięcia dyscyplin",
                    ),
                    (
                        "genetyczny_z_odpinaniem",
                        "genetyczny z odpinaniem - dokładne wyliczenia dla autora i instytucji, następnie odpina dyscypliny i ponawia kalkulację i tak kilka razy...",
                    ),
                ],
                default="genetyczny_z_odpinaniem",
                max_length=25,
                verbose_name="Rodzaj algorytmu",
            ),
        ),
        migrations.DeleteModel(
            name="DyscyplinaNieRaportowana_2022_2025",
        ),
        migrations.DeleteModel(
            name="IloscUdzialowDlaAutora_2022_2025",
        ),
        migrations.DeleteModel(
            name="IloscUdzialowDlaAutoraZaRok",
        ),
        migrations.DeleteModel(
            name="LiczbaNDlaUczelni_2022_2025",
        ),
    ]
