# Generated by Django 4.2.25 on 2025-10-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0394_alter_uczelnia_clarivate_password_and_more"),
        (
            "ewaluacja2021",
            "0016_alter_iloscudzialowdlaautora_2022_2025_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="liczbandlauczelni",
            name="dyscyplina_naukowa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bpp.dyscyplina_naukowa",
            ),
        ),
        migrations.AlterField(
            model_name="liczbandlauczelni",
            name="uczelnia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bpp.uczelnia",
            ),
        ),
    ]
