# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

import ewaluacja2021.validators
from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi pliki do katalogu protected/ewaluacja2021/"""
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "ewaluacja2021")
    os.makedirs(new_dir, exist_ok=True)

    # Przeniesienie plików ImportMaksymalnychSlotow
    ImportMaksymalnychSlotow = apps.get_model("ewaluacja2021", "ImportMaksymalnychSlotow")
    for obj in ImportMaksymalnychSlotow.objects.exclude(plik=""):
        if obj.plik:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik = f"protected/ewaluacja2021/{filename}"
                obj.save(update_fields=["plik"])

    # Przeniesienie plików ZamowienieNaRaport
    ZamowienieNaRaport = apps.get_model("ewaluacja2021", "ZamowienieNaRaport")
    for obj in ZamowienieNaRaport.objects.all():
        # Przeniesienie plik_wyjsciowy
        if obj.plik_wyjsciowy:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik_wyjsciowy.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik_wyjsciowy = f"protected/ewaluacja2021/{filename}"
                obj.save(update_fields=["plik_wyjsciowy"])

        # Przeniesienie wykres_wyjsciowy
        if obj.wykres_wyjsciowy:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.wykres_wyjsciowy.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.wykres_wyjsciowy = f"protected/ewaluacja2021/{filename}"
                obj.save(update_fields=["wykres_wyjsciowy"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ewaluacja2021", "0017_alter_liczbandlauczelni_dyscyplina_naukowa_and_more"),
    ]

    operations = [
        migrations.RunPython(move_files_to_protected, noop),
        migrations.AlterField(
            model_name="importmaksymalnychslotow",
            name="plik",
            field=models.FileField(
                upload_to="protected/ewaluacja2021/",
                validators=[
                    ewaluacja2021.validators.xlsx_header_validator(
                        columns=[
                            "Stopień / Tytuł",
                            "Nazwisko",
                            "Imię",
                            "ORCID",
                            "Dyscyplina",
                            "Uwzględniony w ewaluacji",
                            "maksymalna suma udziałów jednostkowych - wszystkie dyscypliny",
                            "maksymalna suma udziałów jednostkowych - monografie",
                        ],
                        max_header_row=100,
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="zamowienienaraport",
            name="plik_wyjsciowy",
            field=models.FileField(upload_to="protected/ewaluacja2021/"),
        ),
        migrations.AlterField(
            model_name="zamowienienaraport",
            name="wykres_wyjsciowy",
            field=models.ImageField(upload_to="protected/ewaluacja2021/"),
        ),
    ]
