# Generated by Django 4.2.25 on 2025-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja2021", "0018_move_files_to_protected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zamowienienaraport",
            name="status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="zamowienienaraport",
            name="uid_zadania",
            field=models.TextField(blank=True, default=""),
        ),
    ]
