# Generated by Django 5.2.14 on 2026-06-02 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ewaluacja2021", "0019_remove_null_from_string_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wierszimportumaksymalnychslotow",
            name="parent",
        ),
        migrations.AlterUniqueTogether(
            name="liczbandlauczelni",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="liczbandlauczelni",
            name="dyscyplina_naukowa",
        ),
        migrations.RemoveField(
            model_name="liczbandlauczelni",
            name="uczelnia",
        ),
        migrations.RemoveField(
            model_name="wierszimportumaksymalnychslotow",
            name="matched_autor",
        ),
        migrations.RemoveField(
            model_name="wierszimportumaksymalnychslotow",
            name="matched_dyscyplina",
        ),
        migrations.RemoveField(
            model_name="zamowienienaraport",
            name="dyscyplina_naukowa",
        ),
        migrations.DeleteModel(
            name="IloscUdzialowDlaAutora",
        ),
        migrations.DeleteModel(
            name="ImportMaksymalnychSlotow",
        ),
        migrations.DeleteModel(
            name="LiczbaNDlaUczelni",
        ),
        migrations.DeleteModel(
            name="WierszImportuMaksymalnychSlotow",
        ),
        migrations.DeleteModel(
            name="ZamowienieNaRaport",
        ),
    ]
