"""Motyw 'realistyczny' — polskie dane akademickie (domyślny, bez żartu)."""

from __future__ import annotations

from bpp.demo_data.themes.base import Theme

# --- przeniesione z dawnego names.py (skopiuj 1:1 zawartość krotek) ---
IMIONA_POL = (
    # Kobiety
    "Anna",
    "Maria",
    "Katarzyna",
    "Małgorzata",
    "Agnieszka",
    "Barbara",
    "Ewa",
    "Magdalena",
    "Elżbieta",
    "Joanna",
    "Aleksandra",
    "Monika",
    "Zofia",
    "Teresa",
    "Krystyna",
    "Halina",
    "Beata",
    "Jadwiga",
    "Danuta",
    "Iwona",
    "Renata",
    "Wanda",
    "Grażyna",
    "Dorota",
    "Janina",
    "Urszula",
    "Hanna",
    "Marta",
    "Justyna",
    "Karolina",
    "Marzena",
    "Bożena",
    "Lucyna",
    "Wiesława",
    "Stanisława",
    "Helena",
    "Natalia",
    "Paulina",
    "Patrycja",
    "Sylwia",
    "Edyta",
    "Izabela",
    # Mężczyźni
    "Jan",
    "Andrzej",
    "Piotr",
    "Krzysztof",
    "Stanisław",
    "Tomasz",
    "Paweł",
    "Józef",
    "Marcin",
    "Marek",
    "Michał",
    "Grzegorz",
    "Jerzy",
    "Tadeusz",
    "Adam",
    "Łukasz",
    "Zbigniew",
    "Ryszard",
    "Dariusz",
    "Henryk",
    "Mariusz",
    "Wojciech",
    "Robert",
    "Kazimierz",
    "Mateusz",
    "Maciej",
    "Sławomir",
    "Rafał",
    "Bogdan",
    "Janusz",
    "Jacek",
    "Jakub",
    "Artur",
    "Marian",
    "Jarosław",
    "Mirosław",
    "Antoni",
    "Wiesław",
    "Roman",
    "Edward",
    "Sebastian",
    "Damian",
    "Kamil",
    "Daniel",
    "Bartosz",
)

NAZWISKA_POL = (
    "Nowak",
    "Kowalski",
    "Wiśniewski",
    "Wójcik",
    "Kowalczyk",
    "Kamiński",
    "Lewandowski",
    "Zieliński",
    "Szymański",
    "Woźniak",
    "Dąbrowski",
    "Kozłowski",
    "Jankowski",
    "Mazur",
    "Wojciechowski",
    "Kwiatkowski",
    "Krawczyk",
    "Kaczmarek",
    "Piotrowski",
    "Grabowski",
    "Zając",
    "Pawłowski",
    "Michalski",
    "Król",
    "Wieczorek",
    "Jabłoński",
    "Wróbel",
    "Nowakowski",
    "Majewski",
    "Olszewski",
    "Jaworski",
    "Adamczyk",
    "Dudek",
    "Nowicki",
    "Pawlak",
    "Górski",
    "Witkowski",
    "Walczak",
    "Sikora",
    "Baran",
    "Rutkowski",
    "Michalak",
    "Szewczyk",
    "Ostrowski",
    "Tomaszewski",
    "Pietrzak",
    "Marciniak",
    "Wróblewski",
    "Zalewski",
    "Jakubowski",
    "Jasiński",
    "Zawadzki",
    "Sadowski",
    "Bąk",
    "Chmielewski",
    "Włodarczyk",
    "Borkowski",
    "Czarnecki",
    "Sawicki",
    "Sokołowski",
    "Urbański",
    "Kubiak",
    "Maciejewski",
    "Szczepański",
    "Kucharski",
    "Wilk",
    "Kalinowski",
    "Lis",
    "Mazurek",
    "Wysocki",
    "Adamski",
    "Kaźmierczak",
    "Wasilewski",
    "Sobczak",
    "Czerwiński",
    "Andrzejewski",
    "Cieślak",
    "Głowacki",
    "Zakrzewski",
    "Kołodziej",
    "Sikorski",
    "Krupa",
    "Stępień",
    "Kurek",
    "Brzeziński",
    "Borowski",
    "Pawlik",
    "Sowa",
    "Domagała",
    "Wojtasik",
    "Mróz",
    "Małecki",
    "Janik",
    "Bednarek",
    "Bielecki",
    "Marek",
    "Krajewski",
    "Markowski",
    "Konieczny",
    "Lasota",
)

KIERUNKI_POL = (
    "Lekarski",
    "Lekarsko-Dentystyczny",
    "Farmaceutyczny",
    "Nauk o Zdrowiu",
    "Pielęgniarstwa i Nauk o Zdrowiu",
    "Biologii i Ochrony Środowiska",
    "Chemii",
    "Fizyki, Astronomii i Informatyki Stosowanej",
    "Informatyki",
    "Matematyki, Informatyki i Mechaniki",
    "Mechaniczny",
    "Elektroniki, Telekomunikacji i Informatyki",
    "Inżynierii Środowiska",
    "Architektury",
    "Budownictwa Lądowego i Wodnego",
    "Zarządzania",
    "Ekonomii",
    "Prawa i Administracji",
    "Filozoficzny",
    "Filologii Polskiej",
    "Filologiczny",
    "Historyczny",
    "Pedagogiki",
    "Psychologii",
    "Socjologii",
    "Teologii",
    "Sztuk Pięknych",
    "Muzyki",
    "Wychowania Fizycznego",
    "Nauk Geograficznych i Geologicznych",
)

TOPICS = (
    "metod numerycznych",
    "algorytmów uczenia maszynowego",
    "biomarkerów",
    "polimorfizmów genetycznych",
    "interakcji białkowych",
    "modeli statystycznych",
    "systemów rozproszonych",
    "procedur klinicznych",
    "analizy obrazowej",
    "diagnostyki",
    "terapii celowanej",
    "farmakokinetyki",
    "biotransformacji",
    "ekspresji genowej",
    "metabolomiki",
    "proteomiki",
)

SUBJECTS = (
    "skuteczność leczenia",
    "jakość życia pacjentów",
    "wydajność systemu",
    "precyzję pomiarów",
    "stabilność wyników",
    "powtarzalność eksperymentu",
    "koszty operacyjne",
    "bezpieczeństwo procedury",
    "tolerancję terapii",
    "rokowanie pacjenta",
)

CONTEXTS = (
    "warunkach klinicznych",
    "środowisku laboratoryjnym",
    "populacji polskiej",
    "grupie kontrolnej",
    "badaniu wieloośrodkowym",
    "analizie retrospektywnej",
    "warunkach in vitro",
    "modelu zwierzęcym",
    "ośrodkach referencyjnych",
    "badaniu prospektywnym",
)

# --- nowe pule realistyczne ---
JEDNOSTKA_DZIEDZINY = (
    "Kardiologii",
    "Biochemii",
    "Mikrobiologii Lekarskiej",
    "Anatomii Prawidłowej",
    "Genetyki Molekularnej",
    "Chirurgii Ogólnej",
    "Farmakologii",
    "Patomorfologii",
    "Neurologii",
    "Pediatrii",
    "Fizjologii",
    "Immunologii",
    "Histologii",
    "Onkologii",
    "Radiologii",
)
ZRODLO_HUMAN = (
    "Medica Polonica",
    "Biochemica",
    "Clinica",
    "Neurologica",
    "Chirurgica",
    "Oncologica",
    "Pharmaceutica",
    "Microbiologica",
    "Academiae Medicae",
    "Diagnostica",
)
WYDAWCY = (
    "Wydawnictwo Naukowe PWN",
    "Wydawnictwo Lekarskie PZWL",
    "Wydawnictwo Uniwersyteckie",
    "Oficyna Wydawnicza Scholar",
    "Wydawnictwo Naukowe UAM",
    "Elsevier Urban & Partner",
    "Wydawnictwo Czelej",
    "Termedia Wydawnictwa Medyczne",
)
STRESZCZENIE_TEMPLATES = (
    "W niniejszej pracy zbadano wpływ {topic} na {subject}.",
    "Analizę przeprowadzono w {context}, z uwzględnieniem {topic}.",
    "Wyniki wskazują na istotny związek {topic} z {subject}.",
    "Celem badania była ocena {topic} w odniesieniu do {subject}.",
    "Materiał i metody obejmowały {topic} w {context}.",
    "Wnioski potwierdzają znaczenie {topic} dla {subject}.",
)

REALISTYCZNY = Theme(
    key="realistyczny",
    label="Realistyczny (polski akademicki)",
    uczelnia_nazwy=("Uniwersytet Przykładowy", "Akademia Nauk Stosowanych"),
    uczelnia_skrot="UP",
    wydzial_dziedziny=KIERUNKI_POL,
    jednostka_dziedziny=JEDNOSTKA_DZIEDZINY,
    autor_imiona=IMIONA_POL,
    autor_nazwiska=NAZWISKA_POL,
    zrodlo_human=ZRODLO_HUMAN,
    wydawcy=WYDAWCY,
    tytul_topics=TOPICS,
    tytul_subjects=SUBJECTS,
    tytul_contexts=CONTEXTS,
    streszczenie_templates=STRESZCZENIE_TEMPLATES,
)
