# Generated by Django 4.2.19 on 2025-09-05 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Rozpoczęto"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zakończono"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("running", "W trakcie"),
                            ("paused", "Wstrzymany"),
                            ("completed", "Zakończony"),
                            ("failed", "Błąd"),
                            ("cancelled", "Anulowany"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Aktualny krok"
                    ),
                ),
                (
                    "current_step_progress",
                    models.IntegerField(
                        default=0, verbose_name="Postęp aktualnego kroku (%)"
                    ),
                ),
                (
                    "total_steps",
                    models.IntegerField(default=0, verbose_name="Liczba kroków"),
                ),
                (
                    "completed_steps",
                    models.IntegerField(default=0, verbose_name="Ukończone kroki"),
                ),
                (
                    "progress_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dane postępu"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Konfiguracja importu"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Komunikat błędu"),
                ),
                (
                    "error_traceback",
                    models.TextField(blank=True, verbose_name="Ślad stosu błędu"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesja importu",
                "verbose_name_plural": "Sesje importu",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nazwa"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="Nazwa wyświetlana"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                ("order", models.IntegerField(default=0, verbose_name="Kolejność")),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="Opcjonalny"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=60,
                        help_text="Szacowany czas w sekundach",
                        verbose_name="Szacowany czas trwania",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fi-download", max_length=50, verbose_name="Klasa ikony"
                    ),
                ),
            ],
            options={
                "verbose_name": "Krok importu",
                "verbose_name_plural": "Kroki importu",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ImportStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institutions_imported", models.IntegerField(default=0)),
                ("authors_imported", models.IntegerField(default=0)),
                ("publications_imported", models.IntegerField(default=0)),
                ("journals_imported", models.IntegerField(default=0)),
                ("publishers_imported", models.IntegerField(default=0)),
                ("conferences_imported", models.IntegerField(default=0)),
                ("statements_imported", models.IntegerField(default=0)),
                ("institutions_failed", models.IntegerField(default=0)),
                ("authors_failed", models.IntegerField(default=0)),
                ("publications_failed", models.IntegerField(default=0)),
                ("total_api_calls", models.IntegerField(default=0)),
                (
                    "total_api_time",
                    models.FloatField(
                        default=0.0, help_text="Total API time in seconds"
                    ),
                ),
                ("coffee_breaks_recommended", models.IntegerField(default=0)),
                ("motivational_messages_shown", models.IntegerField(default=0)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="pbn_import.importsession",
                        verbose_name="Sesja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statystyki importu",
                "verbose_name_plural": "Statystyki importu",
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Czas"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Informacja"),
                            ("warning", "Ostrzeżenie"),
                            ("error", "Błąd"),
                            ("success", "Sukces"),
                            ("critical", "Krytyczny"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Poziom",
                    ),
                ),
                ("step", models.CharField(max_length=100, verbose_name="Krok")),
                ("message", models.TextField(verbose_name="Komunikat")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="Szczegóły"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="pbn_import.importsession",
                        verbose_name="Sesja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wpis dziennika importu",
                "verbose_name_plural": "Wpisy dziennika importu",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "-timestamp"],
                        name="pbn_import__session_d5adf4_idx",
                    ),
                    models.Index(fields=["level"], name="pbn_import__level_83059d_idx"),
                ],
            },
        ),
    ]
