# Generated by Django 4.2.19 on 2025-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_import", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID zadania Celery"
            ),
        ),
    ]
