# Generated by Django 4.2.25 on 2026-01-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_import", "0002_add_task_id_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportInconsistency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Czas"),
                ),
                (
                    "inconsistency_type",
                    models.CharField(
                        choices=[
                            ("author_not_found", "Autor nie znaleziony w publikacji"),
                            ("author_auto_fixed", "Autor automatycznie poprawiony"),
                            ("author_needs_manual_fix", "Wymaga ręcznej korekty"),
                            (
                                "no_override_without_disciplines",
                                "Brak nadpisania - brak dyscyplin",
                            ),
                            ("publication_not_found", "Brak publikacji w BPP"),
                            ("author_not_in_bpp", "Brak autora w BPP"),
                        ],
                        max_length=50,
                        verbose_name="Typ nieścisłości",
                    ),
                ),
                (
                    "pbn_publication_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID publikacji PBN"
                    ),
                ),
                (
                    "pbn_publication_title",
                    models.TextField(blank=True, verbose_name="Tytuł publikacji PBN"),
                ),
                (
                    "pbn_author_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID autora PBN"
                    ),
                ),
                (
                    "pbn_author_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nazwa autora PBN"
                    ),
                ),
                (
                    "pbn_discipline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dyscyplina PBN"
                    ),
                ),
                (
                    "bpp_publication_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID publikacji BPP"
                    ),
                ),
                (
                    "bpp_publication_title",
                    models.TextField(blank=True, verbose_name="Tytuł publikacji BPP"),
                ),
                (
                    "bpp_author_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID autora BPP"
                    ),
                ),
                (
                    "bpp_author_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nazwa autora BPP"
                    ),
                ),
                ("message", models.TextField(verbose_name="Opis problemu")),
                (
                    "action_taken",
                    models.TextField(blank=True, verbose_name="Podjęte działanie"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Rozwiązano"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data rozwiązania"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inconsistencies",
                        to="pbn_import.importsession",
                        verbose_name="Sesja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nieścisłość importu",
                "verbose_name_plural": "Nieścisłości importu",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "-timestamp"],
                        name="pbn_import__session_ddd09a_idx",
                    ),
                    models.Index(
                        fields=["inconsistency_type"],
                        name="pbn_import__inconsi_a04a9d_idx",
                    ),
                    models.Index(
                        fields=["resolved"], name="pbn_import__resolve_5d9dac_idx"
                    ),
                ],
            },
        ),
    ]
