# Generated by Django 4.2.25 on 2026-01-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_import", "0003_add_import_inconsistency"),
    ]

    operations = [
        migrations.AddField(
            model_name="importinconsistency",
            name="bpp_publication_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Typ publikacji BPP",
            ),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="task_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="ID zadania Celery"
            ),
        ),
    ]
