# Generated by Django 4.2.25 on 2026-01-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_import", "0004_add_bpp_publication_content_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportStatistics",
        ),
    ]
