# Generated by Django 4.2.25 on 2026-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_import", "0006_remove_importstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Ostatnia aktualizacja"
            ),
        ),
    ]
