# Generated by Django 4.2.25 on 2026-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_import", "0007_add_last_updated_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(
                fields=["status", "-started_at"], name="pbn_import__status_ddf88f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importsession",
            index=models.Index(
                fields=["user", "status"], name="pbn_import__user_id_fc5399_idx"
            ),
        ),
    ]
