# Generated by Django 4.2.25 on 2026-01-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_import", "0008_add_importsession_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importinconsistency",
            name="inconsistency_type",
            field=models.CharField(
                choices=[
                    ("author_not_found", "Autor nie znaleziony w publikacji"),
                    ("author_auto_fixed", "Autor automatycznie poprawiony"),
                    ("author_needs_manual_fix", "Wymaga ręcznej korekty"),
                    (
                        "no_override_without_disciplines",
                        "Brak nadpisania - brak dyscyplin",
                    ),
                    ("publication_not_found", "Brak publikacji w BPP"),
                    ("author_not_in_bpp", "Brak autora w BPP"),
                    (
                        "duplicate_orcid",
                        "Duplikat ORCID - wielu autorów z tym samym ORCID",
                    ),
                    (
                        "leftover_affiliation_data",
                        "Pozostałe dane afiliacji po przetworzeniu autorów",
                    ),
                ],
                max_length=50,
                verbose_name="Typ nieścisłości",
            ),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="error_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Komunikat błędu"
            ),
        ),
        migrations.AlterField(
            model_name="importsession",
            name="error_traceback",
            field=models.TextField(
                blank=True, default="", verbose_name="Ślad stosu błędu"
            ),
        ),
    ]
