# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn_import', '0010_alter_importinconsistency_inconsistency_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinconsistency',
            name='session',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='pbn_import.importsession', verbose_name='Sesja'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='session',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pbn_import.importsession', verbose_name='Sesja'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
