# Generated by Django 5.2.14 on 2026-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn_import', '0011_alter_importinconsistency_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinconsistency',
            name='inconsistency_type',
            field=models.CharField(choices=[('author_not_found', 'Autor nie znaleziony w publikacji'), ('author_auto_fixed', 'Autor automatycznie poprawiony'), ('author_replaced', 'Autor zamieniony na innego'), ('author_matched_by_name', 'Autor dopasowany po imieniu i nazwisku'), ('author_needs_manual_fix', 'Wymaga ręcznej korekty'), ('discipline_auto_assigned', 'Dyscyplina przypisana automatycznie z PBN'), ('discipline_added_as_sub', 'Subdyscyplina dopisana automatycznie z PBN'), ('discipline_conflict_no_room', 'Konflikt dyscyplin - brak miejsca'), ('no_override_without_disciplines', 'Brak nadpisania - brak dyscyplin'), ('publication_not_found', 'Brak publikacji w BPP'), ('author_not_in_bpp', 'Brak autora w BPP'), ('duplicate_orcid', 'Duplikat ORCID - wielu autorów z tym samym ORCID'), ('leftover_affiliation_data', 'Pozostałe dane afiliacji po przetworzeniu autorów')], max_length=50, verbose_name='Typ nieścisłości'),
        ),
    ]
