repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.3
      hooks:
        - id: ruff
          args: ["--fix", "--exit-non-zero-on-fix"]
        - id: ruff-format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v6.0.0'
      hooks:
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
            exclude: ^baseline/baseline\.sql$
        -   id: trailing-whitespace
            exclude: ^baseline/baseline\.sql$
        -   id: mixed-line-ending
            exclude: ^baseline/baseline\.sql$
        -   id: check-added-large-files
            args: ['--maxkb=500']
        -   id: check-merge-conflict
        -   id: check-case-conflict
        -   id: debug-statements

    - repo: local
      hooks:
        - id: trufflehog
          name: TruffleHog
          description: Detect secrets in your data.
          entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
          language: system
          stages: ["pre-commit", "pre-push"]

#    - repo: https://github.com/gitguardian/ggshield
#      rev: v1.43.0
#      hooks:
#        - id: ggshield
#          language: python
#          stages: [commit]

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.8
      hooks:
        - id: actionlint

#
#    - repo: local
#      hooks:
#        - id: pylint
#          name: pylint
#          entry: pylint
#          language: system
#          types: [python]
#          args:
#            [
#              "-rn", # Only display messages
#              "-sn", # Don't display the score
#            ]
#
