repos:
    - repo: local
      hooks:
        - id: trufflehog
          name: TruffleHog
          description: Detect secrets in your data.
          entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
          language: system
          stages: ["commit", "push"]

    - repo: https://github.com/gitguardian/ggshield
      rev: v1.43.0
      hooks:
        - id: ggshield
          language: python
          stages: [commit]

    - repo: local
      hooks:
        - id: no_debug
          name: No debug on prod
          types: [python]
          args: [--multiline]
          entry: 'breakpoint\(\)|set_trace'
          language: pygrep

    - repo: https://github.com/zahorniak/pre-commit-circleci.git
      rev: v1.2.0 # Ensure this is the latest tag, comparing to the Releases tab
      hooks:
        - id: circleci_validate

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
        - id: actionlint

    - repo: https://github.com/PyCQA/autoflake
      rev: 'v2.3.1'
      hooks:
        - id: autoflake
          args: ['--in-place', '--remove-all-unused-imports',]

    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: 'v2.0.4'
      hooks:
        - id: autopep8
          args: ['--in-place', '-aaa',]

    - repo: https://github.com/hadialqattan/pycln
      rev: 'v2.5.0'
      hooks:
        - id: pycln

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: 'v5.10.1'  # Use the revision sha / tag you want to point at
      hooks:
        - id: isort
          args: ["--profile", "black"]

    - repo: https://github.com/psf/black
      rev: '25.9.0'
      hooks:
        -   id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v6.0.0'
      hooks:
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: mixed-line-ending

    - repo: https://github.com/PyCQA/flake8
      rev: '7.3.0'
      hooks:
        - id: flake8
          args: ["--exclude=*/migrations/*"]

#
#    - repo: local
#      hooks:
#        - id: pylint
#          name: pylint
#          entry: pylint
#          language: system
#          types: [python]
#          args:
#            [
#              "-rn", # Only display messages
#              "-sn", # Don't display the score
#            ]
#
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.20.0
      hooks:
        - id: pyupgrade
          args: ["--py37-plus"]
