repos:
    - repo: https://github.com/humitos/mirrors-autoflake.git
      rev: v1.1
      hooks:
        - id: autoflake
          args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        -   id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: flake8
