repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.9
      hooks:
        - id: ruff
          args: ["--fix", "--exit-non-zero-on-fix"]
        - id: ruff-format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v6.0.0'
      hooks:
        -   id: check-yaml
        -   id: check-toml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: mixed-line-ending

    - repo: local
      hooks:
        - id: trufflehog
          name: TruffleHog
          description: Detect secrets in your data.
          entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
          language: system
          stages: ["commit", "push"]

    - repo: https://github.com/gitguardian/ggshield
      rev: v1.43.0
      hooks:
        - id: ggshield
          language: python
          stages: [commit]

    - repo: local
      hooks:
        - id: no_debug
          name: No debug on prod
          types: [python]
          args: [--multiline]
          entry: 'breakpoint\(\)|set_trace'
          language: pygrep

    - repo: https://github.com/zahorniak/pre-commit-circleci.git
      rev: v1.2.0 # Ensure this is the latest tag, comparing to the Releases tab
      hooks:
        - id: circleci_validate

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.8
      hooks:
        - id: actionlint

#
#    - repo: local
#      hooks:
#        - id: pylint
#          name: pylint
#          entry: pylint
#          language: system
#          types: [python]
#          args:
#            [
#              "-rn", # Only display messages
#              "-sn", # Don't display the score
#            ]
#
