sudo: required
dist: trusty 
language: python
python: 2.7

cache: 
  directories:
    - $HOME/.cache/bower
    - $HOME/.cache/yarn
    - $HOME/.cache/pip
    - $HOME/.npm

services:
  - redis-server

addons:
  apt:
    sources: 
      - sourceline: "ppa:ubuntu-mozilla-daily/firefox-aurora"          
    packages:
      - xvfb
      - postgresql-plpython-9.4
      - postgresql-9.4
      - language-pack-pl

before_install: 
  # Xvfb
  - export DISPLAY=98.0
  - Xvfb $DISPLAY -screen 0 1024x768x24 > /dev/null 2>&1 &

  # Geckodriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz
  - tar -xzvf geckodriver-v0.16.1-linux64.tar.gz
  - mv geckodriver /home/travis/virtualenv/python2.7.12

  # Latest Firefox
  - sudo apt-get update
  - apt-cache show firefox|grep Version
  - sudo apt-get remove --purge firefox
  - sudo apt-get install -y firefox=53.0.3+build1-0ubuntu0.14.04.2
  - firefox -version
  - /usr/local/bin/firefox -version
  - ls -las /usr/local/bin/firefox
  - ls -las /usr/local
  - find / -name firefox-bin | grep firefox-bin

  # Environment
  - export PGHOST=localhost
  - export PGUSER=bpp
  - export PATH=.:$PATH
  - export DJANGO_SETTINGS_MODULE=django_bpp.settings.test
  - export DJANGO_BPP_SECRET_KEY=0xdeadbeefbabe
  - export DJANGO_BPP_MEDIA_ROOT=$HOME/media
  - export DJANGO_BPP_NOTIFICATIONS_HOST=localhost
  - export DJANGO_BPP_NOTIFICATIONS_PORT=8080
  - export DJANGO_LIVE_TEST_SERVER_ADDRESS=localhost:9000-15000
  - export DJANGO_BPP_DB_HOST=localhost

install:
  - apt-get source nginx
  - git clone https://github.com/wandenberg/nginx-push-stream-module.git > /dev/null
  - export BUILD_ROOT_DIR=`pwd -P`
  - ls -las
  - cd nginx-1.4.6
  - ./configure --add-module=../nginx-push-stream-module --prefix=$BUILD_ROOT_DIR > /dev/null
  - make > /dev/null
  - make install > /dev/null
  - cd ..
  - cd conf
  - wget https://raw.githubusercontent.com/mpasternak/django-bpp/dev/.travis/nginx.conf.patch
  - patch -p0 < nginx.conf.patch
  - cd ..
  - sbin/nginx

  - nvm install 6 > /dev/null
  - npm install -g yarn > /dev/null
  - yarn global add bower grunt-cli > /dev/null

  - sudo /etc/init.d/postgresql restart

  - psql -U postgres -c "CREATE COLLATION \"pl_PL\"(locale='pl_PL.utf8');" template1
  - createlang -U postgres plpythonu template1

  - createuser -dsU postgres $PGUSER
  - createdb -U $PGUSER bpp

  - cp .travis/stellar.yaml .travis/pytest.ini . 

  - pip install -U pip
  - pip install -U tox

script: 
  - /bin/echo DISPLAY: $DISPLAY
  - /bin/echo FIREFOX VERSION
  - firefox -version
  - tox
