language: python
cache: pip
python: 2.7

addons:
  apt:
    packages:
      - xvfb
      - postgresql-plpython-9.4
      - postgresql-9.4
      - oracle-java8-installer
      - oracle-java8-set-default

before_install: 
  - export PGHOST=localhost
  - export PGUSER=bpp
  - export PATH=.:$PATH

install:
  - nvm install 6
  - npm install -g yarn
  - yarn global add bower grunt-cli

  - createuser -dsU postgres bpp
  - createdb -U bpp 
  - pip install -U tox
  - export DISPLAY=":99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - wget https://goo.gl/uTXEJ1
  - java -jar uTXEJ1 &

script: tox