sudo: required

language: python

python: 
  - "2.7"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.yarn-cache

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sudo yarn global add bower grunt-cli npm

  - sudo service postgresql stop

  - pip install -q -U tox pip setuptools virtualenv

  # jak nie dam tego teraz, zrobi katalogi przez dockera, owner root:root
  # a potem bedzie permission deny przy build_wheel wiec:
  - mkdir -p dist dist_dev

services:
  - docker

script:
  - make -f Makefile.docker travis
