#
# Zajmuje się komputerami produkcyjnymi.
# 
# Vagrant/Staging czy serwisy demo to również serwisy produkcyjne
#

staging:
	ansible-playbook ansible/webserver.yml --private-key=.vagrant/machines/staging/virtualbox/private_key

production:
	ansible-playbook -i "/Volumes/Dane zaszyfrowane/Biblioteka Glowna/ansible/hosts.cfg" ansible/webserver.yml

bppdemo:
	ansible-playbook -i "/Volumes/Dane zaszyfrowane/IPL/ansible/hosts.cfg" ansible/webserver.yml

