#
# Zajmuje się komputerami produkcyjnymi.
# 
# Vagrant/Staging czy serwisy demo to również serwisy produkcyjne
#

staging:
	ansible-playbook ansible/webserver.yml --private-key=.vagrant/machines/staging/virtualbox/private_key

demo-vm-ansible:
	ansible-playbook ansible/demo-vm.yml --private-key=.vagrant/machines/staging/virtualbox/private_key

