# Generated by Django 4.2.19 on 2025-08-31 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pbn_api", "0060_alter_osobazinstytucji_personid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoNotRemind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ignored_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data ignorowania"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Opcjonalny powód ignorowania tego naukowca",
                        verbose_name="Powód ignorowania",
                    ),
                ),
                (
                    "ignored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ignorowany przez",
                    ),
                ),
                (
                    "scientist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="do_not_remind",
                        to="pbn_api.scientist",
                        verbose_name="Naukowiec PBN",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignorowany naukowiec PBN",
                "verbose_name_plural": "Ignorowani naukowcy PBN",
                "ordering": ["-ignored_at"],
            },
        ),
    ]
