# Generated by Django 4.2.25 on 2025-12-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import long_running.notification_mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0403_autorzy_ostatnio_zmieniony"),
        ("pbn_api", "0068_add_cache_models"),
        ("importer_autorow_pbn", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchCacheRebuildOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("started_on", models.DateTimeField(blank=True, null=True)),
                ("finished_on", models.DateTimeField(blank=True, null=True)),
                ("finished_successfully", models.BooleanField(default=False)),
                ("traceback", models.TextField(blank=True, null=True)),
                (
                    "total_scientists",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Łączna liczba naukowców"
                    ),
                ),
                (
                    "processed_scientists",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Przetworzonych naukowców"
                    ),
                ),
                (
                    "matches_found",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Znalezionych dopasowań"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Przebudowa cache'u importu autorów PBN",
                "verbose_name_plural": "Przebudowy cache'u importu autorów PBN",
            },
            bases=(
                long_running.notification_mixins.NullNotificationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CachedScientistMatch",
            fields=[
                (
                    "scientist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cached_match",
                        serialize=False,
                        to="pbn_api.scientist",
                        verbose_name="Naukowiec PBN",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Data obliczenia"),
                ),
                (
                    "matched_autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_scientist_matches",
                        to="bpp.autor",
                        verbose_name="Dopasowany autor BPP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache dopasowania naukowca PBN",
                "verbose_name_plural": "Cache dopasowań naukowców PBN",
                "indexes": [
                    models.Index(
                        fields=["computed_at"], name="importer_au_compute_2352da_idx"
                    )
                ],
            },
        ),
    ]
