# Generated by Django 4.2.25 on 2025-10-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_label",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nazwa pozycji menu"
                    ),
                ),
                (
                    "menu_url",
                    models.CharField(max_length=500, verbose_name="URL pozycji menu"),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Data kliknięcia"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kliknięcie w menu",
                "verbose_name_plural": "Kliknięcia w menu",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "menu_label"],
                        name="admin_dashb_user_id_830412_idx",
                    ),
                    models.Index(
                        fields=["user", "-clicked_at"],
                        name="admin_dashb_user_id_7c1441_idx",
                    ),
                ],
            },
        ),
    ]
