---
django_deps_version: "20170426"

supervisor_logdir: /var/log/supervisor

django_home_dir: /home/{{ django_user }}

django_media_root: /home/{{ django_user }}/media

django_venv_dir: "{{ django_home_dir }}/env"

django_python_version: 3.6
django_envvar_prefix: "{{ django_project_name|upper }}"

django_manage_py: "{{ django_home_dir }}/vexec python -mdjango_bpp.manage_command"

django_db_name: "{{ database_name }}"
django_db_user: "{{ database_user }}"
django_db_password: "{{ database_password }}"
django_db_host: localhost

django_db_port: 5432
postgresql_version: 9.5

rabbitmq_user: "{{ database_user }}"
rabbitmq_vhost: "{{ django_hostname }}"
rabbitmq_password: "rabbit-{{ rabbitmq_user }}"

django_gunicorn_port: 9999

django_nginx_http_port: 80
django_nginx_https_port: 443

django_nginx_push_stream_allowed_ips:
  - 127.0.0.1

celery_broker_url: "amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:5672/{{ rabbitmq_vhost }}"

certs_path: "{{ role_path }}/files/"

django_uzywaj_punktacji_wewnetrznej: 1

django_theme_name: app-blue

django_enable_new_reports: 1

django_session_security_warn_after: 540

django_session_security_expire_after: 600