# Generated by Django 4.2.25 on 2026-02-14 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("bpp", "0409_set_default_jest_wydawnictwem_zwartym"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(max_length=50, verbose_name="dostawca danych"),
                ),
                (
                    "identifier",
                    models.CharField(max_length=255, verbose_name="identyfikator"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fetched", "Pobrano dane"),
                            ("verified", "Zweryfikowano"),
                            ("source_matched", "Dopasowano źródło"),
                            ("authors_matched", "Dopasowano autorów"),
                            ("review", "Do przeglądu"),
                            ("completed", "Zakończono"),
                            ("cancelled", "Anulowano"),
                        ],
                        default="fetched",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="Pełna odpowiedź API dostawcy",
                        verbose_name="dane surowe",
                    ),
                ),
                (
                    "normalized_data",
                    models.JSONField(
                        help_text="Dane FetchedPublication jako dict",
                        verbose_name="dane znormalizowane",
                    ),
                ),
                (
                    "matched_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Wybory użytkownika na poszczególnych etapach",
                        verbose_name="dane dopasowane",
                    ),
                ),
                (
                    "jest_wydawnictwem_zwartym",
                    models.BooleanField(
                        default=False, verbose_name="jest wydawnictwem zwartym"
                    ),
                ),
                (
                    "created_record_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID utworzonego rekordu"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="zmodyfikowano"),
                ),
                (
                    "charakter_formalny",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.charakter_formalny",
                        verbose_name="charakter formalny",
                    ),
                ),
                (
                    "created_record_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="typ utworzonego rekordu",
                    ),
                ),
                (
                    "jezyk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.jezyk",
                        verbose_name="język",
                    ),
                ),
                (
                    "typ_kbn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.typ_kbn",
                        verbose_name="typ KBN",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importer_publikacji_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
                (
                    "wydawca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.wydawca",
                        verbose_name="wydawca",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.zrodlo",
                        verbose_name="źródło",
                    ),
                ),
            ],
            options={
                "verbose_name": "sesja importu",
                "verbose_name_plural": "sesje importu",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ImportedAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="kolejność")),
                (
                    "family_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="nazwisko"
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="imiona"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="ORCID"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("auto_exact", "Automatyczne dokładne"),
                            ("auto_loose", "Automatyczne luźne"),
                            ("manual", "Ręczne"),
                            ("unmatched", "Niedopasowany"),
                            ("skip", "Pomiń"),
                        ],
                        default="unmatched",
                        max_length=20,
                        verbose_name="status dopasowania",
                    ),
                ),
                (
                    "matched_autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.autor",
                        verbose_name="dopasowany autor",
                    ),
                ),
                (
                    "matched_dyscyplina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.dyscyplina_naukowa",
                        verbose_name="dyscyplina",
                    ),
                ),
                (
                    "matched_jednostka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.jednostka",
                        verbose_name="jednostka",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="importer_publikacji.importsession",
                        verbose_name="sesja",
                    ),
                ),
            ],
            options={
                "verbose_name": "importowany autor",
                "verbose_name_plural": "importowani autorzy",
                "ordering": ["order"],
                "unique_together": {("session", "order")},
            },
        ),
    ]
