# Generated by Django 4.2.25 on 2026-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_publikacji", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedauthor",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("auto_exact", "Automatyczne dokładne"),
                    ("auto_loose", "Automatyczne luźne"),
                    ("manual", "Ręczne"),
                    ("unmatched", "Niedopasowany"),
                ],
                default="unmatched",
                max_length=20,
                verbose_name="status dopasowania",
            ),
        ),
    ]
