# Generated by Django 4.2.25 on 2026-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_publikacji", "0002_remove_skip_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedauthor",
            name="dyscyplina_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto_jedyna", "Jedyna dyscyplina autora"),
                    ("zgloszenie", "Z aplikacji zgłoszeń publikacji"),
                    ("manual", "Wybór użytkownika"),
                ],
                default="",
                max_length=20,
                verbose_name="źródło dyscypliny",
            ),
        ),
    ]
