# Generated by Django 4.2.30 on 2026-04-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("importer_publikacji", "0004_rename_user_to_created_by_add_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importsession",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="importer_publikacji_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utworzył",
            ),
        ),
    ]
