# Generated by Django 4.2.30 on 2026-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importer_publikacji", "0005_alter_importsession_created_by"),
        ("importer_publikacji", "0005_importsession_wydawnictwo_nadrzedne"),
    ]

    operations = []
