# Generated by Django 5.2.13 on 2026-04-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importer_publikacji", "0005_alter_importsession_created_by"),
        ("importer_publikacji", "0005_importsession_wydawnictwo_nadrzedne"),
    ]

    operations = []
