# Generated by Django 5.2.14 on 2026-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0006_merge_20260421_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Celery task ID'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='last_error_message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ostatni komunikat błędu'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='last_error_traceback',
            field=models.TextField(blank=True, default='', verbose_name='Pełny traceback ostatniego błędu'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='last_failed_stage',
            field=models.CharField(blank=True, default='', help_text="'fetch' lub 'create'", max_length=16, verbose_name='Etap który padł'),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='status',
            field=models.CharField(choices=[('fetched', 'Pobrano dane'), ('fetching', 'Trwa pobieranie'), ('creating', 'Trwa tworzenie rekordu'), ('import_failed', 'Błąd importu'), ('verified', 'Zweryfikowano'), ('source_matched', 'Dopasowano źródło'), ('authors_matched', 'Dopasowano autorów'), ('review', 'Do przeglądu'), ('completed', 'Zakończono'), ('cancelled', 'Anulowano')], default='fetched', max_length=20, verbose_name='status'),
        ),
    ]
