# Generated by Django 5.2.14 on 2026-05-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0416_rename_dynamic_columns_to_admin'),
        ('importer_publikacji', '0006_merge_20260421_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedAuthor_Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pewnosc', models.FloatField(verbose_name='pewność')),
                ('powod', models.CharField(max_length=32, verbose_name='powód dopasowania')),
                ('publikacji_count', models.PositiveIntegerField(default=0, verbose_name='liczba publikacji')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.autor', verbose_name='autor BPP')),
                ('imported_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='importer_publikacji.importedauthor', verbose_name='importowany autor')),
            ],
            options={
                'verbose_name': 'kandydat na autora',
                'verbose_name_plural': 'kandydaci na autora',
                'ordering': ['-pewnosc', '-publikacji_count'],
                'unique_together': {('imported_author', 'autor')},
            },
        ),
    ]
