# Generated by Django 5.2.13 on 2026-04-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importer_publikacji", "0006_merge_20260420_2212"),
        ("importer_publikacji", "0006_merge_20260421_1100"),
    ]

    operations = []
