# Generated by Django 5.2.14 on 2026-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0007_importedauthor_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedauthor',
            name='zapisany_jako',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='zapisane nazwisko'),
        ),
    ]
