# Generated by Django 5.2.14 on 2026-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer_publikacji", "0007_async_import_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importsession",
            name="identifier",
            field=models.TextField(verbose_name="identyfikator"),
        ),
    ]
