# Generated by Django 5.2.14 on 2026-06-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0007_merge_20260421_1248'),
        ('importer_publikacji', '0010_importedauthor_zapisany_jako'),
    ]

    operations = [
    ]
