# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0011_merge_20260601_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedauthor',
            name='session',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='importer_publikacji.importsession', verbose_name='sesja'),
        ),
    ]
