# Generated by Django 5.2.14 on 2026-06-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0423_merge_20260602_1430'),
        ('importer_publikacji', '0011_merge_20260601_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='uczelnia',
            field=models.ForeignKey(blank=True, help_text='Uczelnia hosta, z którego utworzono sesję (multi-hosted). Steruje konfiguracją PBN użytą do sprawdzenia/eksportu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer_publikacji_sessions', to='bpp.uczelnia', verbose_name='uczelnia'),
        ),
    ]
