# Generated by Django 5.2.14 on 2026-06-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0012_alter_importedauthor_session'),
        ('importer_publikacji', '0012_importsession_uczelnia'),
    ]

    operations = [
    ]
