# Generated by Django 5.2.15 on 2026-07-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0013_merge_20260604_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedauthor',
            name='typ_ogolny',
            field=models.SmallIntegerField(choices=[(0, 'autor'), (1, 'redaktor')], default=0, verbose_name='typ autora'),
        ),
    ]
