# Generated by Django 5.2.15 on 2026-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0014_importedauthor_typ_ogolny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsession',
            name='status',
            field=models.CharField(choices=[('fetched', 'Pobrano dane'), ('fetching', 'Trwa pobieranie'), ('creating', 'Trwa tworzenie rekordu'), ('import_failed', 'Błąd importu'), ('verified', 'Zweryfikowano'), ('source_matched', 'Dopasowano źródło'), ('authors_matched', 'Dopasowano autorów'), ('punktacja', 'Punktacja'), ('review', 'Do przeglądu'), ('completed', 'Zakończono'), ('cancelled', 'Anulowano')], default='fetched', max_length=20, verbose_name='status'),
        ),
    ]
