# Generated by Django 5.2.15 on 2026-07-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0016_alter_importsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleWorksImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50, verbose_name='dostawca danych')),
                ('raw_input', models.TextField(verbose_name='surowy wsad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='zmodyfikowano')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importer_publikacji_batches', to=settings.AUTH_USER_MODEL, verbose_name='utworzył')),
            ],
            options={
                'verbose_name': 'import wielu prac',
                'verbose_name_plural': 'importy wielu prac',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MultipleWorksImportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('raw_bibtex', models.TextField(verbose_name='pojedynczy wpis BibTeX')),
                ('title', models.TextField(blank=True, default='', verbose_name='tytuł (podgląd)')),
                ('parse_error', models.TextField(blank=True, default='', verbose_name='błąd parsowania')),
                ('skipped', models.BooleanField(default=False, verbose_name='pominięty')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='importer_publikacji.multipleworksimport', verbose_name='paczka')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_entry', to='importer_publikacji.importsession', verbose_name='sesja importu')),
            ],
            options={
                'verbose_name': 'wpis paczki',
                'verbose_name_plural': 'wpisy paczki',
                'ordering': ['order'],
            },
        ),
    ]
