# Generated by Django 5.2.15 on 2026-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_publikacji', '0017_multiple_works_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='rodzaj_rekordu',
            field=models.CharField(choices=[('ciagle', 'Wydawnictwo ciągłe'), ('zwarte', 'Wydawnictwo zwarte'), ('patent', 'Patent')], default='ciagle', help_text='Docelowy model rekordu. Dla wartości innej niż „Patent” dispatch nadal kieruje się polem „jest wydawnictwem zwartym” (zgodność wsteczna).', max_length=10, verbose_name='rodzaj rekordu'),
        ),
    ]
