# Generated by Django 5.2.16 on 2026-08-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pbn_api', '0079_constraint_publikacja_instytucji'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekordPrzywroconyPrzezImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('przywrocono', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Kiedy import wskrzesił ten rekord.', verbose_name='Przywrócono')),
                ('zrodlo_importu', models.CharField(help_text='Która ścieżka importu wskrzesiła rekord (articles / books / chapters).', max_length=50, verbose_name='Źródło importu')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('pbn_uid', models.ForeignKey(blank=True, help_text='Rekord PBN, przez który import trafił na tę publikację.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbn_api.publication', verbose_name='Publikacja w PBN')),
            ],
            options={
                'verbose_name': 'rekord przywrócony przez import',
                'verbose_name_plural': 'rekordy przywrócone przez import',
                'ordering': ('-przywrocono',),
                'indexes': [models.Index(fields=['-przywrocono', 'content_type'], name='pbnint_przywr_data_ct_idx')],
            },
        ),
    ]
