# Generated by Django 5.2.16 on 2026-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_api", "0079_constraint_publikacja_instytucji"),
        ("pbn_integrator", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rekordprzywroconyprzezimport",
            index=models.Index(
                fields=["content_type", "object_id"], name="pbnint_przywr_ct_objid_idx"
            ),
        ),
    ]
