# Generated by Django 4.2.19 on 2025-09-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0390_add_filters_to_sumy_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrzemapoaniePracAutora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liczba_prac_ciaglych",
                    models.IntegerField(default=0, verbose_name="Liczba prac ciągłych"),
                ),
                (
                    "liczba_prac_zwartych",
                    models.IntegerField(default=0, verbose_name="Liczba prac zwartych"),
                ),
                (
                    "utworzono",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data przemapowania",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
                (
                    "jednostka_do",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_do",
                        to="bpp.jednostka",
                        verbose_name="Jednostka docelowa",
                    ),
                ),
                (
                    "jednostka_z",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_z",
                        to="bpp.jednostka",
                        verbose_name="Jednostka źródłowa",
                    ),
                ),
                (
                    "utworzono_przez",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Wykonane przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przemapowanie prac autora",
                "verbose_name_plural": "Przemapowania prac autorów",
                "ordering": ["-utworzono"],
            },
        ),
    ]
