# Generated by Django 4.2.19 on 2025-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("przemapuj_prace_autora", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="przemapoaniepracautora",
            name="prace_ciagle_historia",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista ID i tytułów przemapowanych prac ciągłych",
                verbose_name="Historia prac ciągłych",
            ),
        ),
        migrations.AddField(
            model_name="przemapoaniepracautora",
            name="prace_zwarte_historia",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista ID i tytułów przemapowanych prac zwartych",
                verbose_name="Historia prac zwartych",
            ),
        ),
    ]
