# Generated by Django 4.2.25 on 2025-12-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0402_autorzy_data_oswiadczenia"),
    ]

    operations = [
        migrations.CreateModel(
            name="KomparatorZrodelMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ostatnie_uruchomienie",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ostatnie uruchomienie"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Bezczynny"),
                            ("running", "W trakcie"),
                            ("completed", "Zakończony"),
                            ("error", "Błąd"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ostatni_blad",
                    models.TextField(
                        blank=True, default="", verbose_name="Ostatni błąd"
                    ),
                ),
                (
                    "statystyki",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Statystyki"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadane komparatora źródeł",
                "verbose_name_plural": "Metadane komparatora źródeł",
            },
        ),
        migrations.CreateModel(
            name="LogAktualizacjiZrodla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rok", models.PositiveSmallIntegerField(verbose_name="Rok")),
                (
                    "typ_zmiany",
                    models.CharField(
                        choices=[
                            ("punkty", "Punkty"),
                            ("dyscypliny", "Dyscypliny"),
                            ("oba", "Punkty i dyscypliny"),
                        ],
                        max_length=20,
                        verbose_name="Typ zmiany",
                    ),
                ),
                (
                    "wartosc_przed",
                    models.TextField(
                        blank=True, default="", verbose_name="Wartość przed"
                    ),
                ),
                (
                    "wartosc_po",
                    models.TextField(blank=True, default="", verbose_name="Wartość po"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiedy"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logi_aktualizacji_pbn",
                        to="bpp.zrodlo",
                        verbose_name="Źródło",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log aktualizacji źródła",
                "verbose_name_plural": "Logi aktualizacji źródeł",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RozbieznoscZrodlaPBN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rok",
                    models.PositiveSmallIntegerField(db_index=True, verbose_name="Rok"),
                ),
                (
                    "ma_rozbieznosc_punktow",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Ma rozbieżność punktów",
                    ),
                ),
                (
                    "punkty_bpp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Punkty BPP",
                    ),
                ),
                (
                    "punkty_pbn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Punkty PBN",
                    ),
                ),
                (
                    "ma_rozbieznosc_dyscyplin",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Ma rozbieżność dyscyplin",
                    ),
                ),
                (
                    "dyscypliny_bpp",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Lista kodów dyscyplin w BPP, oddzielona przecinkami",
                        verbose_name="Dyscypliny BPP",
                    ),
                ),
                (
                    "dyscypliny_pbn",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Lista kodów dyscyplin w PBN, oddzielona przecinkami",
                        verbose_name="Dyscypliny PBN",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano"),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rozbieznosci_pbn",
                        to="bpp.zrodlo",
                        verbose_name="Źródło",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rozbieżność źródła BPP-PBN",
                "verbose_name_plural": "Rozbieżności źródeł BPP-PBN",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["zrodlo"], name="pbn_kompara_zrodlo__8665da_idx"
                    ),
                    models.Index(fields=["rok"], name="pbn_kompara_rok_c7cf81_idx"),
                    models.Index(
                        fields=["ma_rozbieznosc_punktow"],
                        name="pbn_kompara_ma_rozb_93e674_idx",
                    ),
                    models.Index(
                        fields=["ma_rozbieznosc_dyscyplin"],
                        name="pbn_kompara_ma_rozb_dfd108_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="pbn_kompara_created_dcf0dc_idx"
                    ),
                ],
                "unique_together": {("zrodlo", "rok")},
            },
        ),
    ]
