# Generated by Django 4.2.25 on 2025-12-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_komparator_zrodel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrakujacaDyscyplinaPBN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kod_pbn",
                    models.CharField(
                        help_text="Kod dyscypliny w formacie PBN, np. '503'",
                        max_length=10,
                        unique=True,
                        verbose_name="Kod PBN",
                    ),
                ),
                (
                    "kod_bpp",
                    models.CharField(
                        help_text="Kod dyscypliny przekonwertowany do formatu BPP, np. '5.3'",
                        max_length=10,
                        verbose_name="Kod BPP",
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nazwa"
                    ),
                ),
                (
                    "liczba_zrodel",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ile źródeł w PBN używa tej dyscypliny",
                        verbose_name="Liczba źródeł",
                    ),
                ),
                (
                    "ostatnia_aktualizacja",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ostatnia aktualizacja"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brakująca dyscyplina PBN",
                "verbose_name_plural": "Brakujące dyscypliny PBN",
                "ordering": ["kod_pbn"],
            },
        ),
    ]
