# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0424_alter_autor_dyscyplina_autor_and_more'),
        ('pbn_komparator_zrodel', '0002_add_brakujaca_dyscyplina_pbn'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rozbieznosczrodlapbn',
            name='pbn_kompara_zrodlo__8665da_idx',
        ),
        migrations.RemoveIndex(
            model_name='rozbieznosczrodlapbn',
            name='pbn_kompara_rok_c7cf81_idx',
        ),
        migrations.RemoveIndex(
            model_name='rozbieznosczrodlapbn',
            name='pbn_kompara_ma_rozb_93e674_idx',
        ),
        migrations.RemoveIndex(
            model_name='rozbieznosczrodlapbn',
            name='pbn_kompara_ma_rozb_dfd108_idx',
        ),
        migrations.AlterField(
            model_name='rozbieznosczrodlapbn',
            name='zrodlo',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='rozbieznosci_pbn', to='bpp.zrodlo', verbose_name='Źródło'),
        ),
    ]
