from django.urls import path

from . import views
from .views.retry import ImportTaskRetryView
from .views.task_status import ImportTaskStatusView
from .views.zgloszenie import ZgloszenieWyborView

app_name = "importer_publikacji"

urlpatterns = [
    path(
        "",
        views.IndexView.as_view(),
        name="index",
    ),
    path(
        "sessions/",
        views.SessionListView.as_view(),
        name="sessions",
    ),
    path(
        "fetch/",
        views.FetchView.as_view(),
        name="fetch",
    ),
    path(
        "<int:session_id>/verify/",
        views.VerifyView.as_view(),
        name="verify",
    ),
    path(
        "<int:session_id>/source/",
        views.SourceView.as_view(),
        name="source",
    ),
    path(
        "<int:session_id>/authors/",
        views.AuthorsView.as_view(),
        name="authors",
    ),
    path(
        "<int:session_id>/authors/<int:author_id>/match/",
        views.AuthorMatchView.as_view(),
        name="author-match",
    ),
    path(
        "<int:session_id>/authors/<int:author_id>/info/",
        views.AuthorInfoView.as_view(),
        name="author-info",
    ),
    path(
        "<int:session_id>/authors/<int:author_id>/delete/",
        views.AuthorDeleteView.as_view(),
        name="author-delete",
    ),
    path(
        "<int:session_id>/authors/<int:author_id>/create-new/",
        views.AuthorCreateNewView.as_view(),
        name="author-create-new",
    ),
    path(
        "<int:session_id>/authors/<int:author_id>/candidates-modal/",
        views.AuthorCandidatesModalView.as_view(),
        name="author-candidates-modal",
    ),
    path(
        "<int:session_id>/authors/create-unmatched/",
        views.CreateUnmatchedAuthorsView.as_view(),
        name="authors-create-unmatched",
    ),
    path(
        "<int:session_id>/authors/<int:author_id>/set-orcid/",
        views.AuthorSetOrcidView.as_view(),
        name="author-set-orcid",
    ),
    path(
        "<int:session_id>/authors/set-orcids/",
        views.AuthorsSetOrcidsView.as_view(),
        name="authors-set-orcids",
    ),
    path(
        "<int:session_id>/authors/confirm/",
        views.AuthorsConfirmView.as_view(),
        name="authors-confirm",
    ),
    path(
        "<int:session_id>/punktacja/",
        views.PunktacjaView.as_view(),
        name="punktacja",
    ),
    path(
        "<int:session_id>/pbn/",
        views.PbnCheckView.as_view(),
        name="pbn",
    ),
    path(
        "<int:session_id>/pbn/select/",
        views.PbnSelectView.as_view(),
        name="pbn-select",
    ),
    path(
        "<int:session_id>/pbn/clear/",
        views.PbnClearView.as_view(),
        name="pbn-clear",
    ),
    path(
        "<int:session_id>/review/",
        views.ReviewView.as_view(),
        name="review",
    ),
    path(
        "<int:session_id>/create/",
        views.CreateView.as_view(),
        name="create",
    ),
    path(
        "<int:session_id>/done/",
        views.DoneView.as_view(),
        name="done",
    ),
    path(
        "<int:session_id>/cancel/",
        views.CancelView.as_view(),
        name="cancel",
    ),
    path(
        "<int:session_id>/zgloszenie/wybierz/",
        ZgloszenieWyborView.as_view(),
        name="zgloszenie-wybierz",
    ),
    path(
        "batch/<int:batch_id>/",
        views.MultipleWorksImportDetailView.as_view(),
        name="batch-detail",
    ),
    path(
        "batch/entry/<int:entry_id>/import/",
        views.BatchEntryImportView.as_view(),
        name="batch-entry-import",
    ),
    path(
        "batch/entry/<int:entry_id>/skip/",
        views.BatchEntrySkipView.as_view(),
        name="batch-entry-skip",
    ),
    path(
        "task-status/<int:session_id>/",
        ImportTaskStatusView.as_view(),
        name="task-status",
    ),
    path(
        "task-retry/<int:session_id>/",
        ImportTaskRetryView.as_view(),
        name="task-retry",
    ),
]
