from .conference import *  # noqa
from .discipline import *  # noqa
from .institution import *  # noqa
from .journal import *  # noqa
from .monkeypatch_nowrap_foreignkey_admin import *  # noqa
from .oswiadczenieinstytucji import *  # noqa
from .publication import *  # noqa
from .publikacjainstytucji import *  # noqa
from .publisher import *  # noqa
from .scientist import *  # noqa
from .sentdata import *  # noqa
from .tlumacz_dyscyplin import *  # noqa
