# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi istniejące pliki do katalogu protected/import_pracownikow/"""
    ImportPracownikow = apps.get_model("import_pracownikow", "ImportPracownikow")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "import_pracownikow")
    os.makedirs(new_dir, exist_ok=True)

    for obj in ImportPracownikow.objects.exclude(plik_xls=""):
        if obj.plik_xls:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik_xls.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik_xls = f"protected/import_pracownikow/{filename}"
                obj.save(update_fields=["plik_xls"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("import_pracownikow", "0008_nullbooleanfield"),
    ]

    operations = [
        migrations.RunPython(move_files_to_protected, noop),
        migrations.AlterField(
            model_name="importpracownikow",
            name="plik_xls",
            field=models.FileField(upload_to="protected/import_pracownikow/"),
        ),
    ]
