# Generated by Django 5.2.15 on 2026-07-09 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _ustaw_stan(apps, schema_editor):
    Model = apps.get_model("import_pracownikow", "ImportPracownikow")
    Model.objects.filter(performed=True, integrated=True).update(stan="zintegrowany")
    Model.objects.exclude(performed=True, integrated=True).update(stan="porzucony")


def _wstecz(apps, schema_editor):
    pass  # pola performed/integrated już usunięte — brak sensownego wstecz


class Migration(migrations.Migration):
    dependencies = [
        ("import_pracownikow", "0009_move_files_to_protected"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importpracownikow",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RemoveField(
            model_name="importpracownikow",
            name="last_updated_on",
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="current_stage",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="language",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="log",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="log_seq",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="result_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="stage_states",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="stan",
            field=models.CharField(
                choices=[
                    ("utworzony", "utworzony"),
                    ("przeanalizowany", "przeanalizowany (dry-run gotowy)"),
                    ("zatwierdzony", "zatwierdzony do zapisu"),
                    ("zintegrowany", "zintegrowany"),
                    ("porzucony", "porzucony"),
                ],
                default="utworzony",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="status_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(_ustaw_stan, _wstecz),
        migrations.RemoveField(
            model_name="importpracownikow",
            name="integrated",
        ),
        migrations.RemoveField(
            model_name="importpracownikow",
            name="performed",
        ),
        migrations.AlterField(
            model_name="importpracownikow",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
