# Generated by Django 5.2.15 on 2026-07-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0467_seed_crossref_mapper_rows"),
        ("import_pracownikow", "0010_liveops"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikowrow",
            name="diff_do_utworzenia",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="pominiety_bo_nieaktualny",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.autor",
            ),
        ),
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="autor_jednostka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.autor_jednostka",
            ),
        ),
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="funkcja_autora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.funkcja_autora",
            ),
        ),
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="grupa_pracownicza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.grupa_pracownicza",
            ),
        ),
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="jednostka",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.jednostka",
            ),
        ),
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="wymiar_etatu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.wymiar_etatu",
            ),
        ),
    ]
