# Generated by Django 5.2.15 on 2026-07-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_pracownikow', '0011_row_nullable_diff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importpracownikow',
            name='mapowanie_kolumn',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='importpracownikow',
            name='stan',
            field=models.CharField(choices=[('utworzony', 'utworzony'), ('zmapowany', 'zmapowany (kolumny określone)'), ('przeanalizowany', 'przeanalizowany (dry-run gotowy)'), ('zatwierdzony', 'zatwierdzony do zapisu'), ('zintegrowany', 'zintegrowany'), ('porzucony', 'porzucony')], default='utworzony', max_length=20),
        ),
        migrations.CreateModel(
            name='ProfilMapowania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('mapowanie', models.JSONField(default=dict)),
                ('ostatnio_uzyty', models.DateTimeField(blank=True, null=True)),
                ('utworzony_przez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil mapowania importu pracowników',
                'verbose_name_plural': 'profile mapowania importu pracowników',
                'ordering': ['nazwa'],
            },
        ),
    ]
