# Generated by Django 5.2.15 on 2026-07-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0467_seed_crossref_mapper_rows'),
        ('import_pracownikow', '0012_mapowanie_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpracownikowrow',
            name='confidence',
            field=models.CharField(blank=True, choices=[('twardy', 'twardy match'), ('zgadywanie', 'zgadywanie'), ('wielu', 'wielu kandydatów'), ('brak', 'brak dopasowania')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='importpracownikowrow',
            name='korekta_uzytkownika',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importpracownikowrow',
            name='wybrany_kandydat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bpp.autor'),
        ),
        migrations.CreateModel(
            name='ImportPracownikowRowKandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pewnosc', models.FloatField(verbose_name='pewność')),
                ('powod', models.CharField(max_length=32, verbose_name='powód dopasowania')),
                ('publikacji_count', models.PositiveIntegerField(default=0, verbose_name='liczba publikacji')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.autor', verbose_name='autor BPP')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydaci', to='import_pracownikow.importpracownikowrow', verbose_name='wiersz importu')),
            ],
            options={
                'verbose_name': 'kandydat na autora (import pracowników)',
                'verbose_name_plural': 'kandydaci na autora (import pracowników)',
                'ordering': ['-pewnosc'],
            },
        ),
    ]
