# Generated by Django 5.2.15 on 2026-07-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0467_seed_crossref_mapper_rows'),
        ('import_pracownikow', '0013_confidence_kandydaci'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpracownikowrow',
            name='utworz_nowego',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImportPracownikowOdpiecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaznaczone', models.BooleanField(default=False)),
                ('wykonane', models.BooleanField(default=False)),
                ('autor_jednostka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.autor_jednostka', verbose_name='powiązanie autor-jednostka')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpiecia', to='import_pracownikow.importpracownikow', verbose_name='import pracowników')),
            ],
            options={
                'verbose_name': 'odpięcie autora spoza pliku (import pracowników)',
                'verbose_name_plural': 'odpięcia autorów spoza pliku (import pracowników)',
                'ordering': ['autor_jednostka__autor__nazwisko'],
            },
        ),
    ]
