# Generated by Django 5.2.15 on 2026-07-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0467_seed_crossref_mapper_rows"),
        ("import_pracownikow", "0015_przepnij_prace"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="tworz_brakujace_jednostki",
            field=models.BooleanField(
                default=True,
                help_text="Gdy zaznaczone, jednostki nieobecne w bazie (i bez bliskiego dopasowania) trafiają na ekran weryfikacji do utworzenia. Gdy odznaczone — wiersze bez dopasowanej jednostki są pomijane.",
                verbose_name="Twórz brakujące jednostki",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="jednostka_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twardy", "twardy match"),
                    ("zgadywanie", "zgadywanie"),
                    ("wielu", "wielu kandydatów"),
                    ("brak", "brak dopasowania"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ImportPracownikowJednostka",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa_zrodlowa",
                    models.CharField(max_length=512, verbose_name="nazwa źródłowa"),
                ),
                (
                    "skrot_sugerowany",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="sugerowany skrót"
                    ),
                ),
                (
                    "tryb",
                    models.CharField(
                        choices=[
                            ("zgadywanie", "auto-dopasowanie (podobna nazwa)"),
                            ("brak", "brak dopasowania (do utworzenia)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auto_similarity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="podobieństwo auto"
                    ),
                ),
                (
                    "decyzja",
                    models.CharField(
                        choices=[
                            (
                                "akceptuj",
                                "akceptuj (utwórz nową / użyj auto-dopasowania)",
                            ),
                            ("mapuj", "mapuj na istniejącą"),
                            ("pomin", "pomiń (nie importuj tych wierszy)"),
                        ],
                        default="akceptuj",
                        max_length=20,
                    ),
                ),
                (
                    "auto_jednostka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.jednostka",
                        verbose_name="auto-dopasowana jednostka",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jednostki_do_decyzji",
                        to="import_pracownikow.importpracownikow",
                        verbose_name="import pracowników",
                    ),
                ),
                (
                    "utworzona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ustawiane przez integrację. Guard idempotencji (restart / podwójny commit nie duplikuje jednostek).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.jednostka",
                        verbose_name="jednostka utworzona/rozstrzygnięta",
                    ),
                ),
                (
                    "wybrana_jednostka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.jednostka",
                        verbose_name="wybrana istniejąca jednostka (mapuj)",
                    ),
                ),
                (
                    "wybrany_parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Miejsce w drzewie dla nowej jednostki. Puste = root (gdy uczelnia nie używa wydziałów) albo Wydział Domyślny (gdy używa).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.jednostka",
                        verbose_name="wybrany parent (wydział)",
                    ),
                ),
            ],
            options={
                "verbose_name": "decyzja o jednostce (import pracowników)",
                "verbose_name_plural": "decyzje o jednostkach (import pracowników)",
                "ordering": ["nazwa_zrodlowa"],
                "unique_together": {("parent", "nazwa_zrodlowa")},
            },
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="zrodlo_jednostki",
            field=models.ForeignKey(
                blank=True,
                help_text="Decyzja o źródłowej nazwie jednostki (współdzielona przez wiersze o tej samej nazwie). Wypełniona, gdy jednostka wymaga rozstrzygnięcia (utworzenie / mapowanie / auto-dopasowanie).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiersze",
                to="import_pracownikow.importpracownikowjednostka",
            ),
        ),
    ]
