# Generated by Django 5.2.15 on 2026-07-11 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0467_seed_crossref_mapper_rows"),
        (
            "import_pracownikow",
            "0016_importpracownikow_tworz_brakujace_jednostki_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="tworz_brakujace_tytuly",
            field=models.BooleanField(
                default=True,
                help_text="Gdy zaznaczone, tytuły nieobecne w bazie (i bez bliskiego dopasowania) trafiają na ekran weryfikacji do utworzenia. Gdy odznaczone — wiersze z niedopasowanym tytułem zostają bez tytułu.",
                verbose_name="Twórz brakujące tytuły",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="tytul_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twardy", "twardy match"),
                    ("zgadywanie", "zgadywanie"),
                    ("wielu", "wielu kandydatów"),
                    ("brak", "brak dopasowania"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ImportPracownikowTytul",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa_zrodlowa",
                    models.CharField(max_length=512, verbose_name="nazwa źródłowa"),
                ),
                (
                    "tryb",
                    models.CharField(
                        choices=[
                            ("zgadywanie", "auto-dopasowanie (podobna nazwa)"),
                            ("brak", "brak dopasowania (do utworzenia)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auto_similarity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="podobieństwo auto"
                    ),
                ),
                (
                    "nazwa_do_utworzenia",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="nazwa do utworzenia",
                    ),
                ),
                (
                    "skrot_do_utworzenia",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="skrót do utworzenia",
                    ),
                ),
                (
                    "decyzja",
                    models.CharField(
                        choices=[
                            (
                                "akceptuj",
                                "akceptuj (utwórz nowy / użyj auto-dopasowania)",
                            ),
                            ("mapuj", "mapuj na istniejący"),
                            ("pomin", "pomiń (nie ustawiaj tytułu tym wierszom)"),
                        ],
                        default="akceptuj",
                        max_length=20,
                    ),
                ),
                (
                    "auto_tytul",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.tytul",
                        verbose_name="auto-dopasowany tytuł",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tytuly_do_decyzji",
                        to="import_pracownikow.importpracownikow",
                        verbose_name="import pracowników",
                    ),
                ),
                (
                    "utworzony",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ustawiane przez integrację. Guard idempotencji (restart / podwójny commit nie duplikuje tytułów).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.tytul",
                        verbose_name="tytuł utworzony/rozstrzygnięty",
                    ),
                ),
                (
                    "wybrany_tytul",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.tytul",
                        verbose_name="wybrany istniejący tytuł (mapuj)",
                    ),
                ),
            ],
            options={
                "verbose_name": "decyzja o tytule (import pracowników)",
                "verbose_name_plural": "decyzje o tytułach (import pracowników)",
                "ordering": ["nazwa_zrodlowa"],
                "unique_together": {("parent", "nazwa_zrodlowa")},
            },
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="zrodlo_tytulu",
            field=models.ForeignKey(
                blank=True,
                help_text="Decyzja o źródłowym tytule (współdzielona przez wiersze o tej samej nazwie). Wypełniona, gdy tytuł wymaga rozstrzygnięcia (utworzenie / mapowanie / auto-dopasowanie).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiersze_tytul",
                to="import_pracownikow.importpracownikowtytul",
            ),
        ),
    ]
