# Generated by Django 5.2.15 on 2026-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "import_pracownikow",
            "0017_importpracownikow_tworz_brakujace_tytuly_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="zakres_integracji",
            field=models.CharField(
                choices=[
                    ("pelny", "pełny import (struktura + osoby)"),
                    ("jednostki", "tylko jednostki"),
                    ("struktura", "jednostki + tytuły (bez osób)"),
                ],
                default="pelny",
                help_text="Co „Zapisz do bazy” faktycznie tworzy: pełny import (struktura + osoby), same jednostki, albo jednostki + tytuły (bez osób). Ustawiane przez przycisk zatwierdzenia na hubie.",
                max_length=20,
                verbose_name="Zakres integracji",
            ),
        ),
    ]
