# Generated by Django 5.2.15 on 2026-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0018_importpracownikow_zakres_integracji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importpracownikow",
            name="stan",
            field=models.CharField(
                choices=[
                    ("utworzony", "utworzony"),
                    ("zmapowany", "zmapowany (kolumny określone)"),
                    ("przeanalizowany", "przeanalizowany (dry-run gotowy)"),
                    ("zatwierdzony", "zatwierdzony do zapisu"),
                    ("struktura_zintegrowana", "struktura zapisana (osoby czekają)"),
                    ("zintegrowany", "zintegrowany"),
                    ("porzucony", "porzucony"),
                ],
                default="utworzony",
                max_length=32,
            ),
        ),
    ]
