# Generated by Django 5.2.15 on 2026-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0019_alter_importpracownikow_stan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twardy", "twardy match"),
                    ("zgadywanie", "zgadywanie"),
                    ("wielu", "wielu kandydatów"),
                    ("brak", "brak dopasowania"),
                    ("reczny", "ręczny (wybór użytkownika)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
