# Generated by Django 5.2.15 on 2026-07-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0020_confidence_status_reczny"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="data_zmian_personalnych",
            field=models.DateField(
                blank=True,
                help_text="Data, na którą obowiązuje ten wykaz zmian personalnych. Zostanie użyta jako data początku pracy przy DOPISYWANIU autora do jednostki (nowe powiązanie), gdy wiersz w pliku nie podaje własnej daty zatrudnienia. Nie nadpisuje dat z pliku ani dat istniejących powiązań.",
                null=True,
                verbose_name="Data zmian personalnych",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="przepnij_wszystkie_prace",
            field=models.BooleanField(
                default=False,
                help_text="Gdy zaznaczone, wszystkie prace autorów zostaną domyślnie oznaczone do przepięcia na jednostki z pliku. ZAZNACZ przy imporcie struktury autorów do ŚWIEŻEJ bazy (np. tuż po imporcie do PBN). Na „dojrzałej” bazie produkcyjnej NA PEWNO zostaw odznaczone — przepięłoby to historyczne afiliacje. Można korygować per wiersz przed zapisem osób.",
                verbose_name="Zaznacz wszystkie prace do przepięcia na nowe jednostki",
            ),
        ),
    ]
