# Generated by Django 5.2.15 on 2026-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0021_pola_data_zmian_i_przepnij_wszystkie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importpracownikowrow",
            name="confidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twardy", "twardy match"),
                    ("zgadywanie", "zgadywanie"),
                    ("wielu", "wielu kandydatów"),
                    ("brak", "brak dopasowania"),
                    ("reczny", "ręczny (wybór użytkownika)"),
                    ("dedup", "rekord główny (deduplikacja)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
