# Generated by Django 5.2.15 on 2026-07-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0468_stopien_sluzbowy_stanowisko_dydaktyczne"),
        ("import_pracownikow", "0022_alter_importpracownikowrow_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="tworz_brakujace_stanowiska",
            field=models.BooleanField(
                default=True,
                help_text="Gdy zaznaczone, stanowiska dydaktyczne nieobecne w bazie (i bez bliskiego dopasowania) trafiają na ekran weryfikacji do utworzenia. Gdy odznaczone — wiersze z niedopasowanym stanowiskiem zostają bez stanowiska.",
                verbose_name="Twórz brakujące stanowiska dydaktyczne",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikow",
            name="tworz_brakujace_stopnie",
            field=models.BooleanField(
                default=True,
                help_text="Gdy zaznaczone, stopnie służbowe nieobecne w bazie (i bez bliskiego dopasowania) trafiają na ekran weryfikacji do utworzenia. Gdy odznaczone — wiersze z niedopasowanym stopniem zostają bez stopnia.",
                verbose_name="Twórz brakujące stopnie służbowe",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="stanowisko_dydaktyczne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bpp.stanowiskodydaktyczne",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="stanowisko_dydaktyczne_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twardy", "twardy match"),
                    ("zgadywanie", "zgadywanie"),
                    ("wielu", "wielu kandydatów"),
                    ("brak", "brak dopasowania"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="stopien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bpp.stopiensluzbowy",
            ),
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="stopien_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("twardy", "twardy match"),
                    ("zgadywanie", "zgadywanie"),
                    ("wielu", "wielu kandydatów"),
                    ("brak", "brak dopasowania"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importpracownikow",
            name="zakres_integracji",
            field=models.CharField(
                choices=[
                    ("pelny", "pełny import (struktura + osoby)"),
                    ("jednostki", "tylko jednostki"),
                    (
                        "struktura",
                        "jednostki + tytuły + stopnie + stanowiska (bez osób)",
                    ),
                ],
                default="pelny",
                help_text="Co „Zapisz do bazy” faktycznie tworzy: pełny import (struktura + osoby), same jednostki, albo jednostki + tytuły + stopnie + stanowiska (bez osób). Ustawiane przez przycisk zatwierdzenia na hubie.",
                max_length=20,
                verbose_name="Zakres integracji",
            ),
        ),
        migrations.CreateModel(
            name="ImportPracownikowStanowisko",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa_zrodlowa",
                    models.CharField(max_length=512, verbose_name="nazwa źródłowa"),
                ),
                (
                    "tryb",
                    models.CharField(
                        choices=[
                            ("zgadywanie", "auto-dopasowanie (podobna nazwa)"),
                            ("brak", "brak dopasowania (do utworzenia)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auto_similarity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="podobieństwo auto"
                    ),
                ),
                (
                    "nazwa_do_utworzenia",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="nazwa do utworzenia",
                    ),
                ),
                (
                    "skrot_do_utworzenia",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="skrót do utworzenia",
                    ),
                ),
                (
                    "decyzja",
                    models.CharField(
                        choices=[
                            (
                                "akceptuj",
                                "akceptuj (utwórz nowe / użyj auto-dopasowania)",
                            ),
                            ("mapuj", "mapuj na istniejące"),
                            ("pomin", "pomiń (nie ustawiaj stanowiska tym wierszom)"),
                        ],
                        default="akceptuj",
                        max_length=20,
                    ),
                ),
                (
                    "auto_stanowisko",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.stanowiskodydaktyczne",
                        verbose_name="auto-dopasowane stanowisko",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stanowiska_do_decyzji",
                        to="import_pracownikow.importpracownikow",
                        verbose_name="import pracowników",
                    ),
                ),
                (
                    "utworzone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ustawiane przez integrację. Guard idempotencji (restart / podwójny commit nie duplikuje stanowisk).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.stanowiskodydaktyczne",
                        verbose_name="stanowisko utworzone/rozstrzygnięte",
                    ),
                ),
                (
                    "wybrane_stanowisko",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.stanowiskodydaktyczne",
                        verbose_name="wybrane istniejące stanowisko (mapuj)",
                    ),
                ),
            ],
            options={
                "verbose_name": "decyzja o stanowisku dydaktycznym (import pracowników)",
                "verbose_name_plural": "decyzje o stanowiskach dydaktycznych (import pracowników)",
                "ordering": ["nazwa_zrodlowa"],
                "unique_together": {("parent", "nazwa_zrodlowa")},
            },
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="zrodlo_stanowiska_dydaktycznego",
            field=models.ForeignKey(
                blank=True,
                help_text="Decyzja o źródłowym stanowisku dydaktycznym (współdzielona przez wiersze o tej samej nazwie). Wypełniona, gdy stanowisko wymaga rozstrzygnięcia (utworzenie / mapowanie / auto-dopasowanie).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiersze_stanowisko",
                to="import_pracownikow.importpracownikowstanowisko",
            ),
        ),
        migrations.CreateModel(
            name="ImportPracownikowStopien",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nazwa_zrodlowa",
                    models.CharField(max_length=512, verbose_name="nazwa źródłowa"),
                ),
                (
                    "tryb",
                    models.CharField(
                        choices=[
                            ("zgadywanie", "auto-dopasowanie (podobna nazwa)"),
                            ("brak", "brak dopasowania (do utworzenia)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "auto_similarity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="podobieństwo auto"
                    ),
                ),
                (
                    "nazwa_do_utworzenia",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="nazwa do utworzenia",
                    ),
                ),
                (
                    "skrot_do_utworzenia",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="skrót do utworzenia",
                    ),
                ),
                (
                    "decyzja",
                    models.CharField(
                        choices=[
                            (
                                "akceptuj",
                                "akceptuj (utwórz nowy / użyj auto-dopasowania)",
                            ),
                            ("mapuj", "mapuj na istniejący"),
                            ("pomin", "pomiń (nie ustawiaj stopnia tym wierszom)"),
                        ],
                        default="akceptuj",
                        max_length=20,
                    ),
                ),
                (
                    "auto_stopien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.stopiensluzbowy",
                        verbose_name="auto-dopasowany stopień",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stopnie_do_decyzji",
                        to="import_pracownikow.importpracownikow",
                        verbose_name="import pracowników",
                    ),
                ),
                (
                    "utworzony",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ustawiane przez integrację. Guard idempotencji (restart / podwójny commit nie duplikuje stopni).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.stopiensluzbowy",
                        verbose_name="stopień utworzony/rozstrzygnięty",
                    ),
                ),
                (
                    "wybrany_stopien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="bpp.stopiensluzbowy",
                        verbose_name="wybrany istniejący stopień (mapuj)",
                    ),
                ),
            ],
            options={
                "verbose_name": "decyzja o stopniu służbowym (import pracowników)",
                "verbose_name_plural": "decyzje o stopniach służbowych (import pracowników)",
                "ordering": ["nazwa_zrodlowa"],
                "unique_together": {("parent", "nazwa_zrodlowa")},
            },
        ),
        migrations.AddField(
            model_name="importpracownikowrow",
            name="zrodlo_stopnia",
            field=models.ForeignKey(
                blank=True,
                help_text="Decyzja o źródłowym stopniu służbowym (współdzielona przez wiersze o tej samej nazwie). Wypełniona, gdy stopień wymaga rozstrzygnięcia (utworzenie / mapowanie / auto-dopasowanie).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wiersze_stopien",
                to="import_pracownikow.importpracownikowstopien",
            ),
        ),
    ]
