# Generated by Django 5.2.15 on 2026-07-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0023_slowniki_stopnie_stanowiska"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikowrow",
            name="stany_pol_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
