# Generated by Django 5.2.16 on 2026-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0024_importpracownikowrow_stany_pol_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="plik_po_imporcie",
            field=models.FileField(
                blank=True,
                help_text="Zamrożony, skorygowany plik „po imporcie” wygenerowany przy finalizacji — trwały rekord tego, co trafiło do BPP (niezależny od późniejszych edycji). Housekeeping go NIE kasuje.",
                null=True,
                upload_to="protected/import_pracownikow/",
            ),
        ),
    ]
