# Generated by Django 5.2.16 on 2026-07-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0469_przyszle_daty_zakonczenia_zatrudnienia"),
        ("import_pracownikow", "0025_importpracownikow_plik_po_imporcie"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                help_text="Uczelnia, do której należy ten import — ustalana z requestu (host → Site → Uczelnia) w chwili utworzenia importu. Integracja biegnie w tle (bez requestu), więc uczelnię trzeba złapać w widoku i tu utrwalić. W instalacji multi-hosted (>1 uczelnia) to JEDYNE wiarygodne źródło uczelni do tworzenia jednostek — bez tego ``get_single_uczelnia_or_none()`` zwróciłoby ``None`` i nowe jednostki nie powstałyby. ``NULL`` dla starych importów i instalacji single-tenant (fallback: jedyna uczelnia w systemie).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bpp.uczelnia",
                verbose_name="uczelnia",
            ),
        ),
    ]
