# Generated by Django 5.2.16 on 2026-07-15 17:07

import django.db.models.deletion
from django.db import migrations, models


def backfill_uczelnia(apps, schema_editor):
    """Single-tenant: przypisz jedyną uczelnię wszystkim NULL-owym
    ``ProfilMapowania`` i ``ImportPracownikow`` — bez tego ścisłe filtrowanie
    po uczelni ukryłoby legacy-rekordy (sprzed pola ``uczelnia``). 0 lub >1
    uczelni → no-op (rekordy nowe są już ostemplowane, jednoznacznej uczelni
    brak, nie zgadujemy)."""
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    if Uczelnia.objects.count() != 1:
        return
    u = Uczelnia.objects.get()
    apps.get_model("import_pracownikow", "ProfilMapowania").objects.filter(
        uczelnia__isnull=True
    ).update(uczelnia=u)
    apps.get_model("import_pracownikow", "ImportPracownikow").objects.filter(
        uczelnia__isnull=True
    ).update(uczelnia=u)


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0469_przyszle_daty_zakonczenia_zatrudnienia"),
        ("import_pracownikow", "0026_importpracownikow_uczelnia"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilmapowania",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                help_text="Uczelnia, do której należy profil (multi-hosted). NULL dla profili sprzed migracji 0027 / instalacji single-tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.uczelnia",
                verbose_name="uczelnia",
            ),
        ),
        migrations.RunPython(backfill_uczelnia, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profilmapowania",
            name="nazwa",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="profilmapowania",
            unique_together={("uczelnia", "nazwa")},
        ),
    ]
