# Generated by Django 5.2.16 on 2026-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_pracownikow", "0027_profil_uczelnia"),
    ]

    operations = [
        migrations.AddField(
            model_name="importpracownikow",
            name="nadpisuj_daty_zatrudnienia",
            field=models.BooleanField(
                default=False,
                help_text="Gdy zaznaczone, daty rozpoczęcia i zakończenia pracy <strong>ISTNIEJĄCYCH</strong> okresów zatrudnienia zostaną <strong>NADPISANE</strong> wartościami z pliku — tam, gdzie plik niesie datę różną od bazy.<br>Użyj do KOREKTY dat (np. po wcześniejszym imporcie pliku bez dat, który ostemplował wszystkich datą importu).<br>Puste komórki pliku niczego nie kasują. Dotyczy wyłącznie osób obecnych w pliku.",
                verbose_name="Nadpisuj daty zatrudnienia (od/do) wartościami z pliku",
            ),
        ),
    ]
