# Generated by Django 4.2.25 on 2025-12-16 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PbnWysylkaOswiadczenTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("running", "W trakcie"),
                            ("completed", "Zakonczone"),
                            ("failed", "Blad"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("total_publications", models.IntegerField(default=0)),
                ("processed_publications", models.IntegerField(default=0)),
                (
                    "current_publication",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("rok_od", models.IntegerField(default=2022)),
                ("rok_do", models.IntegerField(default=2025)),
                (
                    "resume_mode",
                    models.BooleanField(
                        default=False, help_text="True = kontynuuj, False = od nowa"
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pbn_wysylka_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie wysylki oswiadczen",
                "verbose_name_plural": "Zadania wysylki oswiadczen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PbnWysylkaLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("pbn_uid", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Sukces"),
                            ("error", "Blad"),
                            ("skipped", "Pominieto"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("json_sent", models.JSONField(blank=True, null=True)),
                ("json_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "app_label": "bpp",
                            "model__in": ["wydawnictwo_ciagle", "wydawnictwo_zwarte"],
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="pbn_wysylka_oswiadczen.pbnwysylkaoswiadczentask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log wysylki",
                "verbose_name_plural": "Logi wysylki",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "status"], name="pbn_wysylka_task_id_ae3506_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="pbn_wysylka_content_f4ae2f_idx",
                    ),
                ],
            },
        ),
    ]
