# Generated by Django 4.2.25 on 2025-12-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_wysylka_oswiadczen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbnwysylkaoswiadczentask",
            name="tytul",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Filtr tytulu (zawiera)",
                max_length=500,
            ),
        ),
    ]
