# Generated by Django 4.2.25 on 2026-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_wysylka_oswiadczen", "0002_add_tytul_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbnwysylkaoswiadczentask",
            name="synchronized_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pbnwysylkalog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Sukces"),
                    ("error", "Blad"),
                    ("skipped", "Pominieto"),
                    ("synchronized", "Zsynchronizowana"),
                    ("maintenance", "Prace serwisowe PBN"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pbnwysylkaoswiadczentask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekuje"),
                    ("running", "W trakcie"),
                    ("completed", "Zakonczone"),
                    ("failed", "Blad"),
                    ("maintenance", "Prace serwisowe PBN"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
