# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pbn_wysylka_oswiadczen', '0003_add_synchronized_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbnwysylkalog',
            name='content_type',
            field=models.ForeignKey(db_index=False, limit_choices_to={'app_label': 'bpp', 'model__in': ['wydawnictwo_ciagle', 'wydawnictwo_zwarte']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='pbnwysylkalog',
            name='task',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pbn_wysylka_oswiadczen.pbnwysylkaoswiadczentask'),
        ),
    ]
