---
- name: Stat cached selenium
  stat: path=/var/cache/wget/selenium-server-standalone-{{ selenium_version }}.jar
  register: sel

- name: Download Selenium
  get_url: url=https://goo.gl/uTXEJ1 dest=/var/cache/wget/
  when: not sel.stat.exists
  notify: 
    - restart supervisor services

- name: Stat cached geckodriver
  stat: path=/var/cache/wget/geckodriver-v{{ geckodriver_version }}-{{ geckodriver_platform }}.tar.gz
  register: gd

- name: Download geckodriver
  get_url: url=https://github.com/mozilla/geckodriver/releases/download/v{{ geckodriver_version }}/geckodriver-v{{ geckodriver_version }}-{{ geckodriver_platform }}.tar.gz dest=/var/cache/wget/
  when: not gd.stat.exists

- name: Stat geckodriver bin
  stat: path=/usr/bin/geckodriver
  register: gd

- name: Unpack geckodriver
  shell: tar -xzf /var/cache/wget/geckodriver-v{{ geckodriver_version }}-{{ geckodriver_platform }}.tar.gz
  args: 
    chdir: /usr/bin
    creates: /usr/bin/geckodriver
  when: not gd.stat.exists
  notify: 
    - restart supervisor services

- name: Supervisor service template installed
  template: src=selenium.conf dest=/etc/supervisor/conf.d/0050-selenium.conf
  notify: 
    - restart supervisor
    - restart supervisor services

- name: Add localhost to /etc/hosts
  lineinfile: dest=/etc/hosts line="192.168.111.1 macosx.localnet" owner=root group=root mode=0644
