---
- name: Stat cached selenium
  stat: path=/var/cache/wget/selenium-server-standalone-{{ selenium_version }}.jar
  register: sel

- name: Download Selenium
  get_url: url=https://goo.gl/uTXEJ1 dest=/var/cache/wget/
  when: not sel.stat.exists
  notify: 
    - restart supervisor services

- name: Supervisor service template installed
  template: src=selenium.conf dest=/etc/supervisor/conf.d/0050-selenium.conf
  notify: 
    - restart supervisor
    - restart supervisor services

- name: Add localhost to /etc/hosts
  lineinfile: dest=/etc/hosts line="192.168.111.1 macosx.localnet" owner=root group=root mode=0644

- include: geckodriver.yml
- include: chromedriver.yml
