# Generated by Django 3.0.11 on 2021-03-15 00:41

from django.db import migrations, models

import bpp.models.uczelnia


class Migration(migrations.Migration):

    dependencies = [
        ("raport_slotow", "0010_auto_20210314_2204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raportslotowuczelnia",
            name="do_roku",
            field=models.IntegerField(
                default=bpp.models.uczelnia.UczelniaManager.do_roku_default
            ),
        ),
        migrations.AlterField(
            model_name="raportslotowuczelniawiersz",
            name="avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=16,
                null=True,
                verbose_name="Średnio punktów dla autora na slot",
            ),
        ),
        migrations.AlterField(
            model_name="raportslotowuczelniawiersz",
            name="pkd_aut_sum",
            field=models.DecimalField(
                decimal_places=4, max_digits=16, verbose_name="Suma punktów dla autora"
            ),
        ),
        migrations.AlterField(
            model_name="raportslotowuczelniawiersz",
            name="slot",
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
