# Generated by Django 4.2.8 on 2023-12-09 20:13

from django.db import migrations, models

import bpp.models.uczelnia


class Migration(migrations.Migration):
    dependencies = [
        ("raport_slotow", "0013_nullbooleanfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raportslotowuczelnia",
            name="do_roku",
            field=models.IntegerField(
                default=bpp.models.uczelnia.UczelniaManager.do_roku_default
            ),
        ),
    ]
