# Generated by Django 5.2.14 on 2026-06-04 16:11

import bpp.models.uczelnia
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport_slotow', '0019_alter_raportslotowuczelnia_do_roku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raportslotowuczelnia',
            name='do_roku',
            field=models.IntegerField(default=bpp.models.uczelnia.do_roku_default),
        ),
    ]
