# Generated by Django 5.2.14 on 2026-06-03 11:27

import django.db.models.deletion
from django.db import migrations, models

import bpp.models.uczelnia


def backfill(apps, schema_editor):
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    RSU = apps.get_model("raport_slotow", "RaportSlotowUczelnia")
    u = list(Uczelnia.objects.all()[:2])
    if len(u) == 1:
        RSU.objects.filter(uczelnia__isnull=True).update(uczelnia=u[0])


def backfill_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0427_cpd_index_rekord_uczelnia_dyscyplina'),
        ('raport_slotow', '0019_alter_raportslotowuczelnia_do_roku'),
    ]

    operations = [
        migrations.AddField(
            model_name='raportslotowuczelnia',
            name='uczelnia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='bpp.uczelnia',
            ),
        ),
        migrations.AlterField(
            model_name='raportslotowuczelnia',
            name='do_roku',
            field=models.IntegerField(
                default=bpp.models.uczelnia.UczelniaManager.do_roku_default
            ),
        ),
        migrations.RunPython(backfill, backfill_reverse),
    ]
