# Generated by Django 5.2.14 on 2026-06-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raport_slotow', '0020_fix_do_roku_default_modulowa_funkcja'),
        ('raport_slotow', '0020_raportslotowuczelnia_uczelnia'),
    ]

    operations = [
    ]
