# Generated by Django 4.2.16 on 2024-11-17 20:41

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import long_running.notification_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bpp", "0356_drop_kc_komisja_centralna"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportListMinisterialnych",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("started_on", models.DateTimeField(blank=True, null=True)),
                ("finished_on", models.DateTimeField(blank=True, null=True)),
                ("finished_successfully", models.BooleanField(default=False)),
                ("traceback", models.TextField(blank=True, null=True)),
                ("rok", models.IntegerField()),
                ("plik", models.FileField(upload_to="import_list_ministerialnych")),
                ("zapisz_zmiany_do_bazy", models.BooleanField(default=False)),
                ("importuj_dyscypliny", models.BooleanField(default=True)),
                ("importuj_punktacje", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_updated_on"],
                "abstract": False,
            },
            bases=(
                long_running.notification_mixins.ASGINotificationMixin,
                long_running.notification_mixins.NullNotificationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="WierszImportuDyscyplinZrodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dane_z_xls",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("nr_wiersza", models.PositiveSmallIntegerField()),
                ("rezultat", models.TextField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="import_list_ministerialnych.importlistministerialnych",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.zrodlo",
                    ),
                ),
            ],
            options={
                "ordering": ("nr_wiersza",),
            },
        ),
    ]
