# Generated by Django 4.2.16 on 2024-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_list_ministerialnych", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wierszimportudyscyplinzrodel",
            name="nr_wiersza",
            field=models.PositiveIntegerField(),
        ),
    ]
