# Generated by Django 4.2.16 on 2024-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "import_list_ministerialnych",
            "0003_rename_wierszimportudyscyplinzrodel_wierszimportulistyministerialnej",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importlistministerialnych",
            name="ignoruj_zrodla_bez_odpowiednika",
            field=models.BooleanField(default=True),
        ),
    ]
