# Generated by Django 4.2.19 on 2025-09-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "import_list_ministerialnych",
            "0004_importlistministerialnych_ignoruj_zrodla_bez_odpowiednika",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wierszimportulistyministerialnej",
            name="duplicate_of_row",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wierszimportulistyministerialnej",
            name="duplicate_reason",
            field=models.CharField(
                blank=True,
                help_text="Type of duplicate: ISSN, E-ISSN, mniswId, or combination",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="wierszimportulistyministerialnej",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
    ]
