# Generated by Django 4.2.25 on 2025-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_list_ministerialnych", "0005_add_duplicate_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="importlistministerialnych",
            name="nie_porownuj_po_tytulach",
            field=models.BooleanField(
                default=True,
                help_text='zaznaczenie tej opcji spowoduje, że import list ministerialnych będzie porównywał wyłącznie ISSN, E-ISSN, MNISWID a nie będzie zwracał uwagi na tytuły. Dla niektórych arkuszy jest to pożądane, np w sytuacji gdy występują w nich periodyki identycznie nazwane (np. "Electronics (Switzerland)" oraz "Electronics", gdy w bazie jest wyłącznie źródło "Electronics").',
            ),
        ),
    ]
