# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi pliki z import_list_ministerialnych/ do protected/import_list_ministerialnych/"""
    ImportListMinisterialnych = apps.get_model(
        "import_list_ministerialnych", "ImportListMinisterialnych"
    )
    old_dir = os.path.join(settings.MEDIA_ROOT, "import_list_ministerialnych")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "import_list_ministerialnych")
    os.makedirs(new_dir, exist_ok=True)

    for obj in ImportListMinisterialnych.objects.exclude(plik=""):
        if obj.plik:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik = f"protected/import_list_ministerialnych/{filename}"
                obj.save(update_fields=["plik"])

    # Usuń stary katalog jeśli pusty
    if os.path.exists(old_dir) and not os.listdir(old_dir):
        os.rmdir(old_dir)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "import_list_ministerialnych",
            "0006_importlistministerialnych_nie_porownuj_po_tytulach",
        ),
    ]

    operations = [
        migrations.RunPython(move_files_to_protected, noop),
        migrations.AlterField(
            model_name="importlistministerialnych",
            name="plik",
            field=models.FileField(upload_to="protected/import_list_ministerialnych/"),
        ),
    ]
