# Generated by Django 4.2.25 on 2025-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_list_ministerialnych", "0007_move_files_to_protected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wierszimportulistyministerialnej",
            name="rezultat",
            field=models.TextField(blank=True, default=""),
        ),
    ]
