# Generated by Django 5.2.15 on 2026-07-03 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_list_ministerialnych', '0008_remove_null_from_string_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importlistministerialnych',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='importlistministerialnych',
            name='last_updated_on',
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='current_stage',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='log_seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='result_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='stage_states',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='importlistministerialnych',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importlistministerialnych',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
