# Generated by Django 4.2.25 on 2026-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0414_copy_constance_to_uczelnia"),
        ("miniblog", "0002_auto_20180101_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="uczelnie",
            field=models.ManyToManyField(
                blank=True,
                help_text="Universities where this article is displayed. Leave empty for all universities.",
                related_name="articles",
                to="bpp.uczelnia",
                verbose_name="Universities",
            ),
        ),
    ]
