# Generated by Django 4.2.30 on 2026-04-16 14:39

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("miniblog", "0002_auto_20180101_2017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="article_body",
            field=model_utils.fields.SplitField(
                help_text='Use the split marker "&lt;!-- tutaj --&gt;" in case you want to displaythe shorter version of the article body',
                verbose_name="Article body",
            ),
        ),
    ]
