# Generated by Django 4.2.25 on 2026-04-09 19:03

from django.db import migrations


def assign_articles_to_all_uczelnie(apps, schema_editor):
    """Assign all existing articles to all existing universities."""
    Article = apps.get_model("miniblog", "Article")
    Uczelnia = apps.get_model("bpp", "Uczelnia")

    uczelnie = list(Uczelnia.objects.all())
    if not uczelnie:
        return

    for article in Article.objects.all():
        article.uczelnie.set(uczelnie)


class Migration(migrations.Migration):
    dependencies = [
        ("miniblog", "0003_article_uczelnie_m2m"),
        ("bpp", "0414_copy_constance_to_uczelnia"),
    ]

    operations = [
        migrations.RunPython(
            assign_articles_to_all_uczelnie, migrations.RunPython.noop
        ),
    ]
