# Generated by Django 5.2.13 on 2026-04-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miniblog", "0003_alter_article_article_body"),
        ("miniblog", "0004_assign_articles_to_all_uczelnie"),
    ]

    operations = []
