# Generated by Django 5.2.14 on 2026-06-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpp', '0421_uczelnia_dspace_aktywny_uczelnia_dspace_api_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapowanie_DSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_uuid', models.UUIDField(verbose_name='UUID kolekcji DSpace')),
                ('opis', models.CharField(blank=True, default='', max_length=255, verbose_name='Opis')),
                ('charakter_formalny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.charakter_formalny', verbose_name='Charakter formalny')),
                ('uczelnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia', verbose_name='Uczelnia')),
            ],
            options={
                'verbose_name': 'Mapowanie DSpace',
                'verbose_name_plural': 'Mapowania DSpace',
                'unique_together': {('uczelnia', 'charakter_formalny')},
            },
        ),
    ]
