# Generated by Django 5.2.14 on 2026-06-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0421_uczelnia_dspace_aktywny_uczelnia_dspace_api_endpoint_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dspace_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentToDSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('dspace_uuid', models.UUIDField(blank=True, null=True, verbose_name='UUID itemu w DSpace')),
                ('data_sent', models.JSONField(verbose_name='Wysłane dane')),
                ('submitted_successfully', models.BooleanField(db_index=True, default=False, verbose_name='Wysłano pomyślnie')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wysyłki')),
                ('exception', models.TextField(blank=True, default='', verbose_name='Kod błędu')),
                ('api_response_status', models.TextField(blank=True, default='', verbose_name='Status odpowiedzi API')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Data operacji')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uczelnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia')),
            ],
            options={
                'verbose_name': 'Informacja o wysłaniu do DSpace',
                'verbose_name_plural': 'Informacje o wysłaniu do DSpace',
                'unique_together': {('content_type', 'object_id', 'uczelnia')},
            },
        ),
    ]
