# Generated by Django 5.2.14 on 2026-06-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dspace_api', '0002_senttodspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='senttodspace',
            name='bitstreams',
            field=models.JSONField(blank=True, default=dict, verbose_name='Bitstreamy (element_id → uuid)'),
        ),
    ]
