# Generated by Django 5.2.14 on 2026-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dspace_api", "0003_senttodspace_bitstreams"),
    ]

    operations = [
        migrations.AddField(
            model_name="senttodspace",
            name="dspace_handle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trwały identyfikator (np. 11089/1234) — podstawa linku do rekordu w repozytorium.",
                max_length=255,
                verbose_name="Handle itemu w DSpace",
            ),
        ),
    ]
