# Generated by Django 4.2.19 on 2025-08-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotADuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scientist_pk",
                    models.CharField(
                        db_index=True,
                        help_text="Primary key of the Scientist record that is NOT a duplicate",
                        max_length=255,
                        verbose_name="PK Scientist",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created on"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who marked this scientist as not a duplicate",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Not a duplicate",
                "verbose_name_plural": "Not duplicates",
                "ordering": ["-created_on"],
                "unique_together": {("scientist_pk", "created_by")},
            },
        ),
    ]
