# Generated by Django 4.2.19 on 2025-08-29 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deduplikator_autorow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAutomatycznegoScalania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_scientist_id",
                    models.CharField(
                        db_index=True,
                        help_text="Primary key of the main scientist record",
                        max_length=255,
                        verbose_name="Main Scientist ID",
                    ),
                ),
                (
                    "duplicate_scientist_id",
                    models.CharField(
                        db_index=True,
                        help_text="Primary key of the duplicate scientist record that was merged",
                        max_length=255,
                        verbose_name="Duplicate Scientist ID",
                    ),
                ),
                (
                    "updated_publications",
                    models.JSONField(
                        help_text="JSON data containing information about publications that were updated during merge",
                        verbose_name="Updated Publications",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created on"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who performed the automatic merge",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log automatycznego scalania",
                "verbose_name_plural": "Logi automatycznego scalania",
                "ordering": ["-created_on"],
            },
        ),
    ]
