# Generated by Django 4.2.19 on 2025-08-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0059_alter_osobazinstytucji__from"),
        ("deduplikator_autorow", "0002_logautomatycznegoscalania"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notaduplicate",
            name="scientist_pk",
            field=models.ForeignKey(
                help_text="Primary key of the Scientist record that is NOT a duplicate",
                on_delete=django.db.models.deletion.CASCADE,
                to="pbn_api.scientist",
            ),
        ),
    ]
