# Generated by Django 4.2.19 on 2025-08-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0387_fix_refresh_cache_locking_deadlocks"),
        ("deduplikator_autorow", "0003_alter_notaduplicate_scientist_pk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notaduplicate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notaduplicate",
            name="autor",
            field=models.OneToOneField(
                default=0,
                help_text="Primary key of the Scientist record that is NOT a duplicate",
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.autor",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="notaduplicate",
            name="scientist_pk",
        ),
    ]
