# Generated by Django 4.2.19 on 2025-09-04 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0389_alter_uczelnia_uzywaj_wydzialow"),
        ("pbn_api", "0060_alter_osobazinstytucji_personid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deduplikator_autorow", "0005_replace_log_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Opcjonalny powód dlaczego autor jest ignorowany",
                        max_length=500,
                        verbose_name="Powód ignorowania",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data utworzenia",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional reference to BPP author",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.autor",
                        verbose_name="Autor (BPP)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Użytkownik który oznaczył autora jako ignorowany",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzył",
                    ),
                ),
                (
                    "scientist",
                    models.OneToOneField(
                        help_text="Scientist record that should be ignored in deduplication",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pbn_api.scientist",
                        verbose_name="Scientist (PBN)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignorowany autor",
                "verbose_name_plural": "Ignorowani autorzy",
                "ordering": ["-created_on"],
            },
        ),
    ]
