# Generated by Django 4.2.25 on 2025-12-03 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0400_add_status_optymalizacji_bulk"),
        ("pbn_api", "0066_add_duplicate_scan_models"),
        ("deduplikator_autorow", "0006_add_ignored_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Rozpoczęto"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zakończono"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("running", "W trakcie"),
                            ("completed", "Zakończone"),
                            ("cancelled", "Anulowane"),
                            ("failed", "Błąd"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_authors_to_scan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Autorów do przeskanowania"
                    ),
                ),
                (
                    "authors_scanned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Przeskanowano autorów"
                    ),
                ),
                (
                    "duplicates_found",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Znaleziono duplikatów"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Komunikat błędu"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID zadania Celery"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Użytkownik który uruchomił skanowanie (null dla zadań automatycznych)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzył",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skanowanie duplikatów",
                "verbose_name_plural": "Skanowania duplikatów",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        db_index=True,
                        help_text="Surowy wynik pewności (-115 do 250)",
                        verbose_name="Wynik pewności",
                    ),
                ),
                (
                    "confidence_percent",
                    models.FloatField(
                        help_text="Znormalizowany wynik (0.0 do 1.0)",
                        verbose_name="Pewność (%)",
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        default=list,
                        help_text="Lista powodów dopasowania",
                        verbose_name="Powody dopasowania",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Do sprawdzenia"),
                            ("merged", "Scalony"),
                            ("not_duplicate", "Nie jest duplikatem"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data sprawdzenia"
                    ),
                ),
                (
                    "main_autor_name",
                    models.CharField(
                        max_length=1024, verbose_name="Nazwa autora głównego"
                    ),
                ),
                (
                    "duplicate_autor_name",
                    models.CharField(max_length=1024, verbose_name="Nazwa duplikatu"),
                ),
                (
                    "main_publications_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Publikacje autora głównego"
                    ),
                ),
                (
                    "duplicate_publications_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Publikacje duplikatu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "duplicate_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates",
                        to="bpp.autor",
                        verbose_name="Potencjalny duplikat",
                    ),
                ),
                (
                    "main_autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_main_candidates",
                        to="bpp.autor",
                        verbose_name="Autor główny",
                    ),
                ),
                (
                    "main_osoba_z_instytucji",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pbn_api.osobazinstytucji",
                        verbose_name="OsobaZInstytucji",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_duplicates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sprawdził",
                    ),
                ),
                (
                    "scan_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="deduplikator_autorow.duplicatescanrun",
                        verbose_name="Skanowanie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kandydat na duplikat",
                "verbose_name_plural": "Kandydaci na duplikaty",
                "ordering": ["-confidence_score", "main_autor__nazwisko"],
                "indexes": [
                    models.Index(
                        fields=["scan_run", "status"],
                        name="deduplikato_scan_ru_e4a11b_idx",
                    ),
                    models.Index(
                        fields=["main_autor", "status"],
                        name="deduplikato_main_au_c4eb68_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.UniqueConstraint(
                fields=("scan_run", "main_autor", "duplicate_autor"),
                name="unique_scan_main_duplicate",
            ),
        ),
    ]
