# Generated by Django 4.2.25 on 2025-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deduplikator_autorow", "0007_add_duplicate_scan_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="duplicatecandidate",
            options={
                "ordering": ["-priority", "-confidence_score", "main_autor__nazwisko"],
                "verbose_name": "Kandydat na duplikat",
                "verbose_name_plural": "Kandydaci na duplikaty",
            },
        ),
        migrations.AddField(
            model_name="duplicatecandidate",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Priorytet wyświetlania: 100=prace 2022-2025 z dyscyplinami, 50=prace 2022-2025, 0=inne",
                verbose_name="Priorytet",
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatecandidate",
            index=models.Index(
                fields=["priority", "confidence_score"],
                name="deduplikato_priorit_39f293_idx",
            ),
        ),
    ]
