# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0424_alter_autor_dyscyplina_autor_and_more'),
        ('deduplikator_autorow', '0011_scan_mode_phase_partial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecandidate',
            name='main_autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_main_candidates', to='bpp.autor', verbose_name='Autor główny'),
        ),
        migrations.AlterField(
            model_name='duplicatecandidate',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priorytet wyświetlania: 100=prace 2022-2025 z dyscyplinami, 50=prace 2022-2025, 0=inne', verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='duplicatecandidate',
            name='scan_run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='deduplikator_autorow.duplicatescanrun', verbose_name='Skanowanie'),
        ),
        migrations.AlterField(
            model_name='logscalania',
            name='created_by',
            field=models.ForeignKey(db_index=False, help_text='Użytkownik który wykonał scalanie', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Wykonał'),
        ),
        migrations.AlterField(
            model_name='logscalania',
            name='main_autor',
            field=models.ForeignKey(db_index=False, help_text='Główny autor BPP do którego przypisano publikacje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_logs_as_main', to='bpp.autor', verbose_name='Autor główny (BPP)'),
        ),
    ]
