# Generated by Django 4.2.19 on 2025-08-27 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import ewaluacja_liczba_n.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bpp", "0387_fix_refresh_cache_locking_deadlocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiczbaNDlaUczelni_2022_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liczba_n",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2, max_digits=9
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.uczelnia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Liczba N dla uczelni 2022-2025",
                "verbose_name_plural": "Liczby N dla uczelni 2022-2025",
                "unique_together": {("uczelnia", "dyscyplina_naukowa")},
            },
        ),
        migrations.CreateModel(
            name="IloscUdzialowDlaAutoraZaRok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilosc_udzialow",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[django.core.validators.MaxValueValidator(4)],
                    ),
                ),
                (
                    "ilosc_udzialow_monografie",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2, max_digits=9
                    ),
                ),
                ("rok", models.IntegerField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "ilość udziałów dla autora za rok",
                "verbose_name_plural": "ilości udziałów dla autorów za lata",
                "unique_together": {("autor", "dyscyplina_naukowa", "rok")},
            },
        ),
        migrations.CreateModel(
            name="IloscUdzialowDlaAutora_2022_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilosc_udzialow",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[django.core.validators.MaxValueValidator(4)],
                    ),
                ),
                (
                    "ilosc_udzialow_monografie",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2, max_digits=9
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "ilość udziałów dla autora 2022-2025",
                "verbose_name_plural": "ilości udziałów dla autorów 2022-2025",
                "unique_together": {("autor", "dyscyplina_naukowa")},
            },
        ),
        migrations.CreateModel(
            name="DyscyplinaNieRaportowana_2022_2025",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.uczelnia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dyscyplina nieraportowana 2022-2025",
                "verbose_name_plural": "Dyscypliny nieraportowane 2022-2025",
                "unique_together": {("uczelnia", "dyscyplina_naukowa")},
            },
        ),
    ]
