# Generated by Django 4.2.19 on 2025-09-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0389_alter_uczelnia_uzywaj_wydzialow"),
        ("ewaluacja_liczba_n", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DyscyplinaNieRaportowana_2022_2025",
            new_name="DyscyplinaNieRaportowana",
        ),
        migrations.RenameModel(
            old_name="LiczbaNDlaUczelni_2022_2025",
            new_name="LiczbaNDlaUczelni",
        ),
        migrations.AlterModelOptions(
            name="iloscudzialowdlaautorazarok",
            options={},
        ),
        migrations.AlterModelOptions(
            name="liczbandlauczelni",
            options={
                "verbose_name": "Liczba N dla uczelni",
                "verbose_name_plural": "Liczby N dla uczelni",
            },
        ),
        migrations.AlterUniqueTogether(
            name="iloscudzialowdlaautorazarok",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="IloscUdzialowDlaAutora_2022_2025",
        ),
    ]
