# Generated by Django 4.2.19 on 2025-09-06 20:03

from django.db import migrations

import ewaluacja_liczba_n.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "ewaluacja_liczba_n",
            "0002_rename_dyscyplinanieraportowana_2022_2025_dyscyplinanieraportowana_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dyscyplinanieraportowana",
            name="liczba_n",
            field=ewaluacja_liczba_n.fields.LiczbaNField(
                decimal_places=2,
                default=0,
                help_text="Liczba N dla dyscypliny (poniżej progu raportowania)",
                max_digits=9,
            ),
        ),
    ]
