# Generated by Django 4.2.19 on 2025-09-06 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import ewaluacja_liczba_n.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0389_alter_uczelnia_uzywaj_wydzialow"),
        ("ewaluacja_liczba_n", "0003_add_liczba_n_to_dyscyplina_nieraportowana"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iloscudzialowdlaautorazarok",
            options={
                "verbose_name": "Ilość udziałów dla autora za rok",
                "verbose_name_plural": "Ilości udziałów dla autorów za rok",
            },
        ),
        migrations.AlterUniqueTogether(
            name="iloscudzialowdlaautorazarok",
            unique_together={("autor", "dyscyplina_naukowa", "rok")},
        ),
        migrations.CreateModel(
            name="IloscUdzialowDlaAutoraZaCalosc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ilosc_udzialow_monografie",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2, max_digits=9
                    ),
                ),
                (
                    "komentarz",
                    models.TextField(
                        blank=True,
                        help_text="Dodatkowe informacje o wyliczeniach",
                        null=True,
                    ),
                ),
                (
                    "ilosc_udzialow",
                    ewaluacja_liczba_n.fields.LiczbaNField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[django.core.validators.MaxValueValidator(16)],
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ilość udziałów dla autora za cały okres",
                "verbose_name_plural": "Ilości udziałów dla autorów za cały okres",
                "unique_together": {("autor", "dyscyplina_naukowa")},
            },
        ),
    ]
