# Generated by Django 4.2.25 on 2025-10-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0392_alter_autor_dyscyplina_rodzaj_autora"),
        ("ewaluacja_liczba_n", "0004_add_ilosc_udzialow_za_calosc"),
    ]

    operations = [
        migrations.AddField(
            model_name="iloscudzialowdlaautorazarok",
            name="autor_dyscyplina",
            field=models.ForeignKey(
                blank=True,
                help_text="Link do oryginalnego rekordu Autor_Dyscyplina za dany rok",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.autor_dyscyplina",
            ),
        ),
    ]
