# Generated by Django 4.2.25 on 2025-10-15 19:05

from django.db import migrations, models
import django.db.models.deletion


def delete_existing_records(apps, schema_editor):
    """
    Usuwa wszystkie istniejące rekordy IloscUdzialowDlaAutoraZaCalosc.

    Jest to konieczne ponieważ dodajemy pole rodzaj_autora, które zmienia
    logikę grupowania - teraz każdy rodzaj autora ma osobny wpis.

    Po uruchomieniu migracji należy przeliczyć dane używając:
    - widoku "Oblicz liczbę N" w interfejsie
    - lub komendy zarządzającej
    """
    IloscUdzialowDlaAutoraZaCalosc = apps.get_model(
        "ewaluacja_liczba_n", "IloscUdzialowDlaAutoraZaCalosc"
    )
    count = IloscUdzialowDlaAutoraZaCalosc.objects.count()
    IloscUdzialowDlaAutoraZaCalosc.objects.all().delete()
    print(f"Usunięto {count} rekordów z IloscUdzialowDlaAutoraZaCalosc")


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0392_alter_autor_dyscyplina_rodzaj_autora"),
        ("ewaluacja_common", "0004_alter_rodzaj_autora_options"),
        ("ewaluacja_liczba_n", "0005_iloscudzialowdlaautorazarok_autor_dyscyplina"),
    ]

    operations = [
        # Najpierw usuń stare unique_together
        migrations.AlterUniqueTogether(
            name="iloscudzialowdlaautorazacalosc",
            unique_together=set(),
        ),
        # Następnie usuń wszystkie istniejące rekordy
        migrations.RunPython(delete_existing_records, migrations.RunPython.noop),
        migrations.AddField(
            model_name="iloscudzialowdlaautorazacalosc",
            name="rodzaj_autora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ewaluacja_common.rodzaj_autora",
                verbose_name="Rodzaj autora",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iloscudzialowdlaautorazacalosc",
            unique_together={("autor", "dyscyplina_naukowa", "rodzaj_autora")},
        ),
    ]
