# Generated by Django 4.2.25 on 2025-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ewaluacja_liczba_n",
            "0006_alter_iloscudzialowdlaautorazacalosc_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="iloscudzialowdlaautorazacalosc",
            name="komentarz",
            field=models.TextField(
                blank=True, default="", help_text="Dodatkowe informacje o wyliczeniach"
            ),
        ),
    ]
