# Generated by Django 4.2.25 on 2025-12-03 15:50

from django.db import migrations
import ewaluacja_liczba_n.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_liczba_n", "0007_alter_iloscudzialowdlaautorazacalosc_komentarz"),
    ]

    operations = [
        migrations.AddField(
            model_name="liczbandlauczelni",
            name="sankcje",
            field=ewaluacja_liczba_n.fields.LiczbaNField(
                decimal_places=2,
                default=0,
                help_text="Sankcje zmniejszające liczbę N dla optymalizacji",
                max_digits=9,
            ),
        ),
    ]
