# Generated by Django 5.2.14 on 2026-06-03 12:47

import django.db.models.deletion
from django.db import migrations, models


def backfill_uczelnia(apps, schema_editor):
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    ZaRok = apps.get_model(
        "ewaluacja_liczba_n", "IloscUdzialowDlaAutoraZaRok"
    )
    ZaCalosc = apps.get_model(
        "ewaluacja_liczba_n", "IloscUdzialowDlaAutoraZaCalosc"
    )

    null_qs = [
        ZaRok.objects.filter(uczelnia__isnull=True),
        ZaCalosc.objects.filter(uczelnia__isnull=True),
    ]
    if not any(qs.exists() for qs in null_qs):
        return

    uczelnie = list(Uczelnia.objects.all()[:2])
    if len(uczelnie) == 1:
        for qs in null_qs:
            qs.update(uczelnia=uczelnie[0])
        return

    raise RuntimeError(
        "Migracja liczba_n per-uczelnia (0009): istnieja wiersze udzialow"
        " bez uczelni, a w systemie jest"
        f" {len(uczelnie)} uczelni - nie mozna zdeterministycznie"
        " przypisac. Przelicz liczbe N per uczelnia (przelicz_n) albo"
        " usun stare IloscUdzialow* i zaaplikuj migracje na czystych"
        " danych."
    )


def backfill_uczelnia_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0427_cpd_index_rekord_uczelnia_dyscyplina'),
        ('ewaluacja_common', '0004_alter_rodzaj_autora_options'),
        ('ewaluacja_liczba_n', '0008_add_sankcje'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iloscudzialowdlaautorazacalosc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='iloscudzialowdlaautorazarok',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='iloscudzialowdlaautorazacalosc',
            name='uczelnia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='bpp.uczelnia',
            ),
        ),
        migrations.AddField(
            model_name='iloscudzialowdlaautorazarok',
            name='uczelnia',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='bpp.uczelnia',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='iloscudzialowdlaautorazacalosc',
            unique_together={
                ('autor', 'dyscyplina_naukowa', 'rodzaj_autora', 'uczelnia')
            },
        ),
        migrations.AlterUniqueTogether(
            name='iloscudzialowdlaautorazarok',
            unique_together={
                ('autor', 'dyscyplina_naukowa', 'rok', 'uczelnia')
            },
        ),
        migrations.RunPython(
            backfill_uczelnia, backfill_uczelnia_reverse
        ),
    ]
