# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0424_alter_autor_dyscyplina_autor_and_more'),
        ('ewaluacja_liczba_n', '0008_add_sankcje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyscyplinanieraportowana',
            name='uczelnia',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia'),
        ),
        migrations.AlterField(
            model_name='iloscudzialowdlaautorazacalosc',
            name='autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.autor'),
        ),
        migrations.AlterField(
            model_name='iloscudzialowdlaautorazarok',
            name='autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.autor'),
        ),
        migrations.AlterField(
            model_name='liczbandlauczelni',
            name='uczelnia',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia'),
        ),
    ]
