name: 'Setup Python Environment'
description: 'Setup Python with UV and cache dependencies'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  install-extras:
    description: 'Install all extras when running uv sync'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      shell: bash
      run: |
        python -m pip install --upgrade pip uv

    - name: Set up Python with caching
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.local/share/uv
          .venv
        key: ${{ runner.os }}-uv-${{ inputs.python-version }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ inputs.python-version }}-
          ${{ runner.os }}-uv-

    - name: Install Python dependencies
      shell: bash
      run: |
        if [ "${{ inputs.install-extras }}" == "true" ]; then
          uv sync --all-extras
        else
          uv sync
        fi
