# Generated by Django 3.2.14 on 2022-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_list_if", "0002_auto_20210308_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlistifrow",
            name="dane_z_xls",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="importlistifrow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
