# Generated by Django 4.2.30 on 2026-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_list_if", "0003_django32"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlistif",
            name="plik_xls",
            field=models.FileField(upload_to="protected/import_common/"),
        ),
    ]
