version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: boot up docker
          command: docker-compose up -d

      - run:
          name: run tests
          command: make travis
