version: 2
jobs:
  build:
    
    docker:
      - image: mpasternak79/circleci-python:3.6-node-browsers
        environment:
          PGUSER: postgres
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: bpp
          DJANGO_BPP_SECRET_KEY: foobar
          DJANGO_SETTINGS_MODULE: django_bpp.settings.test
      - image: mpasternak79/circleci-nginx:1.14.1
      - image: mpasternak79/circleci-postgres:10
      - image: rabbitmq:latest
        
    steps:
      - checkout

      - run: sudo add-apt-repository -y "ppa:dotz/nginx-with-push-stream-module"
      - run: sudo apt-get update
      - run: sudo apt-get install -y nginx-full=1.14.1-0+xenial0+pushstream1

      - run: sudo npm install -g grunt-cli
      - run: sudo pipenv install --system -d
      - run: make assets

      # Baza musi istnieć - worker celery potem wymaga; sklonujemy od razu, żeby
      # nie tracić czasu na tworzenie testowej bazy danych
      - run: createdb bpp
      - run: python src/manage.py migrate
      - run: echo 'CREATE DATABASE "test_bpp" WITH TEMPLATE "bpp"' | psql
      - run: echo 'CREATE DATABASE "test_bpp_gw0" WITH TEMPLATE "bpp"' | psql
      - run: echo 'CREATE DATABASE "test_bpp_gw1" WITH TEMPLATE "bpp"' | psql

      # Uruchamiaj na lokalnym firefoxie używając dwóch CPU
      - run: pytest --cov=src --splinter-webdriver=firefox -n2 --nginx-host=localhost --liveserver=localhost

      # Testy JavaScript
      - run: make js-tests

      # Wyślij statystyki pokrycia kodu testami do coveralls.io  
      - run: coveralls
