version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            
      - run:
          name: boot up docker
          command: docker-compose up -d

      - run:
          name: run tests
          command: make travis
