version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Setup environment for CircleCI
          command: make circle-env
          
      - run:
          name: build docker images
          command: docker-compose build
          
      - run:
          name: boot up docker
          command: make docker-up

      - run:
          name: run tests
          command: make docker-tests
