version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Setup environment for CircleCI
          command: make circle-env
          
      - run:
          name: Build local Docker images
          command: docker-compose build db nginx_http_push node test
          
      - run:
          name: Boot docker 
          command: make docker-up

      #- run:
      #    name: docker-wheels
      #    command: make docker-wheels

      - run:
          name: docker-yarn
          command: make docker-yarn
          
      - run:
          name: docker-grunt
          command: make docker-grunt

      - run:
          name: docker-grunt
          command: make docker-grunt
          
      - run:
          name: docekr-assets
          command: make _docker-assets

      - run:
          name: Python tests
          command: make docker-python-tests
          
      - run:
          name: JS tests
          command: make docker-js-tests
