version: 2
jobs:
  build:

    # branches:
    #   only:
    #     - master
    #     - dev

    docker:
      - image: circleci/python:3.7-node-browsers
        environment:
          PGUSER: postgres
          PGHOST: localhost
          PGPORT: 5432
          PGDATABASE: bpp
          DJANGO_BPP_SECRET_KEY: foobar
          DJANGO_SETTINGS_MODULE: django_bpp.settings.test
      - image: mpasternak79/circleci-postgres:12
      - image: redis:latest

    steps:
      - setup_remote_docker
      
      - checkout

#      - restore_cache:
#          key: cache-8-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "yarn.lock" }}

      - run: sudo apt --quiet install -y --quiet gettext
      - run: sudo npm install -g grunt-cli
      - run: sudo pip install --upgrade pip

      - run:
          name: venv
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
	          pip install --upgrade pip
            pip install -q -r requirements.txt -r requirements_dev.txt

      - run:
          name: make assets
          command: |
            . venv/bin/activate
            make assets

#      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
#          key: cache-8-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}-{{ checksum "yarn.lock" }}
#          paths:
#            - "/home/circleci/.cache"

      # Uruchamiaj na lokalnym firefoxie używając jednego CPU
      - run:
          name: pytest
          command: |
            . venv/bin/activate
            pytest -d -n 2 --cov=src --ds=django_bpp.settings.test

      # Testy JavaScript
      - run: make js-tests

      # Wyślij statystyki pokrycia kodu testami do coveralls.io
      - run:
          name: Submit coverage to coveralls.io
          command: |
            . venv/bin/activate
            coveralls

      # Zbuduj pakiet WHL -- bez wrzucania go na serwer (próbnie)
      - run:
          name: create ONLY whl package -- only on DEV
          command: |
            . venv/bin/activate
            if [ $CIRCLE_BRANCH = 'dev' ]; then make bdist_wheel; fi

      # Skonfiguruj PyPI
      - run:
          name: init .pypirc
          command: |
            echo -e "[distutils]" > ~/.pypirc
            echo -e "index-servers = pypi" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = https://upload.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = dotz" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      # Zbuduj pakiet
      - run:
          name: create and upload packages -- only on MASTER
          command: |
            . venv/bin/activate
            cat ~/.pypirc | grep -v password
            if [ $CIRCLE_BRANCH = 'master' ]; then make bdist_wheel_upload; fi
