version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Setup environment for CircleCI
          command: make circle-env

#      - run:
#          name: Pull docker images from hub
#          command: make _circleci_pull
          
      - run:
          name: Build docker images
          command: docker-compose build 
          
      - run:
          name: Boot docker 
          command: make docker-up

      - run:
          name: docker-grunt
          command: make docker-grunt
          
      - run:
          name: docekr-assets
          command: make docker-assets

      - run:
          name: Python tests
          command: make docker-python-tests
          
      - run:
          name: JS tests
          command: make docker-js-tests

