# Generated by Django 4.2.19 on 2025-09-27 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bpp.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0390_add_filters_to_sumy_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptymalizacjaPublikacji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publikacja_id",
                    bpp.models.fields.TupleField(
                        base_field=models.IntegerField(), db_index=True, size=2
                    ),
                ),
                ("utworzono", models.DateTimeField(auto_now_add=True)),
                ("zmodyfikowano", models.DateTimeField(auto_now=True)),
                ("notatki", models.TextField(blank=True, null=True)),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Optymalizacja publikacji",
                "verbose_name_plural": "Optymalizacje publikacji",
                "ordering": ["-utworzono"],
            },
        ),
        migrations.CreateModel(
            name="HistoriaZmianDyscypliny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rekord_id",
                    bpp.models.fields.TupleField(
                        base_field=models.IntegerField(), db_index=True, size=2
                    ),
                ),
                (
                    "akcja",
                    models.CharField(
                        choices=[("pin", "Przypięto"), ("unpin", "Odpięto")],
                        max_length=20,
                    ),
                ),
                (
                    "punkty_przed",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "punkty_po",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sloty_przed",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sloty_po",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("utworzono", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
                (
                    "dyscyplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
                (
                    "jednostka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.jednostka"
                    ),
                ),
                (
                    "optymalizacja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_zmian",
                        to="ewaluacja_optymalizuj_publikacje.optymalizacjapublikacji",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia zmiany dyscypliny",
                "verbose_name_plural": "Historie zmian dyscyplin",
                "ordering": ["-utworzono"],
            },
        ),
    ]
