# Generated by Django 4.2.19 on 2025-08-31 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("bpp", "0389_alter_uczelnia_uzywaj_wydzialow"),
        ("pbn_api", "0060_alter_osobazinstytucji_personid"),
    ]

    operations = [
        migrations.CreateModel(
            name="RozbieznoscDyscyplinPBN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("app_label", "bpp"),
                            (
                                "model__in",
                                [
                                    "wydawnictwo_ciagle_autor",
                                    "wydawnictwo_zwarte_autor",
                                ],
                            ),
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "dyscyplina_bpp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rozbieznosci_bpp",
                        to="bpp.dyscyplina_naukowa",
                        verbose_name="Dyscyplina w BPP",
                    ),
                ),
                (
                    "dyscyplina_pbn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rozbieznosci_pbn",
                        to="bpp.dyscyplina_naukowa",
                        verbose_name="Dyscyplina w PBN",
                    ),
                ),
                (
                    "oswiadczenie_instytucji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rozbieznosci_dyscyplin",
                        to="pbn_api.oswiadczenieinstytucji",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rozbieżność dyscyplin BPP-PBN",
                "verbose_name_plural": "Rozbieżności dyscyplin BPP-PBN",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="komparator__content_b5e62b_idx",
                    ),
                    models.Index(
                        fields=["oswiadczenie_instytucji"],
                        name="komparator__oswiadc_90a10b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="komparator__created_5f1a67_idx"
                    ),
                ],
                "unique_together": {
                    ("content_type", "object_id", "oswiadczenie_instytucji")
                },
            },
        ),
    ]
