# Generated by Django 4.2.25 on 2026-01-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0068_add_cache_models"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("bpp", "0407_remove_null_from_string_fields"),
        ("komparator_pbn_udzialy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrakAutoraWPublikacji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("brak_autora", "Autor nie istnieje w BPP"),
                            (
                                "brak_powiazania",
                                "Autor nie jest powiązany z publikacją",
                            ),
                            ("brak_publikacji", "Publikacja nie istnieje w BPP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brakujace_powiazania_pbn",
                        to="bpp.autor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "dyscyplina_pbn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brakujacy_autorzy_pbn",
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
                (
                    "oswiadczenie_instytucji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brakujace_autorzy",
                        to="pbn_api.oswiadczenieinstytucji",
                    ),
                ),
                (
                    "pbn_scientist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brakujace_powiazania_bpp",
                        to="pbn_api.scientist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brak autora w publikacji",
                "verbose_name_plural": "Brakujący autorzy w publikacjach",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["typ"], name="komparator__typ_51dddd_idx"),
                    models.Index(
                        fields=["autor"], name="komparator__autor_i_e007d7_idx"
                    ),
                    models.Index(
                        fields=["pbn_scientist"], name="komparator__pbn_sci_c6a265_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="komparator__created_8277b4_idx"
                    ),
                ],
                "unique_together": {("oswiadczenie_instytucji",)},
            },
        ),
    ]
