# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('komparator_pbn_udzialy', '0002_add_brakautora_model'),
        ('pbn_api', '0072_pbn_search_gin_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brakautorawpublikacji',
            name='komparator__autor_i_e007d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='brakautorawpublikacji',
            name='komparator__pbn_sci_c6a265_idx',
        ),
        migrations.RemoveIndex(
            model_name='rozbieznoscdyscyplinpbn',
            name='komparator__content_b5e62b_idx',
        ),
        migrations.RemoveIndex(
            model_name='rozbieznoscdyscyplinpbn',
            name='komparator__oswiadc_90a10b_idx',
        ),
        migrations.AlterField(
            model_name='brakautorawpublikacji',
            name='oswiadczenie_instytucji',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='brakujace_autorzy', to='pbn_api.oswiadczenieinstytucji'),
        ),
        migrations.AlterField(
            model_name='rozbieznoscdyscyplinpbn',
            name='content_type',
            field=models.ForeignKey(db_index=False, limit_choices_to=models.Q(('app_label', 'bpp'), ('model__in', ['wydawnictwo_ciagle_autor', 'wydawnictwo_zwarte_autor'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
