# Generated by Django 5.2.15 on 2026-07-04 20:44

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-fetched_at",),
            },
        ),
        migrations.CreateModel(
            name="AISearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("model", models.CharField(max_length=100)),
                ("pytanie", models.TextField()),
                ("wygenerowany_query", models.TextField(blank=True, default="")),
                ("wybrany_model_danych", models.CharField(max_length=32)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_read_tokens", models.IntegerField(default=0)),
                ("cache_write_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cost_pln",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
                ("retried", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "zapytanie AI",
                "verbose_name_plural": "zapytania AI",
                "ordering": ("-created",),
            },
        ),
    ]
