# Generated by Django 5.2.15 on 2026-07-05 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fxrate",
            options={"ordering": ("-fetched_at", "-id")},
        ),
    ]
