# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0082_auto_20170713_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydawnictwo_zwarte',
            name='liczba_arkuszy_wydawniczych',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Liczba arkuszy wydawniczych'),
        ),
    ]
