# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models

def przerzuc_dane(apps, schema_editor):
    for model in ['Wydawnictwo_Ciagle', 'Wydawnictwo_Zwarte',
                  'Patent', 'Praca_Doktorska', 'Praca_Habilitacyjna']:
        klass = apps.get_model("bpp", model)
        for elem in klass.objects.all():
            elem.uzupelnij_szczegoly()


class Migration(migrations.Migration):
    dependencies = [
        ('bpp', '0083_afiliuje_zatrudniony'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='nr_zeszytu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='strony',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='tom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='praca_doktorska',
            name='nr_zeszytu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='praca_doktorska',
            name='strony',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='praca_doktorska',
            name='tom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='praca_habilitacyjna',
            name='nr_zeszytu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='praca_habilitacyjna',
            name='strony',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='praca_habilitacyjna',
            name='tom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wydawnictwo_ciagle',
            name='nr_zeszytu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wydawnictwo_ciagle',
            name='strony',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wydawnictwo_ciagle',
            name='tom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wydawnictwo_zwarte',
            name='nr_zeszytu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wydawnictwo_zwarte',
            name='strony',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wydawnictwo_zwarte',
            name='tom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),

        migrations.RunPython(
            przerzuc_dane,
            lambda *args, **kw: True
        )
    ]
