# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0083_wydawnictwo_zwarte_liczba_arkuszy_wydawniczych'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='liczba_arkuszy_wydawniczych',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text="Liczba arkuszy wydawniczych, jeżeli wypełniona, będzie \n        uzywana do celów eksportu danych do PBN. Jeżeli nie, to do tych \n        celów będzie używana wartość pola 'Liczba znaków wydawniczych' \n        podzielona przez 40000.000000 z dokładnością do dwóch pól po przecinku. ", max_digits=8, null=True, verbose_name='Liczba arkuszy wydawniczych'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='liczba_arkuszy_wydawniczych',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text="Liczba arkuszy wydawniczych, jeżeli wypełniona, będzie \n        uzywana do celów eksportu danych do PBN. Jeżeli nie, to do tych \n        celów będzie używana wartość pola 'Liczba znaków wydawniczych' \n        podzielona przez 40000.000000 z dokładnością do dwóch pól po przecinku. ", max_digits=8, null=True, verbose_name='Liczba arkuszy wydawniczych'),
        ),
    ]
