# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0084_auto_20170713_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konferencja',
            name='miasto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='konferencja',
            name='panstwo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Państwo'),
        ),
        migrations.AlterField(
            model_name='konferencja',
            name='rozpoczecie',
            field=models.DateField(blank=True, null=True, verbose_name='Rozpoczęcie'),
        ),
        migrations.AlterField(
            model_name='konferencja',
            name='zakonczenie',
            field=models.DateField(blank=True, null=True, verbose_name='Zakończenie'),
        ),
    ]
