# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 23:02
from __future__ import unicode_literals

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0085_auto_20170714_0049'),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0086_widoki_arkusze_wyd",
                                                *args, **kw)),

    ]
