# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 20:54
from __future__ import unicode_literals

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0100_init_nagrody'),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0101_openaccess_w_multiseek")
        )
    ]
