# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 04:51
from __future__ import unicode_literals

from django.db import migrations, models



def zmigruj_typy_odpowiedzialnosci(apps, schema_editor):
    # Typ odpowiedzialnosci dla PBN domyślnie ustawiony jest na
    # "autor", więc ustawiamy tutaj tylko takie rekordy, któe tego
    # autora nie mają...
    from bpp.models.const import PBN_REDAKTOR, PBN_AUTOR, PBN_INNY
    autorzy = ['aut', 'autkoresp']
    redaktorzy = ["rednaukwydpol", "red"]
    Typ_Odpowiedzialnosci = apps.get_model("bpp", "Typ_Odpowiedzialnosci")
    # import pdb; pdb.set_trace()
    for elem in Typ_Odpowiedzialnosci.objects.all():
        v = elem.skrot.lower().replace(" ", "").replace(".", "").strip()

        if v in redaktorzy:
            elem.typ_pbn = PBN_REDAKTOR
        elif v in autorzy:
            elem.typ_pbn =  PBN_AUTOR
        else:
            elem.typ_pbn = PBN_INNY
        elem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0115_auto_20171111_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typ_odpowiedzialnosci',
            options={'ordering': ['nazwa'], 'verbose_name': 'typ odpowiedzialności', 'verbose_name_plural': 'typy odpowiedzialności'},
        ),
        migrations.AddField(
            model_name='typ_odpowiedzialnosci',
            name='typ_pbn',
            field=models.SmallIntegerField(choices=[(0, 'autor'), (1, 'redaktor'), (2, 'inny')], default=0, verbose_name='Typ odpowiedzialności dla PBN'),
        ),
        migrations.RunPython(
            zmigruj_typy_odpowiedzialnosci,
            migrations.RunPython.noop
        )
    ]
