# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0119_pola_patentow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='kc_impact_factor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, default=None, help_text='Jeżeli wpiszesz\n        wartość w to pole, to zostanie ona użyta w raporcie dla Komisji\n        Centralnej w punkcie IXa tego raportu.', max_digits=6, null=True, verbose_name='KC: Impact factor'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='kc_impact_factor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, default=None, help_text='Jeżeli wpiszesz\n        wartość w to pole, to zostanie ona użyta w raporcie dla Komisji\n        Centralnej w punkcie IXa tego raportu.', max_digits=6, null=True, verbose_name='KC: Impact factor'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='kc_impact_factor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, default=None, help_text='Jeżeli wpiszesz\n        wartość w to pole, to zostanie ona użyta w raporcie dla Komisji\n        Centralnej w punkcie IXa tego raportu.', max_digits=6, null=True, verbose_name='KC: Impact factor'),
        ),
        migrations.AlterField(
            model_name='punktacja_zrodla',
            name='kc_impact_factor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, default=None, help_text='Jeżeli wpiszesz\n        wartość w to pole, to zostanie ona użyta w raporcie dla Komisji\n        Centralnej w punkcie IXa tego raportu.', max_digits=6, null=True, verbose_name='KC: Impact factor'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='kc_impact_factor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, default=None, help_text='Jeżeli wpiszesz\n        wartość w to pole, to zostanie ona użyta w raporcie dla Komisji\n        Centralnej w punkcie IXa tego raportu.', max_digits=6, null=True, verbose_name='KC: Impact factor'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='kc_impact_factor',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=3, default=None, help_text='Jeżeli wpiszesz\n        wartość w to pole, to zostanie ona użyta w raporcie dla Komisji\n        Centralnej w punkcie IXa tego raportu.', max_digits=6, null=True, verbose_name='KC: Impact factor'),
        ),
    ]
