# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 22:07
from __future__ import unicode_literals

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0135_merge_20180612_2304'),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0136_ranking_liczba_cytowan")
        )
    ]
