# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 07:19
from __future__ import unicode_literals

import bpp.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0138_uczelnia_pokazuj_liczbe_cytowan_w_rankingu'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='pokazuj_liczbe_cytowan_na_stronie_autora',
            field=bpp.models.fields.OpcjaWyswietlaniaField(choices=[('always', 'zawsze'), ('logged-in', 'tylko dla zalogowanych'), ('never', 'nigdy')], default='always', help_text='Liczba cytowań będzie wyświetlana, gdy większa od 0', max_length=50, verbose_name='Pokazuj liczbę cytowań na podstronie autora'),
        ),
    ]
