# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 11:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def wyrzuc_w_z_informacji(apps, schema_editor):
    Wydawnictwo_Zwarte = apps.get_model("bpp", "Wydawnictwo_Zwarte")
    for elem in Wydawnictwo_Zwarte.objects.filter(
            Q(informacje__istartswith="w:") or
            Q(informacje__istartswith="w :")):
        l = elem.informacje.lower()
        if l[:2] == "w:":
            n = 2
        if l[:3] == "w :":
            n = 3

        ni = elem.informacje[n:].strip()
        elem.informacje = ni
        elem.save()


class Migration(migrations.Migration):
    dependencies = [
        ('bpp', '0143_uczelnia_wydruk_logo_szerokosc'),
    ]

    operations = [
        migrations.RunPython(
            wyrzuc_w_z_informacji,
            migrations.RunPython.noop
        )
    ]
