# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0146_auto_20180629_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczelnia',
            name='wydruk_logo_szerokosc',
            field=models.SmallIntegerField(default=250, help_text='Podaj wartość w pikselach. Wysokość zostanie przeskalowana proporcjonalnie. ', verbose_name='Szerokość logo na wydrukach'),
        ),
    ]
