# Generated by Django 2.1.7 on 2019-03-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0154_auto_20190303_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='aktualna_funkcja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktualna_funkcja', to='bpp.Funkcja_Autora'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='aktualna_jednostka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktualna_jednostka', to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='plec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Plec'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='tytul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Tytul'),
        ),
        migrations.AlterField(
            model_name='autor_dyscyplina',
            name='dyscyplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Dyscyplina_Naukowa'),
        ),
        migrations.AlterField(
            model_name='autor_jednostka',
            name='funkcja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Funkcja_Autora'),
        ),
        migrations.AlterField(
            model_name='charakter_formalny',
            name='charakter_pbn',
            field=models.ForeignKey(blank=True, default=None, help_text='Wartość wybrana w tym polu zostanie użyta jako zawartość tagu <is>\n                                      w plikach eksportu do PBN', null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Charakter_PBN', verbose_name='Charakter PBN'),
        ),
        migrations.AlterField(
            model_name='jednostka',
            name='uczelnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Uczelnia'),
        ),
        migrations.AlterField(
            model_name='jednostka',
            name='wydzial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Wydzial', verbose_name='Wydział'),
        ),
        migrations.AlterField(
            model_name='jednostka_wydzial',
            name='jednostka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='jednostka_wydzial',
            name='wydzial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Wydzial'),
        ),
        migrations.AlterField(
            model_name='nagroda',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='nagroda',
            name='organ_przyznajacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.OrganPrzyznajacyNagrody'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='rodzaj_prawa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Rodzaj_Prawa_Patentowego'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='status_korekty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Status_Korekty'),
        ),
        migrations.AlterField(
            model_name='patent_autor',
            name='jednostka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='patent_autor',
            name='typ_odpowiedzialnosci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_Odpowiedzialnosci', verbose_name='Typ odpowiedzialności'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='jednostka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='jezyk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jezyk', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='status_korekty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Status_Korekty'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='typ_kbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_KBN', verbose_name='Typ KBN'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='jednostka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='jezyk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jezyk', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='status_korekty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Status_Korekty'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='typ_kbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_KBN', verbose_name='Typ KBN'),
        ),
        migrations.AlterField(
            model_name='publikacja_habilitacyjna',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'bpp'), ('model', 'wydawnictwo_ciagle')), models.Q(('app_label', 'bpp'), ('model', 'wydawnictwo_zwarte')), models.Q(('app_label', 'bpp'), ('model', 'patent')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='publikacja_habilitacyjna',
            name='praca_habilitacyjna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Praca_Habilitacyjna'),
        ),
        migrations.AlterField(
            model_name='redakcja_zrodla',
            name='redaktor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Autor'),
        ),
        migrations.AlterField(
            model_name='typ_kbn',
            name='charakter_pbn',
            field=models.ForeignKey(blank=True, default=None, help_text='Wartość wybrana w tym polu zostanie użyta jako \n        fallback, tzn. jeżeli dla charakteru formalnego danego rekordu nie \n        określono odpowiedniego charakteru PBN, to zostanie użyta wartość \n        tego pola, o ile wybrana. ', null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Charakter_PBN', verbose_name='Charakter PBN'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='charakter_formalny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Charakter_Formalny', verbose_name='Charakter formalny'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='jezyk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jezyk', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='konferencja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Konferencja'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='openaccess_czas_publikacji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Czas_Udostepnienia_OpenAccess', verbose_name='OpenAccess: czas udostępnienia'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='openaccess_licencja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Licencja_OpenAccess', verbose_name='OpenAccess: licencja'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='openaccess_wersja_tekstu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Wersja_Tekstu_OpenAccess', verbose_name='OpenAccess: wersja tekstu'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='status_korekty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Status_Korekty'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='typ_kbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_KBN', verbose_name='Typ KBN'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle_autor',
            name='jednostka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle_autor',
            name='typ_odpowiedzialnosci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_Odpowiedzialnosci', verbose_name='Typ odpowiedzialności'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle_zewnetrzna_baza_danych',
            name='baza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Zewnetrzna_Baza_Danych'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='charakter_formalny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Charakter_Formalny', verbose_name='Charakter formalny'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='jezyk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jezyk', verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='konferencja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Konferencja'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='openaccess_czas_publikacji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Czas_Udostepnienia_OpenAccess', verbose_name='OpenAccess: czas udostępnienia'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='openaccess_licencja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Licencja_OpenAccess', verbose_name='OpenAccess: licencja'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='openaccess_tryb_dostepu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Tryb_OpenAccess_Wydawnictwo_Zwarte'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='openaccess_wersja_tekstu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Wersja_Tekstu_OpenAccess', verbose_name='OpenAccess: wersja tekstu'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='seria_wydawnicza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Seria_Wydawnicza'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='status_korekty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Status_Korekty'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='typ_kbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_KBN', verbose_name='Typ KBN'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='wydawnictwo_nadrzedne',
            field=models.ForeignKey(blank=True, help_text='Jeżeli dodajesz rozdział,\n        tu wybierz pracę, w ramach której dany rozdział występuje.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wydawnictwa_powiazane_set', to='bpp.Wydawnictwo_Zwarte'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte_autor',
            name='jednostka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Jednostka'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte_autor',
            name='typ_odpowiedzialnosci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Typ_Odpowiedzialnosci', verbose_name='Typ odpowiedzialności'),
        ),
        migrations.AlterField(
            model_name='wydzial',
            name='uczelnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Uczelnia'),
        ),
        migrations.AlterField(
            model_name='zrodlo',
            name='jezyk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Jezyk'),
        ),
        migrations.AlterField(
            model_name='zrodlo',
            name='openaccess_licencja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.Licencja_OpenAccess', verbose_name='OpenAccess: licencja'),
        ),
        migrations.AlterField(
            model_name='zrodlo',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.Rodzaj_Zrodla'),
        ),
    ]
