# Generated by Django 2.1.7 on 2019-06-29 08:46

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0160_auto_20190627_0006'),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0161_dyscyplina_change_trigger")
        ),
    ]
