# Generated by Django 2.1.7 on 2019-09-10 12:16

import bpp.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0178_auto_20190905_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='pokazuj_raport_slotow',
            field=bpp.models.fields.OpcjaWyswietlaniaField(choices=[('always', 'zawsze'), ('logged-in', 'tylko dla zalogowanych'), ('never', 'nigdy')], default='logged-in', max_length=50, verbose_name='Pokazuj raport slotów'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='pokazuj_tabele_slotow_na_stronie_rekordu',
            field=bpp.models.fields.OpcjaWyswietlaniaField(choices=[('always', 'zawsze'), ('logged-in', 'tylko dla zalogowanych'), ('never', 'nigdy')], default='logged-in', max_length=50, verbose_name='Pokazuj tabelę slotów na stronie rekordu'),
        ),
    ]
