# Generated by Django 2.1.10 on 2019-10-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0182_auto_20191013_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_Punktacja_Autora_Sum_Group_Ponizej',
            fields=[
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bpp.Autor')),
                ('pkdautsum', models.FloatField()),
                ('pkdautslotsum', models.FloatField()),
            ],
            options={
                'db_table': 'bpp_temporary_cpasg_2',
                'ordering': ('autor', 'dyscyplina'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cache_Punktacja_Autora_Sum_Ponizej',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkdaut', models.DecimalField(decimal_places=4, max_digits=20)),
                ('slot', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pkdautslot', models.FloatField()),
                ('pkdautsum', models.FloatField()),
                ('pkdautslotsum', models.FloatField()),
            ],
            options={
                'db_table': 'bpp_temporary_cpaq_2',
                'ordering': ('autor', 'dyscyplina', 'pkdautslot'),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='poziom_wydawcy',
            options={'ordering': ('rok',), 'verbose_name': 'poziom wydawcy', 'verbose_name_plural': 'poziomy wydawcy'},
        ),
        migrations.AlterModelOptions(
            name='wydawca',
            options={'ordering': ('nazwa',), 'verbose_name': 'wydawca', 'verbose_name_plural': 'wydawcy'},
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='ranking_autorow_rozbij_domyslnie',
            field=models.BooleanField(default=False, verbose_name='Zaznacz domyślnie "Rozbij punktację na jednostki i wydziały" dla rankingu autorów'),
        ),
    ]
