# Generated by Django 2.2.10 on 2020-03-04 22:09

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0200_auto_20200304_2253"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0201_rekord_mat_z_www")
        )
    ]
