# Generated by Django 3.0.11 on 2021-02-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0240_auto_20210228_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="pbn_uuid",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="system_kadrowy_id",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Identyfikator cyfrowy, używany do matchowania autora z danymi z systemu kadrowego Uczelni",
                null=True,
                unique=True,
                verbose_name="Identyfikator w systemie kadrowym",
            ),
        ),
    ]
