# Generated by Django 3.0.11 on 2021-03-16 14:16

import autoslug.fields
from django.db import migrations

import bpp.models.util


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0250_auto_20210315_2104"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=400,
                null=True,
                populate_from=bpp.models.util.ModelZOpisemBibliograficznym._get_slug,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="praca_doktorska",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=400,
                null=True,
                populate_from=bpp.models.util.ModelZOpisemBibliograficznym._get_slug,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="praca_habilitacyjna",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=400,
                null=True,
                populate_from=bpp.models.util.ModelZOpisemBibliograficznym._get_slug,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=400,
                null=True,
                populate_from=bpp.models.util.ModelZOpisemBibliograficznym._get_slug,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=400,
                null=True,
                populate_from=bpp.models.util.ModelZOpisemBibliograficznym._get_slug,
                unique=True,
            ),
        ),
    ]
