# Generated by Django 3.0.11 on 2021-03-16 12:56

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0251_auto_20210316_1516"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0252_rekord_mat_slug")
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
    ]
