# Generated by Django 3.0.13 on 2021-03-16 22:25

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0252_slug"),
    ]

    operations = [
        #
        # Powyższe operacje wywołają skasowanie tabeli bpp_rekord_mat
        #
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0253_rekord_mat_slug")
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
    ]
