# Generated by Django 3.0.11 on 2021-04-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0008_auto_20210406_0530"),
        ("bpp", "0259_auto_20210421_2323"),
    ]

    operations = [
        migrations.AddField(
            model_name="jednostka",
            name="pbn_uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.Institution",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
    ]
