# Generated by Django 3.0.14 on 2021-05-03 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0010_auto_20210504_0040"),
        ("bpp", "0264_auto_20210428_0011"),
    ]

    operations = [
        migrations.AddField(
            model_name="praca_doktorska",
            name="pbn_uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.Publication",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
        migrations.AddField(
            model_name="praca_habilitacyjna",
            name="pbn_uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.Publication",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
    ]
