# Generated by Django 3.0.14 on 2021-05-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0269_wyzeruj_zrodlo_pbn_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="orcid_w_pbn",
            field=models.NullBooleanField(
                help_text="Jeżeli ORCID jest w bazie PBN, to pole powinno być zaznaczone. Zaznaczenie następuje\n        automatycznie, przez procedury integrujące bazę danych z PBNem w nocy. Można też zaznaczyć ręcznie.\n        Pole wykorzystywane jest gdy autor nie ma odpowiednika w PBN (pole 'PBN UID' rekordu autora jest puste,\n        zaś eksport danych powoduje komunikat zwrotny z PBN o nieistniejącym w ich bazie ORCID). W takich sytuacjach\n        należy pole odznaczyć. ",
                verbose_name="ORCID jest w bazie PBN?",
            ),
        ),
    ]
