# Generated by Django 3.0.14 on 2021-06-06 12:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations

import bpp.models.dyscyplina_naukowa


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0273_jednostka_hier"),
    ]

    operations = [
        migrations.AddField(
            model_name="jednostka",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="bpp.Jednostka",
            ),
        ),
        migrations.AlterField(
            model_name="dyscyplina_naukowa",
            name="kod",
            field=bpp.models.dyscyplina_naukowa.KodDyscyplinyField(
                max_length=20,
                unique=True,
                validators=[
                    bpp.models.dyscyplina_naukowa.waliduj_format_kodu_numer,
                    bpp.models.dyscyplina_naukowa.waliduj_format_kodu_numer,
                    bpp.models.dyscyplina_naukowa.waliduj_format_kodu_numer,
                ],
            ),
        ),
    ]
