# Generated by Django 3.0.14 on 2021-08-18 12:43

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0287_trgrm_extnsn"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0288_rekord_mat_isbn", app_name="bpp"),
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
    ]
