# Generated by Django 3.0.14 on 2021-08-20 15:05

from django.db import migrations

import bpp.models.dyscyplina_naukowa


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0290_bppmultiseekvis_detale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dyscyplina_naukowa",
            name="kod",
            field=bpp.models.dyscyplina_naukowa.KodDyscyplinyField(
                max_length=20, unique=True
            ),
        ),
    ]
