# Generated by Django 3.0.14 on 2021-10-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0296_nulltest_szablonopisu"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="ewaluacja2021_liczba_n",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Ewaluacja 2021",
                max_digits=9,
                null=True,
                verbose_name="Liczba N",
            ),
        ),
    ]
