# Generated by Django 3.0.14 on 2022-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0311_wyd_ciagle_kwartyle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patent_autor",
            name="przypieta",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Możesz odznaczyć, żeby "odpiąć" dyscyplinę od tego autora. Dyscyplina "odpięta" nie będzie\n        wykazywana do PBN oraz nie będzie używana do liczenia punktów dla danej pracy.',
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_autor",
            name="przypieta",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Możesz odznaczyć, żeby "odpiąć" dyscyplinę od tego autora. Dyscyplina "odpięta" nie będzie\n        wykazywana do PBN oraz nie będzie używana do liczenia punktów dla danej pracy.',
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_autor",
            name="przypieta",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Możesz odznaczyć, żeby "odpiąć" dyscyplinę od tego autora. Dyscyplina "odpięta" nie będzie\n        wykazywana do PBN oraz nie będzie używana do liczenia punktów dla danej pracy.',
            ),
        ),
    ]
