# Generated by Django 3.2.15 on 2022-08-28 22:52

from django.db import migrations

import bpp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0326_auto_20220818_0012"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_formularz_zglaszania_publikacji",
            field=bpp.models.fields.OpcjaWyswietlaniaField(
                choices=[
                    ("always", "zawsze"),
                    ("logged-in", "tylko dla zalogowanych"),
                    ("staff", "tylko dla zespołu"),
                    ("never", "nigdy"),
                ],
                default="always",
                help_text="Czy pokazywać formularz zgłaszania publikacji?",
                max_length=50,
                verbose_name="Pokazuj opcję 'Zgłoś nową publikację'",
            ),
        ),
    ]
