# Generated by Django 3.2.16 on 2022-11-22 10:30

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0332_pbn_zawsze_uid_uczelni"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0333_autorzy_kierunek_studiow")
        ),
        # To musi być wczytane, bo "DROP CASCADE" i gubi widoki ewaluacyjne
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        # To również
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
    ]
