# Generated by Django 3.2.16 on 2023-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0333_autorzy_kierunek_studiow"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent_autor",
            name="oswiadczenie_ken",
            field=models.BooleanField(
                default=None,
                help_text="Oświadczenie Komisji Ewaluacji Nauki (Uniwersytet Medyczny w Lublinie)",
                null=True,
                verbose_name="Oświadczenie KEN",
            ),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="oswiadczenie_ken",
            field=models.BooleanField(
                default=None,
                help_text="Oświadczenie Komisji Ewaluacji Nauki (Uniwersytet Medyczny w Lublinie)",
                null=True,
                verbose_name="Oświadczenie KEN",
            ),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="oswiadczenie_ken",
            field=models.BooleanField(
                default=None,
                help_text="Oświadczenie Komisji Ewaluacji Nauki (Uniwersytet Medyczny w Lublinie)",
                null=True,
                verbose_name="Oświadczenie KEN",
            ),
        ),
    ]
