# Generated by Django 3.2.16 on 2023-02-05 22:27

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0334_oswiadczenie_ken_modele"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0335_autorzy_oswiadczenie_ken")
        ),
        # To musi być wczytane, bo "DROP CASCADE" i gubi widoki ewaluacyjne
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        # To również
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
    ]
