# Generated by Django 3.2.16 on 2023-04-16 21:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0335_autorzy_oswiadczenie_ken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jednostka",
            name="opis",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
