# Generated by Django 3.2.16 on 2023-04-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0336_jednostka_opis_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patent_autor",
            name="oswiadczenie_ken",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Oświadczenie Komisji Ewaluacji Nauki (Uniwersytet Medyczny w Lublinie)",
                null=True,
                verbose_name="Oświadczenie KEN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_autor",
            name="oswiadczenie_ken",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Oświadczenie Komisji Ewaluacji Nauki (Uniwersytet Medyczny w Lublinie)",
                null=True,
                verbose_name="Oświadczenie KEN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_autor",
            name="oswiadczenie_ken",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Oświadczenie Komisji Ewaluacji Nauki (Uniwersytet Medyczny w Lublinie)",
                null=True,
                verbose_name="Oświadczenie KEN",
            ),
        ),
    ]
