# Generated by Django 3.2.16 on 2023-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0337_oswiadczenie_ken_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="wydzial",
            name="pokazuj_opis",
            field=models.BooleanField(default=False),
        ),
    ]
