# Generated by Django 3.2.16 on 2023-06-22 17:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0338_wydzial_pokazuj_opis"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="opis",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="pokazuj_opis",
            field=models.BooleanField(
                default=False, help_text="Czy pokazywać tekst z pola 'Opis' na stronie?"
            ),
        ),
    ]
