# Generated by Django 4.2.3 on 2023-09-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0037_alter_discipline_options_and_more"),
        ("bpp", "0340_skasuj_anonimowe_zdarzenia"),
    ]

    operations = [
        migrations.AddField(
            model_name="dyscyplina_naukowa",
            name="pbn_uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.discipline",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
    ]
