# Generated by Django 4.2.5 on 2023-11-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0341_dyscyplina_naukowa_pbn_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dyscyplina_naukowa",
            name="pbn_uid",
        ),
    ]
