# Generated by Django 4.2.8 on 2023-12-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0343_alter_typ_kbn_options_alter_patent_kc_punkty_kbn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pbn_wysylaj_bez_oswiadczen",
            field=models.BooleanField(
                default=False,
                help_text="Umożliwiaj wysyłanie prac bez oświadczeń do PBN. Domyślnie wyłączone.",
                verbose_name="Wysyłaj prace bez oświadczeń",
            ),
        ),
    ]
