# Generated by Django 4.2.8 on 2023-12-10 18:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0344_uczelnia_pbn_wysylaj_bez_oswiadczen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wydzial",
            name="opis",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
