# Generated by Django 4.2.8 on 2023-12-11 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("bpp", "0345_alter_wydzial_opis"), ("multiseek", "0001_initial")]

    operations = [
        migrations.RunSQL(
            "update multiseek_searchform set data = replace(data, 'Punkty PK', 'Punkty MNiSW/MEiN')",
            "update multiseek_searchform set data = replace(data, 'Punkty MNiSW/MEiN', 'Punkty PK')",
        ),
        migrations.RunSQL(
            "update multiseek_searchform set data = replace(data, 'Typ KBN', 'Typ MNiSW/MEiN')",
            "update multiseek_searchform set data = replace(data, 'Typ MNiSW/MEiN', 'Typ KBN')",
        ),
    ]
