# Generated by Django 4.2.9 on 2024-05-22 19:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0346_rename_multiseek_searchform_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="deklaracja_dostepnosci_tekst",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="deklaracja_dostepnosci_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_deklaracje_dostepnosci",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "nie pokazuj"),
                    (1, "zewnętrzny adres URL (wpisz ponizej)"),
                    (2, "tekst na stronie (wpisz poniżej)"),
                ],
                default=0,
            ),
        ),
    ]
