# Generated by Django 4.2.14 on 2024-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0349_uczelnia_ranking_autorow_bez_kol_naukowych"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_autorow_obcych_w_przegladaniu_danych",
            field=models.BooleanField(
                default=False,
                help_text="Autor obcy to taki, który ma afiliację wyłącznie na\n        obcą jednostkę i obca jednostka jest jego jednostką aktualną",
                verbose_name="Pokazuj autorów obcych w przeglądaniu danych",
            ),
        ),
    ]
