# Generated by Django 4.2.14 on 2024-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0350_uczelnia_pokazuj_autorow_obcych_w_przegladaniu_danych"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_autorow_bez_prac_w_przegladaniu_danych",
            field=models.BooleanField(
                default=True,
                verbose_name="Pokazuj autorów nie posiadających rekordów publikacji w przeglądaniu danych",
            ),
        ),
    ]
