# Generated by Django 4.2.16 on 2024-10-15 11:47

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0352_dyscyplina_zrodla_rok"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0353_rekord_mat_kwartyle", app_name="bpp"
            ),
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "../../rozbieznosci_dyscyplin/migrations/0011_null_is_wrong"
            )
        ),
    ]
