# Generated by Django 4.2.16 on 2024-10-14 11:27
from django.db import migrations, transaction
from django.db.models import Q


@transaction.atomic
def ustaw_wstecznie_kwartyle(apps, schema_editor):
    Punktacja_Zrodla = apps.get_model("bpp", "Punktacja_Zrodla")
    Wydawnictwo_Ciagle = apps.get_model("bpp", "Wydawnictwo_Ciagle")

    for wydawnictwo_ciagle in Wydawnictwo_Ciagle.objects.exclude(
        Q(kwartyl_w_wos=None) & Q(kwartyl_w_scopus=None)
    ):
        try:
            pz = Punktacja_Zrodla.objects.get(
                zrodlo=wydawnictwo_ciagle.zrodlo, rok=wydawnictwo_ciagle.rok
            )
        except Punktacja_Zrodla.DoesNotExist:
            Punktacja_Zrodla.objects.create(
                zrodlo=wydawnictwo_ciagle.zrodlo,
                rok=wydawnictwo_ciagle.rok,
                impact_factor=wydawnictwo_ciagle.impact_factor,
                punkty_kbn=wydawnictwo_ciagle.punkty_kbn,
                index_copernicus=wydawnictwo_ciagle.index_copernicus,
                punktacja_wewnetrzna=wydawnictwo_ciagle.punktacja_wewnetrzna,
                punktacja_snip=wydawnictwo_ciagle.punktacja_snip,
                kwartyl_w_wos=wydawnictwo_ciagle.kwartyl_w_wos,
                kwartyl_w_scopus=wydawnictwo_ciagle.kwartyl_w_scopus,
            )
            continue

        if pz.kwartyl_w_wos is None:
            pz.kwartyl_w_wos = wydawnictwo_ciagle.kwartyl_w_wos

        if pz.kwartyl_w_scopus is None:
            pz.kwartyl_w_scopus = wydawnictwo_ciagle.kwartyl_w_scopus

        if (
            wydawnictwo_ciagle.kwartyl_w_scopus is not None
            and pz.kwartyl_w_scopus is not None
            and pz.kwartyl_w_scopus != wydawnictwo_ciagle.kwartyl_w_scopus
        ):
            print(
                f"{wydawnictwo_ciagle} {wydawnictwo_ciagle.rok} {wydawnictwo_ciagle.zrodlo} kwartyl w SCOPUS "
                f"zrodla {pz.kwartyl_w_scopus} zas rekordu {wydawnictwo_ciagle.kwartyl_w_scopus}"
            )

        if (
            wydawnictwo_ciagle.kwartyl_w_wos is not None
            and pz.kwartyl_w_wos is not None
            and pz.kwartyl_w_wos != wydawnictwo_ciagle.kwartyl_w_wos
        ):
            print(
                f"{wydawnictwo_ciagle} {wydawnictwo_ciagle.rok} {wydawnictwo_ciagle.zrodlo} kwartyl w WOS "
                f"zrodla {pz.kwartyl_w_wos} zas rekordu {wydawnictwo_ciagle.kwartyl_w_wos}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0352_dyscyplina_zrodla_rok"),
    ]

    operations = [
        migrations.RunPython(ustaw_wstecznie_kwartyle, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="wydawnictwo_ciagle",
            name="kwartyl_w_scopus",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_ciagle",
            name="kwartyl_w_wos",
        ),
    ]
