# Generated by Django 4.2.16 on 2024-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0353_rekord_mat_kwartyle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dyscyplina_zrodla",
            options={
                "ordering": ["zrodlo__nazwa", "rok", "dyscyplina__nazwa"],
                "verbose_name": "przypisanie dyscypliny do źródła",
                "verbose_name_plural": "przypisanie dyscyplin do źródła",
            },
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="drukuj_alternatywne_oswiadczenia",
            field=models.BooleanField(
                default=True,
                help_text="Jeżeli autor ma dwie dyscypliny, drukuj zawsze dwa oświadczenia",
                verbose_name="Drukuj alternatywne oświadczenia dla autorów",
            ),
        ),
    ]
