# Generated by Django 4.2.16 on 2024-10-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0354_alter_dyscyplina_zrodla_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="drukuj_oswiadczenia",
            field=models.BooleanField(
                default=True,
                help_text="Włącza wydruk oświadczeń z podstrony rekordu - wyłącznie dla osób z grupy 'wprowadzanie danych'.",
                verbose_name="Drukuj oświadczenia dla autorów",
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="drukuj_alternatywne_oswiadczenia",
            field=models.BooleanField(
                default=True,
                help_text="Jeżeli autor ma dwie dyscypliny, drukuj zawsze dwa oświadczenia.",
                verbose_name="Drukuj alternatywne oświadczenia dla autorów",
            ),
        ),
    ]
