# Generated by Django 4.2.16 on 2024-10-17 11:37

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0355_uczelnia_drukuj_oswiadczenia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patent",
            name="kc_impact_factor",
        ),
        migrations.RemoveField(
            model_name="patent",
            name="kc_index_copernicus",
        ),
        migrations.RemoveField(
            model_name="patent",
            name="kc_punkty_kbn",
        ),
        migrations.RemoveField(
            model_name="praca_doktorska",
            name="kc_impact_factor",
        ),
        migrations.RemoveField(
            model_name="praca_doktorska",
            name="kc_index_copernicus",
        ),
        migrations.RemoveField(
            model_name="praca_doktorska",
            name="kc_punkty_kbn",
        ),
        migrations.RemoveField(
            model_name="praca_habilitacyjna",
            name="kc_impact_factor",
        ),
        migrations.RemoveField(
            model_name="praca_habilitacyjna",
            name="kc_index_copernicus",
        ),
        migrations.RemoveField(
            model_name="praca_habilitacyjna",
            name="kc_punkty_kbn",
        ),
        migrations.RemoveField(
            model_name="punktacja_zrodla",
            name="kc_impact_factor",
        ),
        migrations.RemoveField(
            model_name="punktacja_zrodla",
            name="kc_index_copernicus",
        ),
        migrations.RemoveField(
            model_name="punktacja_zrodla",
            name="kc_punkty_kbn",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_ciagle",
            name="kc_impact_factor",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_ciagle",
            name="kc_index_copernicus",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_ciagle",
            name="kc_punkty_kbn",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_zwarte",
            name="kc_impact_factor",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_zwarte",
            name="kc_index_copernicus",
        ),
        migrations.RemoveField(
            model_name="wydawnictwo_zwarte",
            name="kc_punkty_kbn",
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0356_drop_kc_komisja_centralna", app_name="bpp"
            ),
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0356_nowe_sumy_wliczaj_do")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "../../rozbieznosci_dyscyplin/migrations/0011_null_is_wrong"
            )
        ),
    ]
