# Generated by Django 4.2.17 on 2024-12-10 22:43

from django.db import migrations, models

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0356_drop_kc_komisja_centralna"),
    ]

    operations = [
        migrations.AddField(
            model_name="wydawnictwo_ciagle",
            name="openaccess_data_opublikowania",
            field=models.DateField(
                blank=True, null=True, verbose_name="OpenAccess: data publikacji"
            ),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte",
            name="openaccess_data_opublikowania",
            field=models.DateField(
                blank=True, null=True, verbose_name="OpenAccess: data publikacji"
            ),
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0357_openaccess_data_opublikowania", app_name="bpp"
            ),
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0356_nowe_sumy_wliczaj_do")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "../../rozbieznosci_dyscyplin/migrations/0011_null_is_wrong"
            )
        ),
    ]
