# Generated by Django 4.2.18 on 2025-01-20 13:07

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0357_openaccess_data_opublikowania"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0358_nowe_sumy_view_add_pk",
            )
        ),
    ]
