# Generated by Django 4.2.19 on 2025-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0359_patent_slowa_kluczowe_eng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_zrodla_bez_prac_w_przegladaniu_danych",
            field=models.BooleanField(
                default=False,
                verbose_name="Pokazuj źródła bez powiązanych rekordów w przeglądaniu danych",
            ),
        ),
    ]
