# Generated by Django 4.2.19 on 2025-02-17 00:11

from django.db import migrations, models

import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0360_uczelnia_pokazuj_zrodla_bez_prac_w_przegladaniu_danych_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patent",
            name="slowa_kluczowe_eng",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="Lista słów kluczowych -- język angielski",
                null=True,
                size=None,
                verbose_name="Słowa kluczowe -- język angielski",
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="slowa_kluczowe_eng",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="Lista słów kluczowych -- język angielski",
                null=True,
                size=None,
                verbose_name="Słowa kluczowe -- język angielski",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="slowa_kluczowe_eng",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="Lista słów kluczowych -- język angielski",
                null=True,
                size=None,
                verbose_name="Słowa kluczowe -- język angielski",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="slowa_kluczowe_eng",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="Lista słów kluczowych -- język angielski",
                null=True,
                size=None,
                verbose_name="Słowa kluczowe -- język angielski",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="slowa_kluczowe_eng",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                help_text="Lista słów kluczowych -- język angielski",
                null=True,
                size=None,
                verbose_name="Słowa kluczowe -- język angielski",
            ),
        ),
    ]
