# Generated by Django 4.2.19 on 2025-02-17 00:11

from django.db import migrations, models


def utworz_rzeczowniki(apps, schema_editor):
    Rzeczownik = apps.get_model("bpp", "Rzeczownik")
    Rzeczownik.objects.create(
        uid="UCZELNIA",
        m="uczelnia",
        d="uczelni",
        c="uczelni",
        b="uczelnię",
        n="uczelnią",
        ms="uczelni",
        w="uczelnio",
    )

    Rzeczownik.objects.create(
        uid="WYDZIAL",
        m="wydział",
        d="wydziału",
        c="wydziałowi",
        b="wydział",
        n="wydziałem",
        ms="wydziale",
        w="wydział",
    )

    Rzeczownik.objects.create(
        uid="WYDZIAL_PL",
        m="wydziały",
        d="wydziałów",
        c="wydziałom",
        b="wydziały",
        n="wydziałami",
        ms="wydziałach",
        w="wydziały",
    )

    Rzeczownik.objects.create(
        uid="JEDNOSTKA",
        m="jednostka",
        d="jednostki",
        c="jednostce",
        b="jednostkę",
        n="jednostką",
        ms="jednostce",
        w="jednostko",
    )

    Rzeczownik.objects.create(
        uid="JEDNOSTKA_PL",
        m="jednostki",
        d="jednostek",
        c="jednostkom",
        b="jednostki",
        n="jednostkami",
        ms="jednostkach",
        w="jednostki",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0361_alter_patent_slowa_kluczowe_eng_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rzeczownik",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("m", models.CharField(max_length=200)),
                ("d", models.CharField(max_length=200)),
                ("c", models.CharField(max_length=200)),
                ("b", models.CharField(max_length=200)),
                ("n", models.CharField(max_length=200)),
                ("ms", models.CharField(max_length=200)),
                ("w", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "rzeczowniki",
            },
        ),
        migrations.RunPython(utworz_rzeczowniki),
    ]
