# Generated by Django 4.2.19 on 2025-02-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0362_rzeczownik"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_jednostki_na_pierwszej_stronie",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_wydzialy_na_pierwszej_stronie",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="b",
            field=models.CharField(
                help_text="kogo? co?", max_length=200, verbose_name="biernik"
            ),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="c",
            field=models.CharField(
                help_text="komu? czemu?", max_length=200, verbose_name="celownik"
            ),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="d",
            field=models.CharField(
                help_text="kogo? czego?", max_length=200, verbose_name="dopełniacz"
            ),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="m",
            field=models.CharField(
                help_text="kto? co?", max_length=200, verbose_name="mianownik"
            ),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="ms",
            field=models.CharField(
                help_text="o kim? o czym?", max_length=200, verbose_name="miejscownik"
            ),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="n",
            field=models.CharField(
                help_text="z kim? z czym?", max_length=200, verbose_name="narzędnik"
            ),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="uid",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rzeczownik",
            name="w",
            field=models.CharField(
                help_text="o!", max_length=200, verbose_name="wołacz"
            ),
        ),
    ]
