# Generated by Django 4.2.19 on 2025-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0364_rzeczownik_uczelnie_pl"),
    ]

    operations = [
        migrations.AddField(
            model_name="bppuser",
            name="pbn_token_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
