# Generated by Django 4.2.19 on 2025-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0365_bppuser_pbn_token_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uczelnia",
            name="pbn_api_afiliacja_zawsze_na_uczelnie",
            field=models.BooleanField(
                default=True,
                help_text="Jeżeli praca jest w jednostce z wypełnionym PBN UID bądź w jednostce innej-niż-obca, zatrudniającej-pracowników, to zaznaczenie tej opcji spowoduje, ze  zamiast PBN UID tej jednostki zostanie użyty PBN UID uczelni, co efektywnie spowoduje, że afiliacje w PBN będą na uczelnię, nie zaś na konkretną jednostkę. ",
                verbose_name="Wysyłaj zawsze PBN UID uczelni jako afiliację",
            ),
        ),
    ]
