# Generated by Django 4.2.19 on 2025-02-21 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0366_alter_uczelnia_pbn_api_afiliacja_zawsze_na_uczelnie"),
    ]

    operations = [
        migrations.AddField(
            model_name="bppuser",
            name="przedstawiaj_w_pbn_jako",
            field=models.ForeignKey(
                blank=True,
                help_text="Jeżeli wybrany użytkownik nie ma konta w PBNie, może nadal wysyłać prace jako inny użytkiownik systemu BPP; wybierz konto z którego ma być wysyłane w tym polu. ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
