# Generated by Django 4.2.19 on 2025-03-02 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0048_remove_pbn_export_queue_retry_politics_and_more"),
        ("bpp", "0368_wydawnictwo_zwarte_wydawnictwo_nadrzedne_w_pbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="wydawnictwo_nadrzedne_w_pbn",
            field=models.ForeignKey(
                blank=True,
                help_text="Jeżeli ten rekord to rozdział, a redakcja książki nie jest z obecnej instytucji, możesz uzupełnić\n        to pole, aby móc wysłać 'swój' rozdział do PBNu i jednocześnie nie musieć dodawać do bazy BPP 'cudzej' książki.\n        Innymi słowy, jeżeli 'okładki' dla Twojego rozdziału znajdują się w PBN i nie chcesz ich dodawać do BPP,\n        to skorzystaj z tego pola. Jeżeli jednak wypełnisz to pole, to musisz pozostawić oryginalne\n        'Wydawnictwo nadrzędne' puste. ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pbn_api.publication",
                verbose_name="Wydawnictwo nadrzędne w PBN",
            ),
        ),
    ]
