# Generated by Django 4.2.19 on 2025-03-08 01:14

from django.db import migrations


def usun_spacje(apps, schema_editor):
    Dyscyplina_Naukowa = apps.get_model("bpp", "Dyscyplina_Naukowa")
    for elem in Dyscyplina_Naukowa.objects.all():
        elem.nazwa = elem.nazwa.strip()
        elem.kod = elem.kod.strip()
        elem.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0370_alter_autor_dyscyplina_options_jezyk_widoczny"),
    ]

    operations = [migrations.RunPython(usun_spacje)]
