# Generated by Django 4.2.19 on 2025-03-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0371_usun_spacje_z_nazw_dyscyplin"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor_dyscyplina",
            name="dni_absencji",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="autor_dyscyplina",
            name="jest_w_N",
            field=models.BooleanField(default=False),
        ),
    ]
