# Generated by Django 4.2.19 on 2025-03-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0372_autor_dyscyplina_dni_absencji_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="praca_doktorska",
            name="jezyk",
            field=models.ForeignKey(
                limit_choices_to={"widoczny": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.jezyk",
                verbose_name="Język",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="jezyk",
            field=models.ForeignKey(
                limit_choices_to={"widoczny": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.jezyk",
                verbose_name="Język",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="jezyk",
            field=models.ForeignKey(
                limit_choices_to={"widoczny": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.jezyk",
                verbose_name="Język",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="jezyk",
            field=models.ForeignKey(
                limit_choices_to={"widoczny": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.jezyk",
                verbose_name="Język",
            ),
        ),
    ]
