# Generated by Django 4.2.19 on 2025-03-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0373_alter_praca_doktorska_jezyk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor_dyscyplina",
            name="dni_absencji",
        ),
        migrations.RemoveField(
            model_name="autor_dyscyplina",
            name="jest_w_N",
        ),
        migrations.CreateModel(
            name="Autor_Absencja",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rok", models.PositiveSmallIntegerField()),
                ("ile_dni", models.PositiveSmallIntegerField()),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bpp.autor"
                    ),
                ),
            ],
            options={
                "verbose_name": "absencja autora za rok",
                "verbose_name_plural": "absencje autorów za lata",
                "unique_together": {("rok", "autor")},
            },
        ),
    ]
