# Generated by Django 4.2.19 on 2025-03-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0374_remove_autor_dyscyplina_dni_absencji_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor_absencja",
            options={
                "verbose_name": "absencja autora za rok",
                "verbose_name_plural": "absencje autora za lata",
            },
        ),
    ]
