# Generated by Django 4.2.19 on 2025-03-16 19:37

from django.db import migrations, models


def ustaw_rodzaj_autora_na_N_tam_gdzie_pusty(apps, schema_editor):
    Autor_Dyscyplina = apps.get_model("bpp", "Autor_Dyscyplina")
    Autor_Dyscyplina.objects.filter(rodzaj_autora=" ").update(rodzaj_autora="N")


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0375_alter_autor_absencja_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor_dyscyplina",
            name="rodzaj_autora",
            field=models.CharField(
                choices=[
                    (" ", "brak danych"),
                    ("N", "pracownik zaliczany do liczby N"),
                    ("D", "doktorant"),
                    ("Z", "inny zatrudniony"),
                ],
                # Domyślnie ustawiaj autora w N
                default="N",
                max_length=1,
            ),
        ),
        migrations.RunPython(ustaw_rodzaj_autora_na_N_tam_gdzie_pusty),
    ]
