# Generated by Django 4.2.19 on 2025-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0376_alter_autor_dyscyplina_rodzaj_autora"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor_dyscyplina",
            name="zatrudnienie_do",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="autor_dyscyplina",
            name="zatrudnienie_od",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
