# Generated by Django 4.2.19 on 2025-03-16 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0048_remove_pbn_export_queue_retry_politics_and_more"),
        ("bpp", "0377_autor_dyscyplina_zatrudnienie_do_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="praca_doktorska",
            name="pbn_uid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.publication",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="pbn_uid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.publication",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="pbn_uid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.publication",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="pbn_uid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.publication",
                verbose_name="Odpowiednik w PBN",
            ),
        ),
    ]
