# Generated by Django 4.2.19 on 2025-03-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0378_alter_praca_doktorska_pbn_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patent_autor",
            name="upowaznienie_pbn",
            field=models.BooleanField(
                default=True,
                help_text='Tik w polu "upoważnienie PBN" oznacza, że dany autor upoważnił Uczelnię do sprawozdania tej publikacji w ocenie parametrycznej Uczelni',
                verbose_name="Upoważnienie PBN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_autor",
            name="upowaznienie_pbn",
            field=models.BooleanField(
                default=True,
                help_text='Tik w polu "upoważnienie PBN" oznacza, że dany autor upoważnił Uczelnię do sprawozdania tej publikacji w ocenie parametrycznej Uczelni',
                verbose_name="Upoważnienie PBN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_autor",
            name="upowaznienie_pbn",
            field=models.BooleanField(
                default=True,
                help_text='Tik w polu "upoważnienie PBN" oznacza, że dany autor upoważnił Uczelnię do sprawozdania tej publikacji w ocenie parametrycznej Uczelni',
                verbose_name="Upoważnienie PBN",
            ),
        ),
    ]
