# Generated by Django 4.2.19 on 2025-04-06 21:08

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0379_cache_liczba_n_last_updated_and_more"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0380_rekord_wydawca", app_name="bpp"),
        ),
        # Odbudowanie tabeli rekord_mat spowoduje skasowanie bpp_uczelnia_ewaluacja_view,
        # stąd potrzeba zaciągnąć ten plik z poprzednich migracji:
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0358_nowe_sumy_view_add_pk")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "../../rozbieznosci_dyscyplin/migrations/0011_null_is_wrong"
            )
        ),
    ]
