# Generated by Django 4.2.19 on 2025-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0381_uczelnia_przydzielaj_1_slot_gdy_udzial_mniejszy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uczelnia",
            name="przydzielaj_1_slot_gdy_udzial_mniejszy",
            field=models.BooleanField(
                default=False,
                help_text='Jeżeli zaznaczone, system będzie przydzielać 1 slot dla autorów, którzy za 4 lata ewaluacji"\n                  mieliby mieć mniej, niż 1 slot. Obowiązuje zarówno dla artykułów jak i dla monografii. Zatem,\n                  jeżeli ktoś za 4 lata ewaluacji będzie miał zdać 0.8 slota, to gdy ta flaga jest zaznaczona to\n                  system zwiększy to do 1 slota za artykuły oraz do 1 slota za monografie. Jeżeli ta flaga jest\n                  nie zaznaczona, to system policzy takiej osobie 0.8 slota za artykuły i 0.4 slota za monografie. ',
                verbose_name="Przydzielaj 1 slot gdy udziały za 4 lata mniejsze",
            ),
        ),
    ]
