# Generated by Django 4.2.19 on 2025-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0382_alter_uczelnia_przydzielaj_1_slot_gdy_udzial_mniejszy"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="pytaj_o_zgode_na_publikacje_pelnego_tekstu",
            field=models.BooleanField(
                default=False,
                verbose_name="Pytaj o zgodę na publikację pełnego tekstu w formularzu zgłoszeniowym prac",
            ),
        ),
    ]
