# Generated by Django 4.2.19 on 2025-08-11 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0383_uczelnia_pytaj_o_zgode_na_publikacje_pelnego_tekstu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charakter_formalny",
            name="charakter_crossref",
        ),
        migrations.CreateModel(
            name="Crossref_Mapper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charakter_crossref",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "journal-article"),
                            (2, "proceedings-article"),
                            (3, "book"),
                            (4, "book-chapter"),
                            (5, "edited-book"),
                        ],
                        unique=True,
                        verbose_name="Charakter w CrossRef",
                    ),
                ),
                (
                    "charakter_formalny_bpp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.charakter_formalny",
                    ),
                ),
            ],
            options={
                "verbose_name": "mapowanie typu CrossRef na BPP",
                "verbose_name_plural": "mapowania typów CrossRef na BPP",
            },
        ),
    ]
