# Generated by Django 4.2.19 on 2025-08-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0384_remove_charakter_formalny_charakter_crossref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crossref_mapper",
            name="charakter_crossref",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "journal-article"),
                    (2, "proceedings-article"),
                    (3, "book"),
                    (4, "book-chapter"),
                    (5, "edited-book"),
                    (6, "proceedings"),
                ],
                unique=True,
                verbose_name="Charakter w CrossRef",
            ),
        ),
        migrations.AlterField(
            model_name="crossref_mapper",
            name="charakter_formalny_bpp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bpp.charakter_formalny",
            ),
        ),
    ]
