# Generated by Django 4.2.19 on 2025-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0385_alter_crossref_mapper_charakter_crossref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crossref_mapper",
            name="charakter_crossref",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "journal-article"),
                    (2, "proceedings-article"),
                    (3, "book"),
                    (4, "book-chapter"),
                    (5, "edited-book"),
                    (6, "proceedings"),
                    (7, "monograph"),
                    (8, "reference-book"),
                    (9, "book-series"),
                    (10, "book-set"),
                    (11, "book-section"),
                    (12, "book-part"),
                    (13, "dissertation"),
                    (14, "posted-content"),
                    (15, "peer-review"),
                    (16, "other"),
                ],
                unique=True,
                verbose_name="Charakter w CrossRef",
            ),
        ),
    ]
