# Generated by Django 4.2.19 on 2025-08-18 10:40

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0386_alter_crossref_mapper_charakter_crossref"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0387_fix_refresh_cache_locking_deadlocks"
            )
        ),
    ]
