# Generated by Django 4.2.19 on 2025-08-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0387_fix_refresh_cache_locking_deadlocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="uzywaj_wydzialow",
            field=models.BooleanField(
                default=True,
                help_text="Jeżeli struktura instytucji jest 2-progowa: uczelnia -> wydział -> jednostka, zaznacz na TAK. \n        Jeżeli struktura instytucji jest 1-progowa: instytut -> dział, zaznacz na NIE. ",
                verbose_name="Używaj wydziałów",
            ),
        ),
    ]
