# Generated by Django 4.2.25 on 2025-10-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_common", "0004_alter_rodzaj_autora_options"),
        ("bpp", "0391_migrate_rodzaj_autora_to_foreignkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor_dyscyplina",
            name="rodzaj_autora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="autor_dyscyplina",
                to="ewaluacja_common.rodzaj_autora",
                verbose_name="Rodzaj autora",
            ),
        ),
    ]
