# Generated by Django 4.2.25 on 2025-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0392_alter_autor_dyscyplina_rodzaj_autora"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="tytul_strony_glownej",
            field=models.TextField(
                default="Bibliografia Publikacji Pracowników",
                help_text="HTML z tytułem strony głównej. Możesz użyć tagów HTML do formatowania.",
                verbose_name="Tytuł strony głównej",
            ),
        ),
    ]
