# Generated by Django 4.2.25 on 2025-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0393_uczelnia_tytul_strony_glownej"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uczelnia",
            name="clarivate_password",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Hasło"
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="clarivate_username",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Nazwa użytkownika"
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="deklaracja_dostepnosci_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="pbn_app_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Nazwa aplikacji w PBN",
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="pbn_app_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Token aplikacji w PBN",
            ),
        ),
    ]
