# Generated by Django 4.2.25 on 2025-11-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0394_alter_uczelnia_clarivate_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="wymagaj_logowania_zglos_publikacje",
            field=models.BooleanField(
                default=False,
                help_text="Jeśli zaznaczone, użytkownik musi się zalogować przed zgłoszeniem publikacji, niezależnie od ustawienia widoczności przycisku 'Zgłoś nową publikację'. Niezalogowani użytkownicy zostaną przekierowani na stronę logowania.",
                verbose_name="Wymagaj zalogowania użytkownika dla formularza zgłaszania publikacji",
            ),
        ),
    ]
