# Generated by Django 4.2.25 on 2025-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0395_add_wymagaj_logowania_zglos_publikacje"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="nowy_autor_z_formularza_pokazuj",
            field=models.BooleanField(
                default=False,
                help_text="Gdy zaznaczone, autorzy tworzeni automatycznie przez formularze z rozwijaną listą wyboru\n        (autocomplete) będą mieli ustawione pole 'pokazuj' na PRAWDA, co oznacza że będą widoczni na stronach\n        jednostek oraz w rankingach. Gdy odznaczone (domyślnie), nowi autorzy będą ukryci.",
                verbose_name="Nowy autor tworzony przez autocomplete jest widoczny",
            ),
        ),
    ]
