# Generated by Django 4.2.25 on 2025-11-13 00:32

from django.db import migrations, models


def convert_null_to_empty_string(apps, schema_editor):
    """Konwertuje wartości NULL na puste stringi dla pól tekstowych w modelu Autor"""
    Autor = apps.get_model("bpp", "Autor")
    Autor.objects.filter(pseudonim__isnull=True).update(pseudonim="")
    Autor.objects.filter(email__isnull=True).update(email="")
    Autor.objects.filter(www__isnull=True).update(www="")
    Autor.objects.filter(poprzednie_nazwiska__isnull=True).update(poprzednie_nazwiska="")


def reverse_empty_string_to_null(apps, schema_editor):
    """Odwraca konwersję - konwertuje puste stringi z powrotem na NULL (dla rollback)"""
    Autor = apps.get_model("bpp", "Autor")
    Autor.objects.filter(pseudonim="").update(pseudonim=None)
    Autor.objects.filter(email="").update(email=None)
    Autor.objects.filter(www="").update(www=None)
    Autor.objects.filter(poprzednie_nazwiska="").update(poprzednie_nazwiska=None)


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0396_uczelnia_nowy_autor_z_formularza_pokazuj"),
    ]

    operations = [
        migrations.RunPython(convert_null_to_empty_string, reverse_empty_string_to_null),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=128, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="poprzednie_nazwiska",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Jeżeli ten\n        autor(-ka) posiada nazwisko panieńskie, pod którym ukazywały\n        się publikacje lub zmieniał nazwisko z innych powodów, wpisz tutaj\n        wszystkie poprzednie nazwiska, oddzielając je przecinkami.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="pseudonim",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\n    Jeżeli w bazie danych znajdują się autorzy o zbliżonych imionach, nazwiskach i tytułach naukowych,\n    skorzystaj z tego pola aby ułatwić ich rozróżnienie. Pseudonim pokaże się w polach wyszukiwania\n    oraz na podstronie autora, po nazwisku i tytule naukowym.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="www",
            field=models.URLField(
                blank=True, default="", max_length=1024, verbose_name="WWW"
            ),
        ),
    ]
