# Generated by Django 4.2.25 on 2025-11-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0397_remove_null_from_string_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=128, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="poprzednie_nazwiska",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Jeżeli ten\n        autor(-ka) posiada nazwisko panieńskie, pod którym ukazywały\n        się publikacje lub zmieniał nazwisko z innych powodów, wpisz tutaj\n        wszystkie poprzednie nazwiska, oddzielając je przecinkami.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="pseudonim",
            field=models.CharField(
                blank=True,
                default="",
                help_text="\n    Jeżeli w bazie danych znajdują się autorzy o zbliżonych imionach, nazwiskach i tytułach naukowych,\n    skorzystaj z tego pola aby ułatwić ich rozróżnienie. Pseudonim pokaże się w polach wyszukiwania\n    oraz na podstronie autora, po nazwisku i tytule naukowym.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="www",
            field=models.URLField(
                blank=True, default="", max_length=1024, verbose_name="WWW"
            ),
        ),
    ]
