# Generated by Django 4.2.25 on 2025-11-26 08:30

from pathlib import Path

from django.db import connection, migrations


def load_sql(apps, schema_editor):
    sql_file = Path(__file__).parent / "0399_fix_refresh_cache_upsert.sql"
    with open(sql_file) as f:
        sql = f.read()
    # Użyj connection.cursor() zamiast schema_editor.execute()
    # bo schema_editor próbuje interpretować %s jako placeholdery parametrów SQL
    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0398_alter_autor_string_fields_schema"),
    ]

    operations = [
        migrations.RunPython(load_sql, migrations.RunPython.noop),
    ]
