# Generated by Django 4.2.25 on 2025-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("bpp", "0399_fix_refresh_cache_upsert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jednostka",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=128, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="jednostka",
            name="www",
            field=models.URLField(
                blank=True, default="", max_length=1024, verbose_name="WWW"
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="informacje",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Informacje"
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="public_www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2048,
                verbose_name="Adres WWW (wolny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="strony",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola "Szczegóły" w chwili generowania eksportu PBN. Aby uniknąć\n        sytuacji, gdy wskutek błędnego wprowadzenia tekstu do pola\n        "Szczegóły" informacja ta nie będzie mogła być wyekstrahowana\n        z tego pola, kliknij przycisk "Uzupełnij", aby spowodować uzupełnienie\n        tego pola na podstawie pola "Szczegóły".\n        ',
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="szczegoly",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Np. str. 23-45",
                max_length=512,
                verbose_name="Szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="tom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola 'Informacje'. Kliknięcie przycisku \"Uzupełnij\" powoduje\n        również automatyczne wypełnienie tego pola, o ile do formularza\n        zostały wprowadzone odpowiednie informacje. ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="patent",
            name="uwagi",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="patent",
            name="www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="Adres WWW (płatny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="e_isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="E-ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="informacje",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Informacje"
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="numer_odbitki",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="pmc_id",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="PubMed Central ID"
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="public_www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2048,
                verbose_name="Adres WWW (wolny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="strony",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola "Szczegóły" w chwili generowania eksportu PBN. Aby uniknąć\n        sytuacji, gdy wskutek błędnego wprowadzenia tekstu do pola\n        "Szczegóły" informacja ta nie będzie mogła być wyekstrahowana\n        z tego pola, kliknij przycisk "Uzupełnij", aby spowodować uzupełnienie\n        tego pola na podstawie pola "Szczegóły".\n        ',
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="szczegoly",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Np. str. 23-45",
                max_length=512,
                verbose_name="Szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="tom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola 'Informacje'. Kliknięcie przycisku \"Uzupełnij\" powoduje\n        również automatyczne wypełnienie tego pola, o ile do formularza\n        zostały wprowadzone odpowiednie informacje. ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="tytul",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Tytuł"
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="uwagi",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="Adres WWW (płatny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="e_isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="E-ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="informacje",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Informacje"
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="numer_odbitki",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="pmc_id",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="PubMed Central ID"
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="public_www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2048,
                verbose_name="Adres WWW (wolny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="strony",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola "Szczegóły" w chwili generowania eksportu PBN. Aby uniknąć\n        sytuacji, gdy wskutek błędnego wprowadzenia tekstu do pola\n        "Szczegóły" informacja ta nie będzie mogła być wyekstrahowana\n        z tego pola, kliknij przycisk "Uzupełnij", aby spowodować uzupełnienie\n        tego pola na podstawie pola "Szczegóły".\n        ',
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="szczegoly",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Np. str. 23-45",
                max_length=512,
                verbose_name="Szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="tom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola 'Informacje'. Kliknięcie przycisku \"Uzupełnij\" powoduje\n        również automatyczne wypełnienie tego pola, o ile do formularza\n        zostały wprowadzone odpowiednie informacje. ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="tytul",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Tytuł"
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="uwagi",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="Adres WWW (płatny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="nazwa_dopelniacz_field",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Nazwa w dopełniaczu",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="e_issn",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="e-ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="informacje",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Informacje"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="issn",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="nr_zeszytu",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola 'Informacje'. Kliknięcie przycisku \"Uzupełnij\" powoduje\n        również automatyczne wypełnienie tego pola, o ile do formularza\n        zostały wprowadzone odpowiednie informacje. ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="numer_odbitki",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="pmc_id",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="PubMed Central ID"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="public_www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2048,
                verbose_name="Adres WWW (wolny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="strony",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola "Szczegóły" w chwili generowania eksportu PBN. Aby uniknąć\n        sytuacji, gdy wskutek błędnego wprowadzenia tekstu do pola\n        "Szczegóły" informacja ta nie będzie mogła być wyekstrahowana\n        z tego pola, kliknij przycisk "Uzupełnij", aby spowodować uzupełnienie\n        tego pola na podstawie pola "Szczegóły".\n        ',
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="szczegoly",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Np. str. 23-45",
                max_length=512,
                verbose_name="Szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="tom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola 'Informacje'. Kliknięcie przycisku \"Uzupełnij\" powoduje\n        również automatyczne wypełnienie tego pola, o ile do formularza\n        zostały wprowadzone odpowiednie informacje. ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="tytul",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Tytuł"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="uwagi",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle",
            name="www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="Adres WWW (płatny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_streszczenie",
            name="streszczenie",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="e_isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="E-ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="e_issn",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="e-ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="informacje",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Informacje"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="isbn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="issn",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="numer_odbitki",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="numer_w_serii",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="pmc_id",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="PubMed Central ID"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="public_www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2048,
                verbose_name="Adres WWW (wolny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="strony",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola "Szczegóły" w chwili generowania eksportu PBN. Aby uniknąć\n        sytuacji, gdy wskutek błędnego wprowadzenia tekstu do pola\n        "Szczegóły" informacja ta nie będzie mogła być wyekstrahowana\n        z tego pola, kliknij przycisk "Uzupełnij", aby spowodować uzupełnienie\n        tego pola na podstawie pola "Szczegóły".\n        ',
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="szczegoly",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Np. str. 23-45",
                max_length=512,
                verbose_name="Szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="tom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeżeli uzupełnione, to pole będzie eksportowane do\n        danych PBN. Jeżeli puste, informacja ta będzie ekstrahowana z\n        pola 'Informacje'. Kliknięcie przycisku \"Uzupełnij\" powoduje\n        również automatyczne wypełnienie tego pola, o ile do formularza\n        zostały wprowadzone odpowiednie informacje. ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="tytul",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Tytuł"
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="uwagi",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="www",
            field=models.URLField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="Adres WWW (płatny dostęp)",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_streszczenie",
            name="streszczenie",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="wydzial",
            name="poprzednie_nazwy",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="zrodlo",
            name="e_issn",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="e-ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="zrodlo",
            name="issn",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="ISSN"
            ),
        ),
    ]
