# Generated by Django 4.2 on 2024-12-15

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0400_add_status_optymalizacji_bulk"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0401_autorzy_przypieta")
        ),
        # DROP CASCADE removes dependent views, so we need to reload them
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0207_uczelnia_analiza_view")
        ),
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql("0308_ewaluacja_upowaznienia_view")
        ),
    ]
