# Generated by Django 4.2 on 2025-12-17

from django.core.management import call_command
from django.db import migrations, models

from bpp.migration_util import load_custom_sql


def drop_triggers(apps, schema_editor):
    """Drop denorm triggers and cache triggers before bulk operations."""
    call_command("denorm_drop")
    load_custom_sql("0400_drop_cache_triggers")


def restore_triggers(apps, schema_editor):
    """Restore cache and denorm triggers after bulk operations."""
    # Recreate bpp_rekord_mat (includes views)
    load_custom_sql("0403_autorzy_ostatnio_zmieniony")

    # Recreate bpp_autorzy_mat (must be after bpp_rekord_mat due to FK)
    load_custom_sql("0402_autorzy_data_oswiadczenia")

    # Recreate dependent views lost by DROP CASCADE
    load_custom_sql("0207_uczelnia_analiza_view")
    load_custom_sql("0308_ewaluacja_upowaznienia_view")

    # Recreate rozbieznosci_dyscyplin view (from different app)
    load_custom_sql(
        "0017_add_punkty_kbn_and_charakter_formalny",
        app_name="rozbieznosci_dyscyplin",
    )

    # Recreate cache triggers
    load_custom_sql("0400_restore_cache_triggers")

    # Reinstall denorm triggers
    call_command("denorm_init")


def populate_ostatnio_zmieniony(apps, schema_editor):
    """Populate ostatnio_zmieniony from parent rekord."""
    Wydawnictwo_Ciagle_Autor = apps.get_model("bpp", "Wydawnictwo_Ciagle_Autor")
    for autor in Wydawnictwo_Ciagle_Autor.objects.select_related("rekord").iterator():
        autor.ostatnio_zmieniony = autor.rekord.ostatnio_zmieniony
        autor.save(update_fields=["ostatnio_zmieniony"])

    Wydawnictwo_Zwarte_Autor = apps.get_model("bpp", "Wydawnictwo_Zwarte_Autor")
    for autor in Wydawnictwo_Zwarte_Autor.objects.select_related("rekord").iterator():
        autor.ostatnio_zmieniony = autor.rekord.ostatnio_zmieniony
        autor.save(update_fields=["ostatnio_zmieniony"])

    Patent_Autor = apps.get_model("bpp", "Patent_Autor")
    for autor in Patent_Autor.objects.select_related("rekord").iterator():
        autor.ostatnio_zmieniony = autor.rekord.ostatnio_zmieniony
        autor.save(update_fields=["ostatnio_zmieniony"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("bpp", "0402_autorzy_data_oswiadczenia"),
    ]

    operations = [
        # 1. Drop all triggers first
        migrations.RunPython(drop_triggers, migrations.RunPython.noop),
        # Step 1: Add field as nullable
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="patent_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        # Step 2: Populate from rekord.ostatnio_zmieniony
        migrations.RunPython(populate_ostatnio_zmieniony, migrations.RunPython.noop),
        # Step 3: Make NOT NULL
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patent_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        # Restore triggers at the end
        migrations.RunPython(restore_triggers, migrations.RunPython.noop),
    ]
