# Generated by Django 4.2 on 2025-12-17

from django.db import migrations, models


def populate_ostatnio_zmieniony(apps, schema_editor):
    """Populate ostatnio_zmieniony from parent rekord."""
    Wydawnictwo_Ciagle_Autor = apps.get_model("bpp", "Wydawnictwo_Ciagle_Autor")
    for autor in Wydawnictwo_Ciagle_Autor.objects.select_related("rekord").iterator():
        autor.ostatnio_zmieniony = autor.rekord.ostatnio_zmieniony
        autor.save(update_fields=["ostatnio_zmieniony"])

    Wydawnictwo_Zwarte_Autor = apps.get_model("bpp", "Wydawnictwo_Zwarte_Autor")
    for autor in Wydawnictwo_Zwarte_Autor.objects.select_related("rekord").iterator():
        autor.ostatnio_zmieniony = autor.rekord.ostatnio_zmieniony
        autor.save(update_fields=["ostatnio_zmieniony"])

    Patent_Autor = apps.get_model("bpp", "Patent_Autor")
    for autor in Patent_Autor.objects.select_related("rekord").iterator():
        autor.ostatnio_zmieniony = autor.rekord.ostatnio_zmieniony
        autor.save(update_fields=["ostatnio_zmieniony"])


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0402_autorzy_data_oswiadczenia"),
    ]

    operations = [
        # Step 1: Add field as nullable
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="patent_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        # Step 2: Populate from rekord.ostatnio_zmieniony
        migrations.RunPython(populate_ostatnio_zmieniony, migrations.RunPython.noop),
        # Step 3: Make NOT NULL
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patent_autor",
            name="ostatnio_zmieniony",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
