# Generated by Django 4.2.25 on 2025-12-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("bpp", "0403_autorzy_ostatnio_zmieniony"),
    ]

    operations = [
        migrations.CreateModel(
            name="OplatyPublikacjiLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.CharField(max_length=100)),
                ("prev_opl_pub_cost_free", models.BooleanField(blank=True, null=True)),
                (
                    "prev_opl_pub_research_potential",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "prev_opl_pub_research_or_development_projects",
                    models.BooleanField(blank=True, null=True),
                ),
                ("prev_opl_pub_other", models.BooleanField(blank=True, null=True)),
                (
                    "prev_opl_pub_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("new_opl_pub_cost_free", models.BooleanField(blank=True, null=True)),
                (
                    "new_opl_pub_research_potential",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "new_opl_pub_research_or_development_projects",
                    models.BooleanField(blank=True, null=True),
                ),
                ("new_opl_pub_other", models.BooleanField(blank=True, null=True)),
                (
                    "new_opl_pub_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("source_file", models.CharField(blank=True, max_length=500)),
                ("source_row", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log zmian opłat za publikację",
                "verbose_name_plural": "Logi zmian opłat za publikacje",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="bpp_oplatyp_content_45c257_idx",
                    ),
                    models.Index(
                        fields=["changed_at"], name="bpp_oplatyp_changed_cf03ef_idx"
                    ),
                ],
            },
        ),
    ]
