# Generated by Django 4.2.25 on 2025-12-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("bpp", "0404_add_oplaty_publikacji_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="oplatypublikacjilog",
            name="rok",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Rok"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="changed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data zmiany"),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="changed_by",
            field=models.CharField(max_length=100, verbose_name="Zmienione przez"),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="Typ rekordu",
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="new_opl_pub_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Nowa kwota",
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="new_opl_pub_cost_free",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Nowa bezkosztowa"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="new_opl_pub_other",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Nowe inne źródła"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="new_opl_pub_research_or_development_projects",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Nowe projekty badawcze"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="new_opl_pub_research_potential",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Nowy potencjał badawczy"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="object_id",
            field=models.PositiveIntegerField(verbose_name="ID obiektu"),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="prev_opl_pub_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Poprz. kwota",
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="prev_opl_pub_cost_free",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Poprz. bezkosztowa"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="prev_opl_pub_other",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Poprz. inne źródła"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="prev_opl_pub_research_or_development_projects",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Poprz. projekty badawcze"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="prev_opl_pub_research_potential",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Poprz. potencjał badawczy"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="source_file",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Plik źródłowy"
            ),
        ),
        migrations.AlterField(
            model_name="oplatypublikacjilog",
            name="source_row",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Wiersz w pliku"
            ),
        ),
    ]
