# Generated by Django 4.2.25 on 2026-01-12 17:12

from django.db import migrations, models


def convert_nulls_to_empty_strings(apps, schema_editor):
    """Convert NULL values to empty strings before making fields NOT NULL.

    Disables triggers to avoid updating 'ostatnio_zmieniony' timestamps.
    """
    # Tables and fields that need NULL -> '' conversion
    updates = [
        (
            "bpp_praca_doktorska",
            ["miejsce_i_rok", "oznaczenie_wydania", "redakcja", "wydawca_opis"],
        ),
        (
            "bpp_praca_habilitacyjna",
            ["miejsce_i_rok", "oznaczenie_wydania", "redakcja", "wydawca_opis"],
        ),
        ("bpp_wydawnictwo_ciagle_zewnetrzna_baza_danych", ["info"]),
        (
            "bpp_wydawnictwo_zwarte",
            ["miejsce_i_rok", "oznaczenie_wydania", "redakcja", "wydawca_opis"],
        ),
        ("bpp_wydawnictwo_zwarte_zewnetrzna_baza_danych", ["info"]),
    ]

    for table, fields in updates:
        # Disable triggers on this table
        schema_editor.execute(f'ALTER TABLE "{table}" DISABLE TRIGGER ALL')

        for field in fields:
            schema_editor.execute(
                f'UPDATE "{table}" SET "{field}" = %s WHERE "{field}" IS NULL',
                [""],
            )

        # Re-enable triggers on this table
        schema_editor.execute(f'ALTER TABLE "{table}" ENABLE TRIGGER ALL')


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0406_add_pbn_evaluation_fields"),
    ]

    operations = [
        # First, convert all NULL values to empty strings
        migrations.RunPython(
            convert_nulls_to_empty_strings,
            reverse_code=migrations.RunPython.noop,
        ),
        # Then alter the fields to NOT NULL with default=""
        migrations.AlterField(
            model_name="praca_doktorska",
            name="miejsce_i_rok",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Przykładowo:\n        Warszawa 2012. Wpisz proszę "
                "najpierw miejsce potem rok; oddziel\n        spacją.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="oznaczenie_wydania",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="redakcja",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="praca_doktorska",
            name="wydawca_opis",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Wydawca - szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="miejsce_i_rok",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Przykładowo:\n        Warszawa 2012. Wpisz proszę "
                "najpierw miejsce potem rok; oddziel\n        spacją.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="oznaczenie_wydania",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="redakcja",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="wydawca_opis",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Wydawca - szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_zewnetrzna_baza_danych",
            name="info",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Informacje dodatkowe",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="miejsce_i_rok",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Przykładowo:\n        Warszawa 2012. Wpisz proszę "
                "najpierw miejsce potem rok; oddziel\n        spacją.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="oznaczenie_wydania",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="redakcja",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte",
            name="wydawca_opis",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Wydawca - szczegóły",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_zewnetrzna_baza_danych",
            name="info",
            field=models.CharField(
                blank=True,
                default="",
                max_length=512,
                verbose_name="Informacje dodatkowe",
            ),
        ),
    ]
