# Generated by Django 4.2.25 on 2026-02-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0407_remove_null_from_string_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossref_mapper",
            name="jest_wydawnictwem_zwartym",
            field=models.BooleanField(
                default=False,
                help_text="Zaznacz, jeśli prace tego typu powinny być dodawane jako wydawnictwa zwarte (książki, rozdziały). W przeciwnym razie będą traktowane jako wydawnictwa ciągłe (artykuły).",
                verbose_name="Jest wydawnictwem zwartym",
            ),
        ),
    ]
