# Generated by Django 4.2.25 on 2026-02-03 20:52

from django.db import migrations


def set_default_jest_wydawnictwem_zwartym(apps, schema_editor):
    """
    Ustaw domyślne wartości dla pola jest_wydawnictwem_zwartym
    na podstawie typu CrossRef.

    Typy książkowe (jest_wydawnictwem_zwartym=True):
    - BOOK (3)
    - BOOK_CHAPTER (4)
    - EDITED_BOOK (5)
    - MONOGRAPH (7)
    - REFERENCE_BOOK (8)
    - BOOK_SERIES (9)
    - BOOK_SET (10)
    - BOOK_SECTION (11)
    - BOOK_PART (12)
    - DISSERTATION (13)

    Typy ciągłe (jest_wydawnictwem_zwartym=False):
    - JOURNAL_ARTICLE (1)
    - PROCEEDINGS_ARTICLE (2)
    - PROCEEDINGS (6)
    - POSTED_CONTENT (14)
    - PEER_REVIEW (15)
    - OTHER (16)
    """
    Crossref_Mapper = apps.get_model("bpp", "Crossref_Mapper")

    # Typy książkowe - ustawiamy jest_wydawnictwem_zwartym=True
    book_types = [3, 4, 5, 7, 8, 9, 10, 11, 12, 13]

    Crossref_Mapper.objects.filter(charakter_crossref__in=book_types).update(
        jest_wydawnictwem_zwartym=True
    )


def reverse_set_default(apps, schema_editor):
    """
    Cofnij migrację - ustaw wszystkie na False.
    """
    Crossref_Mapper = apps.get_model("bpp", "Crossref_Mapper")
    Crossref_Mapper.objects.all().update(jest_wydawnictwem_zwartym=False)


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0408_add_jest_wydawnictwem_zwartym_to_crossref_mapper"),
    ]

    operations = [
        migrations.RunPython(
            set_default_jest_wydawnictwem_zwartym,
            reverse_set_default,
        ),
    ]
