# Generated by Django 4.2.25 on 2026-04-08 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("bpp", "0410_set_polish_skrot_crossref"),
    ]

    operations = [
        migrations.AddField(
            model_name="bppuser",
            name="accessible_sites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Uczelnie (strony), do których użytkownik ma dostęp. Superużytkownicy mają dostęp do wszystkich.",
                related_name="bpp_users",
                to="sites.site",
                verbose_name="Dostępne strony (uczelnie)",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="site",
            field=models.OneToOneField(
                blank=True,
                help_text="Powiązanie z obiektem Site (domena internetowa tej uczelni).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uczelnia",
                to="sites.site",
                verbose_name="Strona (domena)",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="theme_name",
            field=models.CharField(
                choices=[
                    ("app-green", "Zielony"),
                    ("app-blue", "Niebieski"),
                    ("app-orange", "Pomarańczowy"),
                ],
                default="app-green",
                max_length=50,
                verbose_name="Motyw kolorystyczny",
            ),
        ),
        migrations.AlterField(
            model_name="jezyk",
            name="skrot_crossref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "en - angielski"),
                    ("es", "es - hiszpański"),
                    ("pl", "pl - polski"),
                ],
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Skrót nazwy języka wg API CrossRef",
            ),
        ),
    ]
