# Generated by Django 4.2.30 on 2026-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0410_set_polish_skrot_crossref"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="orcid_client_id",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="ORCID Client ID"
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="orcid_client_secret",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="ORCID Client Secret",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="orcid_sandbox",
            field=models.BooleanField(
                default=True,
                help_text="Sandbox do testów (sandbox.orcid.org). Odznacz dla produkcji (orcid.org).",
                verbose_name="Używaj ORCID Sandbox",
            ),
        ),
        migrations.AlterField(
            model_name="jezyk",
            name="skrot_crossref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "en - angielski"),
                    ("es", "es - hiszpański"),
                    ("pl", "pl - polski"),
                ],
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Skrót nazwy języka wg API CrossRef",
            ),
        ),
    ]
