# Generated by Django 4.2.25 on 2026-04-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0410_set_polish_skrot_crossref"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="wymagaj_oplatach_artykul",
            field=models.BooleanField(
                default=True,
                help_text="Gdy zaznaczone, formularz zgłaszania publikacji będzie pytać o opłaty za artykuły naukowe.",
                verbose_name="Wymagaj informacji o opłatach: artykuł",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wymagaj_oplatach_inne",
            field=models.BooleanField(
                default=False,
                help_text="Gdy zaznaczone, formularz zgłaszania publikacji będzie pytać o opłaty za pozostałe publikacje.",
                verbose_name="Wymagaj informacji o opłatach: inne",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wymagaj_oplatach_monografia",
            field=models.BooleanField(
                default=True,
                help_text="Gdy zaznaczone, formularz zgłaszania publikacji będzie pytać o opłaty za monografie.",
                verbose_name="Wymagaj informacji o opłatach: monografia",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wymagaj_oplatach_rozdzial",
            field=models.BooleanField(
                default=False,
                help_text="Gdy zaznaczone, formularz zgłaszania publikacji będzie pytać o opłaty za rozdziały.",
                verbose_name="Wymagaj informacji o opłatach: rozdział",
            ),
        ),
        migrations.AlterField(
            model_name="jezyk",
            name="skrot_crossref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "en - angielski"),
                    ("es", "es - hiszpański"),
                    ("pl", "pl - polski"),
                ],
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Skrót nazwy języka wg API CrossRef",
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="wymagaj_informacji_o_oplatach",
            field=models.BooleanField(
                default=True,
                help_text="LEGACY: używaj pól wymagaj_oplatach_* poniżej. To pole zachowane dla kompatybilności.",
                verbose_name="Wymagaj informacji o opłatach (legacy)",
            ),
        ),
    ]
