# Generated by Django 4.2.25 on 2026-03-25 05:13

from django.db import migrations, models
import django.db.models.deletion


def convert_nulls_to_empty_strings(apps, schema_editor):
    BppUser = apps.get_model("bpp", "BppUser")
    BppUser.objects.filter(multiseek_format__isnull=True).update(
        multiseek_format=""
    )
    BppUser.objects.filter(multiseek_order_1__isnull=True).update(
        multiseek_order_1=""
    )
    BppUser.objects.filter(pbn_token__isnull=True).update(
        pbn_token=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0410_set_polish_skrot_crossref"),
    ]

    operations = [
        migrations.AddField(
            model_name="bppuser",
            name="autor",
            field=models.OneToOneField(
                blank=True,
                help_text="Autor powiązany z tym kontem użytkownika",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="bpp.autor",
                verbose_name="Powiązany autor",
            ),
        ),
        migrations.AlterField(
            model_name="jezyk",
            name="skrot_crossref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "en - angielski"),
                    ("es", "es - hiszpański"),
                    ("pl", "pl - polski"),
                ],
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Skrót nazwy języka wg API CrossRef",
            ),
        ),
        migrations.RunPython(
            convert_nulls_to_empty_strings,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="bppuser",
            name="multiseek_format",
            field=models.CharField(
                verbose_name=(
                    "Ostatnio wybrany format wyświetlania"
                    " w Multiseeku"
                ),
                max_length=200,
                default="",
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="bppuser",
            name="multiseek_order_1",
            field=models.CharField(
                verbose_name=(
                    "Ostatnio wybrane pole sortowania"
                    " w Multiseeku"
                ),
                max_length=200,
                default="",
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="bppuser",
            name="pbn_token",
            field=models.CharField(
                max_length=128,
                default="",
                blank=True,
            ),
        ),
    ]
