# Generated by Django 4.2.30 on 2026-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0411_uczelnia_orcid_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="orcid_tylko_dla_pracownikow",
            field=models.BooleanField(
                default=False,
                help_text="Gdy zaznaczone, logowanie przez ORCID będzie dostępne wyłącznie dla użytkowników z uprawnieniem 'w zespole' (is_staff) lub superużytkowników.",
                verbose_name="ORCID tylko dla pracowników",
            ),
        ),
    ]
