# Generated by Django 4.2.25 on 2026-04-08 15:14

from django.conf import settings
from django.db import migrations


def link_uczelnia_to_site(apps, schema_editor):
    """Link the first Uczelnia to Site(pk=1) and grant staff users access."""
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    Site = apps.get_model("sites", "Site")
    BppUser = apps.get_model("bpp", "BppUser")

    try:
        site = Site.objects.get(pk=1)
    except Site.DoesNotExist:
        return

    uczelnia = Uczelnia.objects.first()
    if uczelnia is None:
        return

    # Link existing uczelnia to site(pk=1)
    uczelnia.site = site
    # Copy theme from settings if available
    theme = getattr(settings, "THEME_NAME", "app-green")
    uczelnia.theme_name = theme
    uczelnia.save(update_fields=["site", "theme_name"])

    # Grant all staff users access to this site
    staff_users = BppUser.objects.filter(is_staff=True)
    for user in staff_users:
        user.accessible_sites.add(site)


def reverse_link(apps, schema_editor):
    """Reverse: unlink uczelnia from site and clear user access."""
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    BppUser = apps.get_model("bpp", "BppUser")

    Uczelnia.objects.all().update(site=None)
    for user in BppUser.objects.all():
        user.accessible_sites.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0411_uczelnia_site_theme_user_sites"),
    ]

    operations = [
        migrations.RunPython(link_uczelnia_to_site, reverse_link),
    ]
