# Generated by Django 4.2.30 on 2026-04-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0411_nowy_formularz_zgloszenia"),
        ("bpp", "0412_uczelnia_orcid_staff_only"),
    ]

    operations = []
