# Generated by Django 4.2.25 on 2026-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0412_link_uczelnia_to_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="google_analytics_property_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Np. UA-XXXXXXXX-X lub G-XXXXXXXXXX",
                max_length=100,
                verbose_name="Google Analytics Property ID",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="google_verification_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Kod weryfikacyjny Google Search Console",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="pokazuj_oswiadczenie_ken",
            field=models.BooleanField(
                default=False, verbose_name="Pokazuj opcję oświadczenia KEN"
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="skrot_wydzialu_w_nazwie_jednostki",
            field=models.BooleanField(
                default=True,
                verbose_name="Wyświetlaj skrót wydziału w nazwie jednostki",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wydruk_margines_dol",
            field=models.CharField(
                default="2cm", max_length=10, verbose_name="Margines dolny wydruku"
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wydruk_margines_gora",
            field=models.CharField(
                default="2cm", max_length=10, verbose_name="Margines górny wydruku"
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wydruk_margines_lewo",
            field=models.CharField(
                default="2cm", max_length=10, verbose_name="Margines lewy wydruku"
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="wydruk_margines_prawo",
            field=models.CharField(
                default="2cm", max_length=10, verbose_name="Margines prawy wydruku"
            ),
        ),
    ]
