# Generated by Django 4.2.25 on 2026-04-08 18:42

from django.db import migrations


def copy_constance_to_uczelnia(apps, schema_editor):
    """Copy Constance settings to Uczelnia model fields."""
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    uczelnia = Uczelnia.objects.first()
    if uczelnia is None:
        return

    try:
        from constance import config

        uczelnia.google_analytics_property_id = (
            config.GOOGLE_ANALYTICS_PROPERTY_ID or ""
        )
        uczelnia.google_verification_code = (
            config.GOOGLE_VERIFICATION_CODE or ""
        )
        uczelnia.pokazuj_oswiadczenie_ken = bool(
            config.POKAZUJ_OSWIADCZENIE_KEN
        )
        uczelnia.skrot_wydzialu_w_nazwie_jednostki = bool(
            config.SKROT_WYDZIALU_W_NAZWIE_JEDNOSTKI
        )
        uczelnia.wydruk_margines_gora = config.WYDRUK_MARGINES_GORA or "2cm"
        uczelnia.wydruk_margines_dol = config.WYDRUK_MARGINES_DOL or "2cm"
        uczelnia.wydruk_margines_lewo = config.WYDRUK_MARGINES_LEWO or "2cm"
        uczelnia.wydruk_margines_prawo = config.WYDRUK_MARGINES_PRAWO or "2cm"
        uczelnia.save(
            update_fields=[
                "google_analytics_property_id",
                "google_verification_code",
                "pokazuj_oswiadczenie_ken",
                "skrot_wydzialu_w_nazwie_jednostki",
                "wydruk_margines_gora",
                "wydruk_margines_dol",
                "wydruk_margines_lewo",
                "wydruk_margines_prawo",
            ]
        )
    except (ImportError, AttributeError):
        pass  # Constance not configured, defaults on model are fine


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0413_uczelnia_constance_fields"),
    ]

    operations = [
        migrations.RunPython(
            copy_constance_to_uczelnia, migrations.RunPython.noop
        ),
    ]
