# Generated by Django 5.2.13 on 2026-04-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0413_bppuser_autor_onetoone"),
        ("bpp", "0413_merge_20260416_2124"),
    ]

    operations = []
