# Generated by Django 5.2.13 on 2026-05-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0413_bppuser_autor_onetoone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cache_Punktacja_Autora_Sum_Group",
            fields=[
                (
                    "autor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="bpp.autor",
                    )
                ),
                ("pkdautsum", models.FloatField()),
                ("pkdautslotsum", models.FloatField()),
            ],
            options={
                "db_table": "bpp_temporary_cpasg",
                "ordering": ("autor", "dyscyplina"),
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="konferencja",
            name="nazwa",
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="autor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="bpp.autor"
            ),
        ),
        migrations.DeleteModel(name="Cache_Punktacja_Autora_Sum_Gruop"),
    ]
