# Generated by Django 4.2.25 on 2026-04-12 15:18

from django.db import migrations, models


def migrate_accessible_sites_to_uczelnie(apps, schema_editor):
    """Copy accessible_sites (Site M2M) to accessible_uczelnie (Uczelnia M2M).

    For each user, look up the Uczelnia linked to each of their
    accessible Sites and add it to the new M2M.
    """
    BppUser = apps.get_model("bpp", "BppUser")
    Uczelnia = apps.get_model("bpp", "Uczelnia")

    for user in BppUser.objects.prefetch_related("accessible_sites"):
        for site in user.accessible_sites.all():
            try:
                uczelnia = Uczelnia.objects.get(site=site)
                user.accessible_uczelnie.add(uczelnia)
            except Uczelnia.DoesNotExist:
                pass  # Site without linked Uczelnia — skip


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0414_copy_constance_to_uczelnia"),
    ]

    operations = [
        # 1. Add new field first (alongside old one)
        migrations.AddField(
            model_name="bppuser",
            name="accessible_uczelnie",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Uczelnie, do których użytkownik ma dostęp w panelu "
                    "administracyjnym. Puste = dostęp do wszystkich "
                    "(kompatybilność wsteczna)."
                ),
                related_name="staff_users",
                to="bpp.uczelnia",
                verbose_name="Dostępne uczelnie",
            ),
        ),
        # 2. Copy data from old M2M to new M2M
        migrations.RunPython(
            migrate_accessible_sites_to_uczelnie,
            migrations.RunPython.noop,
        ),
        # 3. Remove old field
        migrations.RemoveField(
            model_name="bppuser",
            name="accessible_sites",
        ),
    ]
