# Generated by Django 5.2.13 on 2026-05-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0414_code_review_2026_05_fixes"),
        ("bpp", "0414_merge_20260427_1123"),
    ]

    operations = []
