# Generated by Django 5.2.13 on 2026-04-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0413_bppuser_autor_onetoone"),
        ("bpp", "0415_rename_accessible_sites_to_uczelnie"),
    ]

    operations = []
