# Generated by Django 5.2.13 on 2026-05-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0414_uczelnia_pbn_kasuj_dyscypliny_selektywnie"),
        ("bpp", "0415_merge_20260504_0907"),
    ]

    operations = []
