# Generated by Django 5.2.14 on 2026-05-31 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0416_rename_dynamic_columns_to_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uczelnia",
            name="pokazuj_raport_autorow",
        ),
        migrations.RemoveField(
            model_name="uczelnia",
            name="pokazuj_raport_jednostek",
        ),
        migrations.RemoveField(
            model_name="uczelnia",
            name="pokazuj_raport_uczelni",
        ),
        migrations.RemoveField(
            model_name="uczelnia",
            name="pokazuj_raport_wydzialow",
        ),
    ]
