# Generated by Django 5.2.14 on 2026-06-01 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0416_merge_20260504_1024'),
        ('bpp', '0416_rename_dynamic_columns_to_admin'),
    ]

    operations = [
    ]
