# Generated by Django 5.2.14 on 2026-06-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0417_merge_20260601_0632'),
        ('bpp', '0417_remove_uczelnia_pokazuj_raport_autorow_and_more'),
    ]

    operations = [
    ]
