# Generated by Django 5.2.14 on 2026-06-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0418_autor_dyscyplina_trigger_on_conflict'),
        ('bpp', '0418_merge_20260601_0954'),
    ]

    operations = [
    ]
