# Generated by Django 5.2.14 on 2026-06-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0417_remove_uczelnia_pokazuj_raport_autorow_and_more'),
        ('bpp', '0418_merge_20260521_1015'),
    ]

    operations = [
    ]
