# Generated by Django 5.2.14 on 2026-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0419_merge_20260601_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='pokazuj_siec_powiazan',
            field=models.BooleanField(blank=True, default=None, help_text='Czy udostępniać sieć współautorstwa dla tego autora. Puste = użyj ustawienia uczelni; TAK/NIE nadpisuje je dla tego autora.', null=True, verbose_name='Pokazuj sieć powiązań'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='pokazuj_siec_powiazan',
            field=models.BooleanField(default=True, help_text="Czy na stronie autora udostępniać interaktywną sieć współautorstwa. Ustawienie domyślne dla całej uczelni — pojedynczy autor może je nadpisać własnym polem 'Pokazuj sieć powiązań'.", verbose_name='Pokazuj sieć powiązań autorów'),
        ),
    ]
