# Generated by Django 5.2.14 on 2026-06-03 19:07

import bpp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0420_autor_pokazuj_siec_powiazan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='dspace_aktywny',
            field=models.BooleanField(default=False, help_text='Gdy włączone, rekordy afiliowane do tej uczelni można wysyłać do jej instalacji DSpace.', verbose_name='Włącz eksport do DSpace'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='dspace_api_endpoint',
            field=models.URLField(blank=True, default='', help_text='np. https://repozytorium.uczelnia.pl/server/api', verbose_name='Adres API DSpace'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='dspace_api_password',
            field=bpp.fields.EncryptedTextField(blank=True, default='', verbose_name='Hasło API DSpace'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='dspace_api_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Użytkownik API DSpace'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='dspace_domyslny_jezyk_dc',
            field=models.CharField(blank=True, default='pl', max_length=8, verbose_name='Domyślny język dc.language.iso'),
        ),
    ]
