# Generated by Django 5.2.14 on 2026-06-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0420_merge_20260601_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uczelnia",
            name="theme_name",
            field=models.CharField(
                choices=[
                    ("app-green", "Zielony"),
                    ("app-blue", "Niebieski"),
                    ("app-orange", "Pomarańczowy"),
                    ("app-vizja", "Vizja (federacjavizja.pl — amber/granat)"),
                    ("app-mwsl", "MWSL (mwsl.eu — pomarańcz/granat)"),
                    ("app-uafm", "UAFM (uafm.edu.pl — czerwień/błękit)"),
                ],
                default="app-green",
                max_length=50,
                verbose_name="Motyw kolorystyczny",
            ),
        ),
    ]
