# Generated by Django 5.2.14 on 2026-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0421_alter_uczelnia_theme_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uczelnia",
            name="theme_name",
            field=models.CharField(
                default="app-green", max_length=50, verbose_name="Motyw kolorystyczny"
            ),
        ),
    ]
