# Generated by Django 5.2.14 on 2026-06-03 20:10

import bpp.models.repozytorium
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0421_uczelnia_dspace_aktywny_uczelnia_dspace_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_repozytorium',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element_repozytorium',
            name='plik',
            field=models.FileField(blank=True, max_length=765, null=True, upload_to=bpp.models.repozytorium.element_repozytorium_upload_to, verbose_name='Plik'),
        ),
        migrations.AddField(
            model_name='element_repozytorium',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element_repozytorium',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
