# Generated by Django 5.2.14 on 2026-06-02 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0419_merge_20260601_1319"),
        ("bpp", "0422_alter_uczelnia_theme_name"),
    ]

    operations = []
