# Generated by Django 5.2.14 on 2026-06-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0422_drop_unused_cache_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent_autor',
            name='rekord',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='autorzy_set', to='bpp.patent'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle_autor',
            name='rekord',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='autorzy_set', to='bpp.wydawnictwo_ciagle'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte_autor',
            name='rekord',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='autorzy_set', to='bpp.wydawnictwo_zwarte'),
        ),
    ]
