# Generated by Django 5.2.14 on 2026-06-04 13:57

import bpp.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0423_drop_redundant_fk_indexes_autor'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor_dyscyplina',
            name='autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.autor'),
        ),
        migrations.AlterField(
            model_name='autor_jednostka',
            name='autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.autor'),
        ),
        migrations.AlterField(
            model_name='cache_punktacja_autora',
            name='rekord_id',
            field=bpp.models.fields.TupleField(base_field=models.IntegerField(), size=2),
        ),
        migrations.AlterField(
            model_name='dyscyplina_zrodla',
            name='zrodlo',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.zrodlo'),
        ),
        migrations.AlterField(
            model_name='nagroda',
            name='content_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='opi_2012_afiliacja_do_wydzialu',
            name='autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.autor'),
        ),
        migrations.AlterField(
            model_name='oplatypublikacjilog',
            name='content_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Typ rekordu'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='wydawca',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='bpp.wydawca'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='wydawca',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='bpp.wydawca'),
        ),
        migrations.AlterField(
            model_name='publikacja_habilitacyjna',
            name='praca_habilitacyjna',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.praca_habilitacyjna'),
        ),
        migrations.AlterField(
            model_name='punktacja_zrodla',
            name='zrodlo',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.zrodlo'),
        ),
        migrations.AlterField(
            model_name='ukryj_status_korekty',
            name='uczelnia',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='wydawca',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='bpp.wydawca'),
        ),
    ]
