# Generated by Django 5.2.14 on 2026-06-02 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0423_merge_20260602_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache_punktacja_dyscypliny',
            name='uczelnia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia'),
        ),
        migrations.AddIndex(
            model_name='cache_punktacja_dyscypliny',
            index=models.Index(fields=['uczelnia', 'dyscyplina'], name='bpp_cache_p_uczelni_65b805_idx'),
        ),
    ]
