# Generated by Django 5.2.14 on 2026-06-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0425_drop_redundant_raw_indexes'),
    ]

    operations = [
        # Backfill NULL -> '' ZANIM AlterField ustawi NOT NULL na tych polach
        # (inaczej SET NOT NULL wywala się na istniejących wierszach z NULL).
        migrations.RunSQL(
            sql=[
                "UPDATE bpp_grant SET nazwa_projektu = '' "
                "WHERE nazwa_projektu IS NULL;",
                "UPDATE bpp_grant SET zrodlo_finansowania = '' "
                "WHERE zrodlo_finansowania IS NULL;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='grant',
            name='nazwa_projektu',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='grant',
            name='zrodlo_finansowania',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='grant_rekordu',
            name='grant',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='bpp.grant'),
        ),
        migrations.AlterField(
            model_name='poziom_wydawcy',
            name='rok',
            field=models.IntegerField(),
        ),
    ]
