# Generated by Django 5.2.14 on 2026-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0426_cache_punktacja_autora_view_uczelnia'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cache_punktacja_dyscypliny',
            index=models.Index(fields=['rekord_id', 'uczelnia', 'dyscyplina'], name='bpp_cache_p_rekord__479a7e_idx'),
        ),
    ]
