# Generated by Django 5.2.14 on 2026-06-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0422_element_repozytorium_deleted_at_and_more"),
        ("bpp", "0426_fix_grant_textfield_null_and_redundant_indexes"),
    ]

    operations = []
