# Generated by Django 5.2.14 on 2026-06-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0427_cpd_index_rekord_uczelnia_dyscyplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache_punktacja_dyscypliny',
            name='uczelnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia'),
        ),
    ]
