# Generated by Django 5.2.14 on 2026-06-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0427_merge_20260604_1838'),
        ('bpp', '0428_cpd_uczelnia_not_null'),
    ]

    operations = [
    ]
