# Generated by Django 5.2.14 on 2026-06-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0429_merge_20260604_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydawnictwo_Ciagle_Tytul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_jezyka_pbn', models.CharField(blank=True, default='', max_length=5, verbose_name='Kod języka wg PBN')),
                ('tytul', models.TextField(blank=True, default='', verbose_name='Tytuł')),
                ('jezyk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpp.jezyk')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatkowe_tytuly', to='bpp.wydawnictwo_ciagle')),
            ],
            options={
                'verbose_name': 'dodatkowy tytuł wydawnictwa ciągłego',
                'verbose_name_plural': 'dodatkowe tytuły wydawnictw ciągłych',
                'unique_together': {('rekord', 'kod_jezyka_pbn')},
            },
        ),
        migrations.CreateModel(
            name='Wydawnictwo_Zwarte_Tytul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_jezyka_pbn', models.CharField(blank=True, default='', max_length=5, verbose_name='Kod języka wg PBN')),
                ('tytul', models.TextField(blank=True, default='', verbose_name='Tytuł')),
                ('jezyk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpp.jezyk')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatkowe_tytuly', to='bpp.wydawnictwo_zwarte')),
            ],
            options={
                'verbose_name': 'dodatkowy tytuł wydawnictwa zwartego',
                'verbose_name_plural': 'dodatkowe tytuły wydawnictw zwartych',
                'unique_together': {('rekord', 'kod_jezyka_pbn')},
            },
        ),
    ]
