# Generated by Django 5.2.14 on 2026-06-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0429_cache_trigger_v3'),
        ('bpp', '0430_wydawnictwo_ciagle_tytul_wydawnictwo_zwarte_tytul'),
    ]

    operations = [
    ]
