# Generated by Django 5.2.14 on 2026-06-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0431_merge_20260612_1504'),
        ('bpp', '0431_search_index_gin'),
    ]

    operations = [
    ]
