# Generated by Django 5.2.15 on 2026-06-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0443_drop_pl_PL_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczelnia',
            name='wyszukiwanie_rekordy_na_strone_anonim',
            field=models.SmallIntegerField(default=2000, help_text='Ilość rekordów w wyszukiwaniu powyżej której znika opcja"Pokaż wszystkie" i "Drukuj" dla użytkownika anonimowego. Nie jest zalecane ustawianie powyżej 2000. ', verbose_name='Ilość rekordów na stronę - anonim'),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='wyszukiwanie_rekordy_na_strone_zalogowany',
            field=models.SmallIntegerField(default=10000, help_text='Ilość rekordów w wyszukiwaniu powyżej której znika opcja"Pokaż wszystkie" i "Drukuj" dla użytkownika zalogowanego. Nie jest zalecane ustawianie powyżej 10000. ', verbose_name='Ilość rekordów na stronę - zalogowany'),
        ),
    ]
