# Generated by Django 5.2.15 on 2026-06-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0443_drop_pl_PL_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='charakter_formalny',
            name='ukryty',
            field=models.BooleanField(default=False, help_text='Jeżeli zaznaczone, ten charakter formalny nie będzie\n        proponowany na listach wyboru przy wprowadzaniu nowych rekordów.\n        Istniejące rekordy korzystające z tej wartości pozostają bez zmian.', verbose_name='Ukryj na listach wyboru'),
        ),
        migrations.AddField(
            model_name='charakter_pbn',
            name='ukryty',
            field=models.BooleanField(default=False, help_text='Jeżeli zaznaczone, ten charakter PBN nie będzie\n        proponowany na listach wyboru przy konfiguracji charakterów\n        formalnych i typów MNiSW. Istniejące powiązania pozostają bez zmian.', verbose_name='Ukryj na listach wyboru'),
        ),
        migrations.AddField(
            model_name='typ_kbn',
            name='ukryty',
            field=models.BooleanField(default=False, help_text='Jeżeli zaznaczone, ten typ MNiSW/MEiN nie będzie\n        proponowany na listach wyboru przy wprowadzaniu nowych rekordów.\n        Istniejące rekordy korzystające z tej wartości pozostają bez zmian.', verbose_name='Ukryj na listach wyboru'),
        ),
        migrations.AlterField(
            model_name='charakter_formalny',
            name='charakter_pbn',
            field=models.ForeignKey(blank=True, default=None, help_text='Wartość wybrana w tym polu zostanie użyta jako zawartość tagu &lt;is>\n                                      w plikach eksportu do PBN', limit_choices_to={'ukryty': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.charakter_pbn', verbose_name='Charakter PBN'),
        ),
        migrations.AlterField(
            model_name='praca_doktorska',
            name='typ_kbn',
            field=models.ForeignKey(limit_choices_to={'ukryty': False}, on_delete=django.db.models.deletion.CASCADE, to='bpp.typ_kbn', verbose_name='typ MNiSW/MEiN'),
        ),
        migrations.AlterField(
            model_name='praca_habilitacyjna',
            name='typ_kbn',
            field=models.ForeignKey(limit_choices_to={'ukryty': False}, on_delete=django.db.models.deletion.CASCADE, to='bpp.typ_kbn', verbose_name='typ MNiSW/MEiN'),
        ),
        migrations.AlterField(
            model_name='typ_kbn',
            name='charakter_pbn',
            field=models.ForeignKey(blank=True, default=None, help_text='Wartość wybrana w tym polu zostanie użyta jako\n        fallback, tzn. jeżeli dla charakteru formalnego danego rekordu nie\n        określono odpowiedniego charakteru PBN, to zostanie użyta wartość\n        tego pola, o ile wybrana. ', limit_choices_to={'ukryty': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpp.charakter_pbn', verbose_name='Charakter PBN'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='charakter_formalny',
            field=models.ForeignKey(limit_choices_to={'ukryty': False}, on_delete=django.db.models.deletion.CASCADE, to='bpp.charakter_formalny', verbose_name='Charakter formalny'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_ciagle',
            name='typ_kbn',
            field=models.ForeignKey(limit_choices_to={'ukryty': False}, on_delete=django.db.models.deletion.CASCADE, to='bpp.typ_kbn', verbose_name='typ MNiSW/MEiN'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='charakter_formalny',
            field=models.ForeignKey(limit_choices_to={'ukryty': False}, on_delete=django.db.models.deletion.CASCADE, to='bpp.charakter_formalny', verbose_name='Charakter formalny'),
        ),
        migrations.AlterField(
            model_name='wydawnictwo_zwarte',
            name='typ_kbn',
            field=models.ForeignKey(limit_choices_to={'ukryty': False}, on_delete=django.db.models.deletion.CASCADE, to='bpp.typ_kbn', verbose_name='typ MNiSW/MEiN'),
        ),
    ]
