# Generated by Django 5.2.15 on 2026-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0443_drop_pl_PL_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='sugeruj_punktacje',
            field=models.BooleanField(default=False, help_text='Gdy zaznaczone, system będzie automatycznie podpowiadał punktację\n        (punkty PK/MNiSW, IF, SNIP itd.) dla wprowadzanego wydawnictwa na podstawie\n        punktacji źródła dla danego roku. Sugestia jest WYŁĄCZNIE podpowiedzią — operator\n        może ją w dowolnej chwili ręcznie zmienić. Dotyczy automatycznego importera publikacji\n        oraz uruchamia automatyczne wypełnianie pól punktacji w module redagowania wydawnictw\n        ciągłych (przycisk "Uzupełnij punktację" jest dostępny niezależnie od tego ustawienia).\n        Gdy odznaczone (domyślnie), system zachowuje dotychczasowe zachowanie i nie proponuje\n        punktacji automatycznie.', verbose_name='Sugeruj punktację'),
        ),
    ]
