# Generated by Django 5.2.15 on 2026-06-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0432_merge_0431_merge_20260612_1504_0431_search_index_gin'),
        ('bpp', '0443_drop_pl_PL_collation'),
    ]

    operations = [
    ]
