# Generated by Django 5.2.15 on 2026-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0444_autor_biogram_autor_biogram_format_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="uklad_profilu",
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="uklad_profilu_autora",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Kolejność, widoczność i limity sekcji PRAWEJ kolumny podstrony autora (globalnie dla całej uczelni). Lista pozycji {"klucz", "widoczna", "limit"}. Puste = układ domyślny.',
                null=True,
                verbose_name="Układ profilu autora",
            ),
        ),
    ]
