# Generated by Django 5.2.15 on 2026-06-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0444_alter_uczelnia_wyszukiwanie_rekordy_na_strone_anonim_and_more'),
        ('bpp', '0444_deferred_podstawowe_miejsce_pracy'),
    ]

    operations = [
    ]
