# Generated by Django 5.2.15 on 2026-06-19 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0444_alter_uczelnia_wyszukiwanie_rekordy_na_strone_anonim_and_more"),
        ("bpp", "0445_remove_autor_uklad_profilu_and_more"),
    ]

    operations = []
