# Generated by Django 5.2.15 on 2026-07-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0446_rzeczownik_tylko_mianownik"),
    ]

    operations = [
        migrations.CreateModel(
            name="RodzajJednostki",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=200, unique=True)),
                ("skrot", models.CharField(blank=True, default="", max_length=50)),
                ("kolejnosc", models.PositiveIntegerField(default=0)),
                ("wyklucz_z_rankingu_autorow", models.BooleanField(default=False)),
                ("pokazuj_jako_odrebna_sekcje", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "rodzaj jednostki",
                "verbose_name_plural": "rodzaje jednostek",
                "ordering": ["kolejnosc", "nazwa"],
            },
        ),
    ]
