# Generated by Django 5.2.15 on 2026-06-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0447_autoreksporttask"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="szerokosc_lewej_kolumny",
            field=models.SmallIntegerField(
                choices=[(4, "4 / 12"), (6, "6 / 12 (po połowie)"), (8, "8 / 12")],
                default=6,
                help_text="Szerokość lewej kolumny podstrony autora w jednostkach siatki Foundation (na 12). Prawa kolumna dopełnia do 12. Domyślnie 6/6 (po połowie).",
                verbose_name="Szerokość lewej kolumny profilu autora",
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="uklad_profilu_autora",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Kolejność, kolumna, widoczność i limity sekcji podstrony autora (globalnie dla całej uczelni). Lista pozycji {"klucz", "kolumna", "widoczna", "limit"}. Puste = układ domyślny.',
                null=True,
                verbose_name="Układ profilu autora",
            ),
        ),
    ]
