# Generated by Django 5.2.15 on 2026-07-04 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0448_seed_rodzajjednostki"),
    ]

    operations = [
        migrations.AddField(
            model_name="jednostka",
            name="rodzaj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jednostki",
                to="bpp.rodzajjednostki",
            ),
        ),
    ]
