# Generated by Django 5.2.15 on 2026-07-04 08:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0451_backfill_jednostka_rodzaj"),
    ]

    operations = [
        migrations.AddField(
            model_name="jednostka",
            name="legacy_wydzial_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="jednostka",
            name="poprzednie_nazwy",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AddField(
            model_name="jednostka",
            name="skrot_nazwy",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="jednostka",
            name="zezwalaj_na_ranking_autorow",
            field=models.BooleanField(
                default=True,
                verbose_name="Zezwalaj na generowanie rankingu autorów dla tej jednostki",
            ),
        ),
        migrations.AlterField(
            model_name="jednostka",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=512, populate_from="nazwa", unique=True
            ),
        ),
    ]
