# Generated by Django 5.2.15 on 2026-07-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0444_uczelnia_sugeruj_punktacje'),
        ('bpp', '0453_zrodlo_trigram_indexes'),
    ]

    operations = [
    ]
