# Generated by Django 5.2.15 on 2026-07-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0444_charakter_formalny_ukryty_charakter_pbn_ukryty_and_more'),
        ('bpp', '0453_zrodlo_trigram_indexes'),
    ]

    operations = [
    ]
