# Generated by Django 5.2.15 on 2026-07-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0448_uczelnia_szerokosc_lewej_kolumny_and_more'),
        ('bpp', '0453_zrodlo_trigram_indexes'),
    ]

    operations = [
    ]
