# Generated by Django 5.2.15 on 2026-07-07 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0445_merge_20260621_0640"),
        ("bpp", "0454_merge_20260706_0727"),
        ("bpp", "0464_rodzajjednostki_autor_moze_afiliowac"),
    ]

    operations = []
