# Generated by Django 5.2.15 on 2026-07-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0465_merge_20260707_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bppuser',
            name='zwijaj_dlugie_listy_autorow',
            field=models.IntegerField(choices=[(0, 'Jak ustawienie uczelni'), (1, 'Zawsze zwijaj'), (2, 'Nigdy nie zwijaj')], default=0, help_text='Czy na stronie rekordu zwijać listy autorów dłuższe niż 25 nazwisk (widoczni pierwsi autorzy oraz autorzy z Twojej uczelni; resztę rozwijasz przyciskiem). „Jak ustawienie uczelni” stosuje domyślne ustawienie Twojej uczelni.', verbose_name='Zwijanie długich list autorów'),
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='zwijaj_dlugie_listy_autorow',
            field=models.BooleanField(default=True, help_text='Gdy lista autorów publikacji przekracza 25 nazwisk, domyślnie zwijaj ją na stronie rekordu (widoczni pierwsi autorzy oraz autorzy z naszej uczelni; resztę użytkownik rozwija przyciskiem). Ustawienie domyślne dla całej uczelni — zalogowany użytkownik może je nadpisać we własnym profilu.', verbose_name='Zwijaj długie listy autorów na stronie rekordu'),
        ),
    ]
