# Generated by Django 5.2.15 on 2026-07-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0467_seed_crossref_mapper_rows"),
    ]

    operations = [
        migrations.CreateModel(
            name="StanowiskoDydaktyczne",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=512, unique=True)),
                ("skrot", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "stanowisko dydaktyczne",
                "verbose_name_plural": "stanowiska dydaktyczne",
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="StopienSluzbowy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=512, unique=True)),
                ("skrot", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "verbose_name": "stopień służbowy",
                "verbose_name_plural": "stopnie służbowe",
                "ordering": ["nazwa"],
            },
        ),
        migrations.AddField(
            model_name="autor_jednostka",
            name="stanowisko",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bpp.stanowiskodydaktyczne",
                verbose_name="stanowisko dydaktyczne",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="stopien_sluzbowy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bpp.stopiensluzbowy",
                verbose_name="stopień służbowy",
            ),
        ),
    ]
