# Generated by Django 5.2.15 on 2026-07-08 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0466_bppuser_zwijaj_dlugie_listy_autorow_and_more"),
        ("bpp", "0469_faza_c_czysc_contenttype_wydzial"),
    ]

    operations = []
