# Generated by Django 5.2.16 on 2026-07-22 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0470_merge_20260708_1616"),
        ("bpp", "0472_constraint_autor_jednostka_bez_daty"),
    ]

    operations = []
