# Generated by Django 5.2.16 on 2026-07-20 20:45

import bpp.models.autor
import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0473_guard_autor_jednostka_okresy_bez_nakladan'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='autor_jednostka',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('rozpoczal_prace__isnull', False)), expressions=[('autor', '='), ('jednostka', '='), (bpp.models.autor.DateRange('rozpoczal_prace', 'zakonczyl_prace'), '&&')], name='bpp_autor_jednostka_okresy_bez_nakladan'),
        ),
    ]
