# Generated by Django 5.2.16 on 2026-07-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0473_merge_20260722_1632"),
        ("bpp", "0473_szablon_nazwa_szablonu"),
    ]

    operations = []
