# Generated by Django 5.2.16 on 2026-07-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0474_constraint_autor_jednostka_okresy_bez_nakladan"),
        ("bpp", "0474_merge_20260724_1635"),
    ]

    operations = []
