# Generated by Django 5.2.16 on 2026-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0475_merge_20260724_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="jednostka",
            name="nie_eksportuj_przez_api",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Jeżeli zaznaczone, to ten rekord nie będzie dostępny przez JSON REST API",
                verbose_name="Nie eksportuj przez API",
            ),
        ),
    ]
