# Generated by Django 5.2.16 on 2026-08-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0476_jednostka_nie_eksportuj_przez_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='oai_identyfikator_repozytorium',
            field=models.CharField(blank=True, default='', help_text='Środkowy człon identyfikatorów wystawianych przez endpoint /oai/ (postać: oai:IDENTYFIKATOR:model/id). Puste = domena z pola „Strona (domena)”. Raz opublikowanego identyfikatora nie należy zmieniać — harvestery (OpenAIRE, Primo, BASE) używają go jako trwałej części klucza rekordu.', max_length=255, verbose_name='Identyfikator repozytorium OAI-PMH'),
        ),
    ]
