# Generated by Django 5.2.16 on 2026-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0477_uczelnia_oai_identyfikator_repozytorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='oai_pmh_aktywny',
            field=models.BooleanField(default=True, help_text='Gdy wyłączone, adres /oai/ tej uczelni odpowiada błędem 404. Nie wpływa na pozostałe uczelnie w tej instalacji.', verbose_name='Udostępniaj endpoint OAI-PMH'),
        ),
    ]
