# Generated by Django 5.2.16 on 2026-08-03 18:50

import re

from django.db import migrations, models

# Kod BCP 47 zapisany jako sam podstawowy język (ISO 639-1/639-2), np. "pl",
# "en", "spa". Skróty w bazie bywają opisowe ("ang.", "pol."), stąd filtr.
RE_KOD_JEZYKA = re.compile(r"^[a-z]{2,3}$")

# Skróty licencji Creative Commons innych niż CC0, np. "CC-BY", "CC-BY-ND".
RE_SKROT_CC = re.compile(r"^CC-([A-Z-]+)$")

# CC0 (przekazanie do domeny publicznej) ma INNY schemat URI niż pozostałe
# licencje CC: ``/publicdomain/zero/1.0/`` zamiast ``/licenses/<kod>/<wersja>``.
# Kanoniczny skrót w BPP to "CC-ZERO" (migracja 0195); "CC0"/"CC-0" dokładamy
# jako warianty spotykane w bazach wgranych spoza seeda. Ten test MUSI iść
# przed ``RE_SKROT_CC``, bo "CC-ZERO" pasuje też do wzorca ogólnego i dałby
# nieistniejący adres ``/licenses/zero/4.0/``.
SKROTY_CC0 = ("CC-ZERO", "CC0", "CC-0")

URI_CC0 = "https://creativecommons.org/publicdomain/zero/1.0/"


def noop(apps, schema_editor):
    """Migracje danych są nieodwracalne z sensem: puste pole przed migracją
    jest nieodróżnialne od pustego po niej, więc reverse to no-op."""


def wypelnij_kod_bcp47(apps, schema_editor):
    """``Jezyk.kod_bcp47`` z ``skrot_crossref``, a gdy pusty -- ze ``skrot``.

    ``skrot`` bierzemy tylko wtedy, gdy sam z siebie wygląda jak kod języka
    (2-3 małe litery). Skróty opisowe ("ang.", "hiszp.") pomijamy -- lepszy
    pusty ``xml:lang`` niż wyeksportowany śmieciowy.
    """
    Jezyk = apps.get_model("bpp", "Jezyk")

    for jezyk in Jezyk.objects.all().only("pk", "skrot", "skrot_crossref"):
        kod = (jezyk.skrot_crossref or "").strip()

        if not kod:
            skrot = (jezyk.skrot or "").strip().lower()
            if RE_KOD_JEZYKA.match(skrot):
                kod = skrot

        if kod:
            Jezyk.objects.filter(pk=jezyk.pk).update(kod_bcp47=kod)


def wypelnij_uri_licencji(apps, schema_editor):
    """``Licencja_OpenAccess.uri`` ze skrótu licencji Creative Commons.

    UWAGA: skrót nie niesie WERSJI licencji, a wersja jest częścią URI.
    Zakładana tu wersja ``4.0`` jest świadomym przybliżeniem i wygenerowane
    wartości WYMAGAJĄ RĘCZNEGO PRZEGLĄDU przez redakcję (część zbiorów
    używa 3.0 albo 2.5). Skróty niepasujące do żadnej reguły -- w tym
    "OTHER" -- zostają puste, żeby nie wyeksportować URI wziętego z sufitu.
    """
    Licencja_OpenAccess = apps.get_model("bpp", "Licencja_OpenAccess")

    for licencja in Licencja_OpenAccess.objects.all().only("pk", "skrot"):
        skrot = (licencja.skrot or "").strip().upper()

        if skrot in SKROTY_CC0:
            uri = URI_CC0
        else:
            match = RE_SKROT_CC.match(skrot)
            # Ścieżka w URI Creative Commons jest małymi literami, skróty w
            # bazie -- wielkimi, stąd .lower() na dopasowanej grupie.
            uri = (
                f"https://creativecommons.org/licenses/{match.group(1).lower()}/4.0/"
                if match
                else ""
            )

        if uri:
            Licencja_OpenAccess.objects.filter(pk=licencja.pk).update(uri=uri)


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0478_uczelnia_oai_pmh_aktywny"),
    ]

    operations = [
        migrations.AddField(
            model_name="charakter_formalny",
            name="coar_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pełny identyfikator typu zasobu ze słownika COAR Resource Types, np. http://purl.org/coar/resource_type/c_6501 dla artykułu naukowego. Używany w eksporcie CERIF/OpenAIRE; gdy pusty, prace o tym charakterze formalnym zostaną wyeksportowane bez typu zasobu.",
                max_length=200,
                verbose_name="Typ COAR",
            ),
        ),
        migrations.AddField(
            model_name="jednostka",
            name="ror_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identyfikator jednostki w Research Organization Registry (ROR), np. https://ror.org/0111ttp83 . Używany w eksporcie CERIF/OpenAIRE jako identyfikator zewnętrzny jednostki organizacyjnej; gdy pusty, nie zostanie wyeksportowany.",
                max_length=64,
                verbose_name="Identyfikator ROR",
            ),
        ),
        migrations.AddField(
            model_name="jezyk",
            name="kod_bcp47",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Kod języka w notacji BCP 47 (RFC 5646), np. „pl”, „en”, „en-GB”. Używany w eksporcie CERIF/OpenAIRE jako wartość atrybutu xml:lang; gdy pusty, elementy w tym języku zostaną wyeksportowane bez oznaczenia języka.",
                max_length=35,
                verbose_name="Kod języka wg BCP 47",
            ),
        ),
        migrations.AddField(
            model_name="licencja_openaccess",
            name="uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Kanoniczny adres URI licencji, np. https://creativecommons.org/licenses/by/4.0/ . Używany w eksporcie CERIF/OpenAIRE; gdy pusty, prace na tej licencji zostaną wyeksportowane bez odnośnika do jej treści.",
                max_length=512,
                verbose_name="Adres URI licencji",
            ),
        ),
        migrations.AddField(
            model_name="rodzaj_prawa_patentowego",
            name="coar_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pełny identyfikator typu zasobu ze słownika COAR Resource Types, np. http://purl.org/coar/resource_type/c_15cd dla patentu. Używany w eksporcie CERIF/OpenAIRE; gdy pusty, patenty o tym rodzaju prawa zostaną wyeksportowane bez typu zasobu.",
                max_length=200,
                verbose_name="Typ COAR",
            ),
        ),
        migrations.AddField(
            model_name="tryb_openaccess_wydawnictwo_ciagle",
            name="coar_access_right",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pełny identyfikator prawa dostępu ze słownika COAR Access Rights, np. http://purl.org/coar/access_right/c_abf2 dla „open access”. Używany w eksporcie CERIF/OpenAIRE; gdy pusty, prace o tym trybie zostaną wyeksportowane bez określonego prawa dostępu.",
                max_length=200,
                verbose_name="Prawo dostępu wg COAR",
            ),
        ),
        migrations.AddField(
            model_name="tryb_openaccess_wydawnictwo_zwarte",
            name="coar_access_right",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pełny identyfikator prawa dostępu ze słownika COAR Access Rights, np. http://purl.org/coar/access_right/c_abf2 dla „open access”. Używany w eksporcie CERIF/OpenAIRE; gdy pusty, prace o tym trybie zostaną wyeksportowane bez określonego prawa dostępu.",
                max_length=200,
                verbose_name="Prawo dostępu wg COAR",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="api_v1_wlaczone",
            field=models.BooleanField(
                default=True,
                help_text="Gdy odznaczone, publiczne REST API tej uczelni (/api/v1/) przestaje odpowiadać.",
                verbose_name="Włącz REST API (/api/v1/)",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="eksport_cerif_wlaczony",
            field=models.BooleanField(
                default=True,
                help_text="Gdy odznaczone, endpoint OAI-PMH z danymi w formacie CERIF-XML (OpenAIRE CRIS Guidelines) przestaje odpowiadać dla tej uczelni.",
                verbose_name="Włącz eksport CERIF/OpenAIRE",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="ror_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identyfikator uczelni w Research Organization Registry (ROR), np. https://ror.org/0111ttp83 . Używany w eksporcie CERIF/OpenAIRE jako identyfikator zewnętrzny instytucji; gdy pusty, nie zostanie wyeksportowany.",
                max_length=64,
                verbose_name="Identyfikator ROR",
            ),
        ),
        migrations.AddField(
            model_name="ukryj_status_korekty",
            name="cerif",
            field=models.BooleanField(
                default=True,
                help_text="Dotyczy ukrywania prac w eksporcie CERIF/OpenAIRE",
                verbose_name="Eksport CERIF",
            ),
        ),
        migrations.AlterField(
            model_name="ukryj_status_korekty",
            name="api",
            field=models.BooleanField(
                default=True,
                help_text="Dotyczy ukrywania prac w API JSON-REST oraz OAI-PMH dla Primo",
                verbose_name="API",
            ),
        ),
        migrations.RunPython(wypelnij_kod_bcp47, noop),
        migrations.RunPython(wypelnij_uri_licencji, noop),
    ]
