# Generated by Django 5.2.16 on 2026-08-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0480_cerif_mapowania_slownikow'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczelnia',
            name='eksport_cerif_osoby',
            field=models.BooleanField(default=True, help_text='Gdy odznaczone, zestaw „openaire_cris_persons” pozostaje pusty, a autorzy pojawiają się wyłącznie jako encje osadzone w opisie publikacji: samo imię i nazwisko, bez własnych rekordów, bez ORCID-ów, bez afiliacji i bez historii zatrudnienia. Zestaw musi istnieć nawet pusty — wymagają tego wytyczne OpenAIRE.', verbose_name='Eksportuj dane osób do CERIF/OpenAIRE'),
        ),
    ]
