# Generated by Django 5.2.16 on 2026-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0481_uczelnia_eksport_cerif_osoby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jednostka',
            name='ror_id',
            field=models.CharField(blank=True, default='', help_text='Identyfikator jednostki w Research Organization Registry (ROR), np. https://ror.org/016f61126 (identyfikator ma wbudowaną sumę kontrolną, więc literówka zostanie odrzucona). Używany w eksporcie CERIF/OpenAIRE jako identyfikator zewnętrzny jednostki organizacyjnej; gdy pusty, nie zostanie wyeksportowany.', max_length=64, verbose_name='Identyfikator ROR'),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='ror_id',
            field=models.CharField(blank=True, default='', help_text='Identyfikator uczelni w Research Organization Registry (ROR), np. https://ror.org/016f61126 (identyfikator ma wbudowaną sumę kontrolną, więc literówka zostanie odrzucona). Używany w eksporcie CERIF/OpenAIRE jako identyfikator zewnętrzny instytucji; gdy pusty, nie zostanie wyeksportowany.', max_length=64, verbose_name='Identyfikator ROR'),
        ),
    ]
