# Generated by Django 5.2.16 on 2026-08-04 20:22

import bpp.util.ror
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0483_cerif_znak_towarowy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jednostka',
            name='ror_id',
            field=models.CharField(blank=True, default='', help_text='Identyfikator w Research Organization Registry (ROR), np. https://ror.org/016f61126 — ma wbudowaną sumę kontrolną, więc literówka zostanie odrzucona. Używany w eksporcie CERIF/OpenAIRE jako identyfikator zewnętrzny jednostki organizacyjnej; gdy pusty, nie zostanie wyeksportowany.', max_length=64, validators=[bpp.util.ror.waliduj], verbose_name='Identyfikator ROR'),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='ror_id',
            field=models.CharField(blank=True, default='', help_text='Identyfikator w Research Organization Registry (ROR), np. https://ror.org/016f61126 — ma wbudowaną sumę kontrolną, więc literówka zostanie odrzucona. Używany w eksporcie CERIF/OpenAIRE jako identyfikator zewnętrzny instytucji; gdy pusty, nie zostanie wyeksportowany.', max_length=64, validators=[bpp.util.ror.waliduj], verbose_name='Identyfikator ROR'),
        ),
    ]
