# Generated by Django 5.2.16 on 2026-08-05 08:08

import django.contrib.postgres.fields
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models

import bpp.util.ror


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0484_cerif_walidacja_ror'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instytucja_Finansujaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostatnio_zmieniony', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('adnotacje', models.TextField(blank=True, db_index=True, default='', help_text='Pole do użytku wewnętrznego -\n        wpisane tu informacje nie są wyświetlane na stronach WWW dostępnych\n        dla użytkowników końcowych.')),
                ('nazwa', models.TextField(verbose_name='Nazwa')),
                ('nazwa_en', models.TextField(blank=True, default='', verbose_name='Nazwa (angielska)')),
                ('akronim', models.CharField(blank=True, default='', max_length=50, verbose_name='Akronim')),
                ('kraj', models.CharField(default='PL', help_text='Kod ISO 3166-1 alpha-2. Pole wewnętrzne — profil OpenAIRE nie ma elementu Country w encji OrgUnit.', max_length=2, verbose_name='Kraj')),
                ('ror_id', models.CharField(blank=True, default='', help_text='Identyfikator w Research Organization Registry (ROR), np. https://ror.org/016f61126 — ma wbudowaną sumę kontrolną, więc literówka zostanie odrzucona. Gdy pusty, nie zostanie wyeksportowany.', max_length=64, validators=[bpp.util.ror.waliduj], verbose_name='Identyfikator ROR')),
                ('fundref_id', models.CharField(blank=True, default='', help_text='Identyfikator z Crossref Funder Registry, np. 501100004281.', max_length=50, verbose_name='Crossref Funder ID')),
                ('strona_www', models.URLField(blank=True, default='', verbose_name='Strona WWW')),
            ],
            options={
                'verbose_name': 'instytucja finansująca',
                'verbose_name_plural': 'instytucje finansujące',
                'ordering': ['nazwa'],
            },
        ),
        migrations.AddField(
            model_name='uczelnia',
            name='eksport_cerif_kwoty',
            field=models.BooleanField(default=False, help_text='Czy w eksporcie CERIF-XML wystawiać kwoty finansowania projektów. Domyślnie wyłączone — kwoty zostają w bazie do użytku wewnętrznego.', verbose_name='Eksport CERIF: kwoty finansowania'),
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slowa_kluczowe_eng', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, help_text='Lista słów kluczowych -- język angielski', null=True, size=None, verbose_name='Słowa kluczowe -- język angielski')),
                ('ostatnio_zmieniony', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('adnotacje', models.TextField(blank=True, db_index=True, default='', help_text='Pole do użytku wewnętrznego -\n        wpisane tu informacje nie są wyświetlane na stronach WWW dostępnych\n        dla użytkowników końcowych.')),
                ('tytul', models.TextField(verbose_name='Tytuł')),
                ('tytul_en', models.TextField(blank=True, default='', verbose_name='Tytuł (angielski)')),
                ('akronim', models.CharField(blank=True, default='', max_length=50, verbose_name='Akronim')),
                ('data_rozpoczecia', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('data_zakonczenia', models.DateField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('status', models.CharField(choices=[('planowany', 'planowany'), ('w-trakcie', 'w trakcie'), ('zakonczony', 'zakończony'), ('przerwany', 'przerwany')], default='w-trakcie', max_length=20, verbose_name='Status')),
                ('abstrakt', models.TextField(blank=True, default='', verbose_name='Abstrakt')),
                ('abstrakt_en', models.TextField(blank=True, default='', verbose_name='Abstrakt (angielski)')),
                ('strona_www', models.URLField(blank=True, default='', verbose_name='Strona WWW')),
                ('dyscypliny', models.ManyToManyField(blank=True, to='bpp.dyscyplina_naukowa', verbose_name='Dyscypliny')),
                ('jednostka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpp.jednostka', verbose_name='Jednostka realizująca')),
                ('slowa_kluczowe', taggit.managers.TaggableManager(blank=True, help_text='Lista słów kluczowych -- język polski.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Słowa kluczowe -- język polski')),
            ],
            options={
                'verbose_name': 'projekt',
                'verbose_name_plural': 'projekty',
                'ordering': ['-data_rozpoczecia', 'tytul'],
            },
        ),
        migrations.CreateModel(
            name='Finansowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostatnio_zmieniony', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('adnotacje', models.TextField(blank=True, db_index=True, default='', help_text='Pole do użytku wewnętrznego -\n        wpisane tu informacje nie są wyświetlane na stronach WWW dostępnych\n        dla użytkowników końcowych.')),
                ('typ', models.CharField(choices=[('FundingProgramme', 'program finansowania'), ('Call', 'konkurs'), ('Tender', 'przetarg'), ('Gift', 'darowizna'), ('InternalFunding', 'finansowanie wewnętrzne'), ('Contract', 'umowa'), ('Award', 'nagroda'), ('Grant', 'grant')], default='Grant', max_length=30, verbose_name='Typ')),
                ('nazwa_programu', models.CharField(blank=True, default='', help_text='Nazwa programu lub konkursu, np. „OPUS 24”.', max_length=200, verbose_name='Nazwa programu')),
                ('numer_umowy', models.CharField(blank=True, default='', max_length=200, verbose_name='Numer umowy')),
                ('kwota', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Kwota')),
                ('waluta', models.CharField(blank=True, default='PLN', max_length=3, verbose_name='Waluta')),
                ('grant_doi', models.CharField(blank=True, default='', max_length=200, verbose_name='DOI grantu')),
                ('instytucja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpp.instytucja_finansujaca', verbose_name='Instytucja finansująca')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.projekt', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'finansowanie',
                'verbose_name_plural': 'finansowania',
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='projekt',
            field=models.ForeignKey(blank=True, help_text='Projekt badawczy, w ramach którego przyznano ten grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpp.projekt', verbose_name='Projekt'),
        ),
        migrations.CreateModel(
            name='Projekt_Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('kierownik', 'kierownik'), ('wykonawca', 'wykonawca'), ('wspolwykonawca', 'współwykonawca')], default='wykonawca', max_length=20, verbose_name='Rola')),
                ('od', models.DateField(blank=True, null=True, verbose_name='Od')),
                ('do', models.DateField(blank=True, null=True, verbose_name='Do')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpp.autor', verbose_name='Autor')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.projekt', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'osoba w projekcie',
                'verbose_name_plural': 'osoby w projekcie',
                'constraints': [models.UniqueConstraint(condition=models.Q(('rola', 'kierownik')), fields=('projekt',), name='projekt_jeden_kierownik')],
                'unique_together': {('projekt', 'autor', 'rola')},
            },
        ),
    ]
