# Generated by Django 5.2.16 on 2026-08-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0454_merge_20260706_0757'),
        ('bpp', '0486_seed_instytucje_finansujace'),
    ]

    operations = [
    ]
