# Generated by Django 5.2.16 on 2026-08-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0486_seed_instytucje_finansujace"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="api_v1_dane_bibliograficzne",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Słowniki, struktura uczelni, autorzy, rekordy publikacji, "
                    "źródła i wydawcy."
                ),
                verbose_name="Udostępniaj dane bibliograficzne",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="api_v1_kafelki",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Endpointy /api/v1/recent_author_publications/ i "
                    "/api/v1/recent_unit_publications/, z których korzysta widget "
                    "bpp-publikacje.js. UWAGA: odznaczenie zgasi listy publikacji "
                    "wklejone na stronach WWW jednostek i wydziałów."
                ),
                verbose_name="Udostępniaj kafelki do osadzania",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="api_v1_narzedzia_redaktorskie",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Zapytania DjangoQL (/api/v1/zapytanie/) i raport slotów "
                    "uczelni. Wymagają konta redaktora także wtedy, gdy to pole "
                    "jest zaznaczone — decyduje ono wyłącznie o tym, czy "
                    "endpointy w ogóle istnieją."
                ),
                verbose_name="Udostępniaj narzędzia redaktorskie",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="api_v1_tylko_zalogowani",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Gdy zaznaczone, niezalogowany klient dostaje 401 zamiast "
                    "danych. Nie dotyczy kafelków do osadzania — te z założenia "
                    "wiszą na publicznych stronach."
                ),
                verbose_name="REST API tylko dla zalogowanych",
            ),
        ),
        migrations.AddField(
            model_name="uczelnia",
            name="api_v1_wyszukiwanie",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Endpoint /api/v1/szukaj/ — pełnotekstowe wyszukiwanie po "
                    "wszystkich publikacjach. Kosztowny, objęty osobnym limitem "
                    "zapytań."
                ),
                verbose_name="Udostępniaj wyszukiwanie",
            ),
        ),
        migrations.AlterField(
            model_name="uczelnia",
            name="api_v1_wlaczone",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Gdy odznaczone, publiczne REST API tej uczelni (/api/v1/) "
                    "przestaje odpowiadać. NIE dotyczy kafelków do osadzania — te "
                    "mają własny przełącznik niżej i działają niezależnie, żeby "
                    "wyłączenie API nie psuło widgetów wklejonych na stronach WWW "
                    "jednostek."
                ),
                verbose_name="Włącz REST API (/api/v1/)",
            ),
        ),
    ]
