# Generated by Django 5.2.16 on 2026-08-06 12:48
#
# Indeksy na `deleted_at` są CZĘŚCIOWE (`WHERE deleted_at IS NOT NULL`).
# Pełny btree byłby tu martwym kosztem: `deleted_at IS NULL` pasuje do ~100%
# wierszy, więc planner pod ten predykat i tak wybierze seq scan, a indeks
# zostawałby wyłącznie narzutem (rozmiar rzędu tabeli + wpis przy każdym
# INSERT/UPDATE autorstwa). Selektywne jest zapytanie ODWROTNE —
# `deleted_objects` (`deleted_at IS NOT NULL`) — i to jemu służy ten
# mikroskopijny indeks. Uzasadnienie w `Meta.indexes` modeli.

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0487_api_v1_przelaczniki"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent_autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent_autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent_autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="wydawnictwo_ciagle_autor",
            index=models.Index(
                condition=Q(("deleted_at__isnull", False)),
                fields=["deleted_at"],
                name="wc_autor_deleted_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wydawnictwo_zwarte_autor",
            index=models.Index(
                condition=Q(("deleted_at__isnull", False)),
                fields=["deleted_at"],
                name="wz_autor_deleted_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patent_autor",
            index=models.Index(
                condition=Q(("deleted_at__isnull", False)),
                fields=["deleted_at"],
                name="patent_autor_deleted_at_idx",
            ),
        ),
    ]
