# Generated by Django 5.2.16 on 2026-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0487_api_v1_przelaczniki"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent_autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent_autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent_autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_ciagle_autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wydawnictwo_zwarte_autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="wydawnictwo_ciagle_autor",
            index=models.Index(
                fields=["deleted_at"],
                name="wc_autor_deleted_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wydawnictwo_zwarte_autor",
            index=models.Index(
                fields=["deleted_at"],
                name="wz_autor_deleted_at_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patent_autor",
            index=models.Index(
                fields=["deleted_at"],
                name="patent_autor_deleted_at_idx",
            ),
        ),
    ]
