# Generated by Django 5.2.17 on 2026-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0488_purge_praca_tabela_dbtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="uczelnia",
            name="mcp_wlaczone",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Gdy odznaczone, asystenci AI nie połączą się z bibliografią "
                    "tej uczelni: adresy /mcp i /mcp/auth odpowiadają 404, a strona "
                    "/mcp/ informuje o wyłączeniu. NIE wyłącza REST API ani "
                    "logowania OAuth (/o/) — korzystają z nich także inne "
                    "integracje. Serwer MCP pobiera dane przez REST API, więc przy "
                    "wyłączonym API jego narzędzia i tak nie zwrócą danych."
                ),
                verbose_name="Włącz serwer MCP dla asystentów AI (/mcp)",
            ),
        ),
    ]
