# Generated by Django 5.2.16 on 2026-08-06 17:16
#
# Task 3c. Trzy powiązane zmiany na Wydawnictwo_Ciagle_Autor,
# Wydawnictwo_Zwarte_Autor, Patent_Autor:
#
# 1. `unique_together` (widziałby też wiersze soft-deleted) -> dwa warunkowe
#    `UniqueConstraint` (`condition=deleted_at__isnull`).
# 2. Przywrócenie zwykłego indeksu na FK `rekord` (`AlterField`, kasuje
#    wcześniejsze `db_index=False`). Powód: dopóki `unique_together` dawało
#    PEŁNY (nie częściowy) indeks btree z `rekord` jako kolumną wiodącą,
#    `db_index=False` na FK było uzasadnione — auto-indeks byłby redundantny.
#    Warunkowe constrainty z (1) są CZĘŚCIOWE (`WHERE deleted_at IS NULL`) —
#    nie pokrywają już zapytań po samym `rekord` bez tego predykatu
#    (RI-check Postgresa przy DELETE rodzica, kolektor kaskady Django,
#    `global_objects`/`deleted_objects`.filter(rekord=…)).
# 3. Zastąpienie legacy `RunSQL` z migracji 0132 (2018) — DODATKOWEGO,
#    poza Django ORM, `UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY
#    DEFERRED` (nigdy nie było w żadnym `Meta`, więc `makemigrations` go nie
#    widziało) — `ExclusionConstraint`-em (GiST + btree_gist, rozszerzenie
#    już włączone od migracji 0056). `UniqueConstraint` nie umie łączyć
#    `condition` z `deferrable` (Django to blokuje), a `deferrable` jest
#    wymagany przez drag&drop reorder autorów w adminie (adminsortable2,
#    `sortable_field_name = "kolejnosc"`) — zamiana kolejności dwóch wierszy
#    przejściowo dubluje `kolejnosc` w obrębie jednej transakcji.
#
# UWAGA przy rollbacku (`reverse_sql` niżej): przywraca legacy `UNIQUE
# (rekord_id, kolejnosc) DEFERRABLE`, ale to NIE zadziała, jeśli w tabeli są
# już soft-deletowane wiersze dublujące `(rekord_id, kolejnosc)` z żywymi —
# taki stan jest dozwolony PO tej migracji (to właśnie ona to umożliwia),
# ale narusza bezwarunkowy constraint SPRZED niej. Rollback padnie
# dokładnie wtedy, gdy funkcja soft-delete była już używana.

import django.contrib.postgres.constraints
import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0489_soft_delete_autorzy_views"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patent_autor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wydawnictwo_ciagle_autor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wydawnictwo_zwarte_autor",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="patent_autor",
            name="rekord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorzy_set",
                to="bpp.patent",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_ciagle_autor",
            name="rekord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorzy_set",
                to="bpp.wydawnictwo_ciagle",
            ),
        ),
        migrations.AlterField(
            model_name="wydawnictwo_zwarte_autor",
            name="rekord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autorzy_set",
                to="bpp.wydawnictwo_zwarte",
            ),
        ),
        migrations.AddConstraint(
            model_name="patent_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "typ_odpowiedzialnosci"),
                name="pat_autor_uniq_rekord_autor_typ",
            ),
        ),
        migrations.AddConstraint(
            model_name="patent_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "kolejnosc"),
                name="pat_autor_uniq_rekord_autor_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="patent_autor",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("rekord", "="), ("kolejnosc", "=")],
                name="pat_autor_excl_rekord_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_ciagle_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "typ_odpowiedzialnosci"),
                name="wc_autor_uniq_rekord_autor_typ",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_ciagle_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "kolejnosc"),
                name="wc_autor_uniq_rekord_autor_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_ciagle_autor",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("rekord", "="), ("kolejnosc", "=")],
                name="wc_autor_excl_rekord_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_zwarte_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "typ_odpowiedzialnosci"),
                name="wz_autor_uniq_rekord_autor_typ",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_zwarte_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "kolejnosc"),
                name="wz_autor_uniq_rekord_autor_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_zwarte_autor",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("rekord", "="), ("kolejnosc", "=")],
                name="wz_autor_excl_rekord_kolejnosc",
            ),
        ),
        # Trzeci kawałek Taska 3c (patrz komentarz na górze pliku): usuń
        # legacy constraint z migracji 0132, zastąpiony ExclusionConstraint-
        # em dodanym wyżej. `IF EXISTS` na DROP — instancja, na której ten
        # constraint zdjęto już kiedyś ręcznie (spoza Django), nie może
        # wywalić migracji. `reverse_sql` przywraca oryginalne DDL z 0132
        # bez `IF EXISTS` (ADD CONSTRAINT tego nie ma w składni) — patrz
        # zastrzeżenie o rollbacku na górze pliku.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bpp_patent_autor "
                "DROP CONSTRAINT IF EXISTS "
                "bpp_patent_autor_unique_rekord_id_kolejnosc;"
            ),
            reverse_sql=(
                "ALTER TABLE bpp_patent_autor "
                "ADD CONSTRAINT bpp_patent_autor_unique_rekord_id_kolejnosc "
                "UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY DEFERRED;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bpp_wydawnictwo_ciagle_autor DROP CONSTRAINT "
                "IF EXISTS "
                "bpp_wydawnictwo_ciagle_autor_unique_rekord_id_kolejnosc;"
            ),
            reverse_sql=(
                "ALTER TABLE bpp_wydawnictwo_ciagle_autor ADD CONSTRAINT "
                "bpp_wydawnictwo_ciagle_autor_unique_rekord_id_kolejnosc "
                "UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY DEFERRED;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bpp_wydawnictwo_zwarte_autor DROP CONSTRAINT "
                "IF EXISTS "
                "bpp_wydawnictwo_zwarte_autor_unique_rekord_id_kolejnosc;"
            ),
            reverse_sql=(
                "ALTER TABLE bpp_wydawnictwo_zwarte_autor ADD CONSTRAINT "
                "bpp_wydawnictwo_zwarte_autor_unique_rekord_id_kolejnosc "
                "UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY DEFERRED;"
            ),
        ),
    ]
