# Generated by Django 5.2.16 on 2026-08-06 16:00

import django.contrib.postgres.constraints
import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0489_soft_delete_autorzy_views"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patent_autor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wydawnictwo_ciagle_autor",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wydawnictwo_zwarte_autor",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="patent_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "typ_odpowiedzialnosci"),
                name="pat_autor_uniq_rekord_autor_typ",
            ),
        ),
        migrations.AddConstraint(
            model_name="patent_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "kolejnosc"),
                name="pat_autor_uniq_rekord_autor_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="patent_autor",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("rekord", "="), ("kolejnosc", "=")],
                name="pat_autor_excl_rekord_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_ciagle_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "typ_odpowiedzialnosci"),
                name="wc_autor_uniq_rekord_autor_typ",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_ciagle_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "kolejnosc"),
                name="wc_autor_uniq_rekord_autor_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_ciagle_autor",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("rekord", "="), ("kolejnosc", "=")],
                name="wc_autor_excl_rekord_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_zwarte_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "typ_odpowiedzialnosci"),
                name="wz_autor_uniq_rekord_autor_typ",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_zwarte_autor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("rekord", "autor", "kolejnosc"),
                name="wz_autor_uniq_rekord_autor_kolejnosc",
            ),
        ),
        migrations.AddConstraint(
            model_name="wydawnictwo_zwarte_autor",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("rekord", "="), ("kolejnosc", "=")],
                name="wz_autor_excl_rekord_kolejnosc",
            ),
        ),
        # Drugi kawałek Taska 3c: legacy migracja 0132 dołożyła surowym SQL-em
        # DODATKOWY, poza Django ORM, `UNIQUE (rekord_id, kolejnosc)
        # DEFERRABLE INITIALLY DEFERRED` na wszystkich 3 tabelach — Django
        # nigdy o nim nie wiedział (nie ma go w Meta), więc `makemigrations`
        # go nie widzi i nie usunie. Ten constraint SAM blokował dokładnie tę
        # samą regresję (re-insert po soft-delete), tylko odroczony do
        # `COMMIT`/zwolnienia savepointu, więc test padał dopiero w
        # teardown/`SET CONSTRAINTS ALL IMMEDIATE`, nie na samym INSERT.
        # Zastępujemy go `ExclusionConstraint`-em dodanym wyżej (ten sam,
        # który właśnie stworzyliśmy przez ORM) — jedynym typem ograniczenia
        # w Postgresie łączącym `WHERE` (warunek soft-delete) z
        # `DEFERRABLE` (wymagane przez drag&drop reorder adminsortable2).
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bpp_patent_autor "
                "DROP CONSTRAINT bpp_patent_autor_unique_rekord_id_kolejnosc;"
            ),
            reverse_sql=(
                "ALTER TABLE bpp_patent_autor "
                "ADD CONSTRAINT bpp_patent_autor_unique_rekord_id_kolejnosc "
                "UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY DEFERRED;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bpp_wydawnictwo_ciagle_autor DROP CONSTRAINT "
                "bpp_wydawnictwo_ciagle_autor_unique_rekord_id_kolejnosc;"
            ),
            reverse_sql=(
                "ALTER TABLE bpp_wydawnictwo_ciagle_autor ADD CONSTRAINT "
                "bpp_wydawnictwo_ciagle_autor_unique_rekord_id_kolejnosc "
                "UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY DEFERRED;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE bpp_wydawnictwo_zwarte_autor DROP CONSTRAINT "
                "bpp_wydawnictwo_zwarte_autor_unique_rekord_id_kolejnosc;"
            ),
            reverse_sql=(
                "ALTER TABLE bpp_wydawnictwo_zwarte_autor ADD CONSTRAINT "
                "bpp_wydawnictwo_zwarte_autor_unique_rekord_id_kolejnosc "
                "UNIQUE (rekord_id, kolejnosc) DEFERRABLE INITIALLY DEFERRED;"
            ),
        ),
    ]
