# Generated by Django 5.2.16 on 2026-08-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0499_drop_kronika_views"),
        ("pbn_api", "0079_constraint_publikacja_instytucji"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="praca_habilitacyjna",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="bpp.autor"
            ),
        ),
        migrations.AddConstraint(
            model_name="praca_habilitacyjna",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("autor",),
                name="phab_uniq_autor_zywy",
                violation_error_message="Ten autor ma już pracę habilitacyjną.",
            ),
        ),
    ]
