# Generated by Django 5.2.16 on 2026-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0501_soft_delete_protect_fk"),
        ("pbn_api", "0079_constraint_publikacja_instytucji"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="autor",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=["deleted_at"],
                name="autor_deleted_at_idx",
            ),
        ),
    ]
