# Generated by Django 5.2.16 on 2026-08-16 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0502_autor_soft_delete'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pbn_export_queue', '0011_pbn_export_queue_operacja'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID obiektu')),
                ('akcja', models.CharField(choices=[('delete', 'Usunięcie (kosz)'), ('restore', 'Przywrócenie'), ('hard_delete', 'Usunięcie trwałe')], db_index=True, max_length=20, verbose_name='Akcja')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data operacji')),
                ('powod', models.TextField(blank=True, default='', verbose_name='Powód')),
                ('pbn_status', models.CharField(blank=True, default='', max_length=50, verbose_name='Status PBN')),
                ('content_type', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Typ rekordu')),
                ('pbn_queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pbn_export_queue.pbn_export_queue', verbose_name='Wpis kolejki PBN')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log operacji soft-delete',
                'verbose_name_plural': 'Logi operacji soft-delete',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='bpp_softdel_content_e5d237_idx')],
            },
        ),
    ]
