# Generated by Django 4.2.25 on 2025-12-15 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pbn_downloader_app", "0002_pbninstitutionpeopletask"),
    ]

    operations = [
        migrations.CreateModel(
            name="PbnJournalsDownloadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "current_step",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("journals_processed", models.IntegerField(default=0)),
                ("total_journals", models.IntegerField(blank=True, null=True)),
                ("zrodla_integrated", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pbn_journals_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PBN Journals Download Task",
                "verbose_name_plural": "PBN Journals Download Tasks",
                "ordering": ["-started_at"],
            },
        ),
    ]
