# Generated by Django 4.2.25 on 2025-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_downloader_app", "0003_pbnjournalsdownloadtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pbndownloadtask",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pbninstitutionpeopletask",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pbnjournalsdownloadtask",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
