# Generated by Django 3.2.16 on 2022-11-22 22:00

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_dyscyplin", "0013_rozbieznoscizrodelview"),
        ("bpp", "0333_autorzy_kierunek_studiow"),
    ]

    operations = [
        # Migracja 0333 z bpp skasuje tabele rozbieznosci_dyscyplin, odtówrz na nowo
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0011_null_is_wrong", app_name="rozbieznosci_dyscyplin"
            )
        ),
    ]
