# Generated by Django 3.2.16 on 2023-02-05 22:30

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_dyscyplin", "0014_recreate"),
        ("bpp", "0335_autorzy_oswiadczenie_ken"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0011_null_is_wrong", app_name="rozbieznosci_dyscyplin"
            )
        ),
    ]
