# Generated by Django 4.2.16 on 2024-10-13 13:57

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_dyscyplin", "0015_recreate"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0016_rozbieznosci_dyscyplin_zrodel_v2",
                app_name="rozbieznosci_dyscyplin",
            )
        )
    ]
