# Generated by Django 4.2.25 on 2025-10-12 20:11

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):
    dependencies = [
        ("rozbieznosci_dyscyplin", "0016_rozbieznosci_dyscyplin_zrodel_v2"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0017_add_punkty_kbn_and_charakter_formalny",
                app_name="rozbieznosci_dyscyplin",
            )
        ),
    ]
