# Generated by Django 4.2.25 on 2025-10-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_dyscyplin", "0016_rozbieznosci_dyscyplin_zrodel_v2"),
    ]

    operations = [
        migrations.RunSQL(
            """
            BEGIN;

            DROP VIEW IF EXISTS rozbieznosci_dyscyplin_rozbieznoscizrodelview;

            CREATE VIEW rozbieznosci_dyscyplin_rozbieznoscizrodelview AS
            SELECT DISTINCT  ARRAY [
                     bpp_dyscyplina_zrodla.zrodlo_id,
                     bpp_wydawnictwo_ciagle.id,
                bpp_wydawnictwo_ciagle_autor.autor_id,
                COALESCE(bpp_wydawnictwo_ciagle_autor.dyscyplina_naukowa_id, -1)] AS id,
                        bpp_dyscyplina_zrodla.zrodlo_id,
                        bpp_wydawnictwo_ciagle.rok AS rok,
                        bpp_wydawnictwo_ciagle.id AS wydawnictwo_ciagle_id,
                        bpp_wydawnictwo_ciagle_autor.autor_id,
                        bpp_wydawnictwo_ciagle_autor.dyscyplina_naukowa_id,
                        bpp_wydawnictwo_ciagle.punkty_kbn,
                        bpp_wydawnictwo_ciagle.charakter_formalny_id
            FROM bpp_wydawnictwo_ciagle_autor,
                 bpp_dyscyplina_zrodla,
                 bpp_wydawnictwo_ciagle
            WHERE bpp_dyscyplina_zrodla.zrodlo_id = bpp_wydawnictwo_ciagle.zrodlo_id
              AND bpp_wydawnictwo_ciagle.rok >= 2017
              AND bpp_wydawnictwo_ciagle_autor.rekord_id = bpp_wydawnictwo_ciagle.id
              AND bpp_wydawnictwo_ciagle_autor.dyscyplina_naukowa_id NOT IN (
                SELECT dyscyplina_id
                FROM bpp_dyscyplina_zrodla
                WHERE bpp_dyscyplina_zrodla.zrodlo_id = bpp_wydawnictwo_ciagle.zrodlo_id
                    AND bpp_dyscyplina_zrodla.rok = bpp_wydawnictwo_ciagle.rok);

            COMMIT;
            """,
            reverse_sql="""
            BEGIN;

            DROP VIEW IF EXISTS rozbieznosci_dyscyplin_rozbieznoscizrodelview;

            CREATE VIEW rozbieznosci_dyscyplin_rozbieznoscizrodelview AS
            SELECT DISTINCT  ARRAY [
                     bpp_dyscyplina_zrodla.zrodlo_id,
                     bpp_wydawnictwo_ciagle.id,
                bpp_wydawnictwo_ciagle_autor.autor_id,
                COALESCE(bpp_wydawnictwo_ciagle_autor.dyscyplina_naukowa_id, -1)] AS id,
                        bpp_dyscyplina_zrodla.zrodlo_id,
                        bpp_wydawnictwo_ciagle.rok AS rok,
                        bpp_wydawnictwo_ciagle.id AS wydawnictwo_ciagle_id,
                        bpp_wydawnictwo_ciagle_autor.autor_id,
                        bpp_wydawnictwo_ciagle_autor.dyscyplina_naukowa_id
            FROM bpp_wydawnictwo_ciagle_autor,
                 bpp_dyscyplina_zrodla,
                 bpp_wydawnictwo_ciagle
            WHERE bpp_dyscyplina_zrodla.zrodlo_id = bpp_wydawnictwo_ciagle.zrodlo_id
              AND bpp_wydawnictwo_ciagle.rok >= 2017
              AND bpp_wydawnictwo_ciagle_autor.rekord_id = bpp_wydawnictwo_ciagle.id
              AND bpp_wydawnictwo_ciagle_autor.dyscyplina_naukowa_id NOT IN (
                SELECT dyscyplina_id
                FROM bpp_dyscyplina_zrodla
                WHERE bpp_dyscyplina_zrodla.zrodlo_id = bpp_wydawnictwo_ciagle.zrodlo_id
                    AND bpp_dyscyplina_zrodla.rok = bpp_wydawnictwo_ciagle.rok);

            COMMIT;
            """,
        )
    ]
