# Generated by Django 4.2 on 2025-12-15

from django.db import migrations

from bpp.migration_util import load_custom_sql


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_dyscyplin", "0017_add_punkty_kbn_and_charakter_formalny"),
        ("bpp", "0401_autorzy_przypieta"),
    ]

    operations = [
        migrations.RunPython(
            lambda *args, **kw: load_custom_sql(
                "0017_add_punkty_kbn_and_charakter_formalny",
                app_name="rozbieznosci_dyscyplin",
            )
        ),
    ]
