# Generated by Django 4.2.30 on 2026-04-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rozbieznosci_dyscyplin", "0020_recreate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rozbieznosciview",
            options={
                "managed": False,
                "ordering": ["id"],
                "verbose_name": "rozbieżność rekordu i dyscyplin",
                "verbose_name_plural": "rozbieżności rekordów i dyscyplin",
            },
        ),
    ]
