FROM postgres:9.6

ENV LANG "pl_PL.utf8"

RUN localedef -i pl_PL -c -f UTF-8 -A /usr/share/locale/locale.alias pl_PL.UTF-8
RUN apt-get -qq update && apt-get -qq install -y postgresql-plpython-9.6

#EXPOSE 5432
