FROM python:3.6

RUN apt-get update
RUN apt-get install -y wget
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y --force-yes postgresql-client-9.6 zip

RUN pip install --upgrade --extra-index-url http://dev.iplweb.pl:8080/ --trusted-host dev.iplweb.pl django-bpp

EXPOSE 8000

COPY prod-entrypoint.sh .

RUN chmod +x prod-entrypoint.sh

ENTRYPOINT ["./prod-entrypoint.sh"]
