FROM postgres:11
RUN localedef -i pl_PL -c -f UTF-8 -A /usr/share/locale/locale.alias pl_PL.UTF-8
ENV LANG pl_PL.utf8
RUN apt-mark hold postgresql-11 postgresql-client-11 postgresql-common postgresql-client-common
RUN apt-get update -qq && apt-get install postgresql-plpython-11 -qq -y