build:
	docker build -f ./Dockerfile-circleci-python-3.7-node-browsers-nginx-http-push -t mpasternak79/circleci-python:3.7-node-browsers-nginx-http-push  .

push:
	docker push mpasternak79/circleci-python:3.7-node-browsers-nginx-http-push 
