# Generated by Django 2.1.13 on 2019-11-01 19:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_dbf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bib_Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem_id', models.PositiveSmallIntegerField()),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('source', models.CharField(max_length=10)),
                ('idt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_dbf.Bib')),
            ],
            options={
                'ordering': ('idt', 'source'),
            },
        ),
        migrations.AlterModelOptions(
            name='b_u',
            options={'managed': False, 'ordering': ('idt', 'comm'), 'verbose_name': 'zaimportowane dane OA rekordu', 'verbose_name_plural': 'zaimportowane dane OA rekordow'},
        ),
    ]
