# Generated by Django 4.2.25 on 2025-12-15 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OswiadczeniaExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("running", "W trakcie"),
                            ("completed", "Zakończony"),
                            ("failed", "Błąd"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("html", "HTML (do druku)"), ("pdf", "PDF")],
                        max_length=10,
                    ),
                ),
                ("rok_od", models.IntegerField()),
                ("rok_do", models.IntegerField()),
                (
                    "szukaj_autor",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "szukaj_tytul",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("dyscyplina_id", models.IntegerField(blank=True, null=True)),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                (
                    "current_item",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to="oswiadczenia_exports/"
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
