# Generated by Django 4.2.25 on 2025-12-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oswiadczenia", "0001_add_export_task_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="oswiadczeniaexporttask",
            name="limit",
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name="oswiadczeniaexporttask",
            name="offset",
            field=models.IntegerField(default=0),
        ),
    ]
