# Generated by Django 4.2.25 on 2025-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oswiadczenia", "0002_add_offset_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oswiadczeniaexporttask",
            name="export_format",
            field=models.CharField(
                choices=[
                    ("html", "HTML (ZIP)"),
                    ("pdf", "PDF (ZIP)"),
                    ("docx", "DOCX (ZIP)"),
                    ("html_single", "HTML (jeden plik)"),
                    ("docx_single", "DOCX (jeden plik)"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="oswiadczeniaexporttask",
            name="result_file",
            field=models.FileField(
                blank=True, null=True, upload_to="protected/oswiadczenia/"
            ),
        ),
    ]
