# Generated by Django 4.2.25 on 2025-12-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oswiadczenia", "0003_fix_export_format_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="oswiadczeniaexporttask",
            name="przypieta",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="oswiadczeniaexporttask",
            name="export_format",
            field=models.CharField(
                choices=[
                    ("html", "HTML (ZIP)"),
                    ("pdf", "PDF (ZIP)"),
                    ("docx", "DOCX (ZIP)"),
                    ("html_single", "HTML (jeden plik)"),
                    ("pdf_single", "PDF (jeden plik)"),
                    ("docx_single", "DOCX (jeden plik)"),
                ],
                max_length=15,
            ),
        ),
    ]
