# Generated by Django 4.2.25 on 2025-11-12 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0395_add_wymagaj_logowania_zglos_publikacje"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrzemapowaZrodla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liczba_publikacji",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Liczba przemapowanych publikacji"
                    ),
                ),
                (
                    "publikacje_historia",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista przemapowanych publikacji z podstawowymi informacjami (ID, tytuł, rok)",
                        verbose_name="Historia przemapowanych publikacji",
                    ),
                ),
                (
                    "utworzono",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "cofnieto",
                    models.DateTimeField(
                        blank=True,
                        help_text="Wypełnione jeśli przemapowanie zostało cofnięte",
                        null=True,
                        verbose_name="Data cofnięcia",
                    ),
                ),
                (
                    "cofnieto_przez",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="przemapowania_zrodla_cofnieto",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cofnięto przez",
                    ),
                ),
                (
                    "utworzono_przez",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_zrodla_utworzono",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzono przez",
                    ),
                ),
                (
                    "zrodlo_do",
                    models.ForeignKey(
                        help_text="Źródło, do którego przemapowano publikacje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_lokalne_do",
                        to="bpp.zrodlo",
                        verbose_name="Źródło docelowe",
                    ),
                ),
                (
                    "zrodlo_z",
                    models.ForeignKey(
                        help_text="Źródło, z którego przemapowano publikacje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="przemapowania_lokalne_z",
                        to="bpp.zrodlo",
                        verbose_name="Źródło źródłowe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przemapowanie źródła",
                "verbose_name_plural": "Przemapowania źródeł",
                "ordering": ["-utworzono"],
                "indexes": [
                    models.Index(
                        fields=["zrodlo_z"], name="przemapuj_z_zrodlo__8d9224_idx"
                    ),
                    models.Index(
                        fields=["zrodlo_do"], name="przemapuj_z_zrodlo__54751f_idx"
                    ),
                    models.Index(
                        fields=["utworzono"], name="przemapuj_z_utworzo_67ad91_idx"
                    ),
                ],
            },
        ),
    ]
