# Generated by Django 5.2.14 on 2026-06-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przemapuj_zrodlo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='przemapowazrodla',
            name='przemapuj_z_zrodlo__8d9224_idx',
        ),
        migrations.RemoveIndex(
            model_name='przemapowazrodla',
            name='przemapuj_z_zrodlo__54751f_idx',
        ),
    ]
