# Generated by Django 5.2.15 on 2026-06-29 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpp', '0444_alter_uczelnia_wyszukiwanie_rekordy_na_strone_anonim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RozbieznoscLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metryka', models.CharField(choices=[('if', 'Impact Factor'), ('mnisw', 'Punkty MNiSW'), ('kw_scopus', 'Kwartyl Scopus'), ('kw_wos', 'Kwartyl WoS')], max_length=16, verbose_name='Metryka')),
                ('wartosc_przed', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Wartość przed zmianą')),
                ('wartosc_po', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Wartość po zmianie')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Kiedy')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.wydawnictwo_ciagle', verbose_name='Rekord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('zrodlo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpp.zrodlo', verbose_name='Źródło')),
            ],
            options={
                'verbose_name': 'log zmiany punktacji',
                'verbose_name_plural': 'logi zmian punktacji',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='IgnorowanaRozbieznosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metryka', models.CharField(choices=[('if', 'Impact Factor'), ('mnisw', 'Punkty MNiSW'), ('kw_scopus', 'Kwartyl Scopus'), ('kw_wos', 'Kwartyl WoS')], max_length=16, verbose_name='Metryka')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('rekord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpp.wydawnictwo_ciagle', verbose_name='Rekord')),
            ],
            options={
                'verbose_name': 'ignorowana rozbieżność',
                'verbose_name_plural': 'ignorowane rozbieżności',
                'unique_together': {('metryka', 'rekord')},
            },
        ),
    ]
