# Generated by Django 3.2.14 on 2022-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrator2", "0004_django32"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listaministerialnaelement",
            name="moze_byc_zintegrowany_automatycznie",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
