# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi pliki z integrator2/ do protected/integrator2/"""
    ListaMinisterialnaIntegration = apps.get_model(
        "integrator2", "ListaMinisterialnaIntegration"
    )
    old_dir = os.path.join(settings.MEDIA_ROOT, "integrator2")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "integrator2")
    os.makedirs(new_dir, exist_ok=True)

    for obj in ListaMinisterialnaIntegration.objects.exclude(file=""):
        if obj.file:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.file.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.file = f"protected/integrator2/{filename}"
                obj.save(update_fields=["file"])

    # Usuń stary katalog jeśli pusty
    if os.path.exists(old_dir) and not os.listdir(old_dir):
        os.rmdir(old_dir)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("integrator2", "0005_nullbooleanfield"),
    ]

    operations = [
        migrations.RunPython(move_files_to_protected, noop),
        migrations.AlterField(
            model_name="listaministerialnaintegration",
            name="file",
            field=models.FileField(
                upload_to="protected/integrator2/", verbose_name="Plik"
            ),
        ),
    ]
