# Generated by Django 6.0.6 on 2026-06-30 23:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _live_op_fields():
    """Return the common LiveOperation field list (used by each model)."""
    return [
        (
            "id",
            models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        ("created_on", models.DateTimeField(auto_now_add=True)),
        ("started_on", models.DateTimeField(blank=True, null=True)),
        ("finished_on", models.DateTimeField(blank=True, null=True)),
        ("finished_successfully", models.BooleanField(default=False)),
        ("cancel_requested", models.BooleanField(default=False)),
        ("cancelled", models.BooleanField(default=False)),
        ("traceback", models.TextField(blank=True, null=True)),
        ("result_context", models.JSONField(blank=True, null=True)),
        (
            "status_text",
            models.CharField(blank=True, default="", max_length=255),
        ),
        ("percent", models.PositiveSmallIntegerField(default=0)),
        ("log", models.JSONField(default=list)),
        ("log_seq", models.PositiveIntegerField(default=0)),
        ("current_stage", models.IntegerField(default=-1)),
        ("stage_states", models.JSONField(default=dict)),
        (
            "owner",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(name="demoop", options={}),
        migrations.AlterModelOptions(name="errorop", options={}),
        migrations.CreateModel(name="ChainOpA", fields=_live_op_fields()),
        migrations.CreateModel(name="FailedStageOp", fields=_live_op_fields()),
        migrations.CreateModel(name="NextOp", fields=_live_op_fields()),
        migrations.CreateModel(name="StagedOp", fields=_live_op_fields()),
    ]
