# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksport_pbn', '0008_auto_20160802_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='artykuly',
            field=models.BooleanField(default=True, verbose_name='Artykuły'),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='do_daty',
            field=models.DateField(blank=True, null=True, verbose_name='Do daty'),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='do_roku',
            field=models.IntegerField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016')], default=2016),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='file',
            field=models.FileField(upload_to='eksport_pbn', verbose_name='Plik'),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='ksiazki',
            field=models.BooleanField(default=True, verbose_name='Książki'),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='od_daty',
            field=models.DateField(blank=True, null=True, verbose_name='Od daty'),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='od_roku',
            field=models.IntegerField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016')], default=2016),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='rodzaj_daty',
            field=models.SmallIntegerField(choices=[(1, 'data utworzenia'), (2, 'data aktualizacji'), (3, 'data aktualizacji dla PBN')], default=3, help_text='Jakie pole z datą będzie używane do wybierania rekordów?', verbose_name='Rodzaj pola daty'),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='rozdzialy',
            field=models.BooleanField(default=True, verbose_name='Rozdziały'),
        ),
    ]
