# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksport_pbn', '0009_django110_py3k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='do_roku',
            field=models.IntegerField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], default=2017),
        ),
        migrations.AlterField(
            model_name='plikeksportupbn',
            name='od_roku',
            field=models.IntegerField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], default=2017),
        ),
    ]
