# Generated by Django 3.0.4 on 2020-04-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eksport_pbn", "0011_auto_20180415_0813"),
    ]

    operations = [
        migrations.RemoveField(model_name="plikeksportupbn", name="wydzial",),
    ]
