build-14:
	docker build -f ./Dockerfile-db-psql14 -t mpasternak79/cimg-postgres:14 .

push-14:
	docker push mpasternak79/cimg-postgres:14

build-15-4:
	docker build -f ./Dockerfile-db-psql15 -t mpasternak79/cimg-postgres:15.4 .

push-15-4:
	docker push mpasternak79/cimg-postgres:15.4

build-12:
	docker build -f ./Dockerfile-db-psql12 -t mpasternak79/cimg-postgres:12 .

push-12:
	docker push mpasternak79/cimg-postgres:12
