# Generated by Django 4.2.25 on 2025-11-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0398_alter_autor_string_fields_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Powód wykluczenia z deduplikacji"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ignoredsource_zrodlo_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zrodlo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignored_in_dedup",
                        to="bpp.zrodlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "źródło ignorowane w deduplikacji",
                "verbose_name_plural": "źródła ignorowane w deduplikacji",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="NotADuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notaduplicate_zrodlo_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplikat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="not_duplicate_duplicate",
                        to="bpp.zrodlo",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="not_duplicate_main",
                        to="bpp.zrodlo",
                    ),
                ),
            ],
            options={
                "verbose_name": "oznaczenie 'to nie duplikat'",
                "verbose_name_plural": "oznaczenia 'to nie duplikat'",
                "ordering": ["-created_on"],
                "unique_together": {("zrodlo", "duplikat")},
            },
        ),
    ]
