# Generated by Django 5.2.15 on 2026-07-04 12:09

import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0445_merge_20260622_1134'),
        ('deduplikator_zrodel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanZrodelForDuplicates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('result_context', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=20)),
                ('status_text', models.CharField(blank=True, default='', max_length=255)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.JSONField(default=list)),
                ('log_seq', models.PositiveIntegerField(default=0)),
                ('current_stage', models.IntegerField(default=-1)),
                ('stage_states', models.JSONField(default=dict)),
                ('total_sources', models.PositiveIntegerField(default=0, verbose_name='Źródeł do przeskanowania')),
                ('sources_scanned', models.PositiveIntegerField(default=0, verbose_name='Przeskanowano źródeł')),
                ('duplicates_found', models.PositiveIntegerField(default=0, verbose_name='Znaleziono duplikatów')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skanowanie duplikatów źródeł',
                'verbose_name_plural': 'Skanowania duplikatów źródeł',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SourceDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.IntegerField(db_index=True, verbose_name='Wynik pewności')),
                ('main_nazwa', models.CharField(blank=True, max_length=1024, verbose_name='Nazwa źródła głównego')),
                ('duplicate_nazwa', models.CharField(blank=True, max_length=1024, verbose_name='Nazwa duplikatu')),
                ('main_pub_count', models.PositiveIntegerField(default=0, verbose_name='Publikacje źródła głównego')),
                ('duplicate_pub_count', models.PositiveIntegerField(default=0, verbose_name='Publikacje duplikatu')),
                ('status', models.CharField(choices=[('pending', 'Do sprawdzenia'), ('skipped', 'Odłożony na później'), ('merged', 'Przemapowany/scalony')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpatrzenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('duplicate_zrodlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_candidate_as_duplicate', to='bpp.zrodlo', verbose_name='Potencjalny duplikat')),
                ('main_zrodlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_candidate_as_main', to='bpp.zrodlo', verbose_name='Źródło główne')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Rozpatrzył')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='deduplikator_zrodel.scanzrodelforduplicates', verbose_name='Skanowanie')),
            ],
            options={
                'verbose_name': 'Kandydat na duplikat źródła',
                'verbose_name_plural': 'Kandydaci na duplikaty źródeł',
                'ordering': ['-confidence_score'],
                'indexes': [models.Index(fields=['scan', 'status'], name='deduplikato_scan_id_7d8032_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.comparison.Least('main_zrodlo', 'duplicate_zrodlo'), django.db.models.functions.comparison.Greatest('main_zrodlo', 'duplicate_zrodlo'), models.F('scan'), name='uniq_scan_unordered_pair')],
            },
        ),
    ]
