from collections import OrderedDict

TO_AUTOR = 0
TO_REDAKTOR = 1
TO_INNY = 2
TO_TLUMACZ = 3
TO_KOMENTATOR = 4
TO_RECENZENT = 5
TO_OPRACOWAL = 6

GR_WPROWADZANIE_DANYCH = 'wprowadzanie danych'

CHARAKTER_SLOTY_KSIAZKA = 1
CHARAKTER_SLOTY_ROZDZIAL = 2

RODZAJ_PBN_ARTYKUL = 1
RODZAJ_PBN_ROZDZIAL = 2
RODZAJ_PBN_KSIAZKA = 3

DZIEDZINA_NAUK_HUMANISTYCZNYCH = 1
DZIEDZINA_NAUK_SPOLECZNYCH = 5
DZIEDZINA_NAUK_TEOLOGICZNYCH = 7

DZIEDZINY = OrderedDict()
DZIEDZINY[DZIEDZINA_NAUK_HUMANISTYCZNYCH] = "Nauki humanistyczne"
DZIEDZINY[2] = "Nauki inżynieryjno-techniczne"
DZIEDZINY[3] = "Nauki medyczne i o zdrowiu"
DZIEDZINY[4] = "Nauki rolnicze"
DZIEDZINY[DZIEDZINA_NAUK_SPOLECZNYCH] = "Nauki społeczne"
DZIEDZINY[6] = "Nauki ścisłe i przyrodnicze"
DZIEDZINY[DZIEDZINA_NAUK_TEOLOGICZNYCH] = "Nauki teologiczne"
DZIEDZINY[8] = "Sztuka"
