# Generated by Django 4.2.16 on 2024-10-17 17:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import long_running.notification_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bpp", "0356_drop_kc_komisja_centralna"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportPlikuPolon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("started_on", models.DateTimeField(blank=True, null=True)),
                ("finished_on", models.DateTimeField(blank=True, null=True)),
                ("finished_successfully", models.BooleanField(default=False)),
                ("traceback", models.TextField(blank=True, null=True)),
                ("plik", models.FileField(upload_to="import_polon")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_updated_on"],
                "abstract": False,
            },
            bases=(
                long_running.notification_mixins.ASGINotificationMixin,
                long_running.notification_mixins.NullNotificationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="WierszImportuPlikuPolon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orig", models.JSONField()),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.autor",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="import_polon.importplikupolon",
                    ),
                ),
            ],
        ),
    ]
