# Generated by Django 4.2.16 on 2024-10-18 21:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wierszimportuplikupolon",
            name="orig",
        ),
        migrations.AddField(
            model_name="wierszimportuplikupolon",
            name="dane_z_xls",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wierszimportuplikupolon",
            name="nr_wiersza",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
