# Generated by Django 4.2.16 on 2024-10-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0356_drop_kc_komisja_centralna"),
        ("import_polon", "0002_remove_wierszimportuplikupolon_orig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wierszimportuplikupolon",
            name="dyscyplina_naukowa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bpp.dyscyplina_naukowa",
            ),
        ),
        migrations.AddField(
            model_name="wierszimportuplikupolon",
            name="subdyscyplina_naukowa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bpp.dyscyplina_naukowa",
            ),
        ),
    ]
