# Generated by Django 4.2.16 on 2024-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0003_wierszimportuplikupolon_dyscyplina_naukowa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importplikupolon",
            name="rok",
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
