# Generated by Django 4.2.16 on 2024-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0004_importplikupolon_rok"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wierszimportuplikupolon",
            options={"ordering": ("nr_wiersza",)},
        ),
        migrations.AddField(
            model_name="wierszimportuplikupolon",
            name="rezultat",
            field=models.TextField(blank=True, null=True),
        ),
    ]
