# Generated by Django 4.2.16 on 2024-11-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0005_alter_wierszimportuplikupolon_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importplikupolon",
            name="zapisz_zmiany_do_bazy",
            field=models.BooleanField(default=False),
        ),
    ]
