# Generated by Django 4.2.16 on 2024-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0006_importplikupolon_zapisz_zmiany_do_bazy"),
    ]

    operations = [
        migrations.AddField(
            model_name="importplikupolon",
            name="ukryj_niezmatchowanych_autorow",
            field=models.BooleanField(default=True),
        ),
    ]
