# Generated by Django 4.2.19 on 2025-03-15 08:13

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0373_alter_praca_doktorska_jezyk_and_more"),
        ("import_polon", "0008_importplikuabsencji"),
    ]

    operations = [
        migrations.CreateModel(
            name="WierszImportuPlikuAbsencji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dane_z_xls",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("nr_wiersza", models.PositiveSmallIntegerField()),
                ("rok", models.PositiveSmallIntegerField()),
                ("ile_dni", models.PositiveSmallIntegerField()),
                (
                    "wymaga_zmiany",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("rezultat", models.TextField(blank=True, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.autor",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="import_polon.importplikuabsencji",
                    ),
                ),
            ],
        ),
    ]
