# Generated by Django 4.2.19 on 2025-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0009_wierszimportuplikuabsencji"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wierszimportuplikuabsencji",
            options={"ordering": ("nr_wiersza",)},
        ),
        migrations.AddField(
            model_name="importplikuabsencji",
            name="zapisz_zmiany_do_bazy",
            field=models.BooleanField(default=False),
        ),
    ]
