# Generated by Django 4.2.19 on 2025-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0010_alter_wierszimportuplikuabsencji_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wierszimportuplikuabsencji",
            name="ile_dni",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wierszimportuplikuabsencji",
            name="rok",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
