# Generated by Django 4.2.25 on 2025-10-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0011_alter_wierszimportuplikuabsencji_ile_dni_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportPolonOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupa_stanowisk",
                    models.CharField(
                        help_text="Nazwa grupy stanowisk z pliku POLON (np. 'Pracownik badawczo-dydaktyczny')",
                        max_length=200,
                        unique=True,
                        verbose_name="Grupa stanowisk",
                    ),
                ),
                (
                    "jest_badawczy",
                    models.BooleanField(
                        help_text="Określa czy pracownik tej grupy stanowisk ma być oznaczony jako badawczy (typ B)",
                        verbose_name="Czy jest badawczy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nadpisanie grupy stanowisk",
                "verbose_name_plural": "Nadpisania grup stanowisk",
                "ordering": ("grupa_stanowisk",),
            },
        ),
    ]
