# Generated by Django 4.2.25 on 2025-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0012_importpolonoverride"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importpolonoverride",
            options={
                "ordering": ("grupa_stanowisk",),
                "verbose_name": "Wymuszenie grupy stanowisk",
                "verbose_name_plural": "Wymuszenia grup stanowisk",
            },
        ),
        migrations.AlterField(
            model_name="wierszimportuplikuabsencji",
            name="rezultat",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="wierszimportuplikupolon",
            name="rezultat",
            field=models.TextField(blank=True, default=""),
        ),
    ]
