# Generated by Django 4.2.25 on 2025-12-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_polon", "0013_alter_importpolonoverride_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importplikupolon",
            name="ignoruj_miejsce_pracy",
            field=models.BooleanField(
                default=False,
                help_text="Pomiń walidację pola ZATRUDNIENIE (czy zaczyna się od nazwy uczelni)",
                verbose_name="Ignoruj miejsce pracy",
            ),
        ),
    ]
