# Generated by Django 4.2.25 on 2025-12-22 20:56

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Move existing files from import_polon/ to protected/import_polon/"""
    old_dir = os.path.join(settings.MEDIA_ROOT, "import_polon")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "import_polon")

    # Create new directory if it doesn't exist
    os.makedirs(new_dir, exist_ok=True)

    # Move files and update database records for ImportPlikuPolon
    ImportPlikuPolon = apps.get_model("import_polon", "ImportPlikuPolon")
    for obj in ImportPlikuPolon.objects.all():
        if obj.plik and obj.plik.name.startswith("import_polon/"):
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            new_name = obj.plik.name.replace("import_polon/", "protected/import_polon/")
            new_path = os.path.join(settings.MEDIA_ROOT, new_name)

            if os.path.exists(old_path):
                shutil.move(old_path, new_path)

            obj.plik.name = new_name
            obj.save(update_fields=["plik"])

    # Move files and update database records for ImportPlikuAbsencji
    ImportPlikuAbsencji = apps.get_model("import_polon", "ImportPlikuAbsencji")
    for obj in ImportPlikuAbsencji.objects.all():
        if obj.plik and obj.plik.name.startswith("import_polon/"):
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            new_name = obj.plik.name.replace("import_polon/", "protected/import_polon/")
            new_path = os.path.join(settings.MEDIA_ROOT, new_name)

            if os.path.exists(old_path):
                shutil.move(old_path, new_path)

            obj.plik.name = new_name
            obj.save(update_fields=["plik"])

    # Remove old directory if empty
    if os.path.exists(old_dir):
        try:
            shutil.rmtree(old_dir)
        except OSError:
            pass  # Directory not empty or other error


def reverse_move_files(apps, schema_editor):
    """Reverse migration - move files back to import_polon/"""
    old_dir = os.path.join(settings.MEDIA_ROOT, "protected", "import_polon")
    new_dir = os.path.join(settings.MEDIA_ROOT, "import_polon")

    os.makedirs(new_dir, exist_ok=True)

    ImportPlikuPolon = apps.get_model("import_polon", "ImportPlikuPolon")
    for obj in ImportPlikuPolon.objects.all():
        if obj.plik and obj.plik.name.startswith("protected/import_polon/"):
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            new_name = obj.plik.name.replace("protected/import_polon/", "import_polon/")
            new_path = os.path.join(settings.MEDIA_ROOT, new_name)

            if os.path.exists(old_path):
                shutil.move(old_path, new_path)

            obj.plik.name = new_name
            obj.save(update_fields=["plik"])

    ImportPlikuAbsencji = apps.get_model("import_polon", "ImportPlikuAbsencji")
    for obj in ImportPlikuAbsencji.objects.all():
        if obj.plik and obj.plik.name.startswith("protected/import_polon/"):
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            new_name = obj.plik.name.replace("protected/import_polon/", "import_polon/")
            new_path = os.path.join(settings.MEDIA_ROOT, new_name)

            if os.path.exists(old_path):
                shutil.move(old_path, new_path)

            obj.plik.name = new_name
            obj.save(update_fields=["plik"])

    if os.path.exists(old_dir):
        try:
            shutil.rmtree(old_dir)
        except OSError:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("import_polon", "0014_add_ignoruj_miejsce_pracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importplikuabsencji",
            name="plik",
            field=models.FileField(upload_to="protected/import_polon"),
        ),
        migrations.AlterField(
            model_name="importplikupolon",
            name="plik",
            field=models.FileField(upload_to="protected/import_polon"),
        ),
        migrations.RunPython(move_files_to_protected, reverse_move_files),
    ]
