# Generated by Django 5.2.15 on 2026-07-03 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0445_merge_20260622_1134'),
        ('import_polon', '0015_move_files_to_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='importplikupolon',
            name='uczelnia',
            field=models.ForeignKey(blank=True, help_text='Uczelnia, dla której wykonywany jest import (multi-hosted).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpp.uczelnia'),
        ),
    ]
