"""Konstanty leksykalne dla generatora demo data (data-only, no logic)."""

IMIONA_POL = (
    # Kobiety
    "Anna",
    "Maria",
    "Katarzyna",
    "Małgorzata",
    "Agnieszka",
    "Barbara",
    "Ewa",
    "Magdalena",
    "Elżbieta",
    "Joanna",
    "Aleksandra",
    "Monika",
    "Zofia",
    "Teresa",
    "Krystyna",
    "Halina",
    "Beata",
    "Jadwiga",
    "Danuta",
    "Iwona",
    "Renata",
    "Wanda",
    "Grażyna",
    "Dorota",
    "Janina",
    "Urszula",
    "Hanna",
    "Marta",
    "Justyna",
    "Karolina",
    "Marzena",
    "Bożena",
    "Lucyna",
    "Wiesława",
    "Stanisława",
    "Helena",
    "Natalia",
    "Paulina",
    "Patrycja",
    "Sylwia",
    "Edyta",
    "Izabela",
    # Mężczyźni
    "Jan",
    "Andrzej",
    "Piotr",
    "Krzysztof",
    "Stanisław",
    "Tomasz",
    "Paweł",
    "Józef",
    "Marcin",
    "Marek",
    "Michał",
    "Grzegorz",
    "Jerzy",
    "Tadeusz",
    "Adam",
    "Łukasz",
    "Zbigniew",
    "Ryszard",
    "Dariusz",
    "Henryk",
    "Mariusz",
    "Wojciech",
    "Robert",
    "Kazimierz",
    "Mateusz",
    "Maciej",
    "Sławomir",
    "Rafał",
    "Bogdan",
    "Janusz",
    "Jacek",
    "Jakub",
    "Artur",
    "Marian",
    "Jarosław",
    "Mirosław",
    "Antoni",
    "Wiesław",
    "Roman",
    "Edward",
    "Sebastian",
    "Damian",
    "Kamil",
    "Daniel",
    "Bartosz",
)

NAZWISKA_POL = (
    "Nowak",
    "Kowalski",
    "Wiśniewski",
    "Wójcik",
    "Kowalczyk",
    "Kamiński",
    "Lewandowski",
    "Zieliński",
    "Szymański",
    "Woźniak",
    "Dąbrowski",
    "Kozłowski",
    "Jankowski",
    "Mazur",
    "Wojciechowski",
    "Kwiatkowski",
    "Krawczyk",
    "Kaczmarek",
    "Piotrowski",
    "Grabowski",
    "Zając",
    "Pawłowski",
    "Michalski",
    "Król",
    "Wieczorek",
    "Jabłoński",
    "Wróbel",
    "Nowakowski",
    "Majewski",
    "Olszewski",
    "Jaworski",
    "Adamczyk",
    "Dudek",
    "Nowicki",
    "Pawlak",
    "Górski",
    "Witkowski",
    "Walczak",
    "Sikora",
    "Baran",
    "Rutkowski",
    "Michalak",
    "Szewczyk",
    "Ostrowski",
    "Tomaszewski",
    "Pietrzak",
    "Marciniak",
    "Wróblewski",
    "Zalewski",
    "Jakubowski",
    "Jasiński",
    "Zawadzki",
    "Sadowski",
    "Bąk",
    "Chmielewski",
    "Włodarczyk",
    "Borkowski",
    "Czarnecki",
    "Sawicki",
    "Sokołowski",
    "Urbański",
    "Kubiak",
    "Maciejewski",
    "Szczepański",
    "Kucharski",
    "Wilk",
    "Kalinowski",
    "Lis",
    "Mazurek",
    "Wysocki",
    "Adamski",
    "Kaźmierczak",
    "Wasilewski",
    "Sobczak",
    "Czerwiński",
    "Andrzejewski",
    "Cieślak",
    "Głowacki",
    "Zakrzewski",
    "Kołodziej",
    "Sikorski",
    "Krupa",
    "Stępień",
    "Kurek",
    "Brzeziński",
    "Borowski",
    "Pawlik",
    "Sowa",
    "Domagała",
    "Wojtasik",
    "Mróz",
    "Małecki",
    "Janik",
    "Bednarek",
    "Bielecki",
    "Marek",
    "Krajewski",
    "Markowski",
    "Konieczny",
    "Lasota",
)

KIERUNKI_POL = (
    "Lekarski",
    "Lekarsko-Dentystyczny",
    "Farmaceutyczny",
    "Nauk o Zdrowiu",
    "Pielęgniarstwa i Nauk o Zdrowiu",
    "Biologii i Ochrony Środowiska",
    "Chemii",
    "Fizyki, Astronomii i Informatyki Stosowanej",
    "Informatyki",
    "Matematyki, Informatyki i Mechaniki",
    "Mechaniczny",
    "Elektroniki, Telekomunikacji i Informatyki",
    "Inżynierii Środowiska",
    "Architektury",
    "Budownictwa Lądowego i Wodnego",
    "Zarządzania",
    "Ekonomii",
    "Prawa i Administracji",
    "Filozoficzny",
    "Filologii Polskiej",
    "Filologiczny",
    "Historyczny",
    "Pedagogiki",
    "Psychologii",
    "Socjologii",
    "Teologii",
    "Sztuk Pięknych",
    "Muzyki",
    "Wychowania Fizycznego",
    "Nauk Geograficznych i Geologicznych",
)

TYTULY_TEMPLATES = (
    "Analiza wpływu {topic} na {subject} w {context}",
    "Badania {topic} w kontekście {subject}",
    "Wpływ {topic} na {subject}",
    "{topic}: studium przypadku {subject}",
    "Metodologia {topic} w {context}",
    "Modelowanie {topic} z wykorzystaniem {subject}",
    "Perspektywy rozwoju {topic} w {context}",
    "{topic} jako narzędzie {subject}",
    "Optymalizacja {topic} w {context}",
    "Przegląd literatury: {topic} a {subject}",
)

TOPICS = (
    "metod numerycznych",
    "algorytmów uczenia maszynowego",
    "biomarkerów",
    "polimorfizmów genetycznych",
    "interakcji białkowych",
    "modeli statystycznych",
    "systemów rozproszonych",
    "procedur klinicznych",
    "analizy obrazowej",
    "diagnostyki",
    "terapii celowanej",
    "farmakokinetyki",
    "biotransformacji",
    "ekspresji genowej",
    "metabolomiki",
    "proteomiki",
)

SUBJECTS = (
    "skuteczność leczenia",
    "jakość życia pacjentów",
    "wydajność systemu",
    "precyzję pomiarów",
    "stabilność wyników",
    "powtarzalność eksperymentu",
    "koszty operacyjne",
    "bezpieczeństwo procedury",
    "tolerancję terapii",
    "rokowanie pacjenta",
)

CONTEXTS = (
    "warunkach klinicznych",
    "środowisku laboratoryjnym",
    "populacji polskiej",
    "grupie kontrolnej",
    "badaniu wieloośrodkowym",
    "analizie retrospektywnej",
    "warunkach in vitro",
    "modelu zwierzęcym",
    "ośrodkach referencyjnych",
    "badaniu prospektywnym",
)
