---
- name: Install tightvnc packages
  apt: name={{ item }}
  with_items:
    - tightvncserver
    - "{{ windowmanager }}"
    - xterm

- name: VNC dir created for {{ user }}
  file: path=/home/{{user}}/.vnc state=directory mode=0700 owner={{user}} group={{user}}

- name: Default VNC password
  become: "{{ user }}"
  shell: "echo foobar | vncpasswd -f > ~/.vnc/passwd"

- name: VNC passwd file has proper chmod
  file: path=/home/{{user}}/.vnc/passwd mode=0600

- name: Enable Xtightvnc on boot
  cron: name="Enable Xtightvnc on boot" special_time=reboot job="Xtightvnc -geometry 1200x900 -depth 24 :99" user={{ user }}


- name: Enable {{ windowmanager }} with Xtightvnc display on boot
  cron: name="Enable {{ windowmanager }} on boot" special_time=reboot job="sleep 5 && {{ windowmanager }} -display :99" user={{user}}
