# Generated by Django 4.2.25 on 2026-01-27 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationDuplicateScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Rozpoczęto"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zakończono"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("running", "W trakcie"),
                            ("completed", "Zakończone"),
                            ("cancelled", "Anulowane"),
                            ("failed", "Błąd"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "year_from",
                    models.PositiveIntegerField(
                        default=2022,
                        help_text="Początek zakresu lat do skanowania",
                        verbose_name="Rok od",
                    ),
                ),
                (
                    "year_to",
                    models.PositiveIntegerField(
                        default=2025,
                        help_text="Koniec zakresu lat do skanowania",
                        verbose_name="Rok do",
                    ),
                ),
                (
                    "ignore_doi",
                    models.BooleanField(
                        default=False,
                        help_text="Nie używaj DOI do porównywania",
                        verbose_name="Ignoruj DOI",
                    ),
                ),
                (
                    "ignore_www",
                    models.BooleanField(
                        default=False,
                        help_text="Nie używaj adresów WWW do porównywania",
                        verbose_name="Ignoruj WWW",
                    ),
                ),
                (
                    "ignore_isbn",
                    models.BooleanField(
                        default=False,
                        help_text="Nie używaj ISBN do porównywania",
                        verbose_name="Ignoruj ISBN",
                    ),
                ),
                (
                    "ignore_zrodlo",
                    models.BooleanField(
                        default=False,
                        help_text="Nie używaj źródła do porównywania",
                        verbose_name="Ignoruj źródło",
                    ),
                ),
                (
                    "total_publications_to_scan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Publikacji do przeskanowania"
                    ),
                ),
                (
                    "publications_scanned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Przeskanowano publikacji"
                    ),
                ),
                (
                    "duplicates_found",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Znaleziono duplikatów"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Komunikat błędu"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID zadania Celery"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Użytkownik który uruchomił skanowanie",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzył",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skanowanie duplikatów publikacji",
                "verbose_name_plural": "Skanowania duplikatów publikacji",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicationDuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_object_id",
                    models.PositiveIntegerField(
                        verbose_name="ID oryginalnej publikacji"
                    ),
                ),
                (
                    "duplicate_object_id",
                    models.PositiveIntegerField(verbose_name="ID duplikatu publikacji"),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        db_index=True,
                        help_text="Wynik podobieństwa (0.0 do 1.0)",
                        verbose_name="Wynik podobieństwa",
                    ),
                ),
                (
                    "match_reasons",
                    models.JSONField(
                        default=list,
                        help_text="Lista powodów dopasowania (np. 'DOI', 'tytuł', 'ISBN')",
                        verbose_name="Powody dopasowania",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Do sprawdzenia"),
                            ("confirmed", "Potwierdzony duplikat"),
                            ("not_duplicate", "Nie jest duplikatem"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data sprawdzenia"
                    ),
                ),
                (
                    "original_title",
                    models.CharField(max_length=2048, verbose_name="Tytuł oryginału"),
                ),
                (
                    "duplicate_title",
                    models.CharField(max_length=2048, verbose_name="Tytuł duplikatu"),
                ),
                (
                    "original_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Rok oryginału"
                    ),
                ),
                (
                    "duplicate_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Rok duplikatu"
                    ),
                ),
                (
                    "original_type",
                    models.CharField(
                        help_text="Nazwa modelu (np. 'Wydawnictwo_Ciagle')",
                        max_length=100,
                        verbose_name="Typ oryginału",
                    ),
                ),
                (
                    "duplicate_type",
                    models.CharField(
                        help_text="Nazwa modelu (np. 'Wydawnictwo_Zwarte')",
                        max_length=100,
                        verbose_name="Typ duplikatu",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "duplicate_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_duplicate_duplicates",
                        to="contenttypes.contenttype",
                        verbose_name="Typ duplikatu publikacji",
                    ),
                ),
                (
                    "original_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_duplicate_originals",
                        to="contenttypes.contenttype",
                        verbose_name="Typ oryginalnej publikacji",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_publication_duplicates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sprawdził",
                    ),
                ),
                (
                    "scan_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="deduplikator_publikacji.publicationduplicatescanrun",
                        verbose_name="Skanowanie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kandydat na duplikat publikacji",
                "verbose_name_plural": "Kandydaci na duplikaty publikacji",
                "ordering": ["-similarity_score", "original_title"],
                "indexes": [
                    models.Index(
                        fields=["scan_run", "status"],
                        name="deduplikato_scan_ru_0d8c63_idx",
                    ),
                    models.Index(
                        fields=["similarity_score"],
                        name="deduplikato_similar_17e420_idx",
                    ),
                    models.Index(
                        fields=[
                            "original_content_type",
                            "original_object_id",
                            "status",
                        ],
                        name="deduplikato_origina_a6cdcb_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="publicationduplicatecandidate",
            constraint=models.UniqueConstraint(
                fields=(
                    "scan_run",
                    "original_content_type",
                    "original_object_id",
                    "duplicate_content_type",
                    "duplicate_object_id",
                ),
                name="unique_pub_scan_original_duplicate",
            ),
        ),
    ]
