# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('deduplikator_publikacji', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicationduplicatecandidate',
            name='deduplikato_similar_17e420_idx',
        ),
        migrations.AlterField(
            model_name='publicationduplicatecandidate',
            name='original_content_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='publication_duplicate_originals', to='contenttypes.contenttype', verbose_name='Typ oryginalnej publikacji'),
        ),
        migrations.AlterField(
            model_name='publicationduplicatecandidate',
            name='scan_run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='deduplikator_publikacji.publicationduplicatescanrun', verbose_name='Skanowanie'),
        ),
    ]
