# Generated by Django 5.2.16 on 2026-07-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ORCIDIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255, verbose_name='ORCID iD')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcid_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tożsamość ORCID',
                'verbose_name_plural': 'tożsamości ORCID',
                'constraints': [models.UniqueConstraint(fields=('issuer', 'sub'), name='uniq_orcid_identity'), models.UniqueConstraint(fields=('user', 'issuer'), name='uniq_user_per_orcid_issuer')],
            },
        ),
    ]
