# Generated by Django 3.0.11 on 2021-04-27 22:50

import django.db.models.deletion
from django.db import migrations, models

import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_api", "0008_auto_20210406_0530"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("data_sent", django.contrib.postgres.fields.jsonb.JSONField()),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
    ]
