# Generated by Django 3.0.14 on 2021-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0016_auto_20210713_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="publikacjainstytucji",
            name="userType",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
