# Generated by Django 3.0.14 on 2021-08-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0031_auto_20210820_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentdata",
            name="pbn_uid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pbn_api.Publication",
                verbose_name="Publikacja w PBN",
            ),
        ),
    ]
