# Generated by Django 4.2.3 on 2023-09-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0035_django32"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplineGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField()),
                ("validityDateFrom", models.DateField()),
                ("validityDateTo", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField()),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                ("polonCode", models.CharField(max_length=50)),
                ("scientificFieldName", models.CharField(max_length=200)),
                (
                    "parent_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pbn_api.disciplinegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
