# Generated by Django 4.2.3 on 2023-09-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0036_disciplinegroup_discipline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discipline",
            options={
                "verbose_name": "Dyscyplina PBN",
                "verbose_name_plural": "Dyscypliny PBN",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplinegroup",
            options={
                "verbose_name": "słownik dyscyplin PBN",
                "verbose_name_plural": "słowniki dyscyplin PBN",
            },
        ),
        migrations.AlterField(
            model_name="discipline",
            name="parent_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pbn_api.disciplinegroup",
                verbose_name="Słownik dyscyplin",
            ),
        ),
        migrations.AlterField(
            model_name="discipline",
            name="scientificFieldName",
            field=models.CharField(max_length=200, verbose_name="Dziedzina"),
        ),
    ]
