# Generated by Django 4.2.3 on 2023-09-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0037_alter_discipline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oswiadczenieinstytucji",
            name="disciplines",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
