# Generated by Django 4.2.5 on 2023-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0038_oswiadczenieinstytucji_disciplines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oswiadczenieinstytucji",
            name="area",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
