# Generated by Django 4.2.5 on 2023-11-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0039_alter_oswiadczenieinstytucji_area"),
        ("bpp", "0341_dyscyplina_naukowa_pbn_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TlumaczDyscyplinManager",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TlumaczDyscyplin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dyscyplina_w_bpp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                    ),
                ),
                (
                    "pbn_2017_2021",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dyscyplina_bpp_2017_2021",
                        to="pbn_api.discipline",
                    ),
                ),
                (
                    "pbn_2022_now",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dyscyplina_bpp_2022_now",
                        to="pbn_api.discipline",
                    ),
                ),
            ],
        ),
    ]
