# Generated by Django 4.2.8 on 2023-12-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0041_alter_publisher_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TlumaczDyscyplinManager",
        ),
        migrations.AlterModelOptions(
            name="tlumaczdyscyplin",
            options={
                "ordering": ("dyscyplina_w_bpp__nazwa",),
                "verbose_name": "rekord tłumacza dyscyplin BPP do PBN",
                "verbose_name_plural": "rekordy tłumacza dyscyplin BPP do PBN",
            },
        ),
        migrations.AlterField(
            model_name="tlumaczdyscyplin",
            name="pbn_2017_2021",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dyscyplina_bpp_2017_2021",
                to="pbn_api.discipline",
                verbose_name="Dyscyplina w PBN 2017-2021",
            ),
        ),
        migrations.AlterField(
            model_name="tlumaczdyscyplin",
            name="pbn_2022_now",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dyscyplina_bpp_2022_now",
                to="pbn_api.discipline",
                verbose_name="Dyscyplina w PBN 2022-teraz",
            ),
        ),
    ]
