# Generated by Django 4.2.13 on 2024-06-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0042_delete_tlumaczdyscyplinmanager_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oswiadczenieinstytucji",
            old_name="id",
            new_name="primary_key",
        ),
    ]
