# Generated by Django 4.2.13 on 2024-06-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0043_remove_oswiadczenieinstytucji_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oswiadczenieinstytucji",
            name="id",
            field=models.UUIDField(blank=True, null=True, verbose_name="UID w PBN"),
        ),
        migrations.AlterField(
            model_name="oswiadczenieinstytucji",
            name="primary_key",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
