# Generated by Django 4.2.19 on 2025-02-17 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_api", "0044_oswiadczenieinstytucji_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PBN_Export_Queue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("zamowiono", models.DateTimeField(auto_now_add=True)),
                ("wysylke_podjeto", models.DateTimeField(blank=True, null=True)),
                ("wysylke_zakonczono", models.DateTimeField(blank=True, null=True)),
                ("ilosc_prob", models.PositiveSmallIntegerField(default=0)),
                ("zakonczono_z_bledem", models.BooleanField(default=None, null=True)),
                ("komunikat", models.TextField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "zamowil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
