# Generated by Django 4.2.19 on 2025-02-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0045_pbn_export_queue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pbn_export_queue",
            options={
                "verbose_name": "Kolejka eksportu do PBN",
                "verbose_name_plural": "Kolejka eksportu do PBN",
            },
        ),
        migrations.RemoveField(
            model_name="pbn_export_queue",
            name="zakonczono_z_bledem",
        ),
        migrations.AddField(
            model_name="pbn_export_queue",
            name="zakonczono_pomyslnie",
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
