# Generated by Django 4.2.19 on 2025-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0046_alter_pbn_export_queue_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pbn_export_queue",
            options={
                "ordering": ("-zamowiono", "zamowil"),
                "verbose_name": "Kolejka eksportu do PBN",
                "verbose_name_plural": "Kolejka eksportu do PBN",
            },
        ),
        migrations.AddField(
            model_name="pbn_export_queue",
            name="retry_politics",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pbn_export_queue",
            name="wysylke_zakonczono",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pbn_export_queue",
            name="zamowiono",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
