# Generated by Django 4.2.19 on 2025-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0047_alter_pbn_export_queue_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pbn_export_queue",
            name="retry_politics",
        ),
        migrations.AddField(
            model_name="pbn_export_queue",
            name="retry_after_user_authorised",
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
