# Generated by Django 4.2.19 on 2025-03-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0048_remove_pbn_export_queue_retry_politics_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tlumaczdyscyplin",
            old_name="pbn_2022_now",
            new_name="pbn_2022_2023",
        ),
        migrations.AddField(
            model_name="tlumaczdyscyplin",
            name="pbn_2024_now",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dyscyplina_bpp_2024_now",
                to="pbn_api.discipline",
                verbose_name="Dyscyplina w PBN 2024-teraz",
            ),
        ),
    ]
