# Generated by Django 4.2.19 on 2025-08-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0050_zamapuj_nowe_dyscypliny_2025"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discipline",
            options={
                "ordering": ("name", "code"),
                "verbose_name": "Dyscyplina PBN",
                "verbose_name_plural": "Dyscypliny PBN",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplinegroup",
            options={
                "ordering": ("validityDateFrom",),
                "verbose_name": "słownik dyscyplin PBN",
                "verbose_name_plural": "słowniki dyscyplin PBN",
            },
        ),
        migrations.AlterField(
            model_name="tlumaczdyscyplin",
            name="pbn_2022_2023",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dyscyplina_bpp_2022_2023",
                to="pbn_api.discipline",
                verbose_name="Dyscyplina w PBN 2022-2023",
            ),
        ),
    ]
