# Generated by Django 4.2.19 on 2025-08-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0051_alter_discipline_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublikacjaInstytucji_V2",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("json_data", models.JSONField()),
                (
                    "objectId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pbn_api.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publikacja instytucji V2",
                "verbose_name_plural": "Publikacje instytucji V2",
            },
        ),
    ]
