# Generated by Django 4.2.19 on 2025-08-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0052_publikacjainstytucji_v2"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publikacjainstytucji_v2",
            unique_together={("uuid", "objectId")},
        ),
    ]
