# Generated by Django 4.2.19 on 2025-08-11 08:41

from django.db import migrations, models

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0053_alter_publikacjainstytucji_v2_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="publikacjainstytucji_v2",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publikacjainstytucji_v2",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
