# Generated by Django 4.2.19 on 2025-08-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0054_publikacjainstytucji_v2_created_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsobaZInstytucji",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.TextField()),
                ("lastName", models.TextField()),
                ("institutionName", models.TextField()),
                ("title", models.TextField()),
                ("polonUuid", models.UUIDField(unique=True)),
                ("phdStudent", models.BooleanField()),
                ("_from", models.DateField()),
                ("_to", models.DateField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "institutionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pbn_api.institution",
                    ),
                ),
                (
                    "personId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pbn_api.scientist",
                    ),
                ),
            ],
        ),
    ]
