# Generated by Django 4.2.19 on 2025-08-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0055_osobazinstytucji"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OsobaZInstytucji",
        ),
    ]
