# Generated by Django 4.2.19 on 2025-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0057_osobazinstytucji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osobazinstytucji",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
