# Generated by Django 4.2.19 on 2025-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0058_alter_osobazinstytucji_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osobazinstytucji",
            name="_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
