# Generated by Django 4.2.19 on 2025-08-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0059_alter_osobazinstytucji__from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="osobazinstytucji",
            name="personId",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="pbn_api.scientist"
            ),
        ),
    ]
