# Generated by Django 3.2.25 on 2025-10-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0061_remove_pbn_export_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentdata",
            name="submitted_successfully",
            field=models.BooleanField(
                "Wysłano pomyślnie",
                default=False,
                db_index=True,
                help_text="True gdy API call zakończył się sukcesem",
            ),
        ),
        migrations.AddField(
            model_name="sentdata",
            name="submitted_at",
            field=models.DateTimeField(
                "Data wysyłki",
                null=True,
                blank=True,
                help_text="Kiedy dane zostały wysłane do PBN",
            ),
        ),
        migrations.AddField(
            model_name="sentdata",
            name="api_response_status",
            field=models.TextField(
                "Status odpowiedzi API",
                null=True,
                blank=True,
                help_text="Odpowiedź z PBN API",
            ),
        ),
    ]
