# Generated by Django 4.2.25 on 2025-10-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_api", "0062_sent_data_success_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="PBNOdpowiedziNiepozadane",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kiedy_wyslano",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Kiedy wysłano"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="ID rekordu"
                    ),
                ),
                (
                    "dane_wyslane",
                    models.JSONField(
                        help_text="JSON wysłany do PBN",
                        verbose_name="Dane wysłane do PBN",
                    ),
                ),
                (
                    "odpowiedz_serwera",
                    models.JSONField(
                        help_text="Odpowiedź z serwera PBN",
                        verbose_name="Odpowiedź serwera PBN",
                    ),
                ),
                (
                    "rodzaj_zdarzenia",
                    models.CharField(
                        choices=[
                            ("ZMIANA_UID", "Zmiana UID publikacji przez PBN"),
                            (
                                "UID_JUZ_ISTNIEJE",
                                "PBN odpowiedział UID który już istnieje w bazie",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Rodzaj zdarzenia",
                    ),
                ),
                (
                    "uzytkownik",
                    models.CharField(
                        blank=True,
                        help_text="Login użytkownika który wykonał operację",
                        max_length=150,
                        null=True,
                        verbose_name="Użytkownik",
                    ),
                ),
                (
                    "stary_uid",
                    models.CharField(
                        blank=True,
                        help_text="Poprzedni PBN UID (dla ZMIANA_UID)",
                        max_length=50,
                        null=True,
                        verbose_name="Stary PBN UID",
                    ),
                ),
                (
                    "nowy_uid",
                    models.CharField(
                        db_index=True,
                        help_text="Nowy PBN UID otrzymany z serwera",
                        max_length=50,
                        verbose_name="Nowy PBN UID",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Typ rekordu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niepożądana odpowiedź PBN",
                "verbose_name_plural": "Niepożądane odpowiedzi PBN",
                "ordering": ["-kiedy_wyslano"],
            },
        ),
    ]
