# Generated by Django 4.2.25 on 2025-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0063_pbnodpowiedziniepozadane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pbnodpowiedziniepozadane",
            name="stary_uid",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Poprzedni PBN UID (dla ZMIANA_UID)",
                max_length=50,
                verbose_name="Stary PBN UID",
            ),
        ),
        migrations.AlterField(
            model_name="pbnodpowiedziniepozadane",
            name="uzytkownik",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Login użytkownika który wykonał operację",
                max_length=150,
                verbose_name="Użytkownik",
            ),
        ),
    ]
