# Generated by Django 4.2.25 on 2025-10-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0064_alter_pbnodpowiedziniepozadane_stary_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pbnodpowiedziniepozadane",
            name="uzytkownik",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Login użytkownika który wykonał operację",
                max_length=150,
                null=True,
                verbose_name="Użytkownik",
            ),
        ),
    ]
