# Generated by Django 4.2.25 on 2025-12-03 14:33
# Optimized to use CREATE INDEX CONCURRENTLY IF NOT EXISTS for non-blocking, idempotent index creation

from django.db import migrations, models


def log_progress(message):
    """Helper to create a RunPython that prints a message."""

    def forward(apps, schema_editor):
        print(f"  -> {message}")

    return migrations.RunPython(forward, migrations.RunPython.noop)


def create_index_concurrently(table, column, index_name):
    """Helper to create RunSQL for concurrent index creation with IF NOT EXISTS."""
    return migrations.RunSQL(
        sql=f'CREATE INDEX CONCURRENTLY IF NOT EXISTS "{index_name}" ON "{table}" ("{column}");',
        reverse_sql=f'DROP INDEX CONCURRENTLY IF EXISTS "{index_name}";',
    )


class Migration(migrations.Migration):
    atomic = False  # Required for CONCURRENTLY

    dependencies = [
        ("pbn_api", "0065_make_uzytkownik_nullable"),
    ]

    operations = [
        # ============================================================
        # PHASE 1: Alter fields (fast, no index creation)
        # ============================================================
        log_progress("Phase 1: Altering field definitions..."),
        # Institution fields
        log_progress("  Altering Institution.addressCity..."),
        migrations.AlterField(
            model_name="institution",
            name="addressCity",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Institution.addressPostalCode..."),
        migrations.AlterField(
            model_name="institution",
            name="addressPostalCode",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Institution.addressStreet..."),
        migrations.AlterField(
            model_name="institution",
            name="addressStreet",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Institution.addressStreetNumber..."),
        migrations.AlterField(
            model_name="institution",
            name="addressStreetNumber",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Institution.name..."),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Institution.polonUid..."),
        migrations.AlterField(
            model_name="institution",
            name="polonUid",
            field=models.TextField(blank=True, default=""),
        ),
        # Journal fields
        log_progress("  Altering Journal.eissn..."),
        migrations.AlterField(
            model_name="journal",
            name="eissn",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Journal.issn..."),
        migrations.AlterField(
            model_name="journal",
            name="issn",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Journal.title..."),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Journal.websiteLink..."),
        migrations.AlterField(
            model_name="journal",
            name="websiteLink",
            field=models.TextField(blank=True, default=""),
        ),
        # OsobaZInstytucji field (no index needed)
        log_progress("  Altering OsobaZInstytucji.title..."),
        migrations.AlterField(
            model_name="osobazinstytucji",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        # Publication fields
        log_progress("  Altering Publication.doi..."),
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Publication.isbn..."),
        migrations.AlterField(
            model_name="publication",
            name="isbn",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Publication.publicUri..."),
        migrations.AlterField(
            model_name="publication",
            name="publicUri",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Publication.title..."),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
        # Publisher fields
        log_progress("  Altering Publisher.publisherName..."),
        migrations.AlterField(
            model_name="publisher",
            name="publisherName",
            field=models.TextField(blank=True, default=""),
        ),
        # Scientist fields
        log_progress("  Altering Scientist.lastName..."),
        migrations.AlterField(
            model_name="scientist",
            name="lastName",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Scientist.name..."),
        migrations.AlterField(
            model_name="scientist",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Scientist.orcid..."),
        migrations.AlterField(
            model_name="scientist",
            name="orcid",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Scientist.pbnId..."),
        migrations.AlterField(
            model_name="scientist",
            name="pbnId",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Scientist.polonUid..."),
        migrations.AlterField(
            model_name="scientist",
            name="polonUid",
            field=models.TextField(blank=True, default=""),
        ),
        log_progress("  Altering Scientist.qualifications..."),
        migrations.AlterField(
            model_name="scientist",
            name="qualifications",
            field=models.TextField(blank=True, default="", verbose_name="Tytuł"),
        ),
        # ============================================================
        # PHASE 2: Add indexes CONCURRENTLY IF NOT EXISTS (non-blocking, idempotent)
        # ============================================================
        log_progress("Phase 2: Adding indexes concurrently (non-blocking, skipping existing)..."),
        # Institution indexes
        log_progress("  Adding index on Institution.addressCity..."),
        create_index_concurrently("pbn_api_institution", "addressCity", "pbn_api_inst_addrcity_idx"),
        log_progress("  Adding index on Institution.addressPostalCode..."),
        create_index_concurrently("pbn_api_institution", "addressPostalCode", "pbn_api_inst_addrpost_idx"),
        log_progress("  Adding index on Institution.addressStreet..."),
        create_index_concurrently("pbn_api_institution", "addressStreet", "pbn_api_inst_addrstr_idx"),
        log_progress("  Adding index on Institution.addressStreetNumber..."),
        create_index_concurrently("pbn_api_institution", "addressStreetNumber", "pbn_api_inst_addrnum_idx"),
        log_progress("  Adding index on Institution.name..."),
        create_index_concurrently("pbn_api_institution", "name", "pbn_api_inst_name_idx"),
        log_progress("  Adding index on Institution.polonUid..."),
        create_index_concurrently("pbn_api_institution", "polonUid", "pbn_api_inst_polonuid_idx"),
        # Journal indexes
        log_progress("  Adding index on Journal.eissn..."),
        create_index_concurrently("pbn_api_journal", "eissn", "pbn_api_jour_eissn_idx"),
        log_progress("  Adding index on Journal.issn..."),
        create_index_concurrently("pbn_api_journal", "issn", "pbn_api_jour_issn_idx"),
        log_progress("  Adding index on Journal.title..."),
        create_index_concurrently("pbn_api_journal", "title", "pbn_api_jour_title_idx"),
        log_progress("  Adding index on Journal.websiteLink..."),
        create_index_concurrently("pbn_api_journal", "websiteLink", "pbn_api_jour_website_idx"),
        # Publication indexes
        log_progress("  Adding index on Publication.doi..."),
        create_index_concurrently("pbn_api_publication", "doi", "pbn_api_pub_doi_idx"),
        log_progress("  Adding index on Publication.isbn..."),
        create_index_concurrently("pbn_api_publication", "isbn", "pbn_api_pub_isbn_idx"),
        log_progress("  Adding index on Publication.publicUri..."),
        create_index_concurrently("pbn_api_publication", "publicUri", "pbn_api_pub_uri_idx"),
        log_progress("  Adding index on Publication.title..."),
        create_index_concurrently("pbn_api_publication", "title", "pbn_api_pub_title_idx"),
        # Publisher indexes
        log_progress("  Adding index on Publisher.publisherName..."),
        create_index_concurrently("pbn_api_publisher", "publisherName", "pbn_api_publ_name_idx"),
        # Scientist indexes
        log_progress("  Adding index on Scientist.lastName..."),
        create_index_concurrently("pbn_api_scientist", "lastName", "pbn_api_sci_lastname_idx"),
        log_progress("  Adding index on Scientist.name..."),
        create_index_concurrently("pbn_api_scientist", "name", "pbn_api_sci_name_idx"),
        log_progress("  Adding index on Scientist.orcid..."),
        create_index_concurrently("pbn_api_scientist", "orcid", "pbn_api_sci_orcid_idx"),
        log_progress("  Adding index on Scientist.pbnId..."),
        create_index_concurrently("pbn_api_scientist", "pbnId", "pbn_api_sci_pbnid_idx"),
        log_progress("  Adding index on Scientist.polonUid..."),
        create_index_concurrently("pbn_api_scientist", "polonUid", "pbn_api_sci_polonuid_idx"),
        log_progress("  Adding index on Scientist.qualifications..."),
        create_index_concurrently("pbn_api_scientist", "qualifications", "pbn_api_sci_qual_idx"),
        log_progress("All indexes created successfully!"),
    ]
