# Generated by Django 4.2.25 on 2025-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0067_fix_osobazinstytucji_title_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="conference",
            name="verificationLevel",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="conference",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="institution",
            name="addressCity",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="addressPostalCode",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="addressStreet",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="addressStreetNumber",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="polonUid",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="institution",
            name="verificationLevel",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="institution",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="journal",
            name="eissn",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="journal",
            name="issn",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="journal",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="journal",
            name="verificationLevel",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="journal",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="journal",
            name="websiteLink",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="publication",
            name="isbn",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publicUri",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="publication",
            name="verificationLevel",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="publication",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="publisherName",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="verificationLevel",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="lastName",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="name",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="orcid",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="pbnId",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="polonUid",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="qualifications",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Tytuł"
            ),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="status",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="verificationLevel",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="scientist",
            name="versions",
            field=models.JSONField(default=list),
        ),
    ]
