# Generated by Django 4.2.25 on 2026-04-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0414_copy_constance_to_uczelnia"),
        ("pbn_api", "0068_add_cache_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="osobazinstytucji",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="osoby_z_instytucji",
                to="bpp.uczelnia",
            ),
        ),
        migrations.AddField(
            model_name="oswiadczenieinstytucji",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oswiadczenia_instytucji",
                to="bpp.uczelnia",
            ),
        ),
        migrations.AddField(
            model_name="publikacjainstytucji",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publikacje_instytucji",
                to="bpp.uczelnia",
            ),
        ),
        migrations.AddField(
            model_name="publikacjainstytucji_v2",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publikacje_instytucji_v2",
                to="bpp.uczelnia",
            ),
        ),
        migrations.AddField(
            model_name="sentdata",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_data",
                to="bpp.uczelnia",
            ),
        ),
    ]
