# Generated by Django 5.2.13 on 2026-04-27 16:02

from django.db import migrations, models


def fill_null_strings(apps, schema_editor):
    """Convert NULL → '' on string fields before adding NOT NULL constraint."""
    SentData = apps.get_model("pbn_api", "SentData")
    SentData.objects.filter(exception__isnull=True).update(exception="")
    SentData.objects.filter(api_response_status__isnull=True).update(
        api_response_status=""
    )
    SentData.objects.filter(typ_rekordu__isnull=True).update(typ_rekordu="")


class Migration(migrations.Migration):
    # Migracja musi byc non-atomic: RunPython robi UPDATE na pbn_api_sentdata,
    # ktory generuje deferred trigger events (denorm/easyaudit aktywne na
    # tabeli). Nastepujacy AlterField (ALTER TABLE) wywala sie wtedy z
    # `ObjectInUse: nie mozna ALTER TABLE ... posiada oczekujace zdarzenia
    # wyzwalaczy`. Z atomic=False kazda operacja commituje sie osobno —
    # triggery odpalaja sie po UPDATE, a ALTER startuje z czystym stanem.
    atomic = False

    dependencies = [
        ("pbn_api", "0068_add_cache_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentdata",
            name="api_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pełny URL (domena + ścieżka), do którego wysłano dane",
                max_length=512,
                verbose_name="URL endpointu PBN",
            ),
        ),
        migrations.RunPython(fill_null_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sentdata",
            name="exception",
            field=models.TextField(
                blank=True,
                default="",
                max_length=65535,
                verbose_name="Kod błędu",
            ),
        ),
        migrations.AlterField(
            model_name="sentdata",
            name="api_response_status",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Odpowiedź z PBN API",
                verbose_name="Status odpowiedzi API",
            ),
        ),
        migrations.AlterField(
            model_name="sentdata",
            name="typ_rekordu",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
