# Generated by Django 4.2.25 on 2026-04-08 20:08

from django.db import migrations


def link_pbn_records_to_uczelnia(apps, schema_editor):
    """Set uczelnia FK on all existing PBN per-institution records."""
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    uczelnia = Uczelnia.objects.first()
    if uczelnia is None:
        return

    for model_name in [
        "OsobaZInstytucji",
        "OswiadczenieInstytucji",
        "PublikacjaInstytucji",
        "PublikacjaInstytucji_V2",
        "SentData",
    ]:
        Model = apps.get_model("pbn_api", model_name)
        Model.objects.filter(uczelnia__isnull=True).update(uczelnia=uczelnia)


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0069_add_uczelnia_fk"),
        ("bpp", "0414_copy_constance_to_uczelnia"),
    ]

    operations = [
        migrations.RunPython(
            link_pbn_records_to_uczelnia, migrations.RunPython.noop
        ),
    ]
