# Generated by Django 5.2.14 on 2026-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn_api', '0070_drop_unused_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='addressPostalCode',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institution',
            name='addressStreet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institution',
            name='polonUid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='websiteLink',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publicUri',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisherName',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='lastName',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='orcid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
