# Generated by Django 5.2.14 on 2026-06-02 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0069_sentdata_api_url"),
        ("pbn_api", "0070_link_pbn_to_uczelnia"),
    ]

    operations = []
