# Generated by Django 5.2.14 on 2026-06-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbn_api', '0072_pbn_search_gin_indexes'),
        ('pbn_api', '0073_backfill_publikacjainstytucji_v2_uczelnia'),
    ]

    operations = [
    ]
