# Generated by Django 5.2.15 on 2026-07-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbn_api', '0074_merge_20260604_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdata',
            name='fee_sent',
            field=models.JSONField(blank=True, null=True, verbose_name='Wysłane dane o opłacie'),
        ),
        migrations.AddField(
            model_name='sentdata',
            name='fee_uploaded_okay',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Opłatę wysłano poprawnie'),
        ),
    ]
