# Generated by Django 5.2.16 on 2026-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_api", "0079_constraint_publikacja_instytucji"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentdata",
            name="withdrawn_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Ustawiane po udanym wycofaniu oświadczeń dyscyplin z PBN (soft-delete publikacji). Zerowane przy ponownej udanej wysyłce.",
                null=True,
                verbose_name="Data wycofania oświadczeń",
            ),
        ),
    ]
