# Generated by Django 4.2.25 on 2025-10-21 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_export_queue", "0001_rename_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PBN_Export_Queue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("zamowiono", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("wysylke_podjeto", models.DateTimeField(blank=True, null=True)),
                (
                    "wysylke_zakonczono",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ilosc_prob", models.PositiveSmallIntegerField(default=0)),
                (
                    "zakonczono_pomyslnie",
                    models.BooleanField(db_index=True, default=None, null=True),
                ),
                ("komunikat", models.TextField(blank=True, null=True)),
                (
                    "retry_after_user_authorised",
                    models.BooleanField(db_index=True, default=None, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "zamowil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kolejka eksportu do PBN",
                "verbose_name_plural": "Kolejka eksportu do PBN",
                "ordering": ("-zamowiono", "zamowil"),
            },
        ),
    ]
