# Generated by Django 4.2.25 on 2025-12-18 09:41

from django.db import migrations, models


def classify_existing_errors(apps, schema_editor):
    """Klasyfikuje istniejące błędy na techniczne i merytoryczne."""
    PBN_Export_Queue = apps.get_model("pbn_export_queue", "PBN_Export_Queue")

    # Słowa kluczowe sugerujące błąd techniczny
    tech_keywords = [
        "traceback",
        "connectionerror",
        "sslerror",
        "timeout",
        "brak uprawnień",
        "accessdenied",
        "nieobsługiwany błąd",
        "rekord został usunięty",
    ]

    for item in PBN_Export_Queue.objects.filter(zakonczono_pomyslnie=False):
        komunikat = (item.komunikat or "").lower()
        if any(kw.lower() in komunikat for kw in tech_keywords):
            item.rodzaj_bledu = "TECH"
        else:
            item.rodzaj_bledu = "MERYT"
        item.save(update_fields=["rodzaj_bledu"])


def reverse_classify(apps, schema_editor):
    """Odwraca klasyfikację - ustawia rodzaj_bledu na None."""
    PBN_Export_Queue = apps.get_model("pbn_export_queue", "PBN_Export_Queue")
    PBN_Export_Queue.objects.filter(zakonczono_pomyslnie=False).update(
        rodzaj_bledu=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_export_queue", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbn_export_queue",
            name="rodzaj_bledu",
            field=models.CharField(
                blank=True,
                choices=[("TECH", "Techniczny"), ("MERYT", "Merytoryczny")],
                db_index=True,
                max_length=5,
                null=True,
                verbose_name="Rodzaj błędu",
            ),
        ),
        migrations.RunPython(classify_existing_errors, reverse_classify),
    ]
