# Generated by Django 4.2.25 on 2026-04-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0414_copy_constance_to_uczelnia"),
        ("pbn_export_queue", "0007_reclassify_doiorwwwmissing_errors"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbn_export_queue",
            name="uczelnia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pbn_export_queue",
                to="bpp.uczelnia",
            ),
        ),
    ]
