# Generated by Django 4.2.25 on 2026-04-09 19:05

from django.db import migrations


def link_queue_to_uczelnia(apps, schema_editor):
    Uczelnia = apps.get_model("bpp", "Uczelnia")
    PBN_Export_Queue = apps.get_model("pbn_export_queue", "PBN_Export_Queue")
    uczelnia = Uczelnia.objects.first()
    if uczelnia:
        PBN_Export_Queue.objects.filter(uczelnia__isnull=True).update(uczelnia=uczelnia)


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_export_queue", "0008_add_uczelnia_fk"),
        ("bpp", "0414_copy_constance_to_uczelnia"),
    ]

    operations = [
        migrations.RunPython(
            link_queue_to_uczelnia,
            migrations.RunPython.noop,
        ),
    ]
