# Generated by Django 5.2.15 on 2026-07-12 05:09

from django.conf import settings
from django.db import migrations, models


def deduplikuj_aktywne_wpisy(apps, schema_editor):
    """Zamknij nadmiarowe aktywne wpisy zanim założymy częściowy unikat.

    Częściowy unikat (content_type, object_id) WHERE wysylke_zakonczono IS
    NULL wymaga, by dla każdego rekordu istniał co najwyżej JEDEN aktywny
    wpis. Jeśli w bazie są już duplikaty (efekt wyścigu sprzed tej zmiany),
    zostawiamy najstarszy (najmniejsze id) aktywny wpis, a pozostałe
    zamykamy — bez kasowania (historia komunikatów zostaje).
    """
    from django.db.models import Count
    from django.utils import timezone

    PBN_Export_Queue = apps.get_model("pbn_export_queue", "PBN_Export_Queue")

    grupy_z_duplikatami = (
        PBN_Export_Queue.objects.filter(wysylke_zakonczono__isnull=True)
        .values("content_type_id", "object_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )

    teraz = timezone.now()
    for grupa in grupy_z_duplikatami:
        aktywne = list(
            PBN_Export_Queue.objects.filter(
                content_type_id=grupa["content_type_id"],
                object_id=grupa["object_id"],
                wysylke_zakonczono__isnull=True,
            ).order_by("id")
        )
        # aktywne[0] zostaje aktywny; resztę zamykamy jako nieudane duplikaty.
        for elem in aktywne[1:]:
            elem.wysylke_zakonczono = teraz
            elem.zakonczono_pomyslnie = False
            elem.save(update_fields=["wysylke_zakonczono", "zakonczono_pomyslnie"])


def wstecz_noop(apps, schema_editor):
    # Nieodwracalne: nie przywracamy sztucznie zamkniętych duplikatów.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bpp", "0467_seed_crossref_mapper_rows"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("pbn_export_queue", "0009_link_queue_to_uczelnia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplikuj_aktywne_wpisy, wstecz_noop),
        migrations.AddConstraint(
            model_name="pbn_export_queue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("wysylke_zakonczono__isnull", True)),
                fields=("content_type", "object_id"),
                name="pbn_export_queue_jeden_aktywny_wpis_na_rekord",
            ),
        ),
    ]
