# Generated by Django 5.2.16 on 2026-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pbn_export_queue", "0010_atomowa_kolejka_pbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbn_export_queue",
            name="operacja",
            field=models.CharField(
                choices=[("wysylka", "Wysyłka"), ("wycofanie", "Wycofanie oświadczeń")],
                db_index=True,
                default="wysylka",
                help_text="Wycofanie usuwa oświadczenia dyscyplin publikacji z profilu instytucji w PBN (soft-delete rekordu). Nie kasuje samego obiektu publikacji w PBN — ten jest współdzielony między instytucjami.",
                max_length=16,
                verbose_name="Operacja",
            ),
        ),
    ]
