# Generated by Django 3.0.11 on 2021-03-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("import_dyscyplin_zrodel", "0002_auto_20210315_2215"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importdyscyplinzrodel",
            options={},
        ),
    ]
