- name: Install apt packages and PostgreSQL version {{ postgresql_version }}
  apt: name={{ item }} state=present
  with_items: 
    - postgresql-{{ postgresql_version }}
    - postgresql-plpython-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - python-psycopg2

- name: Create PostgreSQL user
  postgresql_user: name={{ database_user }} password={{ database_password }} role_attr_flags=CREATEDB,SUPERUSER state=present
  become_user: postgres

- name: CreatePostgreSQL database  
  postgresql_db: name={{ database_name }} 
  args: 
    owner: "{{ database_user }}"
    state: present 
    encoding: UTF-8
    lc_collate: pl_PL.UTF-8
    lc_ctype: pl_PL.UTF-8
    template: template0
  become_user: postgres
  
- name: Create PostgreSQL plpython language
  postgresql_lang: db={{ database_name }} lang=plpythonu state=present
  become_user: postgres

- name: Create PostgreSQL collation for pl_PL
  shell: psql -c "CREATE COLLATION pl_PL(locale='pl_PL.utf8');" "{{ database_name }}"
  become_user: postgres
  ignore_errors: yes
  register: psql_coll_err

- name: Check for unexpected error message (if any)
  fail: msg="Nieoczekiwany błąd podczas tworzenia collation"
  when: (psql_coll_err.stderr != "" and psql_coll_err.stderr.find("już istnieje") < 0)

- name: Create PostgreSQL collation for pl_PL
  shell: psql -c "CREATE COLLATION \"pl_PL.utf8\"(locale='pl_PL.utf8');" "{{ database_name }}"
  become_user: postgres
  ignore_errors: yes
  register: psql_coll_err_2

- name: Check for unexpected error message (if any)
  fail: msg="Nieoczekiwany błąd podczas tworzenia collation"
  when: (psql_coll_err_2.stderr != "" and psql_coll_err_2.stderr.find("już istnieje") < 0)

- name: Update unaccent.txt file
  file: src=unaccent-rules.txt dest=/usr/share/postgresql/{{ postgresql_version }}/tsearch_data/unaccent.rules
