FROM ubuntu:16.04

SHELL ["/bin/bash", "-c"]

RUN apt-get update -qq && apt-get -qq install --quiet -qq --yes \
    python \
    python-pip \ 
    virtualenv \
    virtualenvwrapper \
    postgresql-client

RUN . /etc/bash_completion.d/virtualenvwrapper && mkvirtualenv env-bpp

RUN . ~/.virtualenvs/env-bpp/bin/activate && pip install -q -U pip && pip install -q django-bpp django-debug-toolbar==1.6

ADD prod-entrypoint.sh /entrypoint.sh

EXPOSE 8000

ENTRYPOINT /entrypoint.sh
