# Generated by Django 3.2.14 on 2022-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celeryui", "0004_auto_20200213_2147"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
