# Generated by Django 4.2.8 on 2023-12-09 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("celeryui", "0004_auto_20200213_2147"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="uuid",
        ),
    ]
