# Generated by Django 4.2.19 on 2025-09-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0389_alter_uczelnia_uzywaj_wydzialow"),
        ("ewaluacja_metryki", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrykaautora",
            name="jednostka",
            field=models.ForeignKey(
                blank=True,
                help_text="Główna jednostka autora w okresie ewaluacji",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metryka_autora",
                to="bpp.jednostka",
            ),
        ),
    ]
