# Generated by Django 4.2.19 on 2025-09-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_metryki", "0002_alter_metrykaautora_jednostka"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusgenerowania",
            name="liczba_do_przetworzenia",
            field=models.IntegerField(
                default=0, help_text="Całkowita liczba autorów do przetworzenia"
            ),
        ),
    ]
