# Generated by Django 4.2.25 on 2025-10-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_metryki", "0003_add_liczba_do_przetworzenia"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrykaautora",
            name="rodzaj_autora",
            field=models.CharField(
                blank=True,
                help_text="Skrót rodzaju autora (N, D, B, Z)",
                max_length=1,
                null=True,
            ),
        ),
    ]
