# Generated by Django 4.2.25 on 2025-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_metryki", "0004_metrykaautora_rodzaj_autora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrykaautora",
            name="rodzaj_autora",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Skrót rodzaju autora (N, D, B, Z)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="statusgenerowania",
            name="ostatni_komunikat",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Ostatni komunikat z procesu generowania",
            ),
        ),
        migrations.AlterField(
            model_name="statusgenerowania",
            name="task_id",
            field=models.CharField(
                blank=True, default="", help_text="ID zadania Celery", max_length=255
            ),
        ),
    ]
