# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0424_alter_autor_dyscyplina_autor_and_more'),
        ('ewaluacja_metryki', '0005_alter_metrykaautora_rodzaj_autora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrykaautora',
            name='autor',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='metryki', to='bpp.autor'),
        ),
        migrations.AlterField(
            model_name='metrykaautora',
            name='dyscyplina_naukowa',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.dyscyplina_naukowa'),
        ),
        migrations.AlterField(
            model_name='metrykaautora',
            name='jednostka',
            field=models.ForeignKey(blank=True, db_index=False, help_text='Główna jednostka autora w okresie ewaluacji', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metryka_autora', to='bpp.jednostka'),
        ),
    ]
