# Generated by Django 5.2.14 on 2026-06-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaluacja_metryki', '0006_alter_metrykaautora_autor_and_more'),
        ('ewaluacja_metryki', '0008_metrykaautora_uczelnia_notnull'),
    ]

    operations = [
    ]
