# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 17:40
from __future__ import unicode_literals

from pathlib import Path

from django.db import migrations
from django.core import management

def load_fixture(apps, schema_editor):
    fixture = str(Path(__file__).parent / '0001_initial_data.json')
    management.call_command('loaddata', fixture, verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('flexible_reports', '0001_initial')
    ]

    operations = [
        migrations.RunPython(load_fixture,
                             migrations.RunPython.noop)
    ]
