# Generated by Django 5.2.14 on 2026-05-31 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bpp', '0416_rename_dynamic_columns_to_admin'),
        ('flexible_reports', '0011_alter_reportelement_options_alter_column_attrs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinicjaRaportu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('poziom', models.CharField(choices=[('uczelnia', 'Uczelnia'), ('wydzial', 'Wydział'), ('jednostka', 'Jednostka'), ('autor', 'Autor')], max_length=20, verbose_name='Poziom')),
                ('kolejnosc', models.PositiveIntegerField(default=0, verbose_name='Kolejność w menu')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('poziom_dostepu', models.CharField(choices=[('wszyscy', 'Wszyscy (także niezalogowani)'), ('zalogowani', 'Zalogowani'), ('staff', 'Redagujący (is_staff)'), ('superuser', 'Superużytkownicy')], default='zalogowani', max_length=20, verbose_name='Poziom dostępu')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flexible_reports.report', verbose_name='Definicja flexible-reports')),
                ('uczelnie', models.ManyToManyField(blank=True, help_text='Puste = pokazuj na wszystkich uczelniach.', to='bpp.uczelnia', verbose_name='Pokazuj na stronach uczelni')),
                ('wymagane_grupy', models.ManyToManyField(blank=True, help_text='Widoczny gdy użytkownik należy do którejkolwiek z grup (puste = bez wymogu grupy).', to='auth.group', verbose_name='Wymagane grupy')),
            ],
            options={
                'verbose_name': 'definicja raportu',
                'verbose_name_plural': 'definicje raportów',
                'ordering': ['kolejnosc', 'nazwa'],
            },
        ),
    ]
