# Generated by Django 5.2.15 on 2026-06-30 19:10

import django.core.serializers.json
import django.db.models.deletion
import long_running.notification_mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpp', '0444_alter_uczelnia_wyszukiwanie_rekordy_na_strone_anonim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPunktacjiZrodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('finished_successfully', models.BooleanField(default=False)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('rok', models.IntegerField(blank=True, null=True)),
                ('plik', models.FileField(upload_to='protected/import_punktacji_zrodel/')),
                ('zapisz_zmiany_do_bazy', models.BooleanField(default=False, help_text='Gdy odznaczone — tylko podgląd, bez zapisu do bazy.')),
                ('importuj_impact_factor', models.BooleanField(default=True)),
                ('importuj_kwartyl_wos', models.BooleanField(default=True)),
                ('ignoruj_zrodla_bez_odpowiednika', models.BooleanField(default=False)),
                ('nie_porownuj_po_tytulach', models.BooleanField(default=False, help_text='Dopasowuj wyłącznie po ISSN/eISSN, pomijając tytuły.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'import punktacji źródeł',
                'verbose_name_plural': 'importy punktacji źródeł',
            },
            bases=(long_running.notification_mixins.ASGINotificationMixin, long_running.notification_mixins.NullNotificationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WierszImportuPunktacjiZrodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane_z_xls', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('nr_wiersza', models.PositiveIntegerField()),
                ('rezultat', models.TextField(blank=True, default='')),
                ('wymaga_zmian', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_of_row', models.PositiveIntegerField(blank=True, null=True)),
                ('duplicate_reason', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_punktacji_zrodel.importpunktacjizrodel')),
                ('zrodlo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bpp.zrodlo')),
            ],
            options={
                'ordering': ('nr_wiersza',),
            },
        ),
    ]
