---
- hosts: db
  become: yes
  become_method: sudo
  vars:
    database_name: bpp
    database_user: bpp
    database_password: password
    postgresql_version: 9.3
  roles: 
    - postgresql-server

- hosts: master
  become: yes
  become_method: sudo
  roles:
    - nginx-with-pubsub
    - nginx-messaging-test

- hosts: 
    - bpp-staging
  become: yes
  become_method: sudo
  vars:
    database_name: bpp
    database_user: bpp
    database_password: password

    django_group: vagrant
    django_user: vagrant

    django_deps_version: 20160124

    django_hostname: bpp-staging.localnet
    django_secret_key: '0xdeadbeef 3'

    django_db_name: bpp
    django_db_user: bpp
    django_db_password: password
    django_db_host: bpp-db

    django_settings_module: "{{ django_project_name }}.settings.staging"

    django_enable_raven: false
    django_raven_url: none

    django_project_name: django_bpp
    django_toplevel_dir: django-bpp

    django_certs_dir: "roles/django-site/files/" # toplevel katalog gdzie znajduje sie plik nazwa-hosta.cert i nazwa-hosta.key, do nginx SSL

  roles:
    - nginx-with-pubsub
    - postgresql-server
    - rabbitmq-server
    - name: django-site
      tags: ['django-site']

  tasks: 
    - name: RabbitMQ config jest dodany do {{ django_venv_dir }}/bin/activate
      no_log: True
      lineinfile: dest="{{ django_venv_dir }}/bin/activate" line="{{ item }}"
      with_items:
        - export {{ django_envvar_prefix }}_BROKER_URL="amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:5672/{{ rabbitmq_vhost }}"
      notify:
        - supervisor restart
      tags: ['django-site', 'rabbitmq']

