---
- hosts: 
    - bpp-staging.localnet
  become: yes
  become_method: sudo
  vars:
    database_name: staging-bpp
    database_user: staging-bpp
    database_password: "password"

    django_group: vagrant
    django_user: vagrant

    django_deps_version: 20160124

    django_hostname: bpp-staging.localnet
    django_secret_key: '0xdeadbeef 3'

    django_settings_module: "{{ django_project_name }}.settings.production"

    django_enable_raven: false
    django_raven_url: none

    django_project_name: django_bpp
    django_toplevel_dir: django-bpp

    django_notifications_host: bpp-staging.localnet

  roles:
    - nginx-with-pubsub
    - postgresql-server
    - rabbitmq-server
    - redis-server
    - name: django-site
      tags: ['django-site']

  tasks: 
    - name: RabbitMQ config jest dodany do {{ django_venv_dir }}/bin/activate
      no_log: True
      lineinfile: dest="{{ django_venv_dir }}/bin/activate" line="{{ item }}"
      with_items:
        - export {{ django_envvar_prefix }}_BROKER_URL="amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:5672/{{ rabbitmq_vhost }}"
      notify:
        - supervisor restart
      tags: ['django-site', 'rabbitmq']

