# Generated by Django 4.2.25 on 2025-10-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rodzaj_Autora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100, verbose_name="Nazwa")),
                (
                    "skrot",
                    models.CharField(max_length=1, unique=True, verbose_name="Skrót"),
                ),
                (
                    "jest_w_n",
                    models.BooleanField(
                        default=False,
                        verbose_name="Określa czy dany rodzaj autora wchodzi do liczby N",
                    ),
                ),
                (
                    "licz_sloty",
                    models.BooleanField(
                        default=False,
                        verbose_name="Określa, czy dany rodzaj autora ma obliczane sloty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rodzaj autora",
                "verbose_name_plural": "Rodzaje autorów",
                "ordering": ["skrot"],
            },
        ),
    ]
