# Generated by Django 4.2.25 on 2025-10-13 15:36

from django.db import migrations


def create_rodzaje_autorow(apps, schema_editor):
    Rodzaj_Autora = apps.get_model("ewaluacja_common", "Rodzaj_Autora")

    rodzaje = [
        {
            "nazwa": "pracownik naukowy w liczbie N",
            "skrot": "N",
            "jest_w_n": True,
            "licz_sloty": True,
        },
        {"nazwa": "doktorant", "skrot": "D", "jest_w_n": False, "licz_sloty": True},
        {
            "nazwa": "pracownik badawczy spoza N",
            "skrot": "B",
            "jest_w_n": False,
            "licz_sloty": True,
        },
        {
            "nazwa": "inny zatrudniony, nie naukowy",
            "skrot": "Z",
            "jest_w_n": False,
            "licz_sloty": False,
        },
    ]

    for rodzaj in rodzaje:
        Rodzaj_Autora.objects.create(**rodzaj)


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_common", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_rodzaje_autorow),
    ]
