# Generated by Django 4.2.25 on 2025-10-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_common", "0003_add_sort_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rodzaj_autora",
            options={
                "ordering": ["sort"],
                "verbose_name": "Rodzaj autora",
                "verbose_name_plural": "Rodzaje autorów",
            },
        ),
    ]
