# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_dyscyplin', '0004_auto_20180409_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_dyscyplin_row',
            name='dyscyplina',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_dyscyplin_row',
            name='kod_dyscypliny',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import_dyscyplin_row',
            name='kod_subdyscypliny',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='import_dyscyplin_row',
            name='subdyscyplina',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
