# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_dyscyplin', '0008_auto_20180415_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import_dyscyplin_row',
            options={'ordering': ('nazwisko', 'imiona')},
        ),
        migrations.AddField(
            model_name='import_dyscyplin',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
