# Generated by Django 2.1.7 on 2019-03-26 04:53

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('import_dyscyplin', '0014_auto_20190324_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_dyscyplin',
            name='stan',
            field=django_fsm.FSMField(choices=[('nowy', 'nowy'), ('określanie opcji importu', 'określanie opcji importu'), ('opcje importu określone', 'opcje importu określone'), ('przeanalizowany', 'przeanalizowany'), ('błędny', 'błędny'), ('zintegrowany', 'zintegrowany')], default='nowy', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='kolumna',
            name='nazwa_w_pliku',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='kolumna',
            name='rodzaj_pola',
            field=models.CharField(choices=[('nazwisko', 'nazwisko'), ('imię', 'imię'), ('pesel', 'pesel'), ('orcid', 'orcid'), ('nazwa jednostki', 'nazwa jednostki'), ('wydział', 'wydział'), ('dyscyplina', 'dyscyplina'), ('kod dyscypliny', 'kod dyscypliny'), ('procent dyscypliny', 'procent dyscypliny'), ('subdyscyplina', 'subdyscyplina'), ('kod subdyscypliny', 'kod subdyscypliny'), ('procent subdyscypliny', 'procent subdyscypliny'), ('pomiń', 'pomiń')], max_length=50),
        ),
    ]
