# Generated by Django 3.0.4 on 2020-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_dyscyplin", "0017_auto_20190327_2246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kolumna",
            name="rodzaj_pola",
            field=models.CharField(
                choices=[
                    ("tytuł", "tytuł"),
                    ("nazwisko", "nazwisko"),
                    ("imię", "imię"),
                    ("pesel", "pesel"),
                    ("orcid", "orcid"),
                    ("pbn_id", "pbn_id"),
                    ("nazwa jednostki", "nazwa jednostki"),
                    ("wydział", "wydział"),
                    ("dyscyplina", "dyscyplina"),
                    ("kod dyscypliny", "kod dyscypliny"),
                    ("procent dyscypliny", "procent dyscypliny"),
                    ("subdyscyplina", "subdyscyplina"),
                    ("kod subdyscypliny", "kod subdyscypliny"),
                    ("procent subdyscypliny", "procent subdyscypliny"),
                    ("pomiń", "pomiń"),
                ],
                max_length=50,
            ),
        ),
    ]
