# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi istniejące pliki do katalogu protected/import_dyscyplin/"""
    Import_Dyscyplin = apps.get_model("import_dyscyplin", "Import_Dyscyplin")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "import_dyscyplin")
    os.makedirs(new_dir, exist_ok=True)

    for obj in Import_Dyscyplin.objects.exclude(plik=""):
        if obj.plik:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik = f"protected/import_dyscyplin/{filename}"
                obj.save(update_fields=["plik"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("import_dyscyplin", "0021_import_pustych_do_skasowania"),
    ]

    operations = [
        # FIRST: Increase max_length to accommodate longer paths
        migrations.AlterField(
            model_name="import_dyscyplin",
            name="plik",
            field=models.FileField(
                max_length=512, upload_to="protected/import_dyscyplin/"
            ),
        ),
        # THEN: Run the data migration
        migrations.RunPython(move_files_to_protected, noop),
    ]
