# Generated by Django 4.2.25 on 2025-12-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_dyscyplin", "0022_move_files_to_protected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import_dyscyplin",
            name="info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin",
            name="web_page_uid",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="dyscyplina",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="kod_dyscypliny",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="kod_subdyscypliny",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="nazwa_jednostki",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="nazwa_wydzialu",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="import_dyscyplin_row",
            name="subdyscyplina",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
    ]
