# Generated by Django 4.2.19 on 2025-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("komparator_pbn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pbndownloadtask",
            name="current_step",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="pbndownloadtask",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pbndownloadtask",
            name="progress_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pbndownloadtask",
            name="publications_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pbndownloadtask",
            name="statements_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pbndownloadtask",
            name="total_publications",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pbndownloadtask",
            name="total_statements",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
