# Generated by Django 4.2.19 on 2025-08-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("komparator_pbn", "0002_pbndownloadtask_current_step_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PbnDownloadTask",
        ),
    ]
