# Generated by Django 4.2.16 on 2024-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zglos_publikacje", "0015_zgloszenie_publikacji_autor_oswiadczenie_ken"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
