# Generated by Django 4.2.19 on 2025-06-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zglos_publikacje", "0016_zgloszenie_publikacji_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="zgoda_na_publikacje_pelnego_tekstu",
            field=models.BooleanField(
                default=False, verbose_name="Zgoda na publikację pełnego tekstu"
            ),
        ),
    ]
