# Generated by Django 4.2.25 on 2025-11-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zglos_publikacje",
            "0017_zgloszenie_publikacji_zgoda_na_publikacje_pelnego_tekstu",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="rodzaj_zglaszanej_publikacji",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "artykuł naukowy lub monografia"),
                    (3, "rozdział w monografii"),
                    (2, "pozostałe rodzaje"),
                ],
                help_text="Dla artykułów naukowych i monografii może być wymagane wprowadzenie informacji o opłatach za publikację w ostatnim etapie wypełniania formularza. ",
                verbose_name="Rodzaj zgłaszanej publikacji",
            ),
        ),
    ]
