# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi pliki z głównego MEDIA_ROOT i zglos_publikacje/ do protected/zglos_publikacje/"""
    Zgloszenie_Publikacji = apps.get_model("zglos_publikacje", "Zgloszenie_Publikacji")
    old_dir = os.path.join(settings.MEDIA_ROOT, "zglos_publikacje")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "zglos_publikacje")
    os.makedirs(new_dir, exist_ok=True)

    for obj in Zgloszenie_Publikacji.objects.exclude(plik=""):
        if obj.plik:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik = f"protected/zglos_publikacje/{filename}"
                obj.save(update_fields=["plik"])

    # Usuń stary katalog jeśli pusty
    if os.path.exists(old_dir) and not os.listdir(old_dir):
        os.rmdir(old_dir)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("zglos_publikacje", "0019_zgloszenie_publikacji_autor_ostatnio_zmieniony"),
    ]

    operations = [
        migrations.RunPython(move_files_to_protected, noop),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="plik",
            field=models.FileField(
                blank=True,
                help_text=(
                    "Jeżeli zgłaszana publikacja nie jest dostępna nigdzie w sieci internet,\n"
                    "        prosimy o dodanie załącznika"
                ),
                null=True,
                upload_to="protected/zglos_publikacje/",
                verbose_name="Plik załącznika",
            ),
        ),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="przyczyna_zwrotu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="strona_www",
            field=models.URLField(
                blank=True,
                default="",
                help_text=(
                    "Pole opcjonalne. Adres URL lokalizacji pełnego tekstu pracy "
                    "(dostęp otwarty lub nie). Jeżeli praca posiada numer DOI, wpisz go "
                    "w postaci adresu URL czyli https://dx.doi.org/[NUMER_DOI]. Jeżeli praca "
                    "nie posiada numeru DOI bądź nie jest dostępna w sieci, pozostaw to pole puste. "
                    "Adres URL musi być pełny, to znaczy musi zaczynać się od oznaczenia protokołu "
                    "czyli od ciągu znaków http:// lub https:// "
                ),
                max_length=1024,
                verbose_name="Dostępna w sieci pod adresem",
            ),
        ),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="tytul",
            field=models.TextField(
                blank=True, db_index=True, default="", verbose_name="Tytuł"
            ),
        ),
    ]
