# Generated by Django 4.2.25 on 2026-02-03 20:20

from django.db import migrations, models
import zglos_publikacje.models


class Migration(migrations.Migration):

    dependencies = [
        ("zglos_publikacje", "0021_fix_file_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="oryginalna_nazwa_pliku",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Oryginalna nazwa pliku przesłana przez użytkownika",
                max_length=512,
                verbose_name="Oryginalna nazwa pliku",
            ),
        ),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="plik",
            field=models.FileField(
                blank=True,
                help_text="Jeżeli zgłaszana publikacja nie jest dostępna nigdzie w sieci internet,\n        prosimy o dodanie załącznika",
                max_length=765,
                null=True,
                upload_to=zglos_publikacje.models.zgloszenie_publikacji_upload_to,
                verbose_name="Plik załącznika",
            ),
        ),
    ]
