# Generated by Django 4.2.25 on 2026-04-02 08:57

from django.db import migrations, models
import django.db.models.deletion
import zglos_publikacje.models


class Migration(migrations.Migration):

    dependencies = [
        ("pbn_api", "0068_add_cache_models"),
        ("bpp", "0411_nowy_formularz_zgloszenia"),
        ("zglos_publikacje", "0022_uuid_filenames"),
    ]

    operations = [
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="forma_dostepu",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "otwarty dostęp"), (2, "dostęp ograniczony")],
                help_text="Otwarty dostęp lub dostęp ograniczony",
                null=True,
                verbose_name="Forma dostępu",
            ),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="wydawca_bpp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zgloszenia_publikacji",
                to="bpp.wydawca",
                verbose_name="Wydawca (BPP)",
            ),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="wydawca_pbn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zgloszenia_publikacji",
                to="pbn_api.publisher",
                verbose_name="Wydawca (PBN)",
            ),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="wydawca_zgloszenia",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nazwa wydawcy wpisana przez zgłaszającego",
                max_length=512,
                verbose_name="Wydawca (tekst)",
            ),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="wydawnictwo_nadrzedne_bpp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zgloszenia_publikacji",
                to="bpp.wydawnictwo_zwarte",
                verbose_name="Wydawnictwo nadrzędne (BPP)",
            ),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="wydawnictwo_nadrzedne_pbn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zgloszenia_publikacji",
                to="pbn_api.publication",
                verbose_name="Wydawnictwo nadrzędne (PBN)",
            ),
        ),
        migrations.AddField(
            model_name="zgloszenie_publikacji",
            name="wydawnictwo_nadrzedne_tekst",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tytuł monografii, w której jest rozdział -- wpisany ręcznie przez zgłaszającego",
                max_length=512,
                verbose_name="Wydawnictwo nadrzędne (tekst)",
            ),
        ),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="rodzaj_zglaszanej_publikacji",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "artykuł naukowy lub monografia"),
                    (2, "pozostałe rodzaje"),
                    (3, "rozdział w monografii"),
                    (4, "monografia"),
                    (5, "artykuł naukowy"),
                    (6, "inne"),
                ],
                help_text="Dla artykułów naukowych i monografii może być wymagane wprowadzenie informacji o opłatach za publikację w ostatnim etapie wypełniania formularza. ",
                verbose_name="Rodzaj zgłaszanej publikacji",
            ),
        ),
        migrations.AlterField(
            model_name="zgloszenie_publikacji",
            name="strona_www",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Adres URL lub DOI pełnego tekstu pracy. System automatycznie rozpozna, czy podano DOI czy URL.",
                max_length=1024,
                verbose_name="Dostępna w sieci pod adresem",
            ),
        ),
        migrations.CreateModel(
            name="Zgloszenie_Publikacji_Zalacznik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plik",
                    models.FileField(
                        max_length=765,
                        upload_to=zglos_publikacje.models.zgloszenie_publikacji_upload_to,
                        verbose_name="Plik załącznika",
                    ),
                ),
                (
                    "oryginalna_nazwa_pliku",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="Oryginalna nazwa pliku",
                    ),
                ),
                ("kolejnosc", models.PositiveSmallIntegerField(default=0)),
                (
                    "zgloszenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zalaczniki",
                        to="zglos_publikacje.zgloszenie_publikacji",
                    ),
                ),
            ],
            options={
                "verbose_name": "załącznik zgłoszenia publikacji",
                "verbose_name_plural": "załączniki zgłoszenia publikacji",
                "ordering": ("kolejnosc",),
            },
        ),
    ]
