# Generated by Django 4.2.25 on 2025-12-15 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bpp", "0401_autorzy_przypieta"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RozbieznosciPkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pk_before",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Punkty MNiSW przed zmianą",
                    ),
                ),
                (
                    "pk_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Punkty MNiSW po zmianie",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiedy"),
                ),
                (
                    "rekord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.wydawnictwo_ciagle",
                        verbose_name="Rekord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
                (
                    "zrodlo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bpp.zrodlo",
                        verbose_name="Źródło",
                    ),
                ),
            ],
            options={
                "verbose_name": "log zmiany punktów MNiSW",
                "verbose_name_plural": "logi zmian punktów MNiSW",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="IgnorujRozbieznoscPk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(db_index=True, verbose_name="Rekord"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "ignorowanie rozbieżności punktów MNiSW",
                "verbose_name_plural": "ignorowanie rozbieżności punktów MNiSW",
            },
        ),
    ]
