# Generated by Django 3.2.14 on 2022-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formdefaults", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfielddefaultvalue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="formfielddefaultvalue",
            name="value",
            field=models.JSONField(blank=True, null=True, verbose_name="Wartość"),
        ),
        migrations.AlterField(
            model_name="formfieldrepresentation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
