# Generated by Django 3.2.15 on 2022-10-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelAdminColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("col_name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynamic_columns.modeladmin",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "col_name")},
            },
        ),
        migrations.CreateModel(
            name="ModelAdminSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("ordering", models.PositiveSmallIntegerField()),
                (
                    "col",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynamic_columns.modeladmincolumn",
                    ),
                ),
            ],
            options={
                "ordering": ("col__parent", "ordering"),
            },
        ),
    ]
