# Generated by Django 4.2.25 on 2025-10-31 11:22

import bpp.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_metryki", "0005_alter_metrykaautora_rodzaj_autora_and_more"),
        ("bpp", "0394_alter_uczelnia_clarivate_password_and_more"),
        ("ewaluacja_optymalizacja", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnpinningOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia analizy"
                    ),
                ),
                (
                    "rekord_id",
                    bpp.models.fields.TupleField(
                        base_field=models.IntegerField(),
                        db_index=True,
                        size=2,
                        verbose_name="ID rekordu (content_type_id, object_id)",
                    ),
                ),
                (
                    "rekord_tytul",
                    models.TextField(
                        help_text="Cached title for display", verbose_name="Tytuł pracy"
                    ),
                ),
                (
                    "slot_in_work",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Slot value for autor_could_benefit in this work",
                        max_digits=10,
                        verbose_name="Slot autora w tej pracy",
                    ),
                ),
                (
                    "slots_missing",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="slot_maksymalny - slot_nazbierany for autor_could_benefit",
                        max_digits=10,
                        verbose_name="Ile autorowi brakuje slotów",
                    ),
                ),
                (
                    "makes_sense",
                    models.BooleanField(
                        default=False,
                        help_text="True if slot_in_work <= slots_missing (unpinning would help fill the gap)",
                        verbose_name="Czy odpięcie ma sens",
                    ),
                ),
                (
                    "autor_could_benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unpinning_could_benefit",
                        to="bpp.autor",
                        verbose_name="Autor któremu nie weszła praca",
                    ),
                ),
                (
                    "autor_currently_using",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unpinning_currently_using",
                        to="bpp.autor",
                        verbose_name="Autor któremu weszła praca",
                    ),
                ),
                (
                    "dyscyplina_naukowa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.dyscyplina_naukowa",
                        verbose_name="Dyscyplina naukowa",
                    ),
                ),
                (
                    "metryka_could_benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unpinning_could_benefit",
                        to="ewaluacja_metryki.metrykaautora",
                        verbose_name="Metryka autora (któremu nie weszła)",
                    ),
                ),
                (
                    "metryka_currently_using",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unpinning_currently_using",
                        to="ewaluacja_metryki.metrykaautora",
                        verbose_name="Metryka autora (któremu weszła)",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.uczelnia",
                        verbose_name="Uczelnia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Możliwość odpięcia",
                "verbose_name_plural": "Możliwości odpięcia",
                "ordering": ["-makes_sense", "-slots_missing", "rekord_tytul"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="ewaluacja_o_created_9ad094_idx"
                    ),
                    models.Index(
                        fields=["uczelnia", "dyscyplina_naukowa"],
                        name="ewaluacja_o_uczelni_668e75_idx",
                    ),
                    models.Index(
                        fields=["makes_sense"], name="ewaluacja_o_makes_s_8b7068_idx"
                    ),
                    models.Index(
                        fields=["-slots_missing"], name="ewaluacja_o_slots_m_0a5b6a_idx"
                    ),
                ],
            },
        ),
    ]
