# Generated by Django 4.2.25 on 2025-10-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_metryki", "0005_alter_metrykaautora_rodzaj_autora_and_more"),
        ("bpp", "0394_alter_uczelnia_clarivate_password_and_more"),
        ("ewaluacja_optymalizacja", "0002_unpinningopportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="unpinningopportunity",
            name="punkty_roznica_b",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="O ile wzrosną punkty autora B po odpięciu (może być ujemna)",
                max_digits=10,
                verbose_name="Różnica punktów B",
            ),
        ),
        migrations.AddField(
            model_name="unpinningopportunity",
            name="sloty_roznica_b",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="O ile wzrosną sloty autora B po odpięciu (może być ujemna)",
                max_digits=10,
                verbose_name="Różnica slotów B",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="autor_could_benefit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unpinning_could_benefit",
                to="bpp.autor",
                verbose_name="Autor któremu należy odpiąć (ma pełne sloty)",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="autor_currently_using",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unpinning_currently_using",
                to="bpp.autor",
                verbose_name="Autor który skorzysta (ma miejsce na więcej)",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="makes_sense",
            field=models.BooleanField(
                default=False,
                help_text="True if unpinning increases points for autor B",
                verbose_name="Czy odpięcie ma sens",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="metryka_could_benefit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unpinning_could_benefit",
                to="ewaluacja_metryki.metrykaautora",
                verbose_name="Metryka autora (któremu należy odpiąć)",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="metryka_currently_using",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unpinning_currently_using",
                to="ewaluacja_metryki.metrykaautora",
                verbose_name="Metryka autora (który skorzysta)",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="slot_in_work",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Slot value for autor_could_benefit (to unpin) in this work",
                max_digits=10,
                verbose_name="Slot autora A w tej pracy",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="slots_missing",
            field=models.DecimalField(
                decimal_places=4,
                help_text="slot_maksymalny - slot_nazbierany for autor_currently_using (who benefits)",
                max_digits=10,
                verbose_name="Ile autor B może jeszcze wziąć",
            ),
        ),
    ]
