# Generated by Django 4.2.25 on 2025-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ewaluacja_optymalizacja",
            "0003_unpinningopportunity_punkty_roznica_b_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unpinningopportunity",
            name="punkty_roznica_a",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="O ile zmienią się punkty autora A po odpięciu (zazwyczaj 0 lub ujemne)",
                max_digits=10,
                verbose_name="Różnica punktów A",
            ),
        ),
        migrations.AddField(
            model_name="unpinningopportunity",
            name="sloty_roznica_a",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="O ile zmienią się sloty autora A po odpięciu (zazwyczaj 0 lub ujemne)",
                max_digits=10,
                verbose_name="Różnica slotów A",
            ),
        ),
    ]
