# Generated by Django 4.2.25 on 2025-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ewaluacja_optymalizacja",
            "0004_unpinningopportunity_punkty_roznica_a_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="unpinningopportunity",
            name="praca_byla_wykazana_dla_a",
            field=models.BooleanField(
                default=False,
                help_text="True jeśli praca była w prace_nazbierane autora A (wtedy odpięcie spowoduje rzeczywistą stratę punktów)",
                verbose_name="Czy praca była wykazana dla A",
            ),
        ),
        migrations.AddField(
            model_name="unpinningopportunity",
            name="punkty_strata_a",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Rzeczywista strata punktów A (zawsze >= 0). Jeśli praca nie była w prace_nazbierane, strata = 0 (A nie wykazywał tej pracy). Jeśli praca była wykazana, strata = abs(punkty_roznica_a).",
                max_digits=10,
                verbose_name="Rzeczywista strata punktów A",
            ),
        ),
        migrations.AddField(
            model_name="unpinningopportunity",
            name="punkty_zysk_b",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Rzeczywisty zysk punktów B (zawsze >= 0). Równe punkty_roznica_b jeśli dodatnie, inaczej 0.",
                max_digits=10,
                verbose_name="Rzeczywisty zysk punktów B",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="punkty_roznica_a",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Surowa różnica punktów A: punkty_after - punkty_before (zazwyczaj 0 lub ujemne)",
                max_digits=10,
                verbose_name="Różnica punktów A (surowa)",
            ),
        ),
        migrations.AlterField(
            model_name="unpinningopportunity",
            name="punkty_roznica_b",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Surowa różnica punktów B: punkty_after - punkty_before (zazwyczaj dodatnie)",
                max_digits=10,
                verbose_name="Różnica punktów B (surowa)",
            ),
        ),
    ]
