# Generated by Django 4.2.25 on 2025-11-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0400_add_status_optymalizacji_bulk"),
        ("ewaluacja_optymalizacja", "0006_add_status_optymalizacji_z_odpinaniem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusOptymalizacjiBulk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "w_trakcie",
                    models.BooleanField(
                        default=False,
                        help_text="Czy zadanie jest obecnie uruchomione",
                        verbose_name="W trakcie",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID zadania Celery",
                    ),
                ),
                (
                    "data_rozpoczecia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data rozpoczęcia"
                    ),
                ),
                (
                    "data_zakonczenia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                (
                    "ostatni_komunikat",
                    models.TextField(
                        blank=True, default="", verbose_name="Ostatni komunikat"
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.uczelnia",
                        verbose_name="Uczelnia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status optymalizacji bulk",
                "verbose_name_plural": "Status optymalizacji bulk",
            },
        ),
    ]
