# Generated by Django 4.2.25 on 2025-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_optymalizacja", "0007_add_status_optymalizacji_bulk"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusUnpinningAnalyzy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "w_trakcie",
                    models.BooleanField(
                        default=False,
                        help_text="Czy zadanie jest obecnie uruchomione",
                        verbose_name="W trakcie",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID zadania Celery",
                    ),
                ),
                (
                    "data_rozpoczecia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data rozpoczęcia"
                    ),
                ),
                (
                    "data_zakonczenia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                (
                    "ostatni_komunikat",
                    models.TextField(
                        blank=True, default="", verbose_name="Ostatni komunikat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Status analizy unpinning",
                "verbose_name_plural": "Status analizy unpinning",
            },
        ),
    ]
