# Generated by Django 4.2.25 on 2025-11-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_optymalizacja", "0008_add_status_unpinning_analizy"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusoptymalizacjibulk",
            name="plik_zip_wszystkie_xls",
            field=models.FileField(
                blank=True,
                help_text="Cache pliku ZIP generowanego po zakończeniu optymalizacji bulk",
                null=True,
                upload_to="ewaluacja_optymalizacja/cache/",
                verbose_name="Plik ZIP ze wszystkimi XLS",
            ),
        ),
    ]
