# Generated by Django 4.2.25 on 2025-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_optymalizacja", "0009_add_plik_zip_wszystkie_xls"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationrun",
            name="is_optimal",
            field=models.BooleanField(
                default=True,
                help_text="False jeśli solver zwrócił rozwiązanie dopuszczalne ale nieoptymalne (np. z powodu timeout)",
                verbose_name="Rozwiązanie optymalne",
            ),
        ),
    ]
