# Generated by Django 4.2.25 on 2025-12-22 21:09

import os
import shutil

from django.conf import settings
from django.db import migrations, models


def move_files_to_protected(apps, schema_editor):
    """Przenosi pliki z ewaluacja_optymalizacja/cache/ do protected/ewaluacja_optymalizacja/"""
    StatusOptymalizacjiBulk = apps.get_model(
        "ewaluacja_optymalizacja", "StatusOptymalizacjiBulk"
    )
    old_dir = os.path.join(settings.MEDIA_ROOT, "ewaluacja_optymalizacja", "cache")
    new_dir = os.path.join(settings.MEDIA_ROOT, "protected", "ewaluacja_optymalizacja")
    os.makedirs(new_dir, exist_ok=True)

    for obj in StatusOptymalizacjiBulk.objects.exclude(plik_zip_wszystkie_xls=""):
        if obj.plik_zip_wszystkie_xls:
            old_path = os.path.join(settings.MEDIA_ROOT, obj.plik_zip_wszystkie_xls.name)
            if os.path.exists(old_path):
                filename = os.path.basename(old_path)
                new_path = os.path.join(new_dir, filename)
                shutil.move(old_path, new_path)
                obj.plik_zip_wszystkie_xls = f"protected/ewaluacja_optymalizacja/{filename}"
                obj.save(update_fields=["plik_zip_wszystkie_xls"])

    # Usuń stary katalog jeśli pusty
    if os.path.exists(old_dir) and not os.listdir(old_dir):
        os.rmdir(old_dir)

    # Usuń katalog rodzica jeśli również pusty
    parent_dir = os.path.join(settings.MEDIA_ROOT, "ewaluacja_optymalizacja")
    if os.path.exists(parent_dir) and not os.listdir(parent_dir):
        os.rmdir(parent_dir)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ewaluacja_optymalizacja", "0010_add_is_optimal_to_optimizationrun"),
    ]

    operations = [
        migrations.RunPython(move_files_to_protected, noop),
        migrations.AlterField(
            model_name="statusoptymalizacjibulk",
            name="plik_zip_wszystkie_xls",
            field=models.FileField(
                blank=True,
                help_text="Cache pliku ZIP generowanego po zakończeniu optymalizacji bulk",
                null=True,
                upload_to="protected/ewaluacja_optymalizacja/",
                verbose_name="Plik ZIP ze wszystkimi XLS",
            ),
        ),
    ]
