# Generated by Django 4.2.25 on 2026-01-04 00:35

import bpp.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0405_add_rok_to_oplaty_log"),
        ("ewaluacja_optymalizacja", "0011_move_files_to_protected"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusDisciplineSwapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "w_trakcie",
                    models.BooleanField(
                        default=False,
                        help_text="Czy zadanie jest obecnie uruchomione",
                        verbose_name="W trakcie",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID zadania Celery",
                    ),
                ),
                (
                    "data_rozpoczecia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data rozpoczęcia"
                    ),
                ),
                (
                    "data_zakonczenia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                (
                    "ostatni_komunikat",
                    models.TextField(
                        blank=True, default="", verbose_name="Ostatni komunikat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Status analizy zamiany dyscyplin",
                "verbose_name_plural": "Status analizy zamiany dyscyplin",
            },
        ),
        migrations.CreateModel(
            name="DisciplineSwapOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia analizy"
                    ),
                ),
                (
                    "rekord_id",
                    bpp.models.fields.TupleField(
                        base_field=models.IntegerField(),
                        db_index=True,
                        size=2,
                        verbose_name="ID rekordu (content_type_id, object_id)",
                    ),
                ),
                (
                    "rekord_tytul",
                    models.TextField(
                        help_text="Cache tytułu do wyświetlania",
                        verbose_name="Tytuł pracy",
                    ),
                ),
                (
                    "rekord_rok",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Rok publikacji"
                    ),
                ),
                (
                    "rekord_typ",
                    models.CharField(
                        default="",
                        help_text="Ciagle/Zwarte",
                        max_length=50,
                        verbose_name="Typ publikacji",
                    ),
                ),
                (
                    "points_before",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Całkowita punktacja publikacji przed zamianą dyscypliny",
                        max_digits=10,
                        verbose_name="Punkty przed zamianą",
                    ),
                ),
                (
                    "points_after",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Całkowita punktacja publikacji po zamianie dyscypliny",
                        max_digits=10,
                        verbose_name="Punkty po zamianie",
                    ),
                ),
                (
                    "point_improvement",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="points_after - points_before",
                        max_digits=10,
                        verbose_name="Poprawa punktów",
                    ),
                ),
                (
                    "zrodlo_discipline_match",
                    models.BooleanField(
                        default=False,
                        help_text="True jeśli docelowa dyscyplina jest w Dyscyplina_Zrodla dla tego źródła i roku",
                        verbose_name="Dyscyplina pasuje do źródła",
                    ),
                ),
                (
                    "makes_sense",
                    models.BooleanField(
                        default=False,
                        help_text="True jeśli zamiana zwiększa całkowitą punktację",
                        verbose_name="Czy zamiana ma sens",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_swap_opportunities",
                        to="bpp.autor",
                        verbose_name="Autor do zamiany dyscypliny",
                    ),
                ),
                (
                    "current_discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_from",
                        to="bpp.dyscyplina_naukowa",
                        verbose_name="Obecna dyscyplina",
                    ),
                ),
                (
                    "target_discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_to",
                        to="bpp.dyscyplina_naukowa",
                        verbose_name="Docelowa dyscyplina",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.uczelnia",
                        verbose_name="Uczelnia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Możliwość zamiany dyscypliny",
                "verbose_name_plural": "Możliwości zamiany dyscyplin",
                "ordering": ["-makes_sense", "-point_improvement", "rekord_tytul"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="ewaluacja_o_created_0a9788_idx"
                    ),
                    models.Index(
                        fields=["uczelnia"], name="ewaluacja_o_uczelni_ed0a90_idx"
                    ),
                    models.Index(
                        fields=["makes_sense"], name="ewaluacja_o_makes_s_af87d4_idx"
                    ),
                    models.Index(
                        fields=["-point_improvement"],
                        name="ewaluacja_o_point_i_944a76_idx",
                    ),
                    models.Index(
                        fields=["current_discipline"],
                        name="ewaluacja_o_current_03ccd6_idx",
                    ),
                    models.Index(
                        fields=["target_discipline"],
                        name="ewaluacja_o_target__5d8035_idx",
                    ),
                    models.Index(
                        fields=["zrodlo_discipline_match"],
                        name="ewaluacja_o_zrodlo__6d376d_idx",
                    ),
                    models.Index(
                        fields=["rekord_rok"], name="ewaluacja_o_rekord__2272b2_idx"
                    ),
                ],
            },
        ),
    ]
