# Generated by Django 4.2.25 on 2026-01-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0405_add_rok_to_oplaty_log"),
        ("ewaluacja_optymalizacja", "0012_add_discipline_swap_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPrzegladarkaRecalc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "w_trakcie",
                    models.BooleanField(
                        default=False,
                        help_text="Czy przeliczanie jest obecnie uruchomione",
                        verbose_name="W trakcie",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID zadania Celery",
                    ),
                ),
                (
                    "data_rozpoczecia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data rozpoczęcia"
                    ),
                ),
                (
                    "data_zakonczenia",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                (
                    "ostatni_komunikat",
                    models.TextField(
                        blank=True, default="", verbose_name="Ostatni komunikat"
                    ),
                ),
                (
                    "punkty_przed",
                    models.JSONField(
                        default=dict,
                        help_text="Dict: {discipline_id: points_value} przed akcją",
                        verbose_name="Punkty przed zmianą",
                    ),
                ),
                (
                    "uczelnia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bpp.uczelnia",
                        verbose_name="Uczelnia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status przeliczania przeglądarki",
                "verbose_name_plural": "Status przeliczania przeglądarki",
            },
        ),
    ]
