# Generated by Django 4.2.25 on 2026-01-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ewaluacja_optymalizacja", "0013_add_status_przegladarka_recalc"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationrun",
            name="best_bound",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Teoretyczne maksimum punktów obliczone przez solver. Null jeśli niedostępne.",
                max_digits=20,
                null=True,
                verbose_name="Teoretyczna górna granica punktów",
            ),
        ),
        migrations.AddField(
            model_name="optimizationrun",
            name="optimality_gap",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Różnica procentowa między znalezionym rozwiązaniem a teoretycznym maksimum. Wartość 0% oznacza rozwiązanie optymalne. Null jeśli niedostępne.",
                max_digits=10,
                null=True,
                verbose_name="Luka optymalizacyjna (%)",
            ),
        ),
    ]
