# Generated by Django 5.2.14 on 2026-06-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0422_drop_unused_cache_indexes'),
        ('ewaluacja_optymalizacja', '0014_add_optimality_gap_to_optimization_run'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disciplineswapopportunity',
            name='ewaluacja_o_uczelni_ed0a90_idx',
        ),
        migrations.RemoveIndex(
            model_name='disciplineswapopportunity',
            name='ewaluacja_o_current_03ccd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='disciplineswapopportunity',
            name='ewaluacja_o_target__5d8035_idx',
        ),
        migrations.RemoveIndex(
            model_name='optimizationauthorresult',
            name='ewaluacja_o_optimiz_c0f633_idx',
        ),
        migrations.RemoveIndex(
            model_name='optimizationauthorresult',
            name='ewaluacja_o_autor_i_7cf1ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='optimizationpublication',
            name='ewaluacja_o_author__f2e9a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='optimizationpublication',
            name='ewaluacja_o_rekord__f6f179_idx',
        ),
        migrations.AlterField(
            model_name='optimizationauthorresult',
            name='optimization_run',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_results', to='ewaluacja_optymalizacja.optimizationrun', verbose_name='Wynik optymalizacji'),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='dyscyplina_naukowa',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.dyscyplina_naukowa', verbose_name='Dyscyplina naukowa'),
        ),
        migrations.AlterField(
            model_name='unpinningopportunity',
            name='uczelnia',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='bpp.uczelnia', verbose_name='Uczelnia'),
        ),
    ]
