# Generated by Django 5.2.16 on 2026-07-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaluacja_optymalizacja', '0015_remove_disciplineswapopportunity_ewaluacja_o_uczelni_ed0a90_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOdpinaniaWszystkich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_trakcie', models.BooleanField(default=False, help_text='Czy zadanie jest obecnie uruchomione', verbose_name='W trakcie')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID zadania Celery')),
                ('data_rozpoczecia', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('data_zakonczenia', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('ostatni_komunikat', models.TextField(blank=True, default='', verbose_name='Ostatni komunikat')),
            ],
            options={
                'verbose_name': 'Status odpinania wszystkich sensownych',
                'verbose_name_plural': 'Status odpinania wszystkich sensownych',
            },
        ),
    ]
