# Generated by Django 4.2.19 on 2025-08-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bpp", "0389_alter_uczelnia_uzywaj_wydzialow"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_publications_count",
                    models.IntegerField(
                        default=0,
                        help_text="Liczba publikacji, w których obaj autorzy występują razem",
                        verbose_name="Liczba wspólnych publikacji",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ostatnia aktualizacja"
                    ),
                ),
                (
                    "primary_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_connections",
                        to="bpp.autor",
                        verbose_name="Autor główny",
                    ),
                ),
                (
                    "secondary_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_connections",
                        to="bpp.autor",
                        verbose_name="Autor powiązany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Powiązanie autorów",
                "verbose_name_plural": "Powiązania autorów",
                "ordering": ["-shared_publications_count"],
                "indexes": [
                    models.Index(
                        fields=["shared_publications_count"],
                        name="powiazania__shared__c5dc1a_idx",
                    ),
                    models.Index(
                        fields=["last_updated"], name="powiazania__last_up_a4e03f_idx"
                    ),
                ],
                "unique_together": {("primary_author", "secondary_author")},
            },
        ),
    ]
