# Generated by Django 4.2.25 on 2025-10-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bpp", "0394_alter_uczelnia_clarivate_password_and_more"),
        ("powiazania_autorow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorconnection",
            name="primary_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bpp.autor",
                verbose_name="Autor główny",
            ),
        ),
        migrations.AlterField(
            model_name="authorconnection",
            name="secondary_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bpp.autor",
                verbose_name="Autor powiązany",
            ),
        ),
    ]
