# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpp', '0424_alter_autor_dyscyplina_autor_and_more'),
        ('powiazania_autorow', '0003_backfill_powiazania_istniejace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorconnection',
            name='primary_author',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bpp.autor', verbose_name='Autor główny'),
        ),
    ]
