name: build-docker-images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "iplweb/bpp"
          install: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instal eventual build tools
        run: python3 -m pip install django

      - name: Instal eventual build tools
        run: sudo apt update

      - name: Instal eventual build tools
        run: sudo apt install gettext

      - name: Build and push
        run: make assets docker
