name: Coveralls - Finish Parallel Build

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  finish:
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
