name: Django CI

on:
  push:
    branches: dev master
  pull_request:
    branches: dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12,]

    services:
      postgres:
        image: iplweb/bpp_dbserver:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_"isready --username=postgres"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
    - run: |
        uname -a
        sudo apt install software-properties-common
        sudo add-apt-repository -d -y -n ppa:mozillateam/ppa
        sudo add-apt-repository -d -y -n ppa:deadsnakes/ppa
        echo '
        Package: *
        Pin: origin packages.mozilla.org
        Pin-Priority: 1000

        Package: firefox*
        Pin: release o=Ubuntu
        Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/mozilla
        sudo apt update
        sudo apt install -y python3.12 python3.12-dev python3-dev libpq-dev firefox

    - name: Install GekcoDriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux-aarch64.tar.gz
        tar -xvzf geckodriver*
        chmod +x geckodriver
        cp geckodriver /usr/bin/
        cp geckodriver /usr/local/bin/

    - run: firefox -version
    - run: geckodriver --version

    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install pip poetry
        poetry install --with=dev
    - name: Run Tests
      env:
        DJANGO_BPP_DB_HOST: 127.0.0.1
        DJANGO_BPP_DB_PORT: 5433
        DJANGO_BPP_DB_USER: postgres
      run: |
        poetry run pytest -k test_wyrzuc
