name: Testy BPP

on:
  push:
    branches:
      - dev
      - master
      - feature/*
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12,]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: iplweb/bpp_dbserver:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_"isready --username=postgres"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
    - run: |
        uname -a
        sudo apt install software-properties-common
        sudo add-apt-repository -d -y -n ppa:mozillateam/ppa
        sudo add-apt-repository -d -y -n ppa:deadsnakes/ppa
        echo '
        Package: *
        Pin: origin packages.mozilla.org
        Pin-Priority: 1000

        Package: firefox*
        Pin: release o=Ubuntu
        Pin-Priority: -1' | sudo tee /etc/apt/preferences.d/mozilla
        curl -fsSL https://deb.nodesource.com/setup_current.x | sudo bash -
        sudo apt install -y python3.11 python3.11-dev python3-dev libpq-dev firefox firefox-geckodriver nodejs
        sudo npm install -g --force yarn grunt-cli

    - uses: actions/checkout@v4

    - name: Install Python deps via poetry
      run: |
        python -m pip install pip poetry
        poetry install --with=dev

    - name: Build assets (yarn, collectstatic)
      env:
        DJANGO_BPP_DB_HOST: 127.0.0.1
        DJANGO_BPP_DB_PORT: 5433
        DJANGO_BPP_DB_USER: postgres
      run: |
        make assets
        poetry run src/manage.py collectstatic --noinput

    - name: Tests without Selenium
      env:
        DJANGO_BPP_DB_HOST: 127.0.0.1
        DJANGO_BPP_DB_PORT: 5433
        DJANGO_BPP_DB_USER: postgres
      run: |
        poetry run pytest -m "not selenium" --splinter-headless --splinter-webdriver-executable=/usr/lib/firefox/firefox

    - name: Tests -- only Selenium
      env:
        DJANGO_BPP_DB_HOST: 127.0.0.1
        DJANGO_BPP_DB_PORT: 5433
        DJANGO_BPP_DB_USER: postgres
      run: |
        poetry run pytest -k test_bpp_notifications --durations=0 --timeout=1200 --verbose -m "selenium" --splinter-headless --splinter-webdriver-executable=/usr/lib/firefox/firefox

    - name: Tests (no selenium) with Microsoft Auth
      env:
        DJANGO_BPP_DB_HOST: 127.0.0.1
        DJANGO_BPP_DB_PORT: 5433
        DJANGO_BPP_DB_USER: postgres
      run: |
        poetry run pip install django_microsoft_auth
        echo MICROSOFT_AUTH_CLIENT_ID=foobar > ~/.env.local
        echo MICROSOFT_AUTH_CLIENT_SECRET=foobar >> ~/.env.local
        poetry run pytest -m "not selenium" --splinter-headless --splinter-webdriver-executable=/usr/lib/firefox/firefox
