# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egeria', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egeriaimport',
            name='do',
            field=models.DateField(blank=True, help_text='\n    Uwaga, to pole jest opcjonalne, a w przypadku importu danych aktualnych (tzn. obowiązujących\n    OD danego terminu, ale nie mających wyraźnego "zakończenia" w przyszłości) - powinno\n    pozostać puste!', null=True),
        ),
        migrations.AlterField(
            model_name='egeriaimport',
            name='file',
            field=models.FileField(upload_to='egeria_xls', verbose_name='Plik XLS'),
        ),
    ]
