# Generated by Django 4.2.25 on 2025-10-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteCountdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "countdown_time",
                    models.DateTimeField(
                        help_text="Data i godzina, o której serwis zostanie zablokowany",
                        verbose_name="Czas odliczania",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Krótki komunikat wyświetlany w nagłówku strony (max 200 znaków)",
                        max_length=200,
                        verbose_name="Krótka wiadomość",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        help_text="Opcjonalny dłuższy opis wyświetlany na zablokowanej stronie",
                        null=True,
                        verbose_name="Długi opis",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data aktualizacji"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        help_text="Serwis, którego dotyczy odliczanie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.site",
                        verbose_name="Serwis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odliczanie do zamknięcia serwisu",
                "verbose_name_plural": "Odliczania do zamknięcia serwisu",
                "ordering": ["-countdown_time"],
            },
        ),
    ]
