# Generated by Django 4.2.25 on 2025-10-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_countdown", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecountdown",
            name="countdown_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Data i godzina, o której serwis zostanie zablokowany",
                null=True,
                verbose_name="Czas odliczania",
            ),
        ),
    ]
