# Generated by Django 4.2.25 on 2025-10-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_countdown", "0002_alter_sitecountdown_countdown_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecountdown",
            name="maintenance_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Data i godzina zakończenia prac konserwacyjnych (opcjonalnie)",
                null=True,
                verbose_name="Koniec prac konserwacyjnych",
            ),
        ),
    ]
