# Generated by Django 4.2.25 on 2025-10-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_countdown", "0003_sitecountdown_maintenance_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecountdown",
            name="long_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Opcjonalny dłuższy opis wyświetlany na zablokowanej stronie",
                verbose_name="Długi opis",
            ),
        ),
    ]
