---
- name: Add Python 3.6 Xenial PPA
  apt_repository: repo="ppa:jonathonf/python-3.6" state="present"

- name: Update apt cache
  apt:  update_cache=yes

- name: Install package
  apt: name="python3.6" state="present"
